### ISSUE TITLE
Publish builds to MyGet

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#10]

**Comment by SteveSandersonMS** [comment]
@javiercn When you get a chance (before the MVP summit), would you be able to look into what's needed to get some early packages pushed to the MyGet feed? I presume this is going to be necessary before the project templates will be able to work. Let me know if you don't think this is viable!

**Comment by SteveSandersonMS** [comment]
Done (was needed before I can produce any project template content)

**Comment by grahamehorner** [comment]
is the myget feed public ? please update READ.ME so the community may consume packages

**Comment by conficient** [comment]
I assume that it is this url: https://dotnet.myget.org/gallery/blazor-dev_
