### ISSUE TITLE
URL parameters do not get decoded

### ISSUE THREAD

**Issue by masonwheeler** [aspnet/Blazor#1000]
`@page "/user/{Item}"`

If I navigate to `/user/Mason Wheeler`, I expect the `Item` property to contain the string "Mason Wheeler".  Instead it contains the string "Mason%20Wheeler".

**Comment by SteveSandersonMS** [comment]
Thanks for reporting. Duplicates #702

**Comment by TeoChirileanu** [comment]
I cannot find #702. Has it been moved?

**Comment by masonwheeler** [comment]
@TeoChirileanu it's now at https://github.com/aspnet/AspNetCore/issues/5510
