### ISSUE TITLE
Blazor application showing blank page in browser

### ISSUE THREAD

**Issue by skumarvenkat** [aspnet/Blazor#1002]
Hello:

Application not display anything in browser, I don't know what wrong I am doing. How to know what is missing or anything need to configure?

My visual studio version is 15.7.3

Flight finder:
![image](https://user-images.githubusercontent.com/120073/41422456-f3aa57c6-6fc6-11e8-91c9-e7affd649a2f.png)

Thanks

**Comment by majorimi** [comment]
Check the Browser Developer Tools (F12) in the browser. If something is wrong with the code Blazor usually shows you quite useful error messages.

**Comment by SteveSandersonMS** [comment]
Also it's likely that you don't have the correct .NET SDK. Please check the [prerequisites](https://blazor.net/docs/get-started.html) and be sure to have them all.

Closing as this is known to work given the prerequisites, but please let us know if you think you're finding a different problem.
