### ISSUE TITLE
[Interop] Pass Action<T> / Delegate in object

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/Blazor#1005]
I'm currently porting the Web Notifications API from JavaScript to Blazor see: [Blazor.Notifications](https://github.com/vertonghenb/Blazor.Notifications). 

To do so I'm passing an object via interop and registering the `onClick` functions via the new features of the interop introduced in 0.4.0 to callback to C# functions. However it would be nice if we could pass `Action<UIMouseEventArgs>` in the object directly via interop to JavaScript.

Is this even possible?

**Comment by SteveSandersonMS** [comment]
Eventually we intend to extend the JS interop APIs to support passing arbitrary .NET objects by reference into JS, and arbitrary JS objects by reference into .NET. Then we'll make it possible to invoke instance methods on those objects.

This allows for a lot of additional use cases. Your goal to pass delegates and then invoke them would be one of those use cases.

Until that is fully designed and implemented, the best way to achieve what you want is to put the .NET delegate into some static dictionary on the .NET side, keyed by some unique identifier such as a GUID or incrementing series of int values. Then pass the unique identifier over to the JS side. When it wants to "invoke" the delegate, make a call back into .NET passing the unique identifier, where your .NET logic will retrieve the delegate from the dictionary by ID and then call `Invoke` on it. Of course, it's up to you to manage the lifetimes of these instances (you don't want to accumulate more and more delegates in the dictionary forever, as that's leaking memory).
