### ISSUE TITLE
Update template/demo with filtering, paging and sorting features.

### ISSUE THREAD

**Issue by etmendz** [aspnet/Blazor#1014]
Where at least everything is happening on the client side. It would be nicer of course if filtering, paging and sorting are server side.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. 

For templates, there’s always a trade off between how much they act as demos versus how approachable they are. We’ve designed the existing ones to be what we think is the preferred balance. 

For features like paging/sorting/filtering, it would be preferable for there either to be an external tutorial, or a grid component that already has that built in.
