### ISSUE TITLE
Serverless architecture, confused about how I would use Server side mentioned here with Azure functions , event grid and general server less architecture

### ISSUE THREAD

**Issue by nativoplus** [aspnet/Blazor#1021]
I am tracking this project as it grows to move my company to it once it has reached a level of maturity I can feel comfortable with. My question is in regards the server side story that you guys covered AspNetLive community stand up. 

My question is what is the thoughts around the stories to use serverless architecture such as: 
Azure functions, event grid or other (app logic apps)
Will there be an "Azure Web App for Blazor". 

Our app:
Our application is a claim processing application for insurance companies like geico etc.. Because we have PII and the insurance is in several states in the US it is interesting to have a SAAS app.

**Comment by danroth27** [comment]
> Will there be an "Azure Web App for Blazor".

Not that we currently foresee. We think you would typically publish a server-side Blazor to Azure App Service like you would a normal ASP.NET Core app.

**Comment by ChristianWeyer** [comment]
Or to 'web app'-enabled Azure Blob Storage - much cheaper 😇

**Comment by danroth27** [comment]
Yes, for client-side Blazor Azure Blog Storage web app hosting is looking like a great option.
