### ISSUE TITLE
The directory name '/app/dist/' does not exist.

### ISSUE THREAD

**Issue by HK-Zhang** [aspnet/Blazor#1027]
I added docker support for the server project and click F5 to debug app in docker.
Then I get below exception at the code :  app.UseBlazor<Client.Program>();
System.ArgumentException: 'The directory name '/app/dist/' does not exist.'

**Comment by SteveSandersonMS** [comment]
We haven't yet made any attempt to work with VS's built-in docker support. Inevitably it's something we'll get to eventually, but for now you'll have to figure out the details of what makes it work yourself. Hope that's OK!
