### ISSUE TITLE
call IQueryable<T>.Count() will throw exceptions

### ISSUE THREAD

**Issue by edmundhuang** [aspnet/Blazor#1028]
It is easy to reproduce the error.    
1.  Create template project in Visual Studio.  
2.  Modify method "OnParametersSetAsync" in fetchData.cshtml as follow:  
``` cs
protected override async Task OnParametersSetAsync()  
 {  
       forecasts = await Http.GetJsonAsync<WeatherForecast[]>(  
            $"sample-data/weather.json?date={StartDate.ToString("yyyy-MM-dd")}");  
      var q=forecasts.AsQueryable();   

      //Count an IQueryable would throw exception.
       q.Count();
     
......
 }
```

3. Remember to add @using System.Linq in the beginnng of this page.
 
I had done this testing with the lastest blazor (0.4.0.0) package.
NETStandard.Library 2.0.3
![issue](https://user-images.githubusercontent.com/10094089/41664798-1d6700de-74d9-11e8-833b-7ef758963e23.png)

Thanks  
Edmund Huang

**Comment by vertonghenb** [comment]
I don't think it's a Blazor issue per se, but rather the interpreter of mono, see : https://github.com/mono/mono/issues/8872

**Comment by danroth27** [comment]
Might be a linker config issue. Try out https://gist.github.com/Suchiman/a5e65f40c353120c9cf7f6a631ded28b and see if it resolves the issue.

**Comment by danroth27** [comment]
I've confirmed that if I add `<BlazorLinkOnBuild>False</BlazorLinkOnBuild>` then the issue no longer repros, so it looks like this is in fact a linker issue.

**Comment by edmundhuang** [comment]
Yes, it work.
Modified .csproj file as below:
``` xml
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RunCommand>dotnet</RunCommand>
    <RunArguments>blazor serve</RunArguments>
    <LangVersion>7.3</LangVersion>
    <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
  </PropertyGroup>
```
The exception disappear, I got this message in console:
>Blazor is running in dev mode without IL stripping. To make the bundle size significantly smaller, publish the application or see https://go.microsoft.com/fwlink/?linkid=870414

The network, :
35 request, 6.3mb transfer 
Compareing to the original with IL stripping:
22 request, 1.8mb transfer

Thank you for providing a temp way for using LINQ.
However, still hoping this could be solved in the next linker builder release.

By the way, could you provide a basic sample with electron + blazor + server-side-rending?
I am quite interesting to try something in this way.

**Comment by danroth27** [comment]
@edmundhuang Right, turning of linking on build is a big hammer way of verifying that the issue is with the linker configuration. Instead of turning it off completely, you can configure the linker to preserve specific components. Try out the linker configuration shown here: https://gist.github.com/Suchiman/a5e65f40c353120c9cf7f6a631ded28b.

**Comment by edmundhuang** [comment]
@danroth27 
Try the linker configuration as your comment.
Before:
System.Core.dll    150kb
After:
System.Core.dll    191kb
