### ISSUE TITLE
Getting started templates not working

### ISSUE THREAD

**Issue by itorian** [aspnet/Blazor#1029]
I used getting started with Blazor [guidelines from here](https://blazor.net/docs/get-started.html) to configure environment. I'm not able to run any template either from Visual Studio Enterprise 2017 (Version: 15.7.1) or command line.

**Template: Blazor**

Created project in VS by selecting Blazor template, noticed SDK version 2.1.300 in global.json. When running this project with Ctrl-F5, opens up browser, displays 'Loading...' for few sec and then blank page.

After that tried command line option, which displays another error:

CSC : error CS1617: Invalid option '7.3' for /langversion. Use '/langversion:?' to list supported values. [C:\Users\abhimanyu\BlazorApp1\BlazorApp1.csproj]
The build failed. Please fix the build errors and run again.

**Template: Blazor (ASP.NET Core hosted)**

Created project in VS by selecting Blazor (ASP.NET Core hosted) template. When running this project with Ctrl-F5, this displays error:

![image](https://user-images.githubusercontent.com/3646552/41700221-08bf7a46-7545-11e8-9c6a-4a06e510bacf.png)

Any help on this ?

**Comment by SIkebe** [comment]
`dotnet --info` output under the project root?

**Comment by SIkebe** [comment]
And which version of Blazor extension are you using?

**Comment by itorian** [comment]
@SIkebe here's the output of dotnet --info:

C:\Users\abhimanyu\BlazorApp1>dotnet --info
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

**Comment by itorian** [comment]
@SIkebe Blazor extension version

![image](https://user-images.githubusercontent.com/3646552/41758604-745754fa-7607-11e8-9eb8-c3e0d8bf8646.png)

**Comment by SIkebe** [comment]
@itorian dotnet core SDK 2.1.300-preview1-008174 does not meet the requirement.
You need 2.1.300 RTM if you want to try blazor 0.4.0.
https://blogs.msdn.microsoft.com/webdev/2018/06/07/blazor-0-4-0-experimental-release-now-available/

**Comment by SIkebe** [comment]
Blazor 0.3.0 requires dotnet core SDK 2.1.300-preview2-008533 or later.
https://blogs.msdn.microsoft.com/webdev/2018/05/02/blazor-0-3-0-experimental-release-now-available/

**Comment by itorian** [comment]
Resolved. Thank you so much.
