### ISSUE TITLE
why Blazor must be Prerequisites java(JDK)  and node.js ?

### ISSUE THREAD

**Issue by sgf** [aspnet/Blazor#1030]
> want to wirte C# run on browser?
> first,you need install jdk and node.js .
> 

It looks funny

**Comment by davidfowl** [comment]
What did you read that makes you think you need nodejs and the jdk?

**Comment by SIkebe** [comment]
@sgf Who told you that?

**Comment by scottsauber** [comment]
I think he’s talking about the readme which talks about building the git repo (node) and running the tests (JDK via Selenium).

These are only required if you’re going to contribute to Blazor, not consume Blazor.

**Comment by danroth27** [comment]
Correct, node is only needed if you're trying to build the Blazor repo, and Java is only needed to run Selenium for the e2e tests. If you just want to try out C# in the browser you don't need either of those things. [Get started with Blazor](https://blazor.net/docs/get-started.html)
