### ISSUE TITLE
Unable to register component event without ParameterAttribute

### ISSUE THREAD

**Issue by fs86** [aspnet/Blazor#1032]
I noticed that events in custom components can only be registered from the parent component if ParameterAttribute is present. I have followed the example of @danroth27, which is described here: #610 

My custom component:
```csharp
<input type="text" value="@Value" onchange="@OnInputChanged" />

@functions
{
    [Parameter] string Value { get; set; }
    public Action<string> ValueChanged { get; set; }
    void OnInputChanged(UIChangeEventArgs e)
    {
        Value = e.Value.ToString();
        ValueChanged(Value);
    }
}
```

My parent component:
```csharp
<MyCustomComponent Value="@Product.Name" ValueChanged="@OnValueChanged" />

@functions
{
    void OnValueChanged(string value)
    {
        Product.Name = value;
        StateHasChanged();
    }
}
```

Output: "Cannot convert method group 'OnValueChanged' to non-delegate type 'object'. Did you intend to invoke the method?"

If I add [Parameter] to my event, everything works fine.

**Comment by chucker** [comment]
Since @danroth27's example is from before Blazor 0.3, my guess this is by design, since [0.3's release notes state](https://blogs.msdn.microsoft.com/webdev/2018/05/02/blazor-0-3-0-experimental-release-now-available/):

>Upgrade an existing project to Blazor 0.3.0
>To upgrade an existing Blazor project from 0.2.0 to 0.3.0:
>[..]
>Update component parameters to not be public and to add the `[Parameter]` attribute.

**Comment by fs86** [comment]
Many thanks for your response. Then it's probably not a bug.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @chucker!
