### ISSUE TITLE
YAML instead of XML?

### ISSUE THREAD

**Issue by ylluminate** [aspnet/Blazor#1035]
Just saw this project, looks interesting. I find the WASM + JS interop + a fully vertical isomorphic stack very appealing.  Perhaps similar to wonderful options like Ruby on Rails or Roda + Opal + Hyperloop.

Have you considered using YAML for config instead of XML?  I think readability of the language and things like configs are important to really making a stack appealing to devs.  Some folks might like XML, but honestly, it's not as quick to visually parse as a human being and I think decisions about readability and self documentation are important for popularity.

**Comment by SIkebe** [comment]
@ylluminate Which xml files?

**Comment by MihaMarkic** [comment]
No, please don't go YAML. It might work for small configs but certainly not for bigger ones and it has also many problems. Whereas XML is clear and useful.

**Comment by ylluminate** [comment]
Very much disagree, but of course I don't like most of the conventions that are used by .NET developers myself as they have so many negative aspects from a humane perspective. Just going to walk away from this since there doesn't seem to be any significant value to be gained by seeing which of us can relieve ourselves into the wind the farthest. 🤷🏼‍♂️
