### ISSUE TITLE
Add sections...

### ISSUE THREAD

**Issue by desalbres** [aspnet/Blazor#1038]
Hello, 

Could you add @section to razor views like in ASP.NET MVC ?

Thanks,

Raphaël Desalbres

**Comment by SteveSandersonMS** [comment]
We haven't decided yet whether this fits into the programming model, because components are much more powerful than what you'd normally get with sections and layouts. But in any case we're tracking the layouts design in #138 so I'll close as a duplicate of that.

**Comment by desalbres** [comment]
You're right, you shoud keep Blazor the simplest possible to target a broader developers audience !
I've leant angular2 and the learning curve for .NET developers seems steeper than Blazor ! Congrats of all the work done so far, can't wait to see RTM !
