### ISSUE TITLE
Debugging Blazor in Visual Studio

### ISSUE THREAD

**Issue by cwaldron** [aspnet/Blazor#104]
I am able to build the solution from the command line and run the sample from Visual Studio (good).
But when I set a breakpoint in Program.cs the debugger does not trigger the breakpoint.  

![image](https://user-images.githubusercontent.com/2838270/36081691-328cf234-1007-11e8-9b02-9916a0a2941d.png)

I need some guidance on how to properly setup debugging a Blazor application.

Thanks in advance.

**Comment by Postlagerkarte** [comment]
I assume that is currently not possible because there is no DebugAdapter in available -  David Fowler did some work on the adapter but it seems this code hasn't been merged into the current repository (yet?).

**Comment by SteveSandersonMS** [comment]
We don't yet have support for debugging the .NET code that's running inside the browser. That's a significant piece of work that the Mono team is currently making progress with. It's being tracked as #14.
