### ISSUE TITLE
Missing package Mono.WebAssembly.Interop

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/Blazor#1043]
When trying to update to build 10324, NuGet says: "Unable to find package Mono.WebAssembly.Interop. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, MyGet: Blazor-Dev, MyGet: Reactive Extensions, nuget.org

**Comment by TheFanatr** [comment]
I am experiencing the same issue with any new project I try to make.

**Comment by TheFanatr** [comment]
Below is a link to a Mega folder containing the NuGet packages relevant to `Mono.WebAssembly.Interop`. They are built from the latest source in release mode.
https://mega.nz/#F!f8NVCAYC!uiBp9vOq-NUv1vKEJkn4QQ

**Comment by SteveSandersonMS** [comment]
Thanks for reporting it! Now fixed.
