### ISSUE TITLE
Http Posts and Puts failing in Blazor 0.4.0

### ISSUE THREAD

**Issue by simonziegler** [aspnet/Blazor#1046]
Hi,

I have found that Posts and Puts have been failing in a test web app that I created with Blazor 0.3.0 once I update to 0.4.0. I do not know if this is due to an error I am making or a bug. I have isolated the problem to a few lines of code that I have added to an out-of-the-box Blazor 0.4.0 hosted project, which can be found at https://github.com/simonziegler/TestBlazorSendJson. I modified only FetchData.cshtml and SampleDataController.cs. I would really like to find out what is happening here and apply a fix or work around.

Thanks,     Simon

**Comment by Andrzej-W** [comment]
@simonziegler You have to add `[Produces("application/json")]` above your controller class
```C#
[Produces("application/json")]
[Route("api/[controller]")]
public class SampleDataController : Controller
```
Unfortunately I can not explain why it was not necessary for `WeatherForecasts()` method.

You also have to change
```c#
protected async void OnPostClick()
```
to
```c#
protected async Task OnPostClick()
```
Otherwise your UI is not updated after button click.

**Comment by Andrzej-W** [comment]
Strictly speaking your UI is updated but there is no response from WebAPI server yet. `Task` result type means that Blazor will refresh the UI automatically as soon as the task is completed.

**Comment by simonziegler** [comment]
Thanks on both counts - I'll give this a good shot tomorrow. It looks like your help has fixed the example I put on Github before, and I need to try this out with my main web app.

Thanks!

**Comment by Andrzej-W** [comment]
Now I'm a little smarter. I have read this: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1 (all chapters) and here https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.1 I have found that sentence:

> Note in this case the Content-Type returned is text/plain. You can also achieve this same behaviour using just a string response type.

If you want to return simple strings as JSON you have to use `[Produces("application/json")]`. Read more here https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.1#forcing-a-particular-format

Alternatively you can return objects. I have created a class like this:
```c#
public class ReturnMessage
    {
        public string Message { get; set; }
    }
```
and it is returned as JSON by default.

**Comment by simonziegler** [comment]
Aha! Looks like I need to climb the same get-myself-smarter curve. Will report back later!

**Comment by SteveSandersonMS** [comment]
Glad you sorted it out!

**Comment by simonziegler** [comment]
Hi,

Many, many thanks to @Andrzej-W, whose advice got this fixed. Here is a review of what I needed to get done:

First, I followed Andrzej's advice to the letter regarding Http api usage. if you are struggling as I was, please read the articles Andrzej referenced in detail - remember that they refer to ASP.NET 2.1. The reason my web app failed its update to Blazor 0.4.0 was due to my need for a rigorous approach to the api as I was moved to ASP.NET 2.1.

I also however bumped into another issue which runs as follows. My web app has a login screen when you start it up. Simple stuff: user name, password, "remember me" checkbox and a submit button. My `<button> … </button>` block was within the `<form> … </form>` block (where I had put it. When I click that button in Blazor 0.4.0 the client app just gets reloaded, fractionally after performing its `onclick` action. I moved the button out of the `<form> … </form>` block and this problem went away. @SteveSandersonMS - is this one that you want to take a look at?

Since my issue is now resolved (again, thanks to Andrzej) I will close the issue in a few hours if nobody else does so before me. If however @SteveSandersonMS wants to keep it open relating to that button thing, then naturally fine by me.

Kind regards,      Simon

**Comment by RyoukoKonpaku** [comment]
@simonziegler It's a known thing since 0.4 here #951. Did you try putting ```type="button"``` on the button element? What happened I presume was that it made the form submit which triggered the premature reload.

This is due to how 0.4 handles events. I think in the past versions it was preventing the submit occurring via calls to ```preventDefault()``` on events.
