### ISSUE TITLE
Error <LangVersion>7.3</LangVersion>

### ISSUE THREAD

**Issue by IyyappanAmirthalingam** [aspnet/Blazor#1048]
Hi,

When I try to create and run the Blazor app with the following steps it throws the follwing error 

**Steps 👍 
dotnet new -i Microsoft.AspNetCore.Blazor.Templates
dotnet new blazor -o BlazorApp1
cd BlazorApp1
dotnet run**

Error 👎 
**CSC : error CS1617: Invalid option '7.3' for /langversion. Use '/langversion:?' to list supported values. [C:\sample\BlazorApp1\BlazorApp1.csproj]**

**The build failed. Please fix the build errors and run again.**

Thanks.

**Comment by chucker** [comment]
What platform is this?

What does `dotnet --version` say?

**Comment by gustavobigardi** [comment]
@chucker 
Same here.

![image](https://user-images.githubusercontent.com/8357566/41995281-85f6837e-7a27-11e8-9baa-04abf617166c.png)

**Comment by chucker** [comment]
You need to upgrade your .NET Core SDK to at least `2.1.300`.

**Comment by danroth27** [comment]
Thanks for answering,  @chucker!

**Comment by gustavobigardi** [comment]
Thanks @chucker
