### ISSUE TITLE
RTM

### ISSUE THREAD

**Issue by FIVIL** [aspnet/Blazor#1049]
Hi, ive just seen this repo and ive got very excited about it, as im a huge fan of C# instead of JS so i was wondering when you guys are gonna release an RTM stable version of Blazor?, and also is there any documentation like the one for the ASP.net core in docs.microsoft.com or any where else??

tnx

**Comment by Webdiyer** [comment]
You can check this site for documentation :[https://blazor.net/](https://blazor.net/)

**Comment by iAmBipinPaul** [comment]
This is a hub for Blazor related stuff.
 https://github.com/AdrienTorris/awesome-blazor

**Comment by SteveSandersonMS** [comment]
We don't have a specific announcement about release plans yet, but are working on it and will let you know as soon as we do have a specific plan.
