### ISSUE TITLE
Unmount event support

### ISSUE THREAD

**Issue by wanton7** [aspnet/Blazor#105]
What are the plans for unmount event support? Called unmount in React, ngOnDestroy in Angular and beforeDestroy in VueJS?

Sample in old repository was using Bootstrap and anything using jQuery and many 3rd-party JavaScript plugins will leak memory / events if you just replace their HTML.
You need to remove them with jQuery or call functions in 3rd-party plugins to destroy them in unmount event.

**Comment by SteveSandersonMS** [comment]
The components themselves can implement `IDisposable` if they want notification on the .NET side when they are being removed. From the `Dispose` method, they could make a call into JS if they wanted to do any custom teardown of the associated DOM elements. The exact APIs for referencing a component's DOM elements are still under consideration.
