### ISSUE TITLE
Http header field always lowercased

### ISSUE THREAD

**Issue by liuxh0** [aspnet/Blazor#1058]
I'm trying to add custom header using:
```
StringContent body = new StringContent("");
body.Headers.Add("MyHeader", "value");
```

But the request headers are always lowercased, in this case I got `myheader: value`. Calling `TryAddWithoutValidation` does *not* help.

I'm aware that RFC 2616 says header fields should be case-insensitive. But if I use .NET Core/Framework, like if I create an Windows 10 App using Visual Studio, I can send http request *without* lowercased headers.

**Comment by Suchiman** [comment]
The browser is doing this so there's nothing we can do against it.

**Comment by liuxh0** [comment]
Hi @Suchiman , thanks for your reply.

But requests sent by `HttpClient` from Angular are correct. So I am pretending that browsers can do that.

**Comment by Suchiman** [comment]
My guess is that it works when you send and receive json but we request an arraybuffer response which made the headers become lowercase ( https://github.com/aspnet/Blazor/pull/815#issuecomment-388376320 ), i suppose for text the browser runs in a compat mode and keeps header name casing and in these new modes it lowercases them

**Comment by liuxh0** [comment]
@Suchiman , you are absolutely right!

Using **Fetch API** makes *request* headers *always* lowercased, indepent of what kind of response.

However, Angular uses **XMLHttpRequest** (I hope I'm looking the right place since it is really complicated because of dependency injection etc.), that's the reason why I have non-lowercased headers.
