### ISSUE TITLE
Question: getting component with no parameters to render on update

### ISSUE THREAD

**Issue by simonziegler** [aspnet/Blazor#1064]
Hi I have a custom component that can pull all its data from the state object, meaning that I call it like this:

`<div> <MyComponent /> </div>`

I have added `state.OnUserChange += StateHasChanged;` to the Component's `OnInit` function, however when `StateHasChanged()` is called, MyComponent does not render. Within MyComponent I display properties held within the `state` class that were updated prior to calling `StateHasChanged()`.

I can force an update by passing an otherwise pointless parameter to MyComponent, but this is a bit clunky. Any ideas?

Many thanks,     Simon

**Comment by SteveSandersonMS** [comment]
Could you post a minimal repro example? In general calling `StateHasChanged` should trigger a re-render, regardless of parameters, so I'd like to see if there's a bug.

**Comment by simonziegler** [comment]
Thanks @SteveSandersonMS, I’ll try to do this later today or tomorrow

**Comment by simonziegler** [comment]
Hi @SteveSandersonMS, please see https://github.com/simonziegler/BlazorComponentRenderTest. This is your standard Blazor install and I have added _MyComponent to the Counter page. It fails to render when the counter button is pressed (whether due to a bug or my faulty coding remains to be seen), but the component works correctly when you navigate away from and back to the counter page.

Kind regards, Simon

**Comment by SteveSandersonMS** [comment]
You're not calling `NotifyStateChanged` anywhere, so the `AppState` isn't raising its "changed" event. I've made mistakes like that too :)

**Comment by simonziegler** [comment]
Doh! Sorry for wasting your time.
