### ISSUE TITLE
Debugging Blazor BuildTools

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#107]
Please provide guidance/reference on how to debug the blazor build tools from VisualStudio

**Comment by SteveSandersonMS** [comment]
I'm not aware that anything different from VS's usual debug features it needed. I've certainly been using the VS debugger as normal.

**Comment by grahamehorner** [comment]
@SteveSandersonMS I’m unable to get a breakpoint to trigger in the build tools when building a blazor project ? some guidance or pointers would be helpful, I’ve never developed or debugged vs build tools before, tried binging for tips nothing helped
