### ISSUE TITLE
Incorrect values in disposeComponent (BrowserRenderer.ts)

### ISSUE THREAD

**Issue by uazo** [aspnet/Blazor#1071]
Some strange value after last commit (I think #1052)

![browserrenderer ts error](https://user-images.githubusercontent.com/29201891/42177132-e663a630-7e2b-11e8-9d85-11e435585c8c.png)

Renderer.RenderInExistingBatch seems correct, but SharedMemoryRenderBatch.disposedComponentIdsEntry returns invalid values.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this and for providing such a clear fix!
