### ISSUE TITLE
Blazor support removed, if you do this in installer.

### ISSUE THREAD

**Issue by anirudhagupta** [aspnet/Blazor#1074]
I assume you have installed the blazor extension and asp.net workload in visual studio.

now go to  setup: 

uncheck the asp.net and check the asp.net extension again, Blazor is gone.

**Comment by rynowak** [comment]
Hi, we don't control this behavior. VS feedback is a more appropriate place to report issues like this: https://msdn.microsoft.com/en-us/library/zzszcehe(v=vs.110).aspx
