### ISSUE TITLE
How Can i trigger a child component's event from parent

### ISSUE THREAD

**Issue by doga6488** [aspnet/Blazor#1088]
Hi, I am working on version 0.4.0
I know we can handle child component event's from its parent. But I am wondering that if can I do the opposite.Is there a way of function to do this?
Thanks in advance

**Comment by SteveSandersonMS** [comment]
You can get a reference to the child instance using `ref`, and then call a method on that class.

**Comment by SteveSandersonMS** [comment]
Sure. It hasn't made it into docs yet, but I wrote it up here: https://github.com/aspnet/Blazor/pull/685
