### ISSUE TITLE
Informational: Blazor works on iOS 12

### ISSUE THREAD

**Issue by simonziegler** [aspnet/Blazor#1089]
For future reference, I installed the iOS 12 beta on my iPad and Blazor no longer crashes in either Safari or Edge.

**Comment by GoranHalvarsson** [comment]
that is really great news!!

**Comment by SteveSandersonMS** [comment]
Excellent - thanks for letting us know!

**Comment by simonziegler** [comment]
My pleasure and thanks to the team for building Blazor. @SteveSandersonMS - this is your project so can I'll leave it to you to decide whether it is more helpful to leave this note open or to close it.

Kind regards,   Simon

**Comment by Andrzej-W** [comment]
@simonziegler I'm not a big fan of Apple devices. I purchased one iPhone 6s about 2-3 years ago just to test my ASP.NET Core application (and now Blazor). Could you tell me how can I install beta version of iOS. Do I have to register as developer in Apple?

**Comment by simonziegler** [comment]
@Andrzej-W, you will need to go to https://beta.apple.com/sp/betaprogram/. In short however:

- Apple have just moved to public beta, meaning that you don't need to pay to be an Apple developer (I waited for this before jumping in.
- Back your device up to a computer using iTunes, irrespective of whether you already have an iCloud backup. Apple warn that you cannot revert to iOS 11 unless you do a computer backup. This is the most important item on the list as it protects your (brutally expensive) device.
- Navigate to the beta programme website as above on your device. Once you have signed up and verified your account, Apply download a small program of some sort that instructs your device to allow an upgrade to iOS 12 from settings.
- Last, go to settings (perhaps after restarting your device - I forget on this point) and install iOS from the Software Update section.

That's it! Best of luck,

Simon

**Comment by Andrzej-W** [comment]
Thank you @simonziegler for precise instruction.

**Comment by simonziegler** [comment]
Do please let me know how it goes!

**Comment by SteveSandersonMS** [comment]
To keep things tidy, I'll mark this as closed.

Thanks again for letting us know, @simonziegler!
