### ISSUE TITLE
A directory of 3rd party Blazor components

### ISSUE THREAD

**Issue by MihaMarkic** [aspnet/Blazor#1096]
I'm sure this question has been asked before, but right now I can't find it:
is there a directory of 3rd party Blazor components.

It'd be certainly nice to have one.

**Comment by Suchiman** [comment]
There are some listed here https://blazor.net/community.html
There's also https://github.com/AdrienTorris/awesome-blazor

**Comment by MihaMarkic** [comment]
These should be more easily discoverable. Perhaps blazor team could put up an official listing somewhere, or just links to these.

**Comment by Andrzej-W** [comment]
https://blazor.net/ is an official site and at the top of the page you have a link to Community page where you can find a lot of links, including link to Awesome Blazor. It is probably hard to make it more discoverable.
Link to blazor.net is here:
https://github.com/aspnet/Blazor#getting-started

**Comment by MihaMarkic** [comment]
You are right, I take it back :)
