### ISSUE TITLE
How To Use Blazor With MVC

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Blazor#1106]
_From @Sheko007 on July 9, 2018 2:14_

Feature request?:

#### Description of the problem:

Can't Use Blazor With MVC 

 Microsoft.AspNetCore.App 

_Copied from original issue: aspnet/Mvc#8033_

**Comment by mkArtakMSFT** [comment]
@Sheko007, what are the issues you're facing? What version of ASP.NET Core are you trying to use it with?
/cc @danroth27, @rynowak

**Comment by danroth27** [comment]
@Sheko007 Blazor is a client-side framework similar to existing JS frameworks like React or Angular. You can use Blazor with any backend framework that you'd like, including ASP.NET Core. To create an Blazor app with an ASP.NET Core backend you can use the Blazor (hosted) template.
