### ISSUE TITLE
Blazor binding issue

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/Blazor#1109]
I have simple component to display two propeties.
On index page I generate this components from list with option to delete.
When I delete first one, seconds name is not updating, staying old value.
You can see [video](https://www.youtube.com/watch?time_continue=0&v=E25LA4MFzZo) too: 

Component
```
<div class="my-component">
    <h2>ID: @ID</h2>
    <h2>Name: @Name</h2>
</div>

@functions
{
    [Parameter]
    private int ID { get; set; }
    public string Name  = Guid.NewGuid().ToString("d").Substring(1, 8);
}
```
Index Page
```
@addTagHelper *, BlazorLib1
@using BlazorLib1;
@page "/"


<div>

    @foreach (var item in tmp_list)
    {
        <button type="button" class="close" aria-label="Close" onclick=@(() => RemoveItem(item))>
            <span aria-hidden="true">&times;</span>
        </button>

        <div>
            <Component1 ID="@item.id" ref="item.component" />
        </div>
    }

    <button class="btn btn-primary" onclick="@refresh">Refresh</button>

</div>

@functions
{

    List<myClass> tmp_list = new List<myClass>() {
          new myClass() { id = 1},
          new myClass() { id = 2} };

    public void refresh()
    {
        foreach (var item in tmp_list)
        {
            Console.WriteLine(item.id + ": " + item.component.Name);
        }
        Console.WriteLine("        ----          ");
        this.StateHasChanged();
    }

    public void RemoveItem(myClass a)
    {
        tmp_list.Remove(a);
        this.StateHasChanged();
    }

    public class myClass
    {
        public int id { get; set; }
        public Component1 component { get; set; }
    }
}
```

**Comment by Andrzej-W** [comment]
You are deleting element from the list (which is not the same as deleting component) and your page is rendered again. First component receives a new value for parameter `ID`. `Name` variable was initiated when component was created and there is no code to change it. Then Blazor removes second component from the page because it is not needed any more. 

You can also read this issue/answer: https://github.com/aspnet/Blazor/issues/1065#issuecomment-401641165

**Comment by Lupusa87** [comment]
Ok
I understand now how blazor is binding.
Already implemented dispose to my component and will do for all further components too.

I understand your logic why value not updated, so if I need to update UI, all properties should be binded.

Thank you!

**Comment by danroth27** [comment]
@Andrzej-W ej-W Thanks for answering!
