### ISSUE TITLE
@functions section be flexible enough to be placed in a separate file

### ISSUE THREAD

**Issue by irperez** [aspnet/Blazor#1111]
While it may be ideal to have the "@functions" section all on one single file, it may not scale well with a complex component or page.

Just like we can with JavaScript, it may be ideal to have an option to have the logic/code in a separate file.  In fact, if its in a separate file, i'd imagine intellisense and tooling is probably easier.

**Comment by danroth27** [comment]
We are tracking enabling this support via https://github.com/aspnet/Blazor/issues/278
