### ISSUE TITLE
MyGet Feed broken since rename of dev to master

### ISSUE THREAD

**Issue by Suchiman** [aspnet/Blazor#1113]
It seems that the renaming of the dev branch to master broke CI to https://dotnet.myget.org/gallery/blazor-dev

**Comment by SteveSandersonMS** [comment]
Thanks for posting.

I thought I already fixed it earlier this morning. Not sure whether you posted your issue before or after I fixed it.

Do you agree that it's not broken now?

**Comment by Suchiman** [comment]
Yes, seems to be working again 👍  (when i posted, the last build was 4 days ago, when the rename happened).
