### ISSUE TITLE
Is there a way to get the relationship between a child component and its parent component? 

### ISSUE THREAD

**Issue by yangyang80** [aspnet/Blazor#1121]
Hi,

I am a newer for Blazor. My component is as the following:
`<mycomponent>`
`<complexproperty1 propertya="true" propertyb="1"></complexproperty1>`
`<complexproperty2 propertya="true" propertyb="1"></complexproperty2>`
`</mycomponent>`
The child components are some complex properties of mycomponent. I want to get the relationship between the child component and its parent. For example, I want to get the parent component instance in complexproperty1. The complexproperty1 component has no dom element for it. But I cannot find a way to do that. Is there any way to get that? Any help would be appreciated.
BTW, I don't know if it is correct way to implement a Blazor component in this way.

**Comment by Lupusa87** [comment]
I think component reference will help a bit.
Please check this [article](https://blogs.msdn.microsoft.com/webdev/2018/05/02/blazor-0-3-0-experimental-release-now-available/)
Jump to - Capturing reference to components.
Not sure about this all :)

**Comment by yangyang80** [comment]
Thanks @Lupusa87 .
But I don't want to write the complexproperty1 component like the following:
`<complexproperty1 propertya="true" propertyb="1" ref="cp1"></complexproperty1>`
I want that way like web form controls. The child component could get some parent information.
I think we need consider supporting it.

**Comment by Lupusa87** [comment]
For now I don't think we have another way.
Maybe someone more competent will comment :)
I am new too.

**Comment by SteveSandersonMS** [comment]
It's up to the parent component whether it wants to expose information about itself to the child components. If it does, it can pass itself as a parameter to the children, e.g.:

    <SomeOtherComponent Parent=this />

**Comment by yangyang80** [comment]
I don't think it is a good way to use Parameter.
As we know, in web form, we use GridView:
```
<asp:GridView ID="GridView1">
            <Columns>
                <asp:HyperLinkField HeaderText="H1" NavigateUrl="http://baidu.com" Text="H1" />
                <asp:HyperLinkField HeaderText="H2" NavigateUrl="http://baidu.com" Text="H2" />
            </Columns>
 </asp:GridView>
```
The children tags in <Columns> are not fixed. We can add more columns there. How can I implement like this?
If we declare some parameters used to build the relationship between the component and the child component,
```
<asp:GridView ID="GridView1" grid="@gridView">
            <Columns parent="@gridView" collection="@columns">
                <asp:HyperLinkField HeaderText="H1" NavigateUrl="http://baidu.com" Text="H1" parent="@columns" />
                <asp:HyperLinkField HeaderText="H2" NavigateUrl="http://baidu.com" Text="H2" parent="@columns" />
            </Columns>
 </asp:GridView>
```
Do you think the attributes in the tags are a little redudant?
Is it possible the child component could obtain its parent component information in its some lifecycle method? Just like TagHelper of ASP.NET Core?

**Comment by danroth27** [comment]
Please note we are tracking the scenario of writing templated components more broadly with #404
