### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by twheelmaker** [aspnet/Blazor#113]
This looks **amazing**! Just trying to wrap my head around this...

What are the security implications of loading dlls/wasms in the sandbox? Couldn't a bad actor inject/replace arbitrary code into the runtime or is there some protection against that?

Power/battery benchmarking... how much more cpu expensive is mono js sitting idle vs plain js vm sitting idle?

Is it possible to package blazor www output as an electron/cordova/etc standalone mobile app? This makes my head hurt (in a good way).

Are you manipulating the dom directly from C# or just working against a shadow data model? How would one... for example, change css or visibility on an input field? Could the full js/window api be available through a cs wrapper?

**Comment by felipemullen** [comment]
Regarding your first question, this is addressed in [Steve's blog announcement](http://blog.stevensanderson.com/2018/02/06/blazor-intro/)

> Despite what a lot of developers first assume, it does not introduce new security concerns, because it isn’t regular assembly code (e.g., x86/x64 or similar) - it’s a new bytecode format that can only do what JavaScript can do

I would assume it would mean that if you are replacing a .dll in the client, you're going to accomplish about the same as if you were attempting to un-minify javascript code and modify it to your liking

The second question may also be addressed in the blog entry, although I can't recall. Either way, I'm pretty sure that the DOM is exposed via javascript, and the precompiled mono .dll is allowing us to interface with it, similar to asm.js

**Comment by SteveSandersonMS** [comment]
> how much more cpu expensive is mono js sitting idle vs plain js vm sitting idle

If it's idle, it should cause no additional CPU use.

> Is it possible to package blazor www output as an electron/cordova/etc standalone mobile app

Yes, that's what the build produces by default. Hosting it on an ASP.NET server is completely optional. You can just as easily host the static files in Node.js, PHP, GitHub pages ([example site](https://blazor-demo.github.io/)), cloud static file storage, etc.

> Are you manipulating the dom directly from C# or just working against a shadow data model

The Razor components render a UI tree then is then diffed against its previous version, with the delta then being applied to the DOM.

> Could the full js/window api be available through a cs wrapper?

Yes, full JS interop is available. You'll probably maximise perf by not using it in a very chatty way though, and try to keep most of your logic on the .NET side.
