### ISSUE TITLE
WebSockets support

### ISSUE THREAD

**Issue by YandyZaldivar** [aspnet/Blazor#1135]
There is this issue #20 tracking SignalR client support.

I am opening this to follow a standard client WebSockets implementation. Maybe it comes from Mono making `System.Net.WebSockets` available, a separate package/api using JavaScript interop or a new API for Blazor.

Is there any projection on this already?

**Comment by danroth27** [comment]
This should really be provided by the Mono folks.

**Comment by danroth27** [comment]
This issue was moved to mono/mono#9567
