### ISSUE TITLE
Cannot call a method without parameters from JavaScript to C#

### ISSUE THREAD

**Issue by Daendel** [aspnet/Blazor#1143]
When I try to call a method without parameters:

```
var method = Blazor.platform.findMethod("TransactionTypeCreator.Client",
                "TransactionTypeCreator.Client.Services",
                "AppState",
                "UploadInput");

Blazor.platform.callMethod(method, null, null);
```

I get an error in MonoPlatform.ts (line 51): 
`if (args.length > 4) {     <- Uncaught TypeError: Cannot read property 'length' of null`

Why do I need to pass parameters?

**Comment by Suchiman** [comment]
Try `Blazor.platform.callMethod(method, null, []);` instead

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @Suchiman. 

Since the APIs will be different in the next version, I’ll close this.
