### ISSUE TITLE
favicon.ico is not displayed in browser tab

### ISSUE THREAD

**Issue by malibVB** [aspnet/Blazor#1147]
How to set the favico.ico for an blazor app created with vscode?

This is not working:
 `<link href="favicon.ico" rel="icon" type="image/x-icon" />`

I also tried to copy the icon to the path of index.html
It's also not working.

**Comment by malibVB** [comment]
It is correct, I only wrote it wrong in this issue...

![unbenannt](https://user-images.githubusercontent.com/6638897/42888231-18e98b5a-8aa8-11e8-9502-3a10800083e4.PNG)

**Comment by jsakamoto** [comment]
Thank you for show me screen shot!

You should remove '/wwwroot/' path.

![image](https://user-images.githubusercontent.com/95908/42888741-d6ecda4a-8ae3-11e8-81cb-d09fe0b3d0f2.png)

**Comment by malibVB** [comment]
I already tried it out...
it's same...

**Comment by jsakamoto** [comment]
Huum...

By the way, this is not Blazor issue, I think.

Therefore, I recommend create a new thread on the StackOverflow.com, and close this issue.

If you create a new thread on the StackOverflow.com, I'll follow the thread.

**Comment by jsakamoto** [comment]
P.S.  
If you can publish all of the project source files to somewhere I can reach, I'll try to reproduce and resolve this issue.

**Comment by malibVB** [comment]
Your have right it is not a BLAZOR issue...

I tried it out with Firefox browser on another virtual machine...now the icon is there...

In the dev machine I'm using Edge.
Do I need any setting to show the icon?

**Comment by vertonghenb** [comment]
In not entirely sure but check if you have .UseStaticFiles()” in the startup.cs class

Met vriendelijke groeten

Benjamin Vertonghen

**Comment by Suchiman** [comment]
@malibVB sounds like it's cached in edge as not found.

**Comment by malibVB** [comment]
No, i didn't use this option...

**Comment by malibVB** [comment]
@Suchiman : Did you mean, I should clean the cache ? I already done it...

**Comment by SteveSandersonMS** [comment]
I’ll close this as it’s a general front-end web dev question rather than being about Blazor. Hope that’s ok.

**Comment by malibVB** [comment]
It's ok, thank you all...
