### ISSUE TITLE
Accidentally adding a Razor layout crashed Visual Studio

### ISSUE THREAD

**Issue by PeterHimschoot** [aspnet/Blazor#1164]
I added a MVC razor layout to my visual studio project Shared folder (by accident) and Visual Studio crashes continuously. 
I fixed this issue by manually deleting this view from the project using File Explorer.

**Comment by rynowak** [comment]
Do you have a call stack for the crash? You might be able to find this in event viewer.

**Comment by vertonghenb** [comment]
isn't this fixed by #1172?

**Comment by danroth27** [comment]
I'm not able to reproduce this with the latest Blazor release (0.5.1). If you are still hitting this issue please provide a call stack for the crash or provide detailed steps to reproduce the issue.
