### ISSUE TITLE
DateTime always displays as UTC

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/Blazor#1166]
DateTime values  always display as UTC time, rather than local time even when explicitly forcing `.ToLocalTime()`.

This:
```csharp
Console.WriteLine(DateTime.Now.ToLocalTime().ToString("HH:mm"));
```

displays UTC time.

**Comment by ransagy** [comment]
I have this as a workaround, But not the best thing either:
`new Date(new Date().toLocaleString("en-US", { timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone })).getTimezoneOffset() / 60 * -1;`

**Comment by RickStrahl** [comment]
Thanks all for clarification.

**Comment by jsakamoto** [comment]
[FYI] This is my workaround until [mono/mono#6368](https://github.com/mono/mono/issues/6368) is fixed.

- https://github.com/jsakamoto/Toolbelt.Blazor.TimeZoneKit
