### ISSUE TITLE
Blazor failed to load large fils

### ISSUE THREAD

**Issue by kant2002** [aspnet/Blazor#1167]
It is likely not Blazor issue per se, but I would be good if it fail more gracefully, if some inherent limitations from the Browser.

Basically I have following error in Chrome: 
```
mono.js:1 Uncaught (in promise) RuntimeError: memory access out of bounds
    at wasm-function[290]:104
    at wasm-function[2458]:125
    at wasm-function[563]:16
    at wasm-function[246]:115
    at wasm-function[2428]:33
    at wasm-function[2429]:41
    at wasm-function[4877]:10
    at Module._mono_wasm_string_from_js (http://localhost:58134/_framework/wasm/mono.js:1:173587)
    at ccall (http://localhost:58134/_framework/wasm/mono.js:1:5651)
    at http://localhost:58134/_framework/wasm/mono.js:1:6032
```

My scenario following. I have form with input file.
User select text file.
Then application load file, split by lines and process file.
When I load file with only 914KB it works. When I load larger file 7876KB it fails to load with aforementioned error. Not sure who is to blame.

**Comment by SteveSandersonMS** [comment]
Since this seems to be due to the underlying Mono WebAssembly platform rather than anything in Blazor, would you be able to report it to https://github.com/mono/mono? Please mention that this is WebAssembly-specific.

**Comment by kant2002** [comment]
@SteveSandersonMS Seems to be this is indeed could handled on the Blazor side. @kumpera suggest that this is due to way how Blazor configure memory in Mono/WASM. Seems to be there no explicit memory limits in the Blazor and Mono think that memory unlimited, and as such it does not report OOM. If you think it would be worth investigation closes, I could take a look, since I don't like my current workaround for an issue.

**Comment by kant2002** [comment]
@danroth27 thanks! From my understanding that's really the cause

**Comment by rpc-scandinavia** [comment]
Hi, I experience something similar today, with Blazor 0.7.

1) Form with file input, where I select one file.
2) Get data from JS using the File interface.
3) Get "WASM: GC_MAJOR: (LOS overflow)" error.

Everything works with files smaller then around 3 MB.

My first try, was to get the file content from JS in one big BASE64 string. That failed on +3 MB files.

My second try, was to get data from JS in smaller chuncks, and then build the Byte[] in C#. Thta failed on +3 MB files.

My last try, was to stop getting the data into a Byte[], and insted into a MemoryStream.
I discovered that the GC_MAJOR error occured, when I returned the Byte[] at the end of my GetData method (the return statement).
But when giving the GetData method a MemoryStream, and save the received data chuncks into that, I was able to pass the data back from my GetData method and pass it on to my PostData method.
Not I am stuck at:

    await this.httpClient.PostAsync(httpServerAddress, httpDataStream);

So I hope that it is fixed by https://github.com/aspnet/AspNetCore/issues/5617 or something else in Blazor 0.8 or soon.

**Comment by Suchiman** [comment]
@rpc-scandinavia `WASM: GC_MAJOR: (LOS overflow)` isn't an error, it's a debug message, telling you that a full GC occured because the large object heap is full.

**Comment by rpc-scandinavia** [comment]
Thank you @Suchiman, I copy that. I am still working on my problem, and can see that the server receives and responds correctly to the request. In the browsers "Network" I can see that the response to the POST is correct. But I get a exceptiion, which didn't show before I used the MemoryStream (unless I didn't wait long ernough  :-)


Error: System.InvalidOperationException at System.Threading.Tasks.TaskCompletionSource`1[TResult].SetResult (TResult result) <0x41c6f08 + 0x0001c> in <4b5441f51da44e28b14fa0baa2935bda>:0 at Microsoft.AspNetCore.Blazor.Browser.Http.BrowserHttpMessageHandler.ReceiveResponse (System.String id, System.String responseDescriptorJson, System.Byte[] responseBodyData, System.String errorText) <0x41b92b8 + 0x000e0> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0

**Comment by Suchiman** [comment]
@rpc-scandinavia this is more interesting `ReceiveResponse` is the function JS calls when the response has been received here https://github.com/aspnet/Blazor/blob/5deb85df8784800742e7a6d68575c67dd6fedb5a/src/Microsoft.AspNetCore.Blazor.Browser/Http/BrowserHttpMessageHandler.cs#L112
This should only be able to happen if someone were trying to set the Result twice or error it once and then try to set it

**Comment by rpc-scandinavia** [comment]
Okay @Suchiman, I have been poking around in "blazor.webassembly.js" with some "console.log"'s.

This is the response the browser reports in network response:

```
{
  "requestService": "postMuseumPictureImage",
  "requestGuid": "406b2e9a-566f-4d16-a069-7e962bee87e0",
  "responseCode": 0,
  "responseMessage": "Returning one record saved, with the guid '406b2e9a-566f-4d16-a069-7e962bee87e0'.",
  "responseMuseumPicture": {
    "guid": "406b2e9a-566f-4d16-a069-7e962bee87e0",
    "order": 0.0,
    "createdDate": "2019-02-22 22:32:51",
    "modifiedDate": "2019-02-22 22:32:51",
    "deletedDate": "0001-01-01 00:00:00",
    "deleted": false,
    "enabled": false,
    "description": "image/jpeg",
    "originalFileName": "IMG_4498.JPG",
    "originalFileSize": 10533250.0,
    "originalFileDate": "2016-08-20 09:12:02"
  }
}

```
And this is what I got from a "console.log" (i have wrapped the lines):

​```
headers: (7) 
​​0: Array [
	"content-disposition",
	"inline; \"response.json\" 
		creation-date=\"Fri, 22 Feb 2019 22:32:51 +0100\"; 
		modification-date=\"Fri, 22 Feb 2019 22:32:51 +0100\"; 
		read-date=\"Fri, 22 Feb 2019 22:32:51 +0100\";
	" 
]
​​1: Array [ 
	"content-length", 
	"662" 
]
​​2: Array [ 
	"content-type", 
	"application/json" 
]
​​3: Array [ 
	"date", 
	"Fri, 22 Feb 2019 22:32:51 +0100" 
]
​​4: Array [ 
	"last-modified", 
	"Fri, 22 Feb 2019 22:32:51 +0100" 
]
​​5: Array [ 
	"pragma", "public" 
]
​​6: Array [ 
	"server", 
	"Microsoft-NetCore/2.0" 
]
​​length: 7​​__proto__: Array []

​statusCode: 200
​statusText: "OK"
​__proto__: Object { … } blazor.webassembly.js:22:1

```
That content-disposition don't match the browser result.
