### ISSUE TITLE
Incorrect OutputPath when using $(MSBuildThisFileDirectory)

### ISSUE THREAD

**Issue by SlowLogicBoy** [aspnet/Blazor#1179]
I have `Directory.Build.props` file:
```xml
<Project>
    <PropertyGroup>
        <OutputPath>$(MSBuildThisFileDirectory)out\bin</OutputPath>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
</Project>
```
When I build Blazor app I get:
```
C:\Users\User\.nuget\packages\microsoft.aspnetcore.blazor.build\0.4.0\targets\Blazor.MonoRuntime.targets(11,5): 
    warning MSB3026: 
        Could not copy 
"C:\Users\User\.nuget\packages\microsoft.aspnetcore.blazor.build\0.4.0\targets\..\tools\mono\asmjs\mono.asm.js" 
        to 
"d:\Code\Git\MyApp\src\Client\WebApp\d:\Code\Git\MyApp\out\bin\netstandard2.0\dist/_framework/asmjs/mono.asm.js". 
    Beginning retry 1 in 1000ms. The filename, directory name, or volume label syntax is incorrect : 
'd:\Code\Git\MyApp\src\Client\WebApp\d:\Code\Git\MyApp\out\bin\netstandard2.0\dist\_framework\asmjs'  
[d:\Code\Git\MyApp\src\Client\WebApp\WebApp.csproj]
```
Output Path seems to be generated incorrectly:
`d:\Code\Git\MyApp\src\Client\WebApp\d:\Code\Git\MyApp\out\bin\netstandard2.0\dist\_framework\asmjs`

**Workaround:**
I added additional `Directory.Build.props` file in Blazor project directory:
```xml
<Project>
    <!-- Reference to my main Directory.Build.props -->
    <Import Project="..\..\..\Directory.Build.props" />
    <PropertyGroup>
        <!-- Override OutputPath with relative path -->
        <OutputPath>..\..\..\out\bin</OutputPath>
    </PropertyGroup>
</Project>
```

**Comment by SteveSandersonMS** [comment]
[As per docs](https://msdn.microsoft.com/en-us/library/bb629394.aspx), the `OutputPath` value must be relative to the project directory:

> OutputPath ... Specifies the path to the output directory, relative to the project directory, for example, "bin\Debug".

As such you shouldn't construct it as an absolute path using `$(MSBuildThisFileDirectory)`. You might be able to use the info from `$(MSBuildThisFileDirectory)` but you will have to convert the result to a relative path.

**Comment by natemcmaster** [comment]
I ran into this as well. It's pretty common for users to set OutputPath to an absolute path, regardless of what the docs say. Repos like dotnet/corefx and dotnet/roslyn do this.

The fix is pretty simple. Blazor targets need to use `$(TargetDir)` instead. This is more idiomatic. MSBuild takes care constructing `TargetDir` by combining all properties which may affect the output directory and normalizing it to an absolute path.

**Comment by natemcmaster** [comment]
@SlowLogicBoy fixed with PR https://github.com/aspnet/Blazor/pull/1271, which should be in the next release.
