### ISSUE TITLE
DLLImport Native Libraries 

### ISSUE THREAD

**Issue by skyne98** [aspnet/Blazor#1195]
Hey everyone!
I was wondering if it is possible already, or theoretically should be possible to use native LLVM WASM backend, or Emscripten to allow the app to use it's required native binaries?

As far as I understand, that should be possible to achieve and will allow to easily use already existing C# libraries such as LLVMSharp in the browser.

Thanks!

**Comment by Chtau** [comment]
Hi,
you can work with reflection to use nativ Net Libraries.
I'm testing this functionality in one of my repos (https://github.com/Chtau/BlazorWebWinClient).

Currently im upgrading to 0.5 Blazor but the Version build with 0.4 can load NET 4.7 DLL x64.

**Comment by skyne98** [comment]
@Chtau, as far as I can see, you are talking about loading and using .NET libraries, whereas I am talking about actually interacting with native libraries, such as LLVM, for example.

**Comment by peter0302** [comment]
You don't mean "native" as in compiled x86 or x64 machine language do you? That would never be possible afaik. 

Or do you mean invoking other WASM assemblies through interop? That would be wonderful.

**Comment by peter0302** [comment]
I think I understand but just to clarify - so for example if someone got PDFium or FFMpeg or whatever to compile to WASM, you'd want to then be able to use native interop in C# to access that right?

Agreed. I think the Mono team might be working on that. It sounds like it's outside the scope of Blazor but I would definitely like to see that ability.

**Comment by danroth27** [comment]
Native dependencies would need to be compiled to WebAssembly first at which point you could invoke them through JavaScript interop. 

It might also be possible for us to enable calling directly into WebAssembly from .NET (which is already running on WebAssembly), but I'm not certain. @kumpera @SteveSandersonMS  thoughts on this?

**Comment by kumpera** [comment]
It's theoretically possible, but it requires a lot of changes to the toolchain.

There's support for emulating shared libraries with emscripten (out C toolchain) but that comes with a significant perf & footprint cost.

Alternatively, we could link the native lib with the runtime and generate some glue code. For that to work, our toolchain needs to add such support.

It's on our radar, just not a priority. I suggest you voice your opinion in the issue so we can better understand how important it is to our users. https://github.com/mono/mono/issues/8007

**Comment by danroth27** [comment]
Thanks @kumpera! Since this issue is being tracked in the Mono repo I'm going to close this one as external.

**Comment by skyne98** [comment]
Anyways, is there a way to, for example, hack in a bunch of WASM compiled rust code without resorting to make them communicate through JS?

**Comment by SteveSandersonMS** [comment]
@skyne98 Not that I know of. It would involve creating an entire interop system, without there being any clear rules about what types of data can be exchanged.

**Comment by skyne98** [comment]
@SteveSandersonMS, you can always exchange basic serializable data for the beginning

**Comment by sourceskyboxer** [comment]
Hello everyone, I am sorry disturb your issue.
I see like you mean DLLImport works same to Webassembly right?
What does it see in DllImport? You mean native-library.js in [DLLImport("native-library")] or native to current operating system? with xml / config in web directory and DLLImport will check if you are working at Windows than web assembly will know your operating system and detect dll file, right?

Or I understand wrong? I am sorry my bad English.
