### ISSUE TITLE
Chrome: ASP.NET Core Hosted Blazor app does not start if Windows authentication is enabled (Blazor 0.5.0)

### ISSUE THREAD

**Issue by radek7210** [aspnet/Blazor#1200]
Scenario: I have a Blazor app created using the „ASP.NET Core hosted“ template, using IISExpress to run the app. On the server project, I have the „Enable Windows authentication“ checkbox ticked, ie. the corresponding part of lauchSettings.json file is
```code
"iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false,
    "iisExpress": {
      "applicationUrl": "http://localhost:8000/",
      "sslPort": 0
    }
  }
```

When I try to launch the application in Chrome, the Console shows an error and the application will not start:

```code
blazor.webassembly.js:1 GET http://localhost:8000/_framework/blazor.boot.json 401 (Unauthorized)
blazor.webassembly.js:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at Object.<anonymous> (blazor.webassembly.js:1)
    at blazor.webassembly.js:1
    at Object.next (blazor.webassembly.js:1)
    at i (blazor.webassembly.js:1)
```

The “Network” tab indicates a problem with loading the blazor.boot.json file using the “fetch” method (screenshot attached).
![chromefetcherror](https://user-images.githubusercontent.com/41726008/43272916-6e5f7bcc-90fb-11e8-9fdf-3eab4083d6a6.png)

 

The problem started to show after updating Blazor to 0.5.0. Before the update, all was working fine.
I’ve tried many things to troubleshoot the issue:
- in Firefox and in Edge, the same app works fine
- I have tried to set-up CORS middleware on the server-side, no luck (but then I am not sure if this issue is related to CORS at all)
- if I run the Fiddler debugging proxy sitting between Chrome and the IISExpress server, the issue miraculously disappears and the application launches fine even in Chrome (after disabling Fiddler, the issue re-appears)
- tried to empty Chrome cache, disabled all extensions in Chrome, disabled all unnecessary middlewares in the server app -> no luck

Do you have any suggestions what might be wrong? Thanks.

**Comment by danroth27** [comment]
We may be missing some parameter on the fetch request that we make to retrieve *blazor.boot.json*. We'll need to investigate

**Comment by radek7210** [comment]
I can confirm that adding a parameter to the fetch() method that loads the blazor.boot.json file will fix the issue:

blazor.webassembly.js

Original (produces the 401 issue):

```javascript
return[4,fetch("_framework/blazor.boot.json")]
```

Modified (works ok):

```javascript
return[4,fetch("_framework/blazor.boot.json",{method:'Get',credentials: 'include'})]
```

**Comment by chris-ray** [comment]
I published a server-side blazor app to Azure with windows auth enabled and am seeing something similar. Will this be fixed in 0.6 @danroth27 ?

**Comment by danroth27** [comment]
@chris-ray I'm guessing with server-side Blazor the SignalR client will fail to establish a connection to the server when Windows authentication is enabled. So, technically it is a separate issue, but related enough that I think we can track both issues here. 

This isn't planned for 0.6.0 at this time because of other priorities. It's fine if someone wants to take a shot at fixing this though.

**Comment by SteveSandersonMS** [comment]
Fixed with #1349 (thanks, @chris-ray!)

**Comment by SteveSandersonMS** [comment]
Oh, spoke too soon. This issue also covers a related matter about opening the SignalR connection for the server execution model, which is not addressed by #1349.

**Comment by chris-ray** [comment]
#1349 should resolve my issue about server side, was there something else?

**Comment by SteveSandersonMS** [comment]
@chris-ray Oh wait, sorry, yes you were the one reporting that originally! So it sounds like this is resolved.
