### ISSUE TITLE
An error occurred while starting the application.

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Blazor#122]
Hello,

I got the following exception when trying to run the StandaloneApp :

![image](https://user-images.githubusercontent.com/1798510/36260333-5fb4b718-1261-11e8-8c9c-dedfd820429b.png)

**Comment by grahamehorner** [comment]
@MaherJendoubi a silly question, your not running the project in release?

**Comment by MaherJendoubi** [comment]
@grahamehorner  no, I'm running the project in debug.

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/36261631-4a360d66-1265-11e8-8fd7-72ef0351ffa3.png)

**Comment by grahamehorner** [comment]
@MaherJendoubi another silly question tried running VS as Administrator? I'm sure you would have, but just thought id ask.

**Comment by RyoukoKonpaku** [comment]
@MaherJendoubi try deleting the netcoreapp2.0 directory, fixed mine by doing that. If I recall the aspnet team switch from netcore to netstandard on the project type for Blazor.

I'd guess that netcoreapp directory is a remnant of a past build before the change.

**Comment by campersau** [comment]
See https://github.com/aspnet/Blazor/commit/a79775a28e9bc4bda8a05658985617fbc0b3c82b

> Do a "git clean -xdf" on your local copy if you get runtime errors after
updating to this.

**Comment by MaherJendoubi** [comment]
@RyoukoKonpaku By deleting the netcoreapp2.0 directory, it works now! Thanks a lot.
![image](https://user-images.githubusercontent.com/1798510/36271558-3b2c013a-127f-11e8-8306-e9483f23ee46.png)

**Comment by MaherJendoubi** [comment]
It's also fixed in the source code thanks to @SteveSandersonMS : https://github.com/aspnet/Blazor/commit/4f0330b1f10798fcdd625541db952e5380e7867c
