### ISSUE TITLE
can't build default blazor project in 0.5.1

### ISSUE THREAD

**Issue by ghost** [aspnet/Blazor#1225]
can't seem to build the default blazor project in 0.5.1:

```
Error	MSB3073	The command "dotnet "C:\Users\R\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json obj\Debug\netstandard2.0\WebApplication6.dll --references "C:\Users\R\Source\Repos\WebApplication6\WebApplication6\obj\Debug\netstandard2.0\blazor/bootjson-references.txt" --embedded-resources "C:\Users\R\Source\Repos\WebApplication6\WebApplication6\obj\Debug\netstandard2.0\blazor/embedded.resources.txt" --linker-enabled --output "C:\Users\R\Source\Repos\WebApplication6\WebApplication6\obj\Debug\netstandard2.0\blazor/blazor.boot.json"" exited with code -2147450730.	WebApplication6	C:\Users\R\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\Blazor.MonoRuntime.targets	635	
```

**Comment by chucker** [comment]
Error	MSB3073	The command "dotnet "C:\Users\R.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets../tools/Microsoft.AspNetCore.Blazor.Build.dll"

Is this the actual output, or was something swallowed during paste? Because it looks like your `.nuget` folder has a broken path. It should presumably be `C:\Users\R\.nuget`. Does `C:\Users\R.nuget` (note lack of backslash after `R`) exist?

This seems like a broken NuGet installation.

**Comment by danroth27** [comment]
@chucker Looks like that was just a markdown formatting issue, which I went ahead and corrected.

**Comment by MitchellEnsink** [comment]
I was having the same issue when upgrading from 4.0 to either 5.0 or 5.1.

My .NET version was: 2.1.300-preview2-008533
Upgrading to 2.1.302 seems to have fixed it for me.

**Comment by jtavenner** [comment]
I had the same error and upgrading to 2.1.302 corrected it.  The [Blazor Tutorial](https://blogs.msdn.microsoft.com/webdev/2018/03/22/get-started-building-net-web-apps-in-the-browser-with-blazor/) links to 2.1.300 instead of 2.1.302.

**Comment by SteveSandersonMS** [comment]
I've checked this on 2.1.300 and it's working OK, so I guess this only occurs on the 2.1.300-preview builds as mentioned by @MitchellEnsink.

**Comment by Structed** [comment]
I just have had a similar issue while upgrading to Blazor 0.5.1, but with a newer `dotnet` version.

However, when running `dotnet build`, it revealed another dependency i took (in my case `blazor-redux`) [was the cause of the issue](https://github.com/torhovland/blazor-redux/issues/10).
