### ISSUE TITLE
How work blazor on iOS version 9?

### ISSUE THREAD

**Issue by treenew** [aspnet/Blazor#1228]
iOS11+  It's work.
iOS10+ and  Blazor.Polyfill.js   It's work.
iOS9 Is't not work.

**Comment by ghidello** [comment]
Apple should have fixed the safari issue that is blocking ios 11 in the upcoming version 12 (hopefully). Accordingly to “can I use” webassembly support in ios is present starting with version 10.3 https://caniuse.com/#feat=wasm

**Comment by treenew** [comment]
@ghidello thanks.

**Comment by danroth27** [comment]
@ghidello Thanks for answering!
@treenew As we get farther along with the Blazor project we'll publish clearer statement on exactly which browser versions are supported. Right now we're focused on getting basic functionality working.
