### ISSUE TITLE
MarkupString automatically closes tags?

### ISSUE THREAD

**Issue by Worble** [aspnet/Blazor#1230]
Basic recreation:
```html
@((MarkupString)"<p style=\"background-color:red;\">")
@test
@((MarkupString)"</p>")

@functions {
    string test = "test test test";
}
```
Expected:
Html markup should look like:
```html
<p style="background-color:red;">test test test</p>
```

Actual:
Html markup is instead:
```html
<p style="background-color:red;"></p>test test test
```

Using Blazor 5.1

**Comment by uazo** [comment]
and because
```
var i = document.createElement("div");
i.innerHtml = "</p>";
console.log(i.children.length); // is zero
```
is empty so any output.

**Comment by Worble** [comment]
Thanks, that makes sense. I was kind of assuming that the implementation would be a clone of `Html.Raw()`. I hope there are plans to achieve that same functionality.

**Comment by Suchiman** [comment]
@Worble while (MVC) Razor builds strings that get sent to the browser (and thus only need to be eventually valid), Blazor manipulates DOM Elements (thus needing to be immediately complete) which is entirely different in that regard.
When you render a Markup string, it needs to be "complete".

**Comment by Suchiman** [comment]
There is no string built, e.g. `FetchData.cshtml` ends up being compiled to https://gist.github.com/Suchiman/c02bbb9317f16a8cfdd47b3d35fef220
But none of your samples so far indicate any need to use MarkupString in the first place so please Provide a better example.

**Comment by Worble** [comment]
Looking more closely at it, my component was doing too much and refactoring it into smaller components allowed me to eliminate the need for the raw html. Thanks for the help guys!
