### ISSUE TITLE
What's the best way to access innerhtml of a div

### ISSUE THREAD

**Issue by Knudel** [aspnet/Blazor#1235]
I am creating an HTML editor like this:

`<div id="mytextarea" class="CoreEditor" contenteditable="true" spellcheck="false"></div>`

The editor is in a component.
I want to bind (two way) to the InnerHTML of the div, but how can I do that?

Reading and writing the innerHtml through javascript:"

`document.getElementById(selector).innerHTML = value;`

is resulting that the dom seems not always be ready when I bind.

There doesn't seem to be a bindable InnerHTML?

What is the best way?

**Comment by Andrzej-W** [comment]
This is not the answer to you question, but it is probably the answer to your problem :smile:
https://github.com/EdCharbeneau/BlazeDown
At the bottom of GitHub page there are links to online demo and blog post.

**Comment by Knudel** [comment]
Hello Andrzej-W,

I looked at Blazedown but it is binding to a TextArea, this is no problem in Blazor.

I want to hide markup language for my users, so I want an HTML editor.
 
My problem is that I want to bind to the InnerHTML not the tekst of an input of textarea (contenteditable enables this).

**Comment by chucker** [comment]
>I want to hide markup language for my users, so I want an HTML editor.

You cannot currently access the DOM from WebAssembly, so you'll be doing a lot of JS interop.

**Comment by Andrzej-W** [comment]
If you want to create true WYSIWIG editor it is in my opinion impossible in Blazor without JavaScript. Simple examples: how to read current caret position, how to read current selection, etc.

It easy to display editable html in Blazor 0.5:
```html
<div id="mytextarea" class="CoreEditor" contenteditable="true" spellcheck="false">
    @((MarkupString)myhtml)
</div>
<p>HTML: @myhtml</p>
```
```c#
@functions
{
    string myhtml = "<p><b>Bold</b>text</p>";
}
```
But I think you have to use JavaScript to read edited `innerHTML`.

**Comment by danroth27** [comment]
> it is in my opinion impossible in Blazor without JavaScript

Yes, you currently may need to write some JS interop code to read the div content, but it's still pretty straight forward to do: https://blazor.net/docs/javascript-interop.html.

I also would have expected that you could hook the `oninput` event to handle content changes, but it looks like we don't expose the changed value. I've filed https://github.com/aspnet/Blazor/issues/1236 to track that.

**Comment by danroth27** [comment]
We also are tracking using bind with oninput here: https://github.com/aspnet/Blazor/issues/821

**Comment by PirasannaRavi** [comment]
`bind-value-oninput` or `bind` does not work with `contenteditable` divs.

In the below code, the expectation is as and when I edit the div content I need to update the model so that I can then later save it back. 

`<div contenteditable="true" bind-value-oninput="@contentEditableText">
                                               You can Edit this Text
                                            </div>
                                            @contentEditableText`

`@functions {
    string contentEditableText = "You can Edit this Text";
}`
