### ISSUE TITLE
<ClassName> contains multiple public properties with names case-insensitively matching 'children'. Such types cannot be used for JSON deserialization

### ISSUE THREAD

**Issue by RE-Butler** [aspnet/Blazor#1239]
This error occurs in the JS console on this line:

`Containers = await Http.GetJsonAsync<Namespace.dto.Container>("apiURL");`

Here is Namespace.Container:

```csharp
namespace Namespace  
{
    public class Container
    {
        public Guid ContainerId { get; set; }
        public string Name { get; set; }
        public Guid ParentId { get; set; }
        public string Barcode { get; set; }
        public float Height { get; set; }
        public float Width { get; set; }
        public float Length { get; set; }
        public Guid ContainerTypeId { get; set; }
        public Guid LoadId { get; set; }
        public Guid AreaId { get; set; }

        public Container Parent { get; set; }
        public ICollection<Container> Children { get; set; }
        public ICollection<Inventory.Item> Items { get; set; }
        public Area Area { get; set; }
        public ContainerType ContainerType { get; set; }
        public Orders.Load Load { get; set; }

    }
}
namespace Namespace.dto {
    public class Container : Namespace.Container
    {
        public bool Included { get; set; }
        public new ICollection<Dto.Container> Children { get; set; }
        public new ICollection<Inventory.Dto.Item> Items { get; set; }
    }
}
```

All I am doing in the controller is instantiating a Namespace.Container, putting some values in the properties, and then returning it.

When I use Http.GetStringAsync, I can see the JSON as expected.

**Comment by lohithgn** [comment]
Namespace.dto.Container inherits from Namespace.Container. Namespace.Container is the parent now and it already defines Children property. Namespace.dto.Container is also defining Children property. So the error is saying the right thing ? what are you trying to do ? whats the scenario ?

**Comment by RE-Butler** [comment]
The inheritance is because dto.Container is a dto class with additional properties ("included"). The "Children" property is overridden/hidden with the "new" keyword. 

I didn't include **_dto_** the Namespace.**_dto_**.Container in the original question, but I fixed that. My expected behavior is that it would serialize the json that the api controller makes out of a Namespace.dto.Container into a Namespace.dto.Container on the client-side.

**Comment by danroth27** [comment]
Thanks for reporting this issue! Our current JSON serialization support is limited. Long-term we expect to replace it with a more complete implementation, but for now you either need to live with the limitations or switch to a more fully featured JSON serialization library (ex Json.NET). Since we are trying to limit investment in our current JSON serialization support, I'm going to go ahead and close this issue.

**Comment by RE-Butler** [comment]
What is the actual limitation so that I can try to work around it? Is the the fact that I am inheriting and overriding a property? The data type of the property? Or something else?

**Comment by Andrzej-W** [comment]
> Is the the fact that I am inheriting and overriding a property?

Probably.
Simple solution which should work:
* remove Children and Items from Namespace.Container
* remove `new` from Namespace.dto.Container
* create a new class in Namespace which inherits from Container and adds Children and Items.
