### ISSUE TITLE
Bind properties of a class to form values

### ISSUE THREAD

**Issue by enetstudio** [aspnet/Blazor#1244]
Can I create a class, as for instance:

```csharp
public class InputModel
 {
            public string Email { get; set; }
             public string Password { get; set; }
            public bool RememberMe { get; set; }
  }
```

And then bind the values of input elements to the properties of this class, this way:

```html
   <input type="text" bind="@Input.Email" class="form-control" />
```

**Comment by simonziegler** [comment]
Yes. Just give it a go. I have this up and running.

**Comment by danroth27** [comment]
Yup, should work fine. Let us know if you hit any issues with this.

@simonziegler Thanks for answering!
