### ISSUE TITLE
checknodejs -v 8.3.0 exited with code -2147450751

### ISSUE THREAD

**Issue by ppumkin** [aspnet/Blazor#125]
I have downloaded the source code as per instructions.

I have just installed node.js and from command line on any path

```
node --version
v8.9.4
```

When I try to build a sample project in Visual Studio 2017 (15.5.6)

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB3073	The command "dotnet "C:\Code\Other\Blazor\src\Microsoft.AspNetCore.Blazor.BuildTools\tools/Microsoft.AspNetCore.Blazor.BuildTools.dll" checknodejs -v 8.3.0" exited with code -2147450751.	Microsoft.AspNetCore.Blazor.Browser.JS	C:\Code\Other\Blazor\src\Microsoft.AspNetCore.Blazor.Browser.JS\Microsoft.AspNetCore.Blazor.Browser.JS.csproj	25	

I have identified the build target. BuildTools builds OK

```
<Target Name="EnsureNpmRestored" Condition="!Exists('node_modules')">
    <Exec Command="$(BlazorBuildToolsExe) checknodejs -v 8.3.0" />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec Command="npm install" />
  </Target>
```

**Comment by SteveSandersonMS** [comment]
I think if you just rebuild the solution again, it will work. That crazy error code implies something like "the executable does not exist", which it should do if you rebuild.

If this doesn't fix it, I'm afraid it's something you'll need to debug yourself. This is currently working OK in CI and on various developer machines in our team, and it's only an aspect of working on Blazor itself (as opposed to building a Blazor app). Hope that's OK!

**Comment by grahamehorner** [comment]
The issue doesn’t occur when building from the commandline, it only seems to occur from VS2017 v15.5.6
