### ISSUE TITLE
Blazor 0.5.0 is heavy

### ISSUE THREAD

**Issue by Amine-Smahi** [aspnet/Blazor#1264]
Since the new update of blazor, the standard blazor project size changed from 2.1mb to 4.48 wich is the double size. the community wont use a ui framework that eats 4mb from the user bandwidth.

![image](https://user-images.githubusercontent.com/24621701/43705762-69fedde4-995b-11e8-852d-26d585bdedc6.png)

**Comment by SteveSandersonMS** [comment]
I agree that minimising the payload size is extremely important. We hope to put in a lot of optimisations to bring down the size.

The good news however is that it **hasn't** increased to 4MB :) You're looking at the uncompressed size there. The real amount of data transferred over the network is the figure on the bottom to the right, i.e., 1.83MB, which is almost exactly the same as it was before the 0.5.0 update.

**Comment by Amine-Smahi** [comment]
Thank you @SteveSandersonMS
