### ISSUE TITLE
Hosted in Single dll

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/Blazor#1266]
Currently the the hosted solution gives us 3 projects.

I prefer to use "Feature Folders" Jimmy Bogard Style.

a Feature contains:
* Controller
* Request
* Response
* DTOs 
* Handler
* Validator
* Mapper 
* Presentation 
* Entity

Given the 3 projects my folder has to be split up. something like:

Server:
* Controller
* Handler 
* Mapper
* Entity

Shared:
* Request
* Response
* Validator
* DTOs

Client:
* Presentation

Could we get Blazor to build a hosted version with server side API and client as single project and dll?

Then my feature folder would be united once again.  And things would be easier to reason about.

And deployment becomes easier.  1 dll.  

I am sure there are downsides also :)

**Comment by danroth27** [comment]
> Could we get Blazor to build a hosted version with server side API and client as single project and dll?

I think that would be a bit awkward. The client assembly gets downloaded and executed in the browser. It would be strange to include in that assembly server specific concerns like controllers. This server specific code would almost certainly not be work in the browser, so it would be strange to include it with the client-side logic. It would also increase the size of the client assembly.

**Comment by StevenTCramer** [comment]
@danroth27  One would NOT want the whole thing downloaded to the client for sure.  As you state controllers don't make any sense there.  Nor does the DbContext etc.  But if you are building another assembly (wasm) from a source Entry point in the project.  Then IL stripping could and should eliminate all of that right?

I realize that is pushing a ton of logic into the Linker process.  But if we are going to reuse existing .net assemblies and push them to the client without stripping out all the unused code then we are going to have limited options due to size.

I have not looked at how all the IL stripping works so I am only guessing.  

Thanks for responding quickly and all the work you are doing.

**Comment by danroth27** [comment]
Yeah, I thought about that, but then you would need to assembly outputs from the sample project: the unlinked version for the server and the linked one for the client. .NET projects don't typically work that way; you generally only have one assembly output per project. That's one of the reasons why the client and server projects are separate.

I think you could do something closer to what you want though with server-side Blazor, since everything is really running on the server.

**Comment by StevenTCramer** [comment]
Server Side isn't really what I want...  How do you do a PWA offline with that?

But was just looking over IlLinker and yea your right I almost want the client to be a project that just passes the same project back through ILLinker with a different `root`.  Which would as you say have two outputs one for the client and one for the server.  For sure not traditional.  

But sticking with traditional will only get traditional results. :)  Of course not sticking with traditional can give us exceptional failures also :)

I agree It is too early in the process right now.  And I don't know enough about all the pieces. Maybe revisit later.

Thanks again.
