### ISSUE TITLE
Blazor breaks Orchard Core CMS middleware pipeline

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Blazor#1267]
If I just reference `Blazor.Server` it breaks Orchard Core CMS middleware I CSS is not served

Try repro in https://github.com/msproadshow/Orchard/tree/blazor-conference

TheConferenceTheme references `Blazor.Server`
Orchard.CMS.Web references TheConferenceTheme and runs.
Immediately setup screen is displayed broken.

**Comment by xperiandri** [comment]
Maybe related to https://github.com/aspnet/Blazor/issues/1216

**Comment by SteveSandersonMS** [comment]
Yes, closing as duplicate of #1216. Thanks for reporting it though!

**Comment by xperiandri** [comment]
What about a fix to that issue?

**Comment by SteveSandersonMS** [comment]
If you’re asking if this is already fixed, then no sorry - that’s why #1216 is still open.
