### ISSUE TITLE
Unable to use Microsoft.AspNetCore.Identity.SignInManager with Blazor Server Side

### ISSUE THREAD

**Issue by simonziegler** [aspnet/Blazor#1268]
Hi,

I have a Client/Server Blazor project that, among other things, authenticates users using Microsoft.AspNetCore.Identity. The relevant controller uses the SignInManager class from identity.

I am experimenting with migrating this project to Blazor Server Side so that I can improve performance. Calls to a SignInManager object fail however. What I have (unsuccessfully) attempted to do is to make the pre-existing controller a service that is consumed by the App project. Referencing it is fine however I get an exception on calling SignInManager.PasswordSignInAsync. Is this because there is no HttpClient access from the App project, and if so is there a way that I can make this work?

Thank you.

**Comment by DNF-SaS** [comment]
Blazor Server Side has no IOC-registration of System.Net.Http.HttpClient.
ATM, I guess this is by design (look at the example in the default template - the weather forecast also does not fetch data from the server). But it should be possible to use HttpClient also from the server (with all limitations, e.g. being not able to identify a client by it's IP (because it's always from the server))

**Comment by blowdart** [comment]
I don't know what Blazor server-side is, so ... I'm going to guess here from a quick read.

Sign-in needs to be run on the app on the server, for access to databases, signing keys and so on, all things ASP.NET provides. The SignalR communication doesn't flow things like cookies, which asp.net identity expects, so I wouldn't expect this to work at all. An alternative approach would be have an ODIC server, like Identity Server on the backend, talking to ASP.NET identity, then do whatever blazor does for OIDC logins and head down that route, protecting any APIs with JWT tokens issued by the IdentityServer instance.

**Comment by danroth27** [comment]
@simonziegler I don't believe sign in requires an HttpClient at all. But it probably does need to happen in the context of a request. With server-side Blazor your dealing with a SignalR connection, not individual HTTP requests. I think you should be able to use normal Razor Pages/MVC to handle sign in and then once the [authentication cookie](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1#cookie-authentication) is established you can use that to authorize the user. Or, as @blowdart suggested you could setup an OIDC server and use JWT tokens to establish the user identity. 

I think this answers your question, but let us know if anything is unclear!

**Comment by DNF-SaS** [comment]
@danroth27 is it possible to register a HttpClient when running Blazor on Server?
I'd like to switch between WebAssembly and Server for better debugging on Server, but need HttpClient for Backend-Connections.

**Comment by simonziegler** [comment]
@danroth27 and do, Thank you for the viewpoints. This is beyond my skill set and not something that I strictly need for my purposes - a demonstration web app pre funding. If I get funded, some real life engineers will deal with all of this from scratch.

I’ll just say again that I’m in awe of what you folks are doing here. I very much hope that MS decides to make Blazor a supported product, as it is just ideal for the FinTech thing I’m working on. Keep up the great work!

**Comment by danroth27** [comment]
> @danroth27 is it possible to register a HttpClient when running Blazor on Server?
I'd like to switch between WebAssembly and Server for better debugging on Server and need HttpClient for Backend-Connections.

@DNF-SaS Yes, you should be able to add whatever you want to the service collection when running Blazor on the server. For server-side Blazor both the Blazor app and the ASP.NET Core app share the same service provider so you can add the HttpClient in the Server project. When running client-side the Blazor app will use the browser friendly HttpClient.

**Comment by tanngocIT** [comment]
I want to use Microsoft.AspNetCore.Identity.SignInManager for authentication but i can't use it. please give me some demo using that. thanks

**Comment by tanngocIT** [comment]
@xclud thanks for your sharing.
In solution 1: you add code in Server project or App project ??
i try to do that but it not working :((

**Comment by xclud** [comment]
@tanngocIT Update to latest nightly SDK and create a new Razor Component project.

There is no longer Server and App projects. There will be only one project and the structure looks like other asp.net projects. You will find it straight forward.
