### ISSUE TITLE
[Question] Close popup window when we click on outside popup window

### ISSUE THREAD

**Issue by osintsevvladimir** [aspnet/Blazor#1274]
How do I handle an event "document.onclick" inside a DropDownList component?

**Angular example:**
```
@Component({
  host: {
    '(document:click)': 'onClick($event)',
  },
})
```

**Comment by SteveSandersonMS** [comment]
For now you'll need to use JS interop to register your click handler on the document.

Later on we might add special functionality for this sort of use case. It depends on how common a feature request it turns out to be.
