### ISSUE TITLE
calling/downloading common Dlls  from CDN, like android downloadable fonts

### ISSUE THREAD

**Issue by gsmental** [aspnet/Blazor#1275]
Is it possible to downloading common Dlls  from  any CDN, , like android has facility to  downloadable fonts from url. 

It can reduce band-width cost and Common AspNet.Core dlls will be available for all users. it is thinking.

**Comment by iAmBipinPaul** [comment]
#22 duplicate

**Comment by abhisheksiddhu** [comment]
#843 duplicate

**Comment by danroth27** [comment]
Yup, providing a common CDN is something we hope to do at some point. Tracked by #22.
