### ISSUE TITLE
How to deploy Blazor (Server-side in ASP.NET Core) project

### ISSUE THREAD

**Issue by Amine-Smahi** [aspnet/Blazor#1276]
A tutorial may help.

**Comment by iAmBipinPaul** [comment]
Hope this will help.
https://blazor.net/docs/host-and-deploy/index.html#hosted-deployment-with-aspnet-core

**Comment by danroth27** [comment]
Thanks for answering, @iAmBipinPaul 

@Amine-Smahi that doc should have all the info you need, but if you have more questions or run into issues let us know!
