### ISSUE TITLE
JsonPatchDocument

### ISSUE THREAD

**Issue by kiegh** [aspnet/Blazor#1281]
I'm a bit confused as to how we should create a patch document in Blazor to pass to our API for partial updates?

Does anyone have any tips?

**Comment by danroth27** [comment]
There isn't a great story for this in .NET as far as I know. You can use the JsonPatchDocument class in ASP.NET Core to serialize a request payload (for an example see https://github.com/KevinDockx/JsonPatch), but you'd need to use Json.NET and to do that in Blazor you currently need to do some custom configuration of the IL linker. Or you could build your own simple library for creating JSON Patch documents.
