### ISSUE TITLE
New App/Startup model is a massively breaking change

### ISSUE THREAD

**Issue by masonwheeler** [aspnet/Blazor#1287]
In the old version, I had some crucial setup that came between setting up the `ServiceProvider` and launching the `BrowserRenderer`.  It had to happen in that order because it needed access to some of the things that are automagically added to the `ServiceProvider` by the Blazor framework, which the IServiceCollection inside of the setup routine does not give you access to.

This workflow, which used to be explicit, is now broken in 5.0 because it's been replaced with reflection magic.

What is the new way to do things such as [retrieving data from the HttpClient](https://github.com/aspnet/Blazor/issues/567#issuecomment-381226776) or setting up a lambda that calls `IUriHelper.NavigateTo` (needed so I can assign this to a delegate on a static class, so that I'm able to navigate from JS interop)?  I need both of these things, and right now they're both broken because I don't have explicit access to the `BrowserServiceProvider` object anymore.

**Comment by masonwheeler** [comment]
Just to add insult to injury, `BrowserServiceProvider` and `BrowserRenderer` are still in the framework.  My existing code compiles and loads just fine (after I adapted a bit of interop code) but then it just hangs at "Loading...", never actually rendering the page.  No errors are shown in the console, but it does report:

> WASM: Initialized blazor.webassembly.js:1:31958 

So the framework thinks everything is working fine, but nothing is actually working.

**Comment by SteveSandersonMS** [comment]
Yes, we changed the startup model significantly to align it with the traditional ASP.NET Core model.

> What is the new way to do things such as retrieving data from the HttpClient

It's an unusual situation, but there's nothing stopping you from instantiating your own separate `BrowserServiceProvider` in your `Program.cs` and making an async HTTP call before starting up the renderer. Example:

```
using Microsoft.AspNetCore.Blazor.Browser.Http;
using Microsoft.AspNetCore.Blazor.Browser.Services;
using Microsoft.AspNetCore.Blazor.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Net.Http;

namespace MyApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var browserServiceProvider = new BrowserServiceProvider();
            var httpClient = browserServiceProvider.GetRequiredService<HttpClient>();
            
            httpClient.GetStringAsync("sample-data/weather.json").ContinueWith(task =>
            {
                Console.WriteLine(task.Result);

                // Now start the app
                CreateHostBuilder(args).Build().Run();
            });
        }

        public static IWebAssemblyHostBuilder CreateHostBuilder(string[] args) =>
            BlazorWebAssemblyHost.CreateDefaultBuilder()
                .UseBlazorStartup<Startup>();
    }
}
```

I still think this is not the best solution. It would be better to start the Blazor renderer immediately, and in your top-level component, do whatever async loading you need while displaying some "Loading..." UI. Once that async load completes, have it display whatever other components you want, passing in the data you've loaded.

> setting up a lambda that calls IUriHelper.NavigateTo

It's possible I'm misunderstanding, but my guess is that you want JS code to be able to call into .NET and trigger navigation. If so, there's a much easier alternative. Your JS code can simply call `Blazor.navigateTo` (example: `Blazor.navigateTo('counter');`).

**Comment by zac-at-incycle** [comment]
Any updates on this subject?  The example above no longer works.  Maybe an updated example?
