### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Blazor#129]
![image](https://user-images.githubusercontent.com/1798510/36336659-1abe43ca-138a-11e8-86fd-3ebeb002763f.png)

**Comment by Wayne-Mather** [comment]
@MaherJendoubi Why blur your username in all rows except the last one?

**Comment by grahamehorner** [comment]
@MaherJendoubi have you tried cleaning the repo and then building from commandline dotnet build Blazor.sln ?

**Comment by grahamehorner** [comment]
also see https://github.com/aspnet/Blazor/issues/125

**Comment by radialapps** [comment]
Are you sure you've built the entire solution already? Also, try a rebuild as @grahamehorner suggested.

**Comment by ppumkin** [comment]
I had the same. Try and build a test project first, then rebuild solution, then build the project again. There seems to be an order that must be compiled first... not sure what exactly. I closed and rebooted too and now it works fine.

**Comment by MaherJendoubi** [comment]
@ppumkin Thank you! It's a build order...
