### ISSUE TITLE
Getting erro calling registered JSInvokable function in component lib

### ISSUE THREAD

**Issue by rpedretti** [aspnet/Blazor#1295]
I have a Component lib created using the blazom component lib template (CLI) asn have registered a instance method to be invokable in th JS side

```
[JSInvokable]
public Task ClearSelection()
{
...
}
```

But when calling it i get the following error:

```
Error: System.InvalidOperationException: The assembly 'RPedretti.Blazor.Components' contains more than one [JSInvokable] method with identifier 'ClearSelection'. All [JSInvokable] methods within the same assembly must have different identifiers. You can pass a custom identifier as a parameter to the [JSInvokable] attribute.
```

I tried to to register using a identifyer but the error remains. This doesn't happens in a instance method registered in the main assembly

**Comment by danroth27** [comment]
Do you have any other `[JSInvokable]` methods in the RPedretti.Blazor.Components assembly? Can you share the code for the RPedretti.Blazor.Components assembly?

**Comment by rpedretti** [comment]
I do not have any other `[JSInvokable]` in that assembly, only another one in the main assembly. The code can be found [here](https://github.com/rpedretti/BlazorApp/tree/version_0_5_1) at my github account.

**Comment by danroth27** [comment]
Yeah, this looks like a bug in `DotNetDispatcher.ScanAssemblyForCallableMethods`. When you have a `[JSInvokable]` method defined on a base class. Both the base class and the derived class will supply the same `MethodInfo` when collecting all the methods from the exported types in the assembly, but there is no logic to detect and remove these duplicates.

**Comment by rpedretti** [comment]
Thanks! Although in my case i had no `[JSInvokable]` on my base class I have a strong feeling that it will solve the issue.

**Comment by rpedretti** [comment]
Oh, ok. Forgot that's not partial...damn you, UWP!! I was just thinking of the C# part, not the razor one. Thanks for clarifying it for me.
