### ISSUE TITLE
Why not make conventions in strucuture app like MVC or Razor Pages does?

### ISSUE THREAD

**Issue by jonathanperis** [aspnet/Blazor#130]
I was looking at the Standalone project with the recent commits, and I checked the way the project is structured to sort things out, and found that many things that already work the way we know it today in ASP.NET Core MVC and Razor Pages work from different way in Blazor. 

For example, the Layout statement is in a specific file with the @ (Implements <Microsoft.AspNetCore.Blazor.Layouts.ILayoutComponent>) tag instead of being an _Layout.cshtml file, and the screens that reference libraries do on the same page instead of a _ViewImports.cshtml file, and the directive to render the pages today, are under the @Body property, not an @RenderBody as we already know. And if you needed to specify the Layout file, be done with _ViewStart.cshtml as well as it is already known to everyone today. 

I also checked the structure of NavMenu, which when it is referenced, is done through a <c: NavMenu /> tag, why not reference the file as the Partial Views work today? 

Sincerely, <c: NavMenu /> reminds me a lot of WebForms, and this may not be a good thing for other developers

I think a syntax similar to what exists today in AspNetCore, even though it has different functionality, will help developers have a smaller learning curve

**Comment by SteveSandersonMS** [comment]
Great feedback - thanks!

As it happens, the two aspects of the syntax you've raised are both temporary (noted [here](https://github.com/aspnet/Blazor/blob/4bb9747c5a6d1703d4f94fe2be14c1e61a472337/src/Microsoft.AspNetCore.Blazor.Razor.Extensions/BlazorIntermediateNodeWriter.cs#L319) and [here](https://github.com/aspnet/Blazor/blob/1dd8dfcecafdcbf684adc7063e84db5e3c84a3a1/src/Microsoft.AspNetCore.Blazor/Components/RazorToolingWorkaround.cs#L30)). We have some work underway to enable much cleaner syntax and have it supported by VS tooling. The one for components in particular will be extremely nice to work with, with first-class intellisense for your custom component names, parameters, and types. This is still a month or so out, plus it will require people to update to a newer version of VS, so we wanted to have something else in the meantime. Our goal is to let people work with what we're building while it's being built, even if there are some rough edges as we go along. Hope that's OK!

More broadly speaking, while we will take inspiration from Razor Pages, the top goal is to make the best framework even if that involves diverging from existing patterns. Blazor will be like Razor Pages when that's ideal, and not when it isn't. We're also taking inspiration from other SPA frameworks and innovating where applicable. So there isn't one single blueprint we're following, other than the goal of making the best result.
