### ISSUE TITLE
Please, Update Blazor FlightFinder to 0.5.0

### ISSUE THREAD

**Issue by enetstudio** [aspnet/Blazor#1300]
Thanks

**Comment by danroth27** [comment]
@stevesandersonms I believe you already have a PR  out for this. It just needs to be updated to 0.5.1.

**Comment by kant2002** [comment]
@danroth27  It is already update to 0.5.1 in ASP.NET samples repository.

**Comment by SteveSandersonMS** [comment]
Good point - thanks @kant2002!

**Comment by kant2002** [comment]
@SteveSandersonMS I just looking for simple tasks which I could solve.
