### ISSUE TITLE
[Quesion] JS Context is different when published?

### ISSUE THREAD

**Issue by rpedretti** [aspnet/Blazor#1302]
At my machine, in Release build, the `window.AmbientLightSensor` does exists, but after publishing it to Azure the JS context is not the same as running it at localhost.

Is it a bug or a special config is needed to work as expected?

**Comment by SteveSandersonMS** [comment]
We don’t do anything to change the APIs available to JS code. If you have specific repro steps I’d be happy to have a look.

**Comment by rpedretti** [comment]
Ok, I verifyed that running on localhost the api on window object exists both on http and https, but if I access by IP, for instance, it only exists on https, so not blazor related. Just enabled https on azure and everything worked just fine.

**Comment by danroth27** [comment]
Yeah, it's a trend that a growing number of APIs now require HTTPS to be used.
