### ISSUE TITLE
Rendering lists of components

### ISSUE THREAD

**Issue by RoryChrist** [aspnet/Blazor#1304]
I don't see anything mentioned in the "Component model" issue (#1), so I was wondering if there are plans to address rendering list of components.  For example:

```
    @foreach (var item in toDoListItems)
    {
        <ToDoItemComponent Item="@item" />
    }
```

As it currently stands, if I insert an item at position "i", all the existing component instances from "i" to the end of the list will have their parameter set to "i + 1", resulting in a significant number of changes instead of just one component instance being created.  The same with removing an item from a list.

Are there plans to add some sort of "key" functionality, so the framework can match up list items with their original component instances and process changes more efficiently?

**Comment by LunicLynx** [comment]
There are even more issues when removing an element from an for rendered list.

The solution i found to this was to self implement the Component:

```csharp
public class ModalOutlet : BlazorComponent
{
    private readonly Dictionary<ToDoListItem, int> _indicies = new Dictionary<ToDoListItem, int>();
    private readonly List<ToDoListItem> _toDoListItems = new List<ToDoListItem>();
    private int _nextIndex = 4;

    protected override void BuildRenderTree(Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
                  
            foreach (var item in _toDoListItems)
                        {
                            if (!_indicies.TryGetValue(item, out var index))
                            {
                                index = _nextIndex++;
                                _indicies[item] = index;
                            }
 builder.OpenComponent<ToDoItemComponent>(index);
// TODO set Item attribute to item
 builder.CloseComponent();
                        }
                    }
                ));
            );
           
        }
/// ...
}
```

**Comment by SteveSandersonMS** [comment]
Yes, the intended resolution is that we implement a “key” notion just like you suggested. This is tracked in #1

**Comment by sebbert** [comment]
@SteveSandersonMS Sorry, but I can't seem to find where the `key` feature is being tracked in that issue?

**Comment by SteveSandersonMS** [comment]
@sebbert You're quite right. In my mind that was on the list for #1 all along, but in fact it wasn't! Just added it now. Thanks for pointing this out.

**Comment by sebbert** [comment]
@SteveSandersonMS Thanks for the quick reply! :)
