### ISSUE TITLE
<UseRazorBuildServer>false</UseRazorBuildServer> as default

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/Blazor#1306]
```
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <UseRazorBuildServer>false</UseRazorBuildServer>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
```

I am adding <UseRazorBuildServer>false</UseRazorBuildServer> for all my projects because it was taking long to build without this. I did some research and found this solution.

For new people it will be better to avoid this problem having this as default.
If you will not be agree then it is necessary blazor.net to advice about this when getting started with blazor.

**Comment by Andrzej-W** [comment]
Bug is fixed - we have to wait for ASP.NET Core 2.1.3
#1019
https://github.com/aspnet/Razor/issues/2406
