### ISSUE TITLE
Environment.OSVersion.Platform always showing as Unix

### ISSUE THREAD

**Issue by rlmartins76** [aspnet/Blazor#131]
It looks like from my testing that the Platform is always showing as Unix, even when working on a IIS Express in windows. Could very well be from Mono, but wondering if it is by design, a bug or a future enhancement.

**Comment by arkadiuszwojcik** [comment]
Platform is irrelevant. You are in browser sandbox that is aleady abstraction above some platform. As far I know WASM is aiming to be close to Unix platform in terms of its sandbox so probably that is the reason.

**Comment by rlmartins76** [comment]
I understand your statement that Platform is irrelevant in a traditional browser sandbox context, but isn't WebAssembly changing that concept? Given that, in a WebAssembly, the client (browser) has the ability to run .NET code, why would .NET functionality allowed to be restricted to only PlatformId.Unix? (ex: AssemblyBuilder.DefineDynamicAssembly, and many others).

**Comment by wanton7** [comment]
@rlmartins76 like @arkadiuszwojcik said it's a sandbox (OS is hidden) you can't do anything Windows specific in it. Same restrictions that apply to JavaScript apply here. You can't do anything Windows specific in browser with JavaScript as well. If you could, that would be a huge security risk.
