### ISSUE TITLE
Load shared component dynamically

### ISSUE THREAD

**Issue by hokusp** [aspnet/Blazor#1310]
Is it possible to load a dll with a shared BlazorComponent from a file (or download it, or...) and then use it?

thanks for hints

**Comment by euphbriggs** [comment]
From what I understand, you can create a separate project using the "Razor Class Library" project template and use it to create shared components. Is that what you're looking for?

![image](https://user-images.githubusercontent.com/20155143/44092544-5dc51002-9f96-11e8-9d7b-7fe229029947.png)

**Comment by Andrzej-W** [comment]
Probably @hokusp thinks about #25

**Comment by euphbriggs** [comment]
Oh, I see. @hokusp is interested in the *loading* part, not the *creation* part.

**Comment by hokusp** [comment]
yes, thanks for pointing out the existing issue.
