### ISSUE TITLE
When will be officially released?

### ISSUE THREAD

**Issue by renatoprogramer** [aspnet/Blazor#1319]
When will be officially released

I saw that Microsoft is already using this wonder I want to use as fast as possible.

https://webapp.kaiza.la //Example production Blazor

**Comment by shadowmint** [comment]
I'd also like some official clarity on this, but afaik the latest announcement regarding this is https://youtu.be/7Eh_l7jEcCo?t=55m15s, which is that it will ship with .net core 3.0

**Comment by danroth27** [comment]
We are integrating the Blazor component model ("Razor Components") into ASP.NET Core in .NET Core 3.0, which is scheduled to ship mid-2019. Client-side Blazor will be worked on in parallel, but for now the client-side WebAssembly support is still experimental and has no committed ship date. The intent is to support the same component model both server-side and client-side.

Where to you see Microsoft Kaizala using Blazor? I tried out the app but I didn't see anything that indicated Blazor usage.

**Comment by w8w8w8** [comment]
my project contains a lot of mathematical calculations, and I use javascript setInterval call the  .NET methods, then .NET methods  call javascript function to update svg(text,image) dom(>300) value.
but , 2 hours later, the chrome crash.

**Comment by renatoprogramer** [comment]
@danroth27  
I recognized by the faviicon that the guys will forget to withdraw.

**Comment by Suchiman** [comment]
@renatoprogramer that is the default Icon for all ASP.NET applications 😉

**Comment by SteveSandersonMS** [comment]
Closing as answered by @danroth27
