### ISSUE TITLE
Blazor Templates gone in VS 15.8.0

### ISSUE THREAD

**Issue by uwefms** [aspnet/Blazor#1323]
After upgrading to VS 15.8.0 and SDK 2.1.400 all blazor templates (core 2.0 and 2.1) are gone. Creating new apps with dotnet new works as expected and the newly created projects can be edited with VS. Deinstalling and reinstalling the asp.net blazor language services did not help.

   Uwe

**Comment by uwefms** [comment]
Had the same "hanging" problem - solved it by saving before building. I guess VS hangs because the compile starts before the save is finished.

**Comment by MarkStega** [comment]
@uwefms I am not seeing this issue with my installation of 15.8.0 (which was an upgrade from 15.7.6).

I am seeing the issue raised in #1324

**Comment by danroth27** [comment]
@uwefms Could you please check a few things for me?:
- Does the `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\Blazor` folder exist?
- Is the *Templates.pkgdef* file present in that folder? Does the contents of this file match the following:

  ```
  [$RootKey$\TemplateEngine\Templates\Blazor\0.2.0]
  "InstalledPath"="$PackageFolder$\ProjectTemplates"
  ```

- Does the `ProjectTemplates` folder exist in that folder and does it contain the  `Microsoft.AspNetCore.Blazor.Templates.0.5.1.nupkg` package?
- Is the regkey specified above present on your machine with the regkey specified above present on your machine and pointing to the location of the Blazor templates?

If all these things check out, could you please try running `devenv.exe /setup` and see if that addresses the issue?

**Comment by danroth27** [comment]
@phenning

**Comment by uwefms** [comment]
Seems to be OK now after the last language services update. Close it for now.

**Comment by danroth27** [comment]
@uwefms When you hit this issue had you installed a Blazor VSIX update from our CI def feed?

**Comment by uwefms** [comment]
@danroth27 
I am not sure - I noticed the missing templates after upgrading to VS 15.8.0 and SDK 2.1.400. I always update via  VSIX. At present I am using the following version:

ASP.NET Core Blazor Language Services   0.6.0-preview1-20180830.1

Creating the missing ProjectTemplates folder and adding Microsoft.AspNetCore.Blazor.Templates.0.5.1.nupkg manually from /.nuget/packages brought back the templates. Since then - no issue. Just checked 10 secs ago.

**Comment by danroth27** [comment]
> I am using the following version: ASP.NET Core Blazor Language Services 0.6.0-preview1-20180830.1

OK, yeah, it looks like you're using a build form the Blazor dev feed, so this is consistent with the issue I am able to reproduce. Thanks for confirming!

**Comment by andras-ferencz** [comment]
🤔
