### ISSUE TITLE
Server-side Sessions

### ISSUE THREAD

**Issue by kevinjpetersen** [aspnet/Blazor#1327]
Hello! I've been searching and searching and experimenting and I can't seem to find whether or not it's possible to Save and Retrieve Server-side sessions in Blazor Server-side projects.

I know SessionStorage is a thing in the Client-side, but saving user data like ID there would be a massive security risk.

Is it possible at the moment to Save and Retrieve a session on the server, just like you would normally with a HttpContext in ASP.NET Core Controllers?

**Comment by danroth27** [comment]
@rynowak @davidfowl What's the current thinking on this?

**Comment by rynowak** [comment]
We will likely need to do a thing, though some basic building blocks are in place. The main issue is that session doesn't work gracefully with SignalR in all cases.

**Comment by kevinjpetersen** [comment]
@rynowak @danroth27 Thanks for the answer, so at the moment, there isn't any way to set a session? Is this something that will be focused on at some point, or is it more difficult than it sounds to integrate?

**Comment by kevinjpetersen** [comment]
@davidfowl I see.. is this something that will become a priority at some point, or is it just in the backlog for now?

**Comment by RemiBou** [comment]
WOudn't this feature introduce differnece between client-side blazor and server-side blazor (or "razor component")  ? Isn't the goal to make the same code work in both cases ?

**Comment by SteveSandersonMS** [comment]
Since this question is hopefully answered now (and in any case turns out to be more of a question about SignalR), I'll close.

> Wouldn't this feature introduce difference between client-side blazor and server-side blazor (or "razor component") ? 

We're not telling people to use server-side session, but like all other server-side ASP.NET Core features, there's nothing stopping you using them if you want. The developer chooses what to use.

**Comment by danroth27** [comment]
I opened https://github.com/aspnet/SignalR/issues/2827 to track making sessions work with SignalR.

**Comment by danroth27** [comment]
@RemiBou It is a goal is that the same component model works for both client-side and server-side, but I wouldn't say that it's a goal for the *app code* to be exactly the same. For example, one of the benefits of server-side Blazor is that you can directly access server specific resources. You could certainly do work as an app developer to use abstractions that makes the same code work both server-side and client-side, but that's an app specific decision.

**Comment by DNF-SaS** [comment]
Any news on server-side sessions / howto store/access data server-side for multiple users simultaneously?
