### ISSUE TITLE
how to run Blazor in asm.js

### ISSUE THREAD

**Issue by moataz1991** [aspnet/Blazor#1332]
Hello
how to run Blazor App in asm.js , as the issue title  says :)

whats the main difference between  asm.js and webassembly ?

**Comment by SteveSandersonMS** [comment]
Blazor automatically switches to asm.js if the browser doesn't support WebAssembly.

> whats the main difference between asm.js and webassembly ?

I'd recommend a web search to find info about this. Hope that's OK!

**Comment by danroth27** [comment]
@moataz1991 Blazor will fallback to an asmjs based runtime automatically if it detects that WebAssembly isn't supported. However, for older browsers that don't support WebAssembly you will also run into issues with lack of support for other JS features that Blazor uses, like promises. You'll need polyfills to deal with these limitations that Blazor doesn't currently provide. There are some community projects to provide these polyfills though that you can try out: https://github.com/Daddoon/Blazor.Polyfill
