### ISSUE TITLE
ASP.NET Core Blazor Language Service release notes still point to 0.1

### ISSUE THREAD

**Issue by conficient** [aspnet/Blazor#1333]
The **Release Notes** link (in the [manifest](https://github.com/aspnet/Blazor/blob/master/tooling/Microsoft.VisualStudio.BlazorExtension/source.extension.vsixmanifest)) points to 

https://go.microsoft.com/fwlink/?linkid=870448 

which redirects to 

https://github.com/aspnet/blazor/releases/tag/0.1.0

Expected: https://github.com/aspnet/Blazor/releases/tag/0.5.1

**Comment by danroth27** [comment]
@conficient Thanks for letting us know! I've updated the fwlink to point to https://github.com/aspnet/blazor/releases/ so we don't have to update the link every release.
