### ISSUE TITLE
MarkupString not render component

### ISSUE THREAD

**Issue by davidsdearaujo** [aspnet/Blazor#1334]
**MarkupString** render all html elements, but not render a component element

**Comment by danroth27** [comment]
Correct, a `MarkupString` is only for rendering raw HTML content, not for rendering components.

**Comment by davidsdearaujo** [comment]
is there any command to render components by of strings?

**Comment by danroth27** [comment]
Not currently. Taking a string with Razor syntax (HTML + Components) and turning it into something that can be rendered is the job of the Razor compiler, which is used at build-time, not runtime. If it becomes a common request we might consider some loose parsing of some kind.

**Comment by davidsdearaujo** [comment]
Ok, thanks!
