### ISSUE TITLE
event to "Websocket closed"

### ISSUE THREAD

**Issue by cores-system** [aspnet/Blazor#1335]
Hello, how can I subscribe to an event?
`Error: Connection disconnected with error 'Error: Websocket closed with status code: 1006 ()'.`

I would like to display a notification to the user during a disconnect.

**Comment by danroth27** [comment]
I believe that's purely a JS concern. If your browser client reports close code 1006, then you should be looking at the `websocket.onerror(evt)` event for details.

**Comment by cores-system** [comment]
I understand that the exception on the side of JS, but I do not understand how to subscribe to the event.

**Blazor Server side**: 0.5.1
/_framework/blazor.server.js - **obfuscate**

```
websocket.onerror(evt)
VM1612:1 Uncaught ReferenceError: websocket is not defined
    at <anonymous>:1:1
```

```
connectionState
VM1614:1 Uncaught ReferenceError: connectionState is not defined
    at <anonymous>:1:1
```
