### ISSUE TITLE
connectionState to Blazor Server side

### ISSUE THREAD

**Issue by cores-system** [aspnet/Blazor#1337]
Hello, how can I get the connection status?

**Blazor Server side**: 0.5.1
/_framework/blazor.server.js

```
this.connectionState
VM1614:1 Uncaught ReferenceError: connectionState is not defined
    at <anonymous>:1:1
```

**Comment by SteveSandersonMS** [comment]
The connection is *always* active. If it wasn't active, your code wouldn't be running.

Longer term we plan to deal with handling automatic reconnection if there are network issues, but even then, your code is only running when there is a connection.

**Comment by cores-system** [comment]
**I do so**
1) I add a variable to the "/_framework/blazor.server.js" - "window.blazorHub = i";
2) After that, I can subscribe to "window.blazorHub.onclose(e)"

i can do the same without changing  "/_framework/blazor.server.js"?
