### ISSUE TITLE
Encoding 1252 data could not be found

### ISSUE THREAD

**Issue by kant2002** [aspnet/Blazor#1338]
Not sure that this is Blazor issue and not issue of Mono.
```
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
var encoding = Encoding.GetEncoding(1252);
```

This is produces 
```
System.NotSupportedException: Encoding 1252 data could not be found. Make sure you have correct international codeset assembly installed and enabled.
 at System.Text.Encoding.GetEncoding (System.Int32 codepage)
```

**Comment by SteveSandersonMS** [comment]
Thanks for reporting it. Yes, it's an issue in the base class library, so would you please be able to report it to http://github.com/mono/mono? Be sure to state that this is a WebAssembly-specific matter.

**Comment by kant2002** [comment]
@SteveSandersonMS Looks like it maybe packaging issue. See https://github.com/Radarr/Radarr/issues/342 There mention of `mono-locale-extras` package. Looks like this is separate package from `mono`. Could you confirm that it is `mono` should bundle that package inside `mono.wasm` and not Blazor to include this bits as part of distribution ?

**Comment by SteveSandersonMS** [comment]
@kant2002 Blazor doesn't decide which parts of the Mono BCL to include - we take what is shipped in the Mono builds.

**Comment by SteveSandersonMS** [comment]
Also, whether or not Mono can realistically include this in their WebAssembly builds depends on what impact it has on payload size, and whether the linker is able to strip it out when unused somehow.

**Comment by kumpera** [comment]
Mono, by default, doesn't include any code pages.
Blazor should follow what we do on Xamarin and offer to the user the option to include the I18N.* code pages in their build.

The above code page is part of I18N.West.dll, for example.

**Comment by kumpera** [comment]
From the "iOS Build" Project Options page in Visual Studio for Mac.

<img width="562" alt="screen shot 2018-10-22 at 4 17 24 pm" src="https://user-images.githubusercontent.com/5738/47316814-fb164c80-d615-11e8-93c7-3bff96deb95d.png">
