### ISSUE TITLE
Subscribe to the onclose event via JS

### ISSUE THREAD

**Issue by cores-system** [aspnet/Blazor#1339]
Hello, I want to subscribe to the onclose event via JS. 

**Here is an example of what I need**: 
https://youtu.be/11I4lK00KeI

How do I do this without changing "/_framework/blazor.server.js" ?

---
**Blazor Server side**: 0.5.1
/_framework/blazor.server.js

**Comment by SteveSandersonMS** [comment]
We don't currently expose any API like that. When we implement connection management and automatic reconnection, we'll provide APIs to respond to disconnection.

**Comment by SteveSandersonMS** [comment]
Would #1341 meet your needs?

**Comment by cores-system** [comment]
@SteveSandersonMS , yes.

**Comment by cores-system** [comment]
Is it dangerous to open access to a signalr connection?
`i = (new s.HubConnectionBuilder)`

**Comment by SteveSandersonMS** [comment]
@cores-system Yes, anything you do with undocumented APIs is dangerous!

**Comment by cores-system** [comment]
@SteveSandersonMS, Thanks for the temporary API, this fix #1339 can be used in 0.6?
