### ISSUE TITLE
Splitting up generated classes into webforms-like .design files

### ISSUE THREAD

**Issue by tjbortz1s** [aspnet/Blazor#134]
I've been playing around with blazor and a few times now I've been going back to the generated code to get a look at what is going on with it and how the generated code corresponds to what I write in the .cshtml file.  The process of finding the generated file, and finding the class within that file has been somewhat tedious.  

Not hard at all, and a very minor little thing to consider, but it has been a bit of an annoyance.

It might be a good idea to split up the generated classes in a manner similar to webforms with a .html.designer or similar that appears under the .cshtml file.  

Alternatively, if doing that could clutter the main project files, it could be cool if the generated files were created in a directory structure that matched the cshtml files they are being generated from. That folder could then be included in the project so they are more easily found and viewed.

**Comment by ppumkin** [comment]
When I started I was a bit confused as to what these files where... any way I now know. 

I support your idea too and probably linking the generated file to the actual cshtml is a good idea.. kind of feels webformy ... but ony genx guys will complain about that.

**Comment by jonathanperis** [comment]
ASP.NET Core Razor Pages does this. Today.

**Comment by ppumkin** [comment]
It technically does not do "this" exactly, it allows you split your Page code, into "code behind" if you want to seperate it out.

What is happening "here" is more like "designer" files in old webformy ways... where you did not edit them as they were always auto generated.

Still.. very valid point, you could still look into those files if you wanted and they where all pinned under the main source file, ie Page.

**Comment by SteveSandersonMS** [comment]
The long term goal is that the tooling and syntax are clear enough that wanting to see the generated code would be extremely rare. Most developers shouldn't care that it exists any more than C# devs needing to look at the MSIL produced when their code is compiled, or today's ASP.NET MVC developers wanting to see the code generated from their Razor views. As such we wouldn't want to put those files right in your face, such as by making them part of the visible project structure.

That said, I know while we're working through this experimental phase that there will be a *lot* of times where the tooling doesn't make clear what the right syntax for something is, and as an advanced developer you'll want to see what's going on inside.

So as a tip for you advanced devs, if you go into a `.cs` file and write the type name of a component you want to see the generated code for, you can then use "Go to definition" (e.g., press F12) on that type and the IDE will jump directly to the corresponding generated code.

Longer term the exact set of tooling items remains to be decided and we'll certainly be guided by feedback as we progress. For now we're building towards the goal of people never feeling any reason to go look at those files :)
