### ISSUE TITLE
Unable to run blazor app - get 502.5 error

### ISSUE THREAD

**Issue by PhilPJL** [aspnet/Blazor#1342]
VS 15.8.1
Blazor 0.5.1

Create new blazor app.
Ctrl-F5 run using IIS express/Edge

![image](https://user-images.githubusercontent.com/271656/44413218-b82af080-a562-11e8-8993-ebf5d5000c0f.png)

I'm pretty sure I've configured IIS correctly as specified at https://go.microsoft.com/fwlink/?LinkID=808681.

The event log says

> Application 'MACHINE/WEBROOT/APPHOST/WEBAPPLICATION2' with physical root 'C:\Users\xxxx\source\repos\WebApplication2\WebApplication2\' failed to start process with commandline 'c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\microsoft\web tools\projectsystem\VSIISExeLauncher.exe -argFile "C:\Users\xxxx\AppData\Local\Temp\tmp2D5D.tmp"', ErrorCode = '0x80004005 : 0.

Any ideas?

**Comment by danroth27** [comment]
What .NET Core SDK versions do you have installed? You can run `dotnet --info` to find out. 

Can you try removing the global.json file from the generated project and see if that resolves the issue?

**Comment by PhilPJL** [comment]
Hi and thanks.  Removing global.json fixed it.

If it's any use - 
![image](https://user-images.githubusercontent.com/271656/44467323-7fe6e900-a61a-11e8-94ae-db055d5beb60.png)

**Comment by mjganesh** [comment]
Change your version in global.json file as
{
  "sdk": {
    "version": "2.1.401"
  }
}

**Comment by danroth27** [comment]
@dsghi Good point. https://github.com/aspnet/Blazor.Docs/pull/244. This is also fixed in 0.6.0 #1386
