### ISSUE TITLE
dbContext getting updated without post while using EF Core with server-side Blazor

### ISSUE THREAD

**Issue by AnkitSharma-007** [aspnet/Blazor#1347]
I tried creating a SPA using EF Core with Server-side Blazor. I put a form in a modal pop up and implement a CRUD with it. 
When i try editing a record in the form and close the modal pop up with out posting the form (not saving the record), it updates the dbContext object also. This affects the "fetch" part of the app also and shows the edited record on the UI. 
Although this does not update my database as post action is not executed. But this creates a data mismatch between UI and database. 
If i try to use the same code with traditional client-side Blazor app, i am not facing this issue and it work as expected.

Can anyone please verify this and tell if this is an expected behavior or an issue?

Application Code: https://github.com/AnkitSharma-007/Blazor-Server-Side-SPA

Related Article link to create the DB and sample app :  http://ankitsharmablogs.com/single-page-application-using-server-side-blazor/

**Comment by enetstudio** [comment]
@AnkitSharma-007,

This has nothing to do with Blazor...
I believe this is because the entity is tracked by the DBContext object, the result of which is the display of the edited entity. Of course, when you end your program the edited values are not saved as SaveChanges was not called. This does not occur when you use client-side Blazor as the Web is stateless. But when you use server-side Blazor, all the code is executed on the server, so DBContext can track and look after her babies.

**Comment by AnkitSharma-007** [comment]
If this is the case, then how can we use EF Core with Server-side Blazor? The code which i am using currently is valid only in positive scenarios and is not 100% correct. Is there any work around for this?

**Comment by AnkitSharma-007** [comment]
Yes this works for GetAllEmployees() method. Editing a record and closing the popup without saving it, will no longer updating the Fetch part of application. But if i again open the popup for the same record then it still shows the previously edited record in the popup.
Repro steps :- Click edit for any record. Change any field and close the popup without saving. Again open the edit for same record. it will show the previously edited record in the popup.

**Comment by enetstudio** [comment]
@AnkitSharma-007
Sorry, but I can't run your program as I have no means to do so. I have only VS 2010 on Windows Server 2003.
However let me suggest the following:
1. protected Employee emp = new Employee(); should be protected Employee emp { get; set; }
2. In the closeModal method you must set the emp property to null as follows:
 protected void closeModal()
        {
            this.isAdd = false;
            this.isDelete = false;
            emp = null;
        }
Try the above and see whether it works...

You should understand that your application is running on the server, and its behavior is more like a winforms or wpf apps than web app

**Comment by longinos10** [comment]
Where you get the Details of the Employee

I found this in StackOverflow  https://stackoverflow.com/questions/34967116/how-to-combine-find-and-asnotracking  

`                        var employee = await _context.Employees.FindAsync(id);
            _context.Entry(employee).State = EntityState.Detached;
            return employee;
`
            
And it wroked, and also I tried this and it worked too
 `            var emp = _context.Employees.AsNoTracking();
            return await emp.FirstOrDefaultAsync(e => e.EmployeeId == id);
`

**Comment by AnkitSharma-007** [comment]
Thanks @longinos10 for your reply. Both of your suggested methods work fine for me. i choose to use the first one with a little tweak to fit my application. 

@enetstudio : your suggestion doesn't solve my issue but thanks for your response.
