### ISSUE TITLE
Router intercepts clicks on <a> with target='_blank'

### ISSUE THREAD

**Issue by cores-system** [aspnet/Blazor#1352]
Hello, blazor intercepts a click even if you specify **target="_ blank"** in the link.

**Test Host**:
http://domain.com/

**Examples**
```
<a href="/api/rewriteurl/test" target="_blank">not work</a>
<a href="https://domain.com/api/rewriteurl/test" target="_blank">WORK</a>
<a href="http://domain.com/api/rewriteurl/test" target="_blank">not work</a>
<a href="http://domain2.com/api/rewriteurl/test" target="_blank">WORK</a>
```

I think that it's not necessary to intercept links with **target="_ blank"**

**Blazor Server side**: 0.6.0-preview1-20180822.3
/_framework/blazor.server.js

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. If you are interested in submitting a PR to correct this (assuming it's simple and also comes with an E2E test) we'd be happy to consider it!

**Comment by cores-system** [comment]
@SteveSandersonMS. Unfortunately I'm not strong at JS.

**Comment by cores-system** [comment]
Sent a solution

**Comment by enetstudio** [comment]
@cores-system: Hello, blazor intercepts a click even if you specify target="_ blank" in the link.

This is because Blazor is designed correctly.

@cores-system: I think that it's not necessary to intercept links with target="_ blank"

Blazor should not change how the web works.
Try your code anywhere, in any framework, and see that the click event is always intercepted. That's the way it was designed. Personally, I don't think Blazor should rectify this "flaw"

**Comment by cores-system** [comment]
@enetstudio, Then another question, how to open a link in a new tab?

**Comment by RemiBou** [comment]
@cores-system the only probem is that Blazr calls preventDefault when you click on a link so the page is not fully reloaded, look how I fixed the ctrl+click problem here : https://github.com/aspnet/Blazor/pull/868 it should be trivial to look for a target attribute.

On angular it's managed here on line 292 : https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/modules/angular1_router/src/ng_route_shim.js

**Comment by cores-system** [comment]
@RemiBou, preventDefault () is not called if the link specified target="_blank"
https://github.com/aspnet/Blazor/pull/1354/commits/53d5da450fe856407c372f1ab76d10d687732093

**Comment by cores-system** [comment]
I need to open the link in a new window by clicking "click", not just "ctrl+click"

**Comment by RemiBou** [comment]
@cores-system  If you don't call preventDefault, the browser will handle the creation of the new window because it will see the _blank attribute. You could add E2E test for validating this

**Comment by cores-system** [comment]
@RemiBou, I'll try to do E2E tomorrow.

But to understand the essence (considering that I translate through translate.google.com), it should look like this http://test-new.admtop.pro/  instead http://test-old.admtop.pro/
