### ISSUE TITLE
SignalR trigger UI update from server?

### ISSUE THREAD

**Issue by mgamache** [aspnet/Blazor#1359]
I need to update the browser based on server events (using a Blazor app). Is the Blazor/Chat example still valid? I am using the new Server Side project template (from 0.5.1) that uses SignalR as a transport.  Can I use the built-in Blazor connection or do I need to wire-up another SignalR connection? 

Just getting started with Blazor.
Thanks.

**Comment by cores-system** [comment]
@mgamache, I'm using an internal event.

**Comment by cores-system** [comment]
@mgamache, You can use the built-in Blazor connection.

**Sample**
https://blazorchat.azurewebsites.net/
https://github.com/cores-system/BlazorChat

**Comment by SteveSandersonMS** [comment]
@mgamache If you're using the server-side template, there's no need to have a special connection just to send events from the server. All the .NET code is running on the server anyway. Your .NET code can just modify the state of components and call `StateHasChanged` at any time, then the UI will update in the browser. There's no need to open a separate connection for this.
