### ISSUE TITLE
ROUTE SUBFOLDER  "organization"

### ISSUE THREAD

**Issue by renatoprogramer** [aspnet/Blazor#1361]
I noticed that there is a deficiency in the route part of the Blazor, I would like to be able to do by organization subfolder

**Organization folder**
```
-> Pages -> Admin -> dashboard.cshtml
```
**Current**
`@page "/adminDashboard"`

**Sugestion**
`@page "/admin/dashboard"`

**Comment by SteveSandersonMS** [comment]
Not sure what you mean. Blazor routes can already contain slashes, and it's not affected by the actual paths of files on disk (so you can put `dashboard` inside an `admin` folder if you want). So, `@page "admin/dashboard"` should work fine.

I'd recommend *not* having a leading slash on your route templates, because if you do, your app will not work if deployed to a non-root URL.

**Comment by renatoprogramer** [comment]
I'm facing this problem of routes with subfolders and with parameter, I'm swamped with service here more tonight I try to send my problem I can not create a simple routes with parameter ex `@page="product-detail/{ID}"`  from a fatal error in mono. JS Today the note I complete the error report, but do you know how I can put a root URL?   In angular 6 We can use N index. `<base href="/">` JS and works perfectly the routes in Blazor have something similar?

**Comment by SteveSandersonMS** [comment]
The Blazor application template does include `<base href="/">` in `index.html`, which functions in the standard way for HTML documents. I'm not certain what problem you're facing, but if you can supply some repro code (i.e., stating what code produces a problem) we can have a look.

**Comment by renatoprogramer** [comment]
My problem is with Rostas same, did not know that the Blazor implements the `<base href="/">  `

**Comment by renatoprogramer** [comment]
Could be this feature in the official documentation of Blazor, if the documentation is open source please pass me the git so I can write about this feature

**Comment by danroth27** [comment]
@renatoprogramer The Blazor docs are here: https://github.com/aspnet/Blazor.Docs

**Comment by renatoprogramer** [comment]
@danroth27  Thank you all that can help with this technology I will help this is the future.

**Comment by renatoprogramer** [comment]
@danroth27  I made my commit on this tag in the documentation
