### ISSUE TITLE
HttpClient interception

### ISSUE THREAD

**Issue by Peter-Juhasz** [aspnet/Blazor#1362]
Hey guys,

first of all, thank you for the awesome work you do with Blazor.

What is or what would be the recommended way to reconfigure the HttpClient in the DI? Are Delegating Handlers supported at all?

I need support for the following use cases:
 - Send CSRF token with each POST/PUT/… request like Angular does. (or are there any other way to achieve protection any other way?)
 - Intercept all responses and redirect the currently logged-in user to login, when session expires and the backend API returns 401.
 - Retry for particular error codes.

Thank you.

**Comment by Peter-Juhasz** [comment]
Based on [BrowserServiceProvider.cs](https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor.Browser/Services/BrowserServiceProvider.cs):
```cs
serviceCollection.AddSingleton(new HttpClient(new BrowserHttpMessageHandler())
{
    BaseAddress = new Uri(BrowserUriHelper.Instance.GetBaseUri())
});
```
I have found a workaround, so I can reregister `HttpClient` with all the handlers added:
```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton(_ => new HttpClient(
        new AuthenticationDelegatingHandler(
        new CsrfDelegatingHandler(
            new BrowserHttpMessageHandler()
        ))
    )
    {
        BaseAddress = new Uri(BrowserUriHelper.Instance.GetBaseUri()),
    });
}
```
Obviously for GA that would be great if we could have the same simplicity like ASP.NET Core's new HTTP extensions has, so that you only have to add `DelegatingHandler˙s to the DI.

**Comment by SteveSandersonMS** [comment]
I think your existing solution with registering an `HttpClient` or a `Func<HttpClient>` in DI is a good one. We'll consider adding further parity with ASP.NET Core server-side APIs in the future.

**Comment by dylanberry** [comment]
> Based on [BrowserServiceProvider.cs](https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor.Browser/Services/BrowserServiceProvider.cs):
> 
> ```cs
> serviceCollection.AddSingleton(new HttpClient(new BrowserHttpMessageHandler())
> {
>     BaseAddress = new Uri(BrowserUriHelper.Instance.GetBaseUri())
> });
> ```
> 
> I have found a workaround, so I can reregister `HttpClient` with all the handlers added:
> 
> ```cs
> public void ConfigureServices(IServiceCollection services)
> {
>     services.AddSingleton(_ => new HttpClient(
>         new AuthenticationDelegatingHandler(
>         new CsrfDelegatingHandler(
>             new BrowserHttpMessageHandler()
>         ))
>     )
>     {
>         BaseAddress = new Uri(BrowserUriHelper.Instance.GetBaseUri()),
>     });
> }
> ```
> 
> Obviously for GA that would be great if we could have the same simplicity like ASP.NET Core's new HTTP extensions has, so that you only have to add `DelegatingHandler`'s to the DI.

This is no longer relevant. Is there any way of using `DelegatingHandler` or `MessageProcessingHandler` with the current HttpClient/Http pipeline?

**Comment by bilas-bohdan** [comment]
> M

You can use WebAssemblyHttpMessageHandler instead of BrowserHttpMessageHandler

**Comment by dylanberry** [comment]
`WebAssemblyHttpMessageHandler` works as expected! Thank you! Is there documentation anywhere for this?

**Comment by bilas-bohdan** [comment]
I didn't find any documentation, and I met another problem, I would like to inject my "CustomService" into "CustomDelegatingHandler" to make functional intercepting, but cant find nice solution

**Comment by dylanberry** [comment]
This is about as clean as I could get it: https://gist.github.com/dylanberry/4a24df4fb369770e43b8a3e34997f854

Hope that's helpful.
