### ISSUE TITLE
Shareable string constant as route template

### ISSUE THREAD

**Issue by MarekPokornyOva** [aspnet/Blazor#1363]
Blazor project (ASP.NET Core hosted) (client project) v 0.5.1.

I wanted to create shareable route templates.
```
static class UiPaths
{
    public static string Account = "account";
}
```
---
### Solution 1 - reference string constant in page:
-	Put `@page UiPaths.Account` to Account.cshtml.

Issue 1
-	Compiler complains error: The 'page' directive expects a string surrounded by double quotes.
---

### Solution 2 - create code behind class:
```
	[Microsoft.AspNetCore.Blazor.Components.RouteAttribute(UiPaths.Account)]
	public abstract class AccountPageCodeBehind : Microsoft.AspNetCore.Blazor.Components.BlazorComponent
	{
	}

```

	Remove all @page directives from Account.cshtml.
	Put "@inherits AccountPageCodeBehind" to Account.cshtml.
Issue 2
	The application throws exception in runtime:
	Error: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.InvalidOperationException: The following routes are ambiguous:
		'account' in 'BlazorInNetFW.Client.Pages.Account'
		'account' in 'BlazorInNetFW.Client.Pages.AccountPageCodeBehind'

The problem is ComponentResolver is static class instead of replaceable service and it finds code behind class as a regular component. Then RouteTable creates RouteEntry even for the code behind class.

---
If I understand correctly, only possible solution here is to create and use custom router (instead of Microsoft.AspNetCore.Blazor.Routing.Router). However, I think it would be better if it's possible to maintain route paths/templates in configurable way (possibly even paths taken from a DB) instead of custom Router. Could you provide your opinion and outline code changes (if any), please?

**Comment by SteveSandersonMS** [comment]
Thanks for suggesting this. I've added this requirement to our tracking issue at #293.

In the meantime I'd recommend just duplicating the strings, as there isn't a straightforward way to share them.

**Comment by McHeff** [comment]
So I'm experiencing something super duper weird over here... 

Things have been working just fine until I made a new page... 

Now I'm getting this: 

Error: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.InvalidOperationException: The following routes are ambiguous:
'editfibrebaletemplates/{Id}/{BaleCount}/{Lot}/{CreatedBy}/{Revision}/{SpinProcess}/{IsCurrent}/{IsApproved}' in 'PrillaWeb.Pages.Spinner_Operations.Engineered_Fibre_Selections.EditFibreBaleTemplates'
'editfibrebaletemplates/{Id}/{BaleCount}/{Lot}/{CreatedBy}/{Revision}/{SpinProcess}/{IsCurrent}/{IsApproved}' in 'PrillaWeb.Pages.Spinner_Operations.Engineered_Fibre_Selections.EditFibreBaleTemplates'

And this is the page it's complaining about: 

![image](https://user-images.githubusercontent.com/47241975/55557070-4fefe000-56e9-11e9-8225-70c62220f2c7.png)

As you can see, there is only one page declaration.
And as for my LoadPlanning page, which is the new one I made: 

![image](https://user-images.githubusercontent.com/47241975/55557153-8299d880-56e9-11e9-9093-087cae8fd2a7.png)

She also only has one page declaration? 

WTF

**Comment by McHeff** [comment]
So... I figured out the issue. It has NOTHING to do with page declarations, it actually had to do with my for loop that I had: 

`                foreach (var item in SalesOrderLine.Where(x => (x.Selected == true) && (x.SalesOrder == SearchValue)))
                {
                    SalesOrderPallet = SalesOrderPallet.Where(x => x.StockCode == item.StockCode).ToList<SalesOrderPallets>();
                }`

Was causing the app to throw an ambiguous route error,

I then changed it to this: 

`foreach (var item in SalesOrderLine.Where(x => x.Selected == true))
                {
                    if(item.SalesOrder == SearchValue)
                    {
                        SalesOrderPallet = SalesOrderPallet.Where(x => x.StockCode == item.StockCode).ToList<SalesOrderPallets>();
                    }
                }`

And it works fine now... Super weird?

**Comment by danroth27** [comment]
Hi @McHeff. If you think you've discovered a bug, please file an issue on the https://github.com/aspnet/aspnetcore repo. Now that the Blazor code is part of the main ASP.NET Core repo, we no longer use this repo for Blazor issues.

**Comment by McHeff** [comment]
Sure thing @danroth27, it's really weird because this only happens sometimes... Like I have many razor views in my app, most of them have lambda expressions and nested for loops, but only on this new page did I get ambiguous page route errors... 

On another page, I got that error when I put some binding on my HTML control. Lol, will file an issue now (y)

**Comment by StaticBR** [comment]
In Case anyone also stumble across this issue.
Add this to your Razor file, and you can use route constants:
`@attribute [Microsoft.AspNetCore.Components.RouteAttribute(@UiPaths.Account)]`
