### ISSUE TITLE
Upgrade to 0.5.1 causes error The SPA default page middleware could not return the default page '/index.html'

### ISSUE THREAD

**Issue by dharric** [aspnet/Blazor#1364]
I downloaded the current FlightFinder sample and without modifying code I updated the packages for Blazor from 0.4 to 0.5. Upon launching I get the error in the subject.

**Comment by dharric** [comment]
Issue was partially my fault. I had only updated the assemblies on the Client project but not the Server project. However once I did that I still got an error 502 upon running app. This turned out to be missing Microsoft.AspNetCore.App in c:\program files\dotnet\shared folder, which is odd since I had installed the nuget packages to the project.

**Comment by SteveSandersonMS** [comment]
OK, glad you resolved this. If you are still having trouble with missing assemblies in `c:\program files\dotnet\shared`, I'd recommend reinstalling your .NET Core SDK entirely.

Closing as not a Blazor issue.
