### ISSUE TITLE
Hosting static files in ASP.NET Core hosting project

### ISSUE THREAD

**Issue by SMPX** [aspnet/Blazor#1367]
Client project (in conponent):
I create a link:

`<a href="http://localhost/1.txt">Download file</a>`

In Server proget in wwwroot folder i put file "1.txt"

When run and click <a> - route error:

"Error: System.InvalidOperationException: 'Router' cannot find any component with a route for '/1.txt'"

How a can host static files ?

Thank you.

**Comment by cores-system** [comment]
@SMPX, Only through JSRuntime.
If the pool passes https://github.com/aspnet/Blazor/pull/1354 , then you can use:

<a href="http://localhost/1.txt" target="_self">Download file</a>
OR
<a href="http://localhost/1.txt" target="_blank">Download file</a>

**Comment by SMPX** [comment]
Thank you

**Comment by cores-system** [comment]
@SMPX, Temporary solution.

intertop.js
```
function NavigateTo(url) {
    document.location = url;
    return true;
}
```

index.cshtml
```
@page "/"

<a href="" onclick="@(e => NavigateTo("http://localhost/1.txt"))">Download file</a>

@functions{
    async void NavigateTo(string url)
    {
        await JSRuntime.Current.InvokeAsync<string>("NavigateTo", url);
    }
}
```
