### ISSUE TITLE
Need examples showing Blazor Drag and Drop API

### ISSUE THREAD

**Issue by ericgrantholland** [aspnet/Blazor#1371]
Looking for a working example using the Blazor drag and drop API. Specifically, I'm looking for an example of setting HTML elements as dropzones and draggables WITHOUT explicit JS interop. Looking to hook into the Blazor events designed around UIDragEventArgs.

Please note I'm that I'm also looking to set transfer data using blazor C#, but this issue currently being tracked by #957

**Comment by SteveSandersonMS** [comment]
Since this is a usage question, would you mind posting to StackOverflow instead? Hope that's OK!

I think there's a good chance that an end-to-end drag and drop mechanism will probably still involve JS interop right now, but it perhaps others will have already implemented this and may know better.

**Comment by sven5** [comment]
I created a simple example for drag and drop here: [Demo](https://github.com/sven5/Blazor/tree/master/HelloWorldDragDrop)

**Comment by danroth27** [comment]
@sven5 Nice! It you send us a PR to https://github.com/aspnet/blazor.docs we can add your sample to the [Blazor community page](https://blazor.net/community).
