### ISSUE TITLE
error tip

### ISSUE THREAD

**Issue by male110** [aspnet/Blazor#1374]
<input type="text" bind="@Count" />
<div>@Count</div>
@functions{
    int Count { get; set; }
}
if input 'aaaa',How can i show some tips

**Comment by SteveSandersonMS** [comment]
If you're asking about how to deal with binding an `int` to a textbox, I'd recommend putting the `numeric` attribute on it:

```
<input bind=@Count numeric />
```

If you're looking for a more full-featured validation system, that's something we still have on the backlog. For now you would have to implement it manually, e.g., binding to a `string` value and then having your own logic to show a warning if the current value is not numeric.
