### ISSUE TITLE
Blazor templates missing after installing latest Blazor VSIX from the dev feed

### ISSUE THREAD

**Issue by renatoprogramer** [aspnet/Blazor#1375]
After the last update no longer appears the Blazor as a project.

![image](https://user-images.githubusercontent.com/15394508/44916846-172ff880-ad0d-11e8-8c57-0117743680f4.png)

**Comment by danroth27** [comment]
@renatoprogramer Thank you for reporting this issue!

I'd like to check a few things on your machine to try and figure out what is going wrong:

- Does the `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise|Professional|Community\Common7\IDE\CommonExtensions\Microsoft\Blazor` folder exist?
- Is the *Templates.pkgdef* file present in that folder? Does the contents of this file match the following:

  ```
  [$RootKey$\TemplateEngine\Templates\Blazor\0.2.0]
  "InstalledPath"="$PackageFolder$\ProjectTemplates"
  ```

- Does the `ProjectTemplates` folder exist in that folder and does it contain the  `Microsoft.AspNetCore.Blazor.Templates.0.5.1.nupkg` package?
- Is the regkey specified above present on your machine with the regkey specified above present on your machine and pointing to the location of the Blazor templates?

If all these things check out, could you please try running `devenv.exe /setup` and see if that addresses the issue?

**Comment by danroth27** [comment]
It would also be helpful if you could share the output of `dotnet --info`.

After checking these things another thing you could try is uninstalling and reinstalling the Blazor Language Service VSIX.

**Comment by renatoprogramer** [comment]
Follow some prints of what I got 

![1](https://user-images.githubusercontent.com/15394508/44924639-5ae12d00-ad22-11e8-9aa4-1dbf2758cee4.jpg)
![2](https://user-images.githubusercontent.com/15394508/44924640-5ae12d00-ad22-11e8-89a4-d67e34686c45.jpg)
![3](https://user-images.githubusercontent.com/15394508/44924641-5ae12d00-ad22-11e8-819c-a3a1da1a2a02.jpg)

**Comment by danroth27** [comment]
@renatoprogramer OK, it looks like the issue here is that the ProjectTemplates folder for the Blazor extension is missing. We need to figure out how that happened, but you should be able to repair your setup by manually creating the folder and adding Microsoft.AspNetCore.Blazor.Templates.0.5.1.nupkg to the folder.

**Comment by danroth27** [comment]
Related issue: https://github.com/aspnet/Blazor/issues/1323

**Comment by danroth27** [comment]
@renatoprogramer To help us reproduce this issue, could you please share some historical background on how you got into this state? Which update did you install that resulted in the Blazor templates disappearing? What was the state of your machine before installing the update?

**Comment by renatoprogramer** [comment]
This problem happened when Visual Studio alerted me that it had a pending update of the Blazor clicked normally in the update I closed the VS and rebooted I went to create a new project Blazor to see if it had something new and disappeared my template Blazor my off this I didn't do anything unusual.

![4](https://user-images.githubusercontent.com/15394508/44926822-fb3a5000-ad28-11e8-8625-06709c705256.jpg)

**Comment by renatoprogramer** [comment]
I installed through this link
https://marketplace.visualstudio.com/items?itemName=aspnet.blazor

**Comment by danroth27** [comment]
Great, thx! And what version of VS do you have?

**Comment by renatoprogramer** [comment]
![5](https://user-images.githubusercontent.com/15394508/44927294-74867280-ad2a-11e8-9bdf-3db1d70f1890.jpg)

**Comment by danroth27** [comment]
Actually, hold on, I was just able to reproduce this by updating to the latest VSIX from our CI dev feed. Could you please take a look at your Tools -> Options -> Environment -> Extensions and Updates settings in VS and see what Additional Extension Galleries you have configured there if any?

**Comment by danroth27** [comment]
Yup, you have a CI dev build installed. I can reproduce this. We'll take a look and follow up. Thanks!

**Comment by renatoprogramer** [comment]
![6](https://user-images.githubusercontent.com/15394508/44927458-faa2b900-ad2a-11e8-9506-752fb3505c72.jpg)

**Comment by danroth27** [comment]
@renatoprogramer For now, I recommend uninstalling the Blazor VSIX you have and instead install the latest preview release (0.5.1) from the VS marketplace.

**Comment by renatoprogramer** [comment]
Ok I will try anything eating here again my results, great job.

**Comment by renatoprogramer** [comment]
OK! Now it's working 



![9](https://user-images.githubusercontent.com/15394508/44928323-f330df00-ad2d-11e8-84a1-39dd5238a1e3.jpg)


![10](https://user-images.githubusercontent.com/15394508/44928328-f62bcf80-ad2d-11e8-9567-bb94664e3b8e.jpg)


![8](https://user-images.githubusercontent.com/15394508/44928337-fe840a80-ad2d-11e8-8b60-eadcefb0bbe9.jpg)


**Thank you**
![7](https://user-images.githubusercontent.com/15394508/44928347-02b02800-ad2e-11e8-8e8b-b317b06e3e09.jpg)
