### ISSUE TITLE
Sending objects with only private setters should give a warning

### ISSUE THREAD

**Issue by Sire** [aspnet/Blazor#1376]
When sending objects in Blazor with private setters on their properties, those properties are always empty at the client, and no warnings are given.

This is a limitation of the MessagePack de/serialization, [issue here](https://github.com/neuecc/MessagePack-CSharp/issues/284). Private fields are never serialized.

It would be very helpful to show a warning from JsInterop. It could save hours of head-scratching. At least if ALL properties have private setters - which indicates the developer doesn't know of this limitation. 

There is a very helpful warning from the jsinterop project when you're trying to send an object with a non-public constructor. So it might be possible to add another warning at this location.

Source:
```
var constructorDelegate = ConstructorCache[type] ?? 
throw new InvalidOperationException($"Cannot deserialize JSON into type '{type.FullName}' because it does not have a public parameterless constructor.");

```
[Link to source](https://github.com/dotnet/jsinterop/blob/a9a5bb9eba154d9dc3f43d5636e49d02cbd6cc97/src/Microsoft.JSInterop/Json/SimpleJson/SimpleJson.cs#L1473)

**Comment by SteveSandersonMS** [comment]
Just to clarify, there isn't really any connection between MessagePack de/serialization and JsInterop's JSON handling. There are completely separate serialization mechanisms. When you do JS interop and pass JSON-serializable data, we JSON-serialize the data before it goes to MessagePack. As such, MessagePack only sees a string, not your original .NET object.

As for whether `Microsoft.JSInterop.Json.Serialize` should throw if all getters are private, we'll take that under consideration based on whether this becomes a common feature request. I'm not sure if most other JSON serializers do that, but if they do it would be an argument in favour of that. We'll certainly consider this if others report similar confusion over time. Hope that's OK!

**Comment by OmarTawfik** [comment]
@SteveSandersonMS another symptom:
I wasted a few hours today trying to figure out why `Invoke<T>()`doesn't complete, only to finally realize that because my model `T` does not have a default constructor, therefore it is not able to deserialize it back.
It would be very helpful to throw exceptions on these operations. Please let me know if this is something I should report elsewhere.
