### ISSUE TITLE
How to pass more ChildContents from razor file?

### ISSUE THREAD

**Issue by MarekPokornyOva** [aspnet/Blazor#1378]
Hello,
I'm playing with ChildContent on a component and can't find solution for following:

Let's have reusable base component allowing to include three parts.
**SplitterBase.cshtml**
```
<div class="part1">@Part1</div>
<div class="part2">@Part2</div>
<div class="part3">@Part3</div>

@functions
{
   [Parameter]
   RenderFragment Part1 { get; set; }

   [Parameter]
   RenderFragment Part2 { get; set; }

   [Parameter]
   RenderFragment Part3 { get; set; }

	//just one ChildContent property is not enough in this case
}


```How is it possible to pass the parts from parent component defined in cshtml?
**Splitter.cshtml**
```
<SplitterBase>
	How to define Part1 here?
	How to define Part2 here?
	How to define Part3 here?
</SplitterBase>
```

**Comment by MarekPokornyOva** [comment]
Sorry, difficult to manage entering issues in IE11 here.
Here's rest of the description:

**Splitter.cshtml**```

<SplitterBase>
	How to define Part1 here?
	How to define Part2 here?
	How to define Part3 here?
</SplitterBase>
```

**Comment by MarekPokornyOva** [comment]
**Splitter.cshtml**
```
<SplitterBase>
	How to define Part1 here?
	How to define Part2 here?
	How to define Part3 here?
</SplitterBase>
```

**Comment by MarekPokornyOva** [comment]
Hi @lohithgn,
thanks for your reply. I fully understand what development and prioritization means :-). I'm just clarifying where the project is and how well it's possible to use it for "production" projects (with full respect to its experimental status).

Anyway: many thanks to all the team members for their work! Good luck!

**Comment by Lupusa87** [comment]
What you want try to do is possible but with different approach.
You can make child component and use it inside parent as many as you like and pass parameters to control child content from parent.

You can capture children references and manage them from parent as you like.

If this is not clear please provide exact requirements what result you need and I will code when will have time for it.

From markup nesting components is not supported yet as I know.

**Comment by MarekPokornyOva** [comment]
For anyone who finds this page and is interested in the topic - you might find [https://github.com/MarekPokornyOva/BlazorContentProperty](https://github.com/MarekPokornyOva/BlazorContentProperty) as usefull solution.
