### ISSUE TITLE
Issue #834 nav bug

### ISSUE THREAD

**Issue by footysteve** [aspnet/Blazor#1379]
I'm new to github hope it's ok post about a closed issue. I just encountered this while playing around with blazor

"Blazor App - simple bug, hard to fix - make DOM/window properties and events available in Blazor
#834 by Andrzej-W was closed on May 22"

This is my workaround, 

`
**button class="navbar-toggler" onclick=@Dropdown**

@functions {
    bool collapseNavMenu = true;
    bool dropDownActive = false;

    void ToggleNavMenu()
    {
        if (dropDownActive)
        {
            collapseNavMenu = !collapseNavMenu;
            dropDownActive = !collapseNavMenu;
        }
    }

    void Dropdown()
    {
        collapseNavMenu = !collapseNavMenu;
        dropDownActive = !collapseNavMenu;
    }
}`

Could be coded better I expect, a first cut, it does work though :)

**Comment by SteveSandersonMS** [comment]
Thanks for posting! This is now linked from #834 so hopefully anyone reading there will find your code too.

**Comment by Andrzej-W** [comment]
Thank you @footysteve for your solution. It is better than original Blazor code, but still not perfect.
1. On small screen click hamburger button to open menu.
2. Make screen bigger. You see menu on the left - it is OK.
3. Make screen smaller. Menu on small screen is **visible**. *I would like to have it hidden.*

Let's assume that the above behaviour is expected. Repeat the steps with small change.
1. On small screen click hamburger button to open menu.
2. Make screen bigger. You see menu on the left - it is OK.
3. Click on any menu item.
4. Make screen smaller. Menu on small screen is **hidden**. *This is inconsistency.*

In the future you can post comments directly in closed issues. You don't have to open a new one.
