### ISSUE TITLE
Issue with Javascript Interop in Server Side Blazor Project

### ISSUE THREAD

**Issue by highphilosopher** [aspnet/Blazor#1381]
Currently I am trying to access the play() method on an HTML audio tag.

`<audio id="timeOverPlayer" preload="auto"><source src="@settings["Time Over Sound"]" /></audio>`

I've got a Script tag in my index.html file:

`    <script>
        window.playElement = function (element) {
            document.getElementById(element).play();
            return true;
        }
    </script>`

And I'm trying to call this function from C# with the following static method which is an event handler (if that's important):

```
    public void OnFiveMinuteWarning(object sender, EventArgs args)
    {
        PlayAudio("fiveMinutePlayer");
    }
```

```
    public static Task<bool> PlayAudio(String elementName)
    {
        return JSRuntime.Current.InvokeAsync<bool>("playElement", elementName);
    }
```

When this happens I get no audio and no errors in the console. I can manually call the Javascript from the console, and the audio plays fine. If I add a Wait() on the PlayAudio method call, I get an error:

> System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WebClock.App.Pages.Clocks.OnTimeOver(Object sender, EventArgs args) in C:\Users\samue\source\repos\BlazorClock\WebClock\WebClock.App\Pages\Clocks.cshtml:line 52
   at WebClock.App.Services.Clock._timer_Elapsed(Object sender, ElapsedEventArgs e) in C:\Users\samue\source\repos\BlazorClock\WebClock\WebClock.App\Services\ClockService.cs:line 111
   at System.Timers.Timer.MyTimerCallback(Object state)

> Inner Exception 1:
> JSException: Could not find 'playElement' in 'window'.
> Error: Could not find 'playElement' in 'window'.
>     at http://localhost:37382/_framework/blazor.server.js:23:47556
>     at Array.forEach (<anonymous>)
>     at p (http://localhost:37382/_framework/blazor.server.js:23:47517)
>     at http://localhost:37382/_framework/blazor.server.js:23:48120
>     at new Promise (<anonymous>)
>     at e.beginInvokeJSFromDotNet (http://localhost:37382/_framework/blazor.server.js:23:48094)
>     at http://localhost:37382/_framework/blazor.server.js:16:11652
>     at Array.forEach (<anonymous>)
>     at e.invokeClientMethod (http://localhost:37382/_framework/blazor.server.js:16:11623)
>     at e.processIncomingData (http://localhost:37382/_framework/blazor.server.js:16:10229)
> 

Not sure if this is just not being raised when async or if the error is because I'm Waiting on an async call. At this point I'm pretty puzzled.

**Comment by Lupusa87** [comment]
As Steve said once wait not works in browser.
https://github.com/aspnet/Blazor/issues/1120#issuecomment-404663963

**Comment by RyoukoKonpaku** [comment]
@highphilosopher the reason why the first case doesn't do anything was because you were returning a ```Task``` from the method but didn't execute it yet.

The reason why the second one runs is because the ```await``` keyword starts the task and waits for it to finish. I haven't tried it yet but if you don't particularly care if the ```async``` method finishes or not is that you could do ```PlayAudio("params").Start()``` on the first case though I do think that's not a good idea overall.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @RyoukoKonpaku!

**Comment by highphilosopher** [comment]
@RyoukoKonpaku Actually when I try .Start() I get an error...
System.InvalidOperationException: 'Start may not be called on a promise-style task.'

@SteveSandersonMS 
If I try to await the method call I still get the same error as I do with the Wait() method.

Note that it works fine when called from a button click in the HTML. It's the event firing call stack that fails to find the Javascript function. It seems like it's when the Server side comes back on a call stack that's not started from an async call.

I can even put the method back in the service... Call it from the button and it works. Call it from the event call stack and it fails.
