### ISSUE TITLE
When using binding, on enter key pressed I do not receive the actual input value

### ISSUE THREAD

**Issue by NikolayIT** [aspnet/Blazor#1395]
I have the following code:

    <input bind=@this.Value onkeypress="@KeyPress" />
    @functions {
        public string Value { get; set; }
        void KeyPress(UIKeyboardEventArgs e)
        {
            if (e.Key == "Enter")
            {
                Console.WriteLine(this.Value);
            }
        }
    }

When I write some text in the input field (for example `test1`) and click enter I get empty text written on the console. When I add some more text (like `test2`) and again click enter I get just `test1` (the previous value before the enter click) on the console:

![image](https://user-images.githubusercontent.com/3106986/45209844-a9e51000-b296-11e8-8e41-83c8c1e5c325.png)

**Comment by danroth27** [comment]
I believe this is expected. The bind is handled using the `onchange` event, which isn't triggered until after `onkeypress` is fired.

**Comment by doggy8088** [comment]
@danroth27 How to get input value in the `onkeyup` event?  I can't get input value from `UIKeyboardEventArgs` event data.

**Comment by Andrzej-W** [comment]
@doggy8088 look here for general idea:
https://blazor.net/docs/javascript-interop.html#capture-references-to-elements
This example uses `element.focus()`. You have to create similar JS interoperability for `element.value()`. Of course you have to return `string` from this function. Look at example with `prompt` function in the same doc.

**Comment by michaelvolz** [comment]
Is this by design or will it be changed in the future? It seems to be a common use case.
I have a searchbox, I press enter and now I need the new searchvalue.

**Comment by sven5** [comment]
It works using the `onkeyup` event. The bound value from the input is set.

your code should look like:

```
<input bind=@this.Value onkeyup="@KeyUp" />
@functions {
    public string Value { get; set; }
    void KeyUp(UIKeyboardEventArgs e)
    {
        if (e.Key == "Enter")
        {
            Console.WriteLine(this.Value);
        }
    }
}
```

**Comment by Programmer-david** [comment]
> It works using the `onkeyup` event. The bound value from the input is set.
> 
> your code should look like:
> 
> ```
> <input bind=@this.Value onkeyup="@KeyUp" />
> @functions {
>     public string Value { get; set; }
>     void KeyUp(UIKeyboardEventArgs e)
>     {
>         if (e.Key == "Enter")
>         {
>             Console.WriteLine(this.Value);
>         }
>     }
> }
> ```

Can confirm this works great!

**Comment by surfmuggle** [comment]
Hello  @sven5  is your syntax the current one for server side blazor preview 8?

I would have thought  that this should work.

    <input @bind="todo.Title" @onkeyup="AddTodoOnEnter" />

```
@code {
   private void AddTodoOnEnter( UIKeyboardEventArgs eventArgs)
   {
        if (eventArgs.Key == "13" )        // fire on enter 
        {
            AddTodo();
        }        
   }
}

```
But neither @onkeyup="AddTodoOnEnter"  nor @onkeyup="@AddTodoOnEnter" works. In firefox the DOM property for _blazorEvents_1: does not contain an onkeyup.
