### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#14]
- [ ] Debug server

**Comment by Thaina** [comment]
Doesn't chrome debugger worked?

https://twitter.com/davidfowl/status/891125650286755840

**Comment by RyoukoKonpaku** [comment]
@Thaina I think that example was based on the old Blazor version before the ASP.NET team re-wrote it to what you see today. So I doubt that debugging feature is gonna work now.

**Comment by Thaina** [comment]
Maybe we should ask @davidfowl

Sorry for bother you

**Comment by danroth27** [comment]
Correct, debugging has yet to be implemented with the new code base.

**Comment by ericgrantholland** [comment]
Looks like server-side debugging is working. What about debugging client-side in the functions area? Is this planned to be supported in the future?

**Comment by SteveSandersonMS** [comment]
Since work on this is now underway in the Mono repo, and we've already integrated Blazor with that, I think this issue is no longer tracking anything so I'll close it.

**Comment by janaka** [comment]
Can you clarify if debugging client side works? Particularly interested in VS Code.

**Comment by ericgrantholland** [comment]
Client-side debugging does work in chrome after a few annoying steps. The official write-up for it is actually really good. See below

https://blazor.net/docs/debugging.html

**Comment by didii** [comment]
So how does one exactly debug? I've followed the steps from the guide (https://blazor.net/docs/debugging.html) but I'm facing some issues:

- Alt+Shift+D does nothing
  - I can circumvent this by manually going to http://localhost:9222 and selecting the correct window
- After loading into the inspector view, no .dll show up in the file list so I can't set any breakpoint

Steps I took:

1. Build the solution in Debug
2. Open chrome with `%programfiles(x86)%\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222 http://localhost:52734`
3. Open a new tab in chrome and navigate to `localhost:9222` and select the window where the blazor app is running in
4. In the tab sources the .dll is not visible (after refreshing the app, the entry `wasm` appears, but seems to contain only IL-like code)

Should I open a new issue for this? Can't find anything related to my current problem.

**Comment by Gnredwards** [comment]
@didii I experienced a similar issue, in the end the problem was cause because I'm using an alternative keyboard layout (Dvorak). Hitting what I thought was Alt + Shift + D did nothing (this is Alt + Shift + H on a Qwerty keyboard).  When I tried using the "real" D key it worked.  Hope this may be of some use.

**Comment by didii** [comment]
@Gnredwards thanks. I just solved it myself yesterday evening. I simply had an extension that used that same keyboard shortcut and blocked Blazor from doing anything. So after disabling it, it worked!
