### ISSUE TITLE
Task.Delay exception

### ISSUE THREAD

**Issue by rlmartins76** [aspnet/Blazor#140]
static void Main(string[] args)
        {
            Test();
           
            new BrowserRenderer().AddComponent<Home>("app");
        }

        static async void Test()
        {
            await Task.Delay(1000);
        }

**Comment by danroth27** [comment]
@rlmartins76 Could you please provide details on the exception that you are seeing? Also, what are the exact steps needed to reproduce the issue? I assume you are just modifying the sample StandAlone app?

@kumpera I believe you said there might be a known issue with `Task.Delay()` in our current Mono drop, correct?

**Comment by SteveSandersonMS** [comment]
It is a known issue in Mono (yes, the one @danroth27, @kumpera and I discussed previously).

It's also related to the problem with using `HttpClient`, i.e., tasks based on timers currently just throw.

**Comment by danroth27** [comment]
@kumpera is there a GitHub issue tracking this on the Mono side?

**Comment by rlmartins76** [comment]
Thanks for the information. I did changed the sample with the code I supplied in my initial issue post. It will be great to know if there is a bug created on mono side, so I can track it. Async/awaits are becoming more and more the norm this days.

**Comment by SteveSandersonMS** [comment]
Note that `async`/`await` itself does work. You can use them with `TaskCompletionSource`, for example. What doesn't yet work on Mono for WASM is any task whose implementation involves a timer (which is most of the useful ones).

**Comment by rlmartins76** [comment]
@stevesandersonMS noted.

**Comment by kumpera** [comment]
This was fixed on a recent version of mono

**Comment by rlmartins76** [comment]
Looking forward to see the new version of mono as part of blazor.

**Comment by davidnmbond** [comment]
In the original post, the Test() function was not awaited.  Would that matter?
