### ISSUE TITLE
A compatible SDK version for global.json version: [2.1.300] ... was not found

### ISSUE THREAD

**Issue by StingyJack** [aspnet/Blazor#1401]
I was getting this when trying to follow the Getting Started guide.  I found my version number by using `dotnet --version` (it was 2.1.401) and then I replaced the 2.1.300 into the `global.json`.

The Getting Started does work at this point, are there any known problems with using a slightly later version of the dotnet SDK?

**Comment by danroth27** [comment]
Nope, using a later SDK is fine. We'll be removing the global.json files in our next release. Sorry about the confusion!

**Comment by kaby76** [comment]
Same problem here. After creating the application through VS, change the file "global.json" in your solution directory to use the SDK version you have installed. E.g., for 2.1.402,
`{
  "sdk": {
    "version": "2.1.402"
  }
}
`
And now the "Hello World" example works. -K
