### ISSUE TITLE
Why blazor app doesn't work when i change root to folder “_framework”

### ISSUE THREAD

**Issue by PeskovV** [aspnet/Blazor#1421]
I change my base href in `index.html`: was `href="/"` has become `href="/schedule/"`

Also i change `Configure`:
 

     app.UseStaticFiles();
                app.UseStaticFiles(new StaticFileOptions()
                {
                    FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(),@"Schedule.Client", @"dist")),
                    RequestPath = new PathString("/schedule")
                });
Here located my files

[![Here located my files:][1]][1]

css, js, resources work good, but _framework which includes wasm files and doesn't work correct.

index.html:

    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width">
        <title>Schedule</title>
        <link rel="icon" href="css/Resources/icon_title.png" />
        <base href="/schedule/" />
        <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" crossorigin="anonymous">
        <link href="css/site.css" rel="stylesheet" />
        <link href="css/btnstyle.css" rel="stylesheet" />
        <script src="js/SetScroll.js"></script>
    
    </head>
    <body>
        <app>
            <div id="demo" style="margin:auto; top:30px;">
                <img src="css/Resources/logo-fin.png" />
                <div class="circle fas fa-spinner"></div>
            </div>
        </app>
    
        <script src="_framework/blazor.webassembly.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.2.0/js/all.js" crossorigin="anonymous"></script>
    </body>
    </html>

When I start my app, I get error
[![enter image description here][2]][2]

When i use `href="/"`, all is correct

What could be wrong?
Thanks!

Update

I have found the same problem and solution, but there is used a Azure CLI:
https://anthonychu.ca/post/blazor-azure-storage-static-websites/

[![enter image description here][3]][3]
 
  [1]: https://i.stack.imgur.com/q4nsh.png
  [2]: https://i.stack.imgur.com/0yNIS.png
[3]: https://i.stack.imgur.com/gXp6g.png

**Comment by SteveSandersonMS** [comment]
At the very least, you'd need to move your `UseBlazor` call into a block like:

```
app.Map("/schedule", subdirApp =>
{
    subdirApp.UseBlazor<Startup>();
});
```

... so that the `UseBlazor` middleware is operating within the new root.

There might be more as well - I'm not in a position to actually test this right now. However you can find a working example of a Blazor app hosted in a subdirectory at https://github.com/aspnet/Blazor/blob/master/test/testapps/TestServer/Startup.cs#L41

**Comment by PeskovV** [comment]
Hi!
I have started use app.Map. My code:
Srever Startup.cs:
```
 app.Map("/schedule", subdirApp =>
            {
                subdirApp.UseBlazor<Client.Startup>();
            });
```
Client index.html:
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">
    <title>Schedule</title>
    <link rel="icon" href="css/Resources/icon_title.png" />
    <base href="/schedule/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" crossorigin="anonymous">
    <link href="css/site.css" rel="stylesheet" />
    <link href="css/btnstyle.css" rel="stylesheet" />
    <script src="js/SetScroll.js"></script>

</head>
<body>
    <app>
        <div id="demo" style="margin:auto; top:30px;">
            <img src="css/Resources/logo-fin.png" />
            <div class="circle fas fa-spinner"></div>
        </div>
    </app>

    <script src="_framework/blazor.webassembly.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.2.0/js/all.js" crossorigin="anonymous"></script>
</body>
</html>
```
I change base path.

Client Index.cshtml - method OnInitAsync
  ```
protected override async Task OnInitAsync()
  {
        response = await Http.SendAsync(new HttpRequestMessage(HttpMethod.Get, "schedule/..."));
        courseList = await Http.GetJsonAsync<List<string>>("schedule/...");
        _modTime = _dateEntity.Replace(LASTMODDATE, "");
        this.StateHasChanged();
    }

```
When I start my app, I get error
![screenshot_1](https://user-images.githubusercontent.com/26106827/45609742-db619680-ba61-11e8-87bc-1e7c6cb6602d.png)

When i use root whithout "/schedule" all is OK, but when i use this root, i've been starting to get error.
please, help)

**Comment by PeskovV** [comment]
@SteveSandersonMS  Thank you, very much!
