### ISSUE TITLE
Blazor Project won't compile

### ISSUE THREAD

**Issue by redmisfitx** [aspnet/Blazor#1425]
Installed .NET Core SDK 2.1.402 and created a Blazor project in Visual Studio 15.8.4 I am not able to run the project. It throws the following error. I've tried suggestions like deleting the json file which has a reference to .net core 2.1.300 among many other things including clearing all nuget packages and restoring them. All to no avail.

This is the actual error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet "C:\Users\redmi\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json obj\Debug\netstandard2.0\Control Edge.dll --references "C:\Edge\obj\Debug\netstandard2.0\blazor/bootjson-references.txt" --embedded-resources "C:\Edge\obj\Debug\netstandard2.0\blazor/embedded.resources.txt" --linker-enabled --output "C:\Edge\obj\Debug\netstandard2.0\blazor/blazor.boot.json"" exited with code -532462766.	Control Edge	C:\Users\redmi\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\Blazor.MonoRuntime.targets	635

**Comment by danroth27** [comment]
Could you please build the project by running `dotnet msbuild /bl` from the project folder and share the generated *msbuild.binlog* with us?

**Comment by SteveSandersonMS** [comment]
Closing due to lack of info. Hope that's OK.

**Comment by aboimpinto** [comment]
I'm having this same issue with the last preview version of .NET CORE 3

dotnet msbuild /bl
Microsoft (R) Build Engine version 16.0.385-preview+g966cdf2ac6 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\3.0.100-preview-010184\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\3.0.100-preview-010184\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\3.0.100-preview-010184\dotnet.dll -maxcpucount -verbosity:m /bl .\WebApplication3.csproj
C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Users\Esqueleto\source\repos\WebApplication3\WebApplication3\WebApplication3.csproj]
  WebApplication3 -> C:\Users\Esqueleto\source\repos\WebApplication3\WebApplication3\bin\Debug\netstandard2.0\WebApplication3.dll
  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '3.0.0-preview3-27503-5' was not found.
    - Check application dependencies and target a framework version installed at:
        C:\Program Files\dotnet\
    - The .NET Core framework and SDK can be installed from:
        https://aka.ms/dotnet-download
    - The following versions are installed:
        2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.2.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.2.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        3.0.0-preview-27324-5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    - Installing .NET Core prerequisites might help resolve this problem:
        https://go.microsoft.com/fwlink/?linkid=798306
C:\Users\Esqueleto\.nuget\packages\microsoft.aspnetcore.blazor.build\0.9.0-preview3-19154-02\targets\Blazor.MonoRuntime.targets(633,5): error MSB3073: The command "dotnet "C:\Users\Esqueleto\.nuget\packages\microsoft.aspnetcore.blazor.build\0.9.0-preview3-19154-02\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json "obj\Debug\netstandard2.0\WebApplication3.dll" --references "C:\Users\Esqueleto\source\repos\WebApplication3\WebApplication3\obj\Debug\netstandard2.0\blazor\bootjson-references.txt" --embedded-resources "C:\Users\Esqueleto\source\repos\WebApplication3\WebApplication3\obj\Debug\netstandard2.0\blazor\embedded.resources.txt" --linker-enabled --output "C:\Users\Esqueleto\source\repos\WebApplication3\WebApplication3\obj\Debug\netstandard2.0\blazor\blazor.boot.json"" exited with code -2147450730. [C:\Users\Esqueleto\source\repos\WebApplication3\WebApplication3\WebApplication3.csproj]

**Comment by acoop133** [comment]
Trying to build the blazor template "Blazor (ASP.NET Core hosted)"

PM> dotnet msbuild /bl
Microsoft (R) Build Engine version 16.1.54-preview+gd004974104 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\dotnet.dll -maxcpucount -verbosity:m /bl .\SnapRepo.sln
C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Users\acoop\source\repos\SnapRepo\SnapRepo.Server\SnapRepo.Server.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Users\acoop\source\repos\SnapRepo\SnapRepo.Client\SnapRepo.Client.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Users\acoop\source\repos\SnapRepo\SnapRepo.Shared\SnapRepo.Shared.csproj]
  SnapRepo.Shared -> C:\Users\acoop\source\repos\SnapRepo\SnapRepo.Shared\bin\Debug\netstandard2.0\SnapRepo.Shared.dll
  SnapRepo.Client -> C:\Users\acoop\source\repos\SnapRepo\SnapRepo.Client\bin\Debug\netstandard2.0\SnapRepo.Client.dll
  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '3.0.0-preview5-27626-15' was not found.
    - The following frameworks were found:
        2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.2.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        2.2.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        3.0.0-preview4-27615-11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  
  You can resolve the problem by installing the specified framework and/or SDK.
  
  The .NET Core frameworks can be found at:
    - https://aka.ms/dotnet-download
C:\Users\acoop\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview5-19227-01\targets\Blazor.MonoRuntime.targets(633,5): error MSB3073: The command "dotnet "C:\Users\acoop\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview5-19227-01\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json "obj\Debug\netstandard2.0\SnapRepo.Client.dll" --references "C:\Users\acoop\source\repos\SnapRepo\SnapRepo.Client\obj\Debug\netstandard2.0\blazor\bootjson-references.txt" --embedded-resources "C:\Users\acoop\source\repos\SnapRepo\SnapRepo.Client\obj\Debug\netstandard2.0\blazor\embedded.resources.txt" --linker-enabled --output "C:\Users\acoop\source\repos\SnapRepo\SnapRepo.Client\obj\Debug\netstandard2.0\blazor\blazor.boot.json"" exited with code -2147450730. [C:\Users\acoop\source\repos\SnapRepo\SnapRepo.Client\SnapRepo.Client.csproj]

**Comment by chucker** [comment]
@acoop133 the key message is here:

>You can resolve the problem by installing the specified framework and/or SDK.

You need to manually upgrade your .NET Core 3.0 Preview to 5 (you have 4). https://dotnet.microsoft.com/download/dotnet-core/3.0
