### ISSUE TITLE
Web UI designer

### ISSUE THREAD

**Issue by Rgl88** [aspnet/Blazor#143]
Hello
Many backend developers no time or knowledge to build ui via html and css , my suggestion is why we do not have ui design system like silverlight (drag and drop) it can be done via canvas or ...
I know we lose seo in websites but for web applicaions (SPA) it's great feature

**Comment by Terricide** [comment]
Wisej is a pretty useful framework for that exact purpose. Though something that did xaml standard would be awesome.

**Comment by dragnilar** [comment]
Yeah, Wisej is awesome! 

Unfortunately its not free with Visual Studio, which can be a big deterrent. Supposedly it can also be heavy on the server, which I suspect can be a another deterrent.  So that's probably why people are still left hoping that MS can offer their own SPA/client-side framework solution that offers both a designer and all the luxuries of using .NET. 

Anyway, I second Rgl88's suggestion.

**Comment by stavroskasidis** [comment]
I disagree completely. You should embrace the idioms of the web, not fight against it. Fighting against it and hiding everything behind a layer is what made web forms a failure. Maybe a framework like xamarin forms can fill that role better, but Blazor should stay pure html/css.

**Comment by RyoukoKonpaku** [comment]
I agree. A XAML based web framework would be awesome, but Blazor's role is more on the traditional HTML/CSS stack.
A XAML stack should be another project at most. Maybe try asking the guys at Xamarin Forms for it. I'd love for that to happen, but for now let's count on this experiment on Blazor being a success as it can open those opportunities later on.

**Comment by dragnilar** [comment]
That's probably why I said a designer/XAML driven framework should come later; as you kindly pointed out, it feels out of scope for Blazor.

**Comment by davidbmasterson** [comment]
I agree with stavroskasidis I do not want a Microsoft designer I would rather learn more about html and css than a new untried xaml based designer. Html and css are well established and time spent learning them is transferable. The promise of Blazor is to bring c# and the Microsoft tooling to client side web development removing the need to battle with JavaScript or learn typescript with all its build steps.

**Comment by SteveSandersonMS** [comment]
An interesting discussion! I'll mark it closed because it's not an active work item, but please feel free to continue discussing here.

**Comment by melkor54248** [comment]
Stavros has a point, but having a designer won't prevent you from going with pure html/css. I think it's a nice to have feature, low priority though.

**Comment by montyclt** [comment]
Whats about Ouii with WebAssembly?

**Comment by dragnilar** [comment]
Another option may also be Uno, if you are into UWP: https://github.com/nventive/Uno

**Comment by montyclt** [comment]
@dragnilar I'm interesting in Uno.

Why preffer Uno over Xamarin, or why preffer Xamarin over Uno?
