### ISSUE TITLE
Blazor in self hosted OWIN on .NET Framework

### ISSUE THREAD

**Issue by gthvidsten** [aspnet/Blazor#1443]
I have a service written in .NET Framework that hosts its own webserver using OWIN. Having read about Blazor, I want to start experimenting with it and try to host a Blazor webapp in this service.

However, I haven't found any good instructions on how to do self-hosting with Blazor, especially not on OWIN and .Net Framework. I'd really like a native solution, and converting my solution to .NET Core is not viable. Also, I would really like not to have to compile the Blazor webapp in another solution then copying the files to be hosted using i.e. `Microsoft.Owin.StaticFiles` middleware.

The question, then, is quite basic:

How can I host a Blazor webapp in my existing OWIN service?

**Comment by Suchiman** [comment]
The Blazor build produces a dist directory which just needs to be served through the StaticFiles middleware.
Without having tried anything on my own, i would imagine that this should just work (TM) if you use
`app.UseStaticFiles("../relative/path/to/dist/");`
I don't see a reason why the blazor project would need to be a in a different `.sln`

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @Suchiman!

Yes, serving it as static files should be fine. You might also want to implement some middleware of your own to handle the SPA fallback routing (e.g., so a request for `/anypage`) is handled by serving the `index.html` file if it doesn't match a file from the `dist` directory.
