### ISSUE TITLE
Unable to create Blazor app with fsproj

### ISSUE THREAD

**Issue by panesofglass** [aspnet/Blazor#1450]
I've attempted to create an all-F# Blazor app with each release, but it seems that the current solution requires a `csproj` and expects all files to be C#. I suspect this is because the Blazor tooling is inspecting the solution to find `.cshtml` files and generate the `.g.cs` files the compiler will use. I've built a F# renderer, [Trail](https://github.com/panesofglass/trail), that doesn't require this step, and I would love to build Blazor apps with just the `fsproj`. The only thing in the `csproj` in my Trail sample apps is the [call to build and run the host builder](https://github.com/panesofglass/trail/blob/master/sample/standalone/BlazorApp1/Program.cs).

I think this should be possible as the mono wasm tooling appears able to run F# projects. I would be very glad to help out with investigating whether this is possible and desirable from a Blazor project perspective.

**Comment by danroth27** [comment]
> I've attempted to create an all-F# Blazor app with each release, but it seems that the current solution requires a csproj and expects all files to be C#. 

@panesofglass Can you walk me through the steps you are trying and describe what specifically doesn't work?

> I think this should be possible as the mono wasm tooling appears able to generate wasm from F# projects

I believe that's unrelated. Blazor doesn't generate any WebAssembly files currently (although an AoT compilation story to WebAssembly is something we're investigating with the mono team). The WebAssembly for the .NET runtime is prebuilt and packaged with the Blazor framework. Blazor projects are built to normal .NET assemblies, which presumably an F# Blazor project would do as well.

**Comment by rynowak** [comment]
I'm not sure exactly what you're asking for help with, but `.cshtml` files require a `.csproj` and that will be the case for the foreseeable future. 

Blazor generates C# files during the build, and those files are compiled into an assembly with other C# files in the same project. If you're trying to create an all F# Blazor app, you'll need to forego `.cshtml` entirely, or put in a project that you reference from F#.

**Comment by panesofglass** [comment]
@danroth27 yes, I'll create a branch in https://github.com/panesofglass/trail soon that will show what I've tried so far.

@rynowak I am not using cshtml but generating the target render tree from F#, e.g.

``` fsharp
[<LayoutAttribute(typeof<MainLayout>)>]
[<RouteAttribute("/")>]
type Index () =
    inherit Trail.Component()

    override __.Render() =
        Dom.Fragment [
            Dom.h1 [] [ Dom.text "Hello, world!" ]
            Dom.text "\n\nWelcome to your new app.\n\n"
            Dom.comp<SurveyPrompt> [Dom.HtmlAttribute("title", "How is Blazor working for you?")] []
        ]
```

**Comment by rynowak** [comment]
Ok, so if there's a specific problem that we can help - could you provide more information?

**Comment by panesofglass** [comment]
It seems without the `Microsoft.AspNetCore.Blazor.Build` reference, the `*.blazor.config`, `dist` folder, etc. are not generated. However, that reference appears to expect a `.csproj` and C# files.

**Comment by rynowak** [comment]
Alright thanks, I'll take a look at this and see what the problem is.

**Comment by rynowak** [comment]
Fixed for the 0.6 release

**Comment by panesofglass** [comment]
Thank you, @rynowak!

**Comment by panesofglass** [comment]
I just want to add that I am delighted you took the time to investigate and resolve this issue. Thank you very much!

**Comment by rynowak** [comment]
Thanks! 

If you want to experiment with unblocking with this locally, you can hack your RazorCompilation.targets to improve this check https://github.com/aspnet/Blazor/commit/5df4eef30497bf13217312b250b247bc83994a9e

If you run into any other issues let us know.

**Comment by panesofglass** [comment]
This works great! Thanks again, @rynowak!
