### ISSUE TITLE
base class, public/private parameter 

### ISSUE THREAD

**Issue by emelhu** [aspnet/Blazor#1459]
![1](https://user-images.githubusercontent.com/7081135/45879252-0fabbe80-bda4-11e8-8cd5-7049b2383079.jpg)
![2](https://user-images.githubusercontent.com/7081135/45879256-13d7dc00-bda4-11e8-8c0b-c22c0b30c9ef.jpg)

### **Only a warning, but.._**.

**Comment by monterolebronhg** [comment]
Marking the parameter as protected will help you.
I think the code analyzer should suggest to mark the parameter as protected instead of private.

**Comment by vertonghenb** [comment]
There is a code snippet to create parameters, so you won't get this issue in the future:
`para > tab > tab`

**Comment by SteveSandersonMS** [comment]
Thanks for the answers!

**Comment by emelhu** [comment]
Thanks!
