### ISSUE TITLE
onkeypress (Backspace) does not work in the following browsers: Chrome and Edge , but it's working in MOZILLA FIREFOX

### ISSUE THREAD

**Issue by carlosalcantara2668** [aspnet/Blazor#1462]
what is working in mozilla,

Backspace
Backspace
Backspace
ArrowLeft
ArrowUp
ArrowDown
ArrowRight
ArrowLeft

![keyboar](https://user-images.githubusercontent.com/16179281/45912802-229aaf00-bdf5-11e8-8810-ca0050d14489.JPG)

@using Microsoft.JSInterop

Type here: <input onkeypress=@OnKeyPressed />

<ul>
    @foreach (var key in keysPressed)
    {
        <li>@key</li>
    }
</ul>

@functions {
List<string> keysPressed = new List<string>();

void OnKeyPressed(UIKeyboardEventArgs eventArgs)
{
    Console.WriteLine(Json.Serialize(eventArgs));
    keysPressed.Add(eventArgs.Key);
}
}

**Comment by carlosalcantara2668** [comment]
onkeypress does not work in the following browsers: Chrome and Edge

Backspace
Backspace
Backspace
ArrowLeft
ArrowUp
ArrowDown
ArrowRight
ArrowLeft

**Comment by csnewman** [comment]
You are using the incorrect event:
"The keypress event is fired when a key that produces a character value is pressed down. Examples of keys that produce a character value are alphabetic, numeric, and punctuation keys."

You should use onkeyup or onkeydown for non printable characters. This is a browser thing, and not related to blazor.
