### ISSUE TITLE
Building the repo with v0.5.1 tooling (Microsoft.VisualStudio.BlazorExtension.vsix) installed

### ISSUE THREAD

**Issue by maxild** [aspnet/Blazor#1467]
Following the getting started guide, I installed the (latest) v0.5.1 Blazor Language Services extension from the Visual Studio Marketplace. 

After creating a few projects with vs2017, I cloned the repo (with submodules) 

```
git clone https://github.com/aspnet/Blazor.git
git submodule update --init --recursive
```

But it seems that having installed the v0.5.1 Blazor Language Services extension interferes with the build both using cli (running ```build.cmd```) and building inside vs2017. Some Razor tooling exited with non-zero status code, and I got the message:

* "rzc discover exited with code 1"

This [comment](https://github.com/aspnet/Blazor/issues/662#issuecomment-384081422) and the fact that the build VSIX couldn't get deployed (because a higher version was installed), made me uninstall the v0.5.1 Blazor Language Services extension. 

After uninstalling the v0.5.1 VSIX the build succeeded on the commandline and in vs2017.

Questions:

1. Does installing the v0.5.1 VSIX make it impossible to build the repo (master branch)?
2. Are there any Build Properties I can use for building the repo and having the v0.5.1 tooling installed at the same time?

**Comment by Suchiman** [comment]
After some thinking about this message i figured that it's complaining about the `Version` here  https://github.com/aspnet/Blazor/blob/0f01f01ef90dd9c06e591432cfe548e7922eead7/tooling/Microsoft.VisualStudio.BlazorExtension/source.extension.vsixmanifest#L4
If you set it to a version higher than the installed one (e.g. `15.8.0.0`) then the error will go away.
#Contributor Pain

**Comment by maxild** [comment]
@Suchiman Thanks. But I am not a VSIX developer, so how ```Version="|%CurrentProject%;GetBuildVersion|"``` gets resolved is a mystery to me. Can you be more specific about how I can up the version to ```15.8.0.0``` in the repo working tree?  Aaahhh....Maybe you are saying that I should just override the version attribute with

```xml
<Identity Id="Microsoft.VisualStudio.BlazorExtension" Version="15.8.0" Language="en-US" Publisher="Microsoft" />
```

**Comment by maxild** [comment]
I am closing the issue, because changing the VSIX manifest file by hand in the repo working tree to 15.8.0.0 > 15.7.x.y  (the version of the v0.5.1 tooling in the gallery) did the trick.
