### ISSUE TITLE
blazor code behind

### ISSUE THREAD

**Issue by giangcoi48k** [aspnet/Blazor#1472]
Why blazor does not have code behind file, like old style webform or new style razor web pages?

**Comment by lohithgn** [comment]
you can do code behind style with Blazor too. take a look at this example i have created for Blazor - https://github.com/lohithgn/blazor-tour-of-heroes/tree/master/src/BlazorTourOfHeroes/BlazorTourOfHeroes.Client/Pages/Heroes

hope this helps.
