### ISSUE TITLE
Enhance template with header and footer examples

### ISSUE THREAD

**Issue by kant2002** [aspnet/Blazor#1488]
I experience at least two cases (one at Gitter, second at GitHub) where people was hit by name resolution mechanism for tags. Header/Footer is common cause right now. I propose modify existing templates with `AppHeader.cshtml` and `AppFooter.cshtml` and put there warnings 
1.Why they named such and not just `Header` and `Footer.cshtml`
2. Maybe add link to some documentation page in http://blazor.net/docs where this topic would be discussed in more details.

This allow postpone making decision what should be done with such naming conflicts.

**Comment by RyoukoKonpaku** [comment]
If i remember they will resolve this issue by requiring components to start with a capital character just like how component resolution on React works to avoid the problem as well. This way it can determine ```<footer>``` and ```<Footer>``` respectively. #1173 here's the open issue for it and here's a bit more with discussion #1155 for the issue.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion.

Yes, @RyoukoKonpaku's description matches what I'd like to see as a long-term resolution to this.

In the shorter term, I would not like to complicate the default templates by adding extra `AppHeader`/`AppFooter` components as an indirect way of hinting at the limitation. I know a few people would benefit, but it's also noise that everyone would have to bear, and would quickly get really bad if we added comments about all limitations. Hope that's OK.
