### ISSUE TITLE
Template enhancements

### ISSUE THREAD

**Issue by dlr1** [aspnet/Blazor#1489]
Is there a plan to allow piece of html(though not going to be reused) be declared else where in the page and refer to it by name or id so that the actual html in the body of the page will be cleaner?

ex:
```<Template id="mytemplate1">... </Template>```
Use it like below
```
if(true)
<mytemplate1/>
```

**Comment by Suchiman** [comment]
In Blazor 0.6 you should be able to use https://github.com/aspnet/Blazor/pull/1360

**Comment by dlr1** [comment]
I saw you can have some html in a file and use it in another file. This is for those scenarios for reuse. but creating a file for block of html when it is not reused, we will end up creating bunch of files

**Comment by Suchiman** [comment]
@dlr1 i don't know if you've looked at the PR description but this allows you to declare a variable that holds a html snippet that you can render (in the same file)

**Comment by dlr1** [comment]
yes, I know you can create a RenderFragment and use that, I was thinking along these lines in angular, all in Html
```
<div class="lessons-list" *ngIf="lessons else loading">
  ... 
</div>

<ng-template #loading>
    <div>Loading...</div>
</ng-template>

```

**Comment by rpedretti** [comment]
@dlr1,  The only thing that changes from angular is the way you declare the template and the if statement. 

```
@{ RenderFragment loading = () => @<div>Loading...</div>; }
@if(lessons)
{
    <div class="lessons-list">
        ...
    </div>
}
else {
    @loading();
}
```

**Comment by dlr1** [comment]
@rpedretti I guess so, Thanks.
