### ISSUE TITLE
Milestones for future releases?

### ISSUE THREAD

**Issue by daveabrock** [aspnet/Blazor#1491]
Do you have a short list/documentation of milestones you are hitting for the next few releases - like 0.6, 0.7, and so on? I am doing some conference talks on Blazor and the information might be useful, if you have it!

**Comment by danroth27** [comment]
Blazor 0.6.0 is pretty much done, so you can look at the release notes for the [0.6.0-preview1 release](https://github.com/aspnet/blazor/releases/0.6.0-preview1) to see what's there. 

We still need to do planning for 0.7.0 and beyond but we will be happy to share those plans once they are ready. You can look at our [project backlog](https://github.com/aspnet/blazor/projects/3) to get a feel for what we are looking at doing next.
