### ISSUE TITLE
Call DOM's methods

### ISSUE THREAD

**Issue by doggy8088** [aspnet/Blazor#1495]
For DOM properties, we can use binding syntax to get/set it.  But for DOM methods, is it possible to easily call to arbitary DOM's method without implementing JS Interop?  Such as calling `focus()` or `blur()` methods of a input element.

**Comment by SteveSandersonMS** [comment]
You will need to use JS interop for this. It's quite trivial to do, and if you want, you can wrap up all the JS interop calls in a reusable project or package so it makes a nice set of .NET APIs to reuse.

**Comment by zwcloud** [comment]
Any documentation about JavaScript interop? How to use it? Any examples/demos? @SteveSandersonMS

**Comment by zwcloud** [comment]
The documentation for JS interop: https://blazor.net/docs/javascript-interop.html
