### ISSUE TITLE
Successive calls to StateHasChanged don't seem to work as intended

### ISSUE THREAD

**Issue by nvonbenken** [aspnet/Blazor#1496]
I initially began my project following the FlightFinder sample here: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/FlightFinder

I found my components were not updating properly. I then simplified it to the version I have now, and I still cannot get the loader to display.

My impression was that calling `StateHasChanged` in my `RunTest()` function would reload things but it looks like its only ever reloading one time, when the execution of the function is complete. My loading spinner never renders and my results component never gets hidden based on the if blocks around each of them. 

Am I approaching this the wrong way to get them to render in proper sequence/when they should based on my test running?

```
@inject AppState state

<div>
  <h3>Choose Test Params</h3>
  <div class="container form-group">
    <label for="source">Data Source:</label>
    <select class="form-control" id="source" disabled bind="testParams.DataSource">
      <option value="1">Source 1</option>
    </select>

    <label for="recCount">Record Count:</label>
    <select class="form-control" id="recCount" bind="testParams.RecordCount">
      <option value="1">1</option>
      <option value="50">50</option>
      <option value="500">500</option>
      <option value="1000">1000</option>
    </select>

    <label for="ddlThreads">Thread Count:</label>
    <select class="form-control" id="ddlThreads" bind="testParams.ThreadCount">
      <option value="1">1</option>
      <option value="3">3</option>
      <option value="5">5</option>
    </select>

    <button class="btn btn-primary" type="button" onclick=@(() => RunTest())>Run Test</button>
  </div>

  @if(IsLoading)
  {
    <div class="loader" />
  }

  @if(TestComplete)
  {
    <Results Res=state.Res></Results>
  }

  @*<Graph></Graph>*@
</div>

@functions
{
  [Parameter] Action<TestParams> OnRun { get; set; }

  private bool IsLoading { get; set; }
  private bool TestComplete { get; set; }
  private TestParams testParams = new TestParams(1, "", 1);

  private void RunTest()
  {
    IsLoading = true;
    TestComplete = false;
    StateHasChanged();

    OnRun(testParams);

    IsLoading = false;
    TestComplete = true;
    StateHasChanged();
  }
}
```

**Comment by Andrzej-W** [comment]
`StateHasChanged` doesn't force immediate UI update - it is only a signal for Blazor runtime to refresh component view during the next rendering cycle. You can easily achieve the intended effect by changing your `RunTest` and `OnRun` functions to async. Here is the simple example with `OnRun` changed to `Task.Delay(3000)` to easily demonstrate the effect:
```html
@page "/"
<div>
    <button class="btn btn-primary" type="button" onclick=@ResetState>Reset State</button>
    <button class="btn btn-primary" type="button" onclick=@RunTest>Run Test</button>
</div>

@if (IsLoading)
{
    <div>Loading data</div>
}

@if (TestCompleted)
{
    <div>Test completed</div>
}
```
```c#
@functions
{
    private bool IsLoading { get; set; } = false;
    private bool TestCompleted { get; set; } = false;

    private void ResetState()
    {
        IsLoading = false;
        TestCompleted = false;
    }

    private async Task RunTest()
    {
        IsLoading = true;
        TestCompleted = false;
        await Task.Delay(3000);
        IsLoading = false;
        TestCompleted = true;
    }
}
```
Key takeaways:
- `RunTest` has to be `async` and has to have return type `Task` (which is something like `void` in synchronous programming).
- `OnRun` has to be async and return `Task` or `Task<some type>`.
- You have to change application state (for example `IsLoading`) and then `await`. At this time control returns to Blazor and view is rendered.
- Your `OnRun` function completes and `RunTest` continues execution. Blazor knows that `RunTest` is `async` and is smart enough to rerender the view when it completes.

**Comment by nvonbenken** [comment]
This worked great, thanks for the help!
