### ISSUE TITLE
Issue with multiproject template creation with 2.2 Preview2 SDK

### ISSUE THREAD

**Issue by seancpeters** [aspnet/Blazor#1497]
_From @livarcocc on September 27, 2018 18:37_

@danroth27 commented on [Thu Sep 27 2018](https://github.com/dotnet/sdk/issues/2556)

Repro steps:

1. Install the Blazor 0.6.0-preview1 templates: `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.6.0-preview1-final --nuget-source https://dotnet.myget.org/f/blazor-dev/api/v3/index.json`
1. Create a multi-project Blazor hosted template: `dotnet new blazorhosted -o BlazorHostedApp1`

Expected result: Template creates successfully

Actual result: Project template creation fails

```
C:\Users\Admin\Desktop>dotnet new blazorhosted -o BlazorHostedApp2
The template "Blazor (hosted in ASP.NET server)" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on BlazorHostedApp2\BlazorHosted-CSharp.Server\BlazorHosted-CSharp.Server.csproj...
MSBUILD : error MSB1009: Project file does not exist.
Switch: BlazorHostedApp2\BlazorHosted-CSharp.Server\BlazorHosted-CSharp.Server.csproj

Restore failed.
Running 'dotnet restore' on BlazorHostedApp2\BlazorHosted-CSharp.Client\BlazorHosted-CSharp.Client.csproj...
MSBUILD : error MSB1009: Project file does not exist.
Switch: BlazorHostedApp2\BlazorHosted-CSharp.Client\BlazorHosted-CSharp.Client.csproj

Restore failed.
Running 'dotnet restore' on BlazorHostedApp2\BlazorHosted-CSharp.Shared\BlazorHosted-CSharp.Shared.csproj...
MSBUILD : error MSB1009: Project file does not exist.
Switch: BlazorHostedApp2\BlazorHosted-CSharp.Shared\BlazorHosted-CSharp.Shared.csproj

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

Works fine with the 2.1.402 SDK.

---

@livarcocc commented on [Thu Sep 27 2018](https://github.com/dotnet/sdk/issues/2556#issuecomment-425199378)

This seems an issue with the template and with the post action to restore the projects created. I am moving the issue to dotnet/template, where they can help better correcting it.

_Copied from original issue: dotnet/templating#1668_

**Comment by seancpeters** [comment]
The reason this is happening is how the primary outputs are setup, for example this:
```
    {
      "condition": "(OS == \"Windows_NT\" && HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
      "path": "BlazorHosted-CSharp.Server\\BlazorHosted-CSharp.Server.csproj"
    },
    {
      "condition": "(OS != \"Windows_NT\" && HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
      "path": "BlazorHosted-CSharp.Server/BlazorHosted-CSharp.Server.csproj"
    },
```
Template processing expects forward slashes for all paths, so there's no need to condition them with forward or back slashes based on OS. The above can be rewritten as:
```
    {
      "condition": "(HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
      "path": "BlazorHosted-CSharp.Server/BlazorHosted-CSharp.Server.csproj"
    },
```
The same change should be applied for the other .csproj primary outputs.


The reason this causes problems is that during template processing, the file renames are setup with forward slashes. Since backslashed paths in the primary outputs don't match the replacement mapping, the outputs don't get modified.

**Comment by danroth27** [comment]
@rynowak @SteveSandersonMS 

@seancpeters To be clear, this template is working fine with the latest 2.1 SDK. It only breaks with the 2.2 SDK. What accounts for the change in behavior?

**Comment by danroth27** [comment]
Regardless, I think we'll need to do something about this for our 0.6.0 release.

**Comment by seancpeters** [comment]
@danroth27 - Unfortunately the backslashed paths were an unsupported configuration that happened to work in older versions.

**Comment by SteveSandersonMS** [comment]
Thanks for the pointers about this, @seancpeters! I'm fixing it now for our 0.6.0 release.
