### ISSUE TITLE
Routing enhancements

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#150]
We currently have a very bare-bones routing system, which is probably enough for 0.1.0.

Possible future enhancements:

 * ~~URL pattern matching (e.g, `/products/{id}`)~~ Covered by #266
 * Simpler way of accessing the querystring/hash in components. Currently you can get the absolute URL from `UriHelper` but it doesn't come pre-parsed, and there's no way to bind specific querystring params to properties automatically.
 * Some equivalent to attribute routing, so components can specify their own URL patterns instead of it all being in a central location
 * Outbound URL generation (e.g., `<a page=@About>About us</a>`)
 * Multiple nested routers

**Comment by jonathanperis** [comment]
Outbound URL generation will be a nice addition

**Comment by grahamehorner** [comment]
@SteveSandersonMS areas?

**Comment by SteveSandersonMS** [comment]
Areas is #25

**Comment by muqeet-khan** [comment]
Would there be a downside to using client side URLs\Fragments\Hashbang when Blazor is used within a MVC app? 

For example:

```
https://mvcapp/mvcroute/foo
https://mvcapp/mvcroute2/#/blazorapp1/open to all
https://mvcapp/mvcroute2/admin#/blazorapp2/admin_only
```

Set it up something like:

```
app.UseBlazor("/mvcroute2",new BlazorOptions(){
 UseFragmentsForRouting = true
});
...
```

**Comment by SteveSandersonMS** [comment]
I expect we could support hash URLs if we wanted, but also I don't think we'd require them - it should work perfectly fine with regular URLs without hashes.

**Comment by SteveSandersonMS** [comment]
For some reason this got duplicated, so closing this in favour of the newer and more up-to-date #293.
