### ISSUE TITLE
Blazor doesn't load

### ISSUE THREAD

**Issue by sth349** [aspnet/Blazor#1500]
I'm using Blazor 0.5.0.
I have published the default template but when I launch the index.html chrome just displays "loading" and it never actually loads, normally when I run dotnet run it works but I can't use the static files.
The browser console displays:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND /C:/css/bootstrap/bootstrap.min.css:1 
Failed to load resource: net::ERR_FILE_NOT_FOUND /C:/css/site.css:1 
Failed to load resource: net::ERR_FILE_NOT_FOUND blazor.webassembly.js:1 
```
I need the static files as I want to wrap it in a Apache Cordova container, is there a more productive way to do it?

**Comment by lohithgn** [comment]
without looking at your code … its not possible to detect whats going wrong.
with the error message you have posted - your CSS is referencing "C:\" path - which is wrong. do make sure you have the right paths to your assets. Blazor although is client side - is still hosted on a server and static assets are all served from server

**Comment by SteveSandersonMS** [comment]
It's unclear what's going on here, but it's *very* unlikely your project is really directly inside the root of your `c:\` drive, so I suspect some unusual file structure or config is breaking it. Perhaps something you've set up while trying to integrate with Cordova.

Can you please try creating a new project and starting again? I think something is very strange and wrong about your current file structure.

This definitely doesn't happen out of the box, so it doesn't give any reason to think it's a bug, so I'll close this.

Or if you do have repro steps and believe it's a Blazor issue, please let us know! Thanks.

**Comment by apayero** [comment]
I think this is Priview 7 problem, because I got the same issue publish a project on Azure Content.
but with priview 6 all was ok.

**Comment by ibbgomes** [comment]
I have the same problem when using static files. Was anyone able to resolve this issue?
