### ISSUE TITLE
Blazor (ASP.NET Core hosted) project create failed

### ISSUE THREAD

**Issue by edwardyehuang** [aspnet/Blazor#1502]
When I tried to create a project in Visual studio with "Blazor (ASP.NET Core hosted) " template, its create 3 folders:

- XXXX.shared
- XXXX.server
- XXXX.client

Only the shared project is loaded Others cannot be loaded and seems incompleted.

**Comment by danroth27** [comment]
Please install [.NET Core SDK version 2.1.302](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.2.md) and it should address this issue.
