### ISSUE TITLE
Blazor won't load in IIS

### ISSUE THREAD

**Issue by chanhong** [aspnet/Blazor#1512]
I created a basic Blazor application using VS 2017 and select "Blazor" and it runs fine in VS 2017 but when I create a website in Windows 2016 IIS that point to the "public" folder that I published in VS 2017, it just stuck at "loading..." and here are the log of the reason why it got stuck.

[Blazor_IIS_stuck_at_loading_with_error.txt](https://github.com/aspnet/Blazor/files/2439214/Blazor_IIS_stuck_at_loading_with_error.txt)

Blazor is what I have been waiting for a long time but not being able to run in IIS is a big obstacle!

Thanks

**Comment by uwefms** [comment]
Blazor is running fine on IIS (Win 12 Server or locally on win 10 IIS)

Dis you adjust your index.html file in the wwwroot dir of the client ?

`	
	<base href="/raumdispo/" />

	
	

	
	
`
You might also have to adjust your navigate and http calls like

`tagNodes = await Http.GetJsonAsync<TagNode[]>(AppCache.BaseUrl + "/RaumNode/GetTagNodes/" + Convert.ToInt32(currentRaumId)); 

UriHelper.NavigateTo(AppCache.BaseHref + "/sendemail/" + currentRaumName.Trim() + "/" + nRaum_Id);			
`
To achieve this I created a appcache class:

`namespace RaumDispo.Client
{
    public class AppCache
    {		
		// IIS Express
//		public static string BaseUrl { get; set;} = "/api";
//		public static string BaseHref = "";
			   		 
		// IIS
		public static string BaseUrl = "/RaumDispo/api";
		public static string BaseHref = "/RaumDispo";
   }
}
`
Before publishing I would test the app on the local IIS

![iis](https://user-images.githubusercontent.com/13874580/46401359-fd634600-c6fc-11e8-997a-2736c5a6d88a.jpg)

This helped me to start
[https://dzone.com/articles/deploying-a-blazor-application-on-iis](url)

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @uwefms!

**Comment by SteveSandersonMS** [comment]
Since your IIS site is returning 404s for the requests for the `.wasm` and `.dll` files, you will need to [configure it to serve files with those extensions](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/staticcontent/mimemap).

**Comment by chanhong** [comment]
The only two files in the "publish" folder are: BlazorBrowser (solution
name) and web.config so I think the issue here is the Blazor template does
not publish those missing files or something.

**Comment by chanhong** [comment]
I think I got something here!

These two lines in MonoPlatform.ts and UriHelper.ts to stop Blazor from
running in IIS.

WASM: 20
MonoPlatform.ts:202 WASM: 20
module.printErr @ MonoPlatform.ts:202
UriHelper.ts:99 Uncaught (in promise) abort(20). Build with -s ASSERTIONS=1
for more info.
