### ISSUE TITLE
Why is WeatherForecastService an abstract class and not an interface?

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/Blazor#1514]
This is more of a general C# question than a Blayzor question but I was just curious why `WeatherForecastService` is an abstract class implemented by `DefaultWeatherForecastService` rather than making it an interface?

Is this unique to Blayzor in that is HAS to be abstract?

**Comment by Meir017** [comment]
looks like it was written quickly or something like that.
It's injected using
```cs
services.AddSingleton<WeatherForecastService, DefaultWeatherForecastService>();
```

The blazor source code contains interfaces, ex: `IBlazorApplicationBuilder` and many more

**Comment by SteveSandersonMS** [comment]
I don't think there's any important reason for this. It would work the same and be equally good either way.
