### ISSUE TITLE
Missing access modifier 

### ISSUE THREAD

**Issue by kant2002** [aspnet/Blazor#1529]
1. On the `Index.cshtml` from the template (which does not have `@functions` section)
2. Create new `@functions` sections
3. Start typing `override OnI` 
4. press Tab
5. Added 
```csharp
override void OnInit()
{
    base.OnInit();
}
```

should be 
```csharp
protected override void OnInit()
{
    base.OnInit();
}
```

## Notes
Happens
```csharp
@functions  {

    override void OnInit()
    {
        base.OnInit();
    }
}

```
Does not happens (correct)

```csharp
@functions  {
    public void test()
    {

    }
    protected override void OnInit()
    {
        base.OnInit();
    }
}

```
Does not happens (correct)

```csharp
@functions  {
    private int x;

    protected override void OnInit()
    {
        base.OnInit();
    }
}

```

so essentially, my observation related just if you have first method in the `@functions` section it does not pickup the correct access modifier

**Comment by rynowak** [comment]
Is the bug here that C# completion behaves differently? You should report this on https://developercommunity.visualstudio.com/spaces/8/index.html - we don't control this behaviour in Razor or Blazor. This is the C# editor.

**Comment by kant2002** [comment]
Ok. Reasonable. It looks like Razor language service have some issue then. What would be your wild guess, is it most likely error in Razor Language service, or in the C# Editor itself ?

**Comment by kant2002** [comment]
I report using VS reporting tool, with logs. Hopefully that helps relevant VS team.

**Comment by rynowak** [comment]
I'm one of the developers for Razor, and I know that we are not in control of this behaviour. 😆 

This is likely a behavior difference in how the C# editor behaves inside Razor. C# special cases lots of things for Razor and ASPX. I'm honestly not sure if this is intended or not, and there may be a historical reason for it. 

https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/Venus/ContainedDocument.cs

**Comment by kant2002** [comment]
Thanks for information. Links was really-really interesting. I really trying to cheat and don't go to Developer Community Portal, since this is black box sometimes. Also issue in C# editor appears to be fixed in slower pace, then any ASP.NET stuff. At least this is impression.
