### ISSUE TITLE
[Feature Request] Add Support for Razor template Syntax in @functions block 

### ISSUE THREAD

**Issue by syedqutub** [aspnet/Blazor#1533]
Hi,
I noticed that creating an object for `RenderFragment` by using `@<tag></tag>`
only works in @ block. It would be great if we could use Razor template syntax in @functions block if possible. (it might almost feel like React!).

Thanks anyway for this great framework!!

**Comment by SteveSandersonMS** [comment]
This is a feature we just added in 0.6.0.

**Comment by rynowak** [comment]
> This is a feature we just added in 0.6.0.

@syedqutub is right - this doesn't work in the functions block. That will require changes to the core of Razor to support.

**Comment by SteveSandersonMS** [comment]
Oh right - thanks for clarifying.
