### ISSUE TITLE
Microsoft.AspNetCore.Blazor.Browser.Interop is missing from master branch

### ISSUE THREAD

**Issue by jvelezc** [aspnet/Blazor#1535]
What is my alternative way of doing  RegisteredFunction.Invoke<bool> or where did this code go since the master branch does not have an interop folder anymore.

I see there branches with it...https://github.com/aspnet/Blazor/blob/javiercn/interop-cleanup/src/Microsoft.AspNetCore.Blazor.Browser/Interop/RegisteredFunction.cs

**Comment by rolshevsky** [comment]
@jvelezc per my understanding with this `PR` (#1351) `JsonInterop` was moved here: [dotnet/jsinterop](https://github.com/dotnet/jsinterop).

**Comment by jvelezc** [comment]
K I will try Install-Package Microsoft.JSInterop -Version 0.6.0 see what happens will report back.

**Comment by rolshevsky** [comment]
@jvelezc You do not need to install `JsInterop` separately, it's should be already included to Blazor: [JavascriptInterop](https://blazor.net/docs/javascript-interop.html)

![rider64_2018-10-08_00-10-11](https://user-images.githubusercontent.com/4366995/46586980-8f1cdb80-ca8e-11e8-8631-ca3a8e187d08.png)
