### ISSUE TITLE
Direct links do not work when base url is not '/'

### ISSUE THREAD

**Issue by jagalves** [aspnet/Blazor#1542]
When downloading blazor.webassembly.js it actually downloads index.html.

Steps to reproduce:
1. Create a new blazor project (not server side)
2. Publish it
3. On local IIS deployment create a virtual directory "ui" whose physical address points to the publish location
5. Make sure IIS has permissions in the publish folder (read access to "Everyone")
6. In the browser, go to http://localhost/ui  -> WORKS
7. Using the web page naviagtion links, click "Counter" -> WORKS. Also copy the url in the browser
8. In a new browser tab, past the url from the previous step -> FAILS

In the browser's dev tool I can see the page trying to download http://localhost/ui/ui/_framework/blazor.webassembly.js instead of http://localhost/ui/_framework/blazor.webassembly.js

**Comment by jagalves** [comment]
Forgot to add that you need to set <base href="ui/" /> in index.html

**Comment by seriouz** [comment]
I think this could be related to #1543

**Comment by SteveSandersonMS** [comment]
Try: `<base href="/ui/">`

This is known to work with the correct base href (our automated tests run on a subdirectory to verify this) so I'll close it, but please let me know if you still believe there's a bug, and especially if you can explain why it works in the automated tests but doesn't in some other scenario. Hope that's OK!

**Comment by jagalves** [comment]
It works. I feel silly now for not trying that (or maybe I did but didn't draw the right conclusion).

Thanks!

**Comment by seriouz** [comment]
If you are using nginx as reverse proxy, could use share an example config please?

**Comment by jagalves** [comment]
Nope, sorry. Locally using IIS and remotely in azure appService.

**Comment by SteveSandersonMS** [comment]
@jagalves No worries! It's an easy thing to get wrong, and there's no obvious way of debugging it. I only remember the syntax because so many people have asked about it.

**Comment by haavamoa** [comment]
> If you are using nginx as reverse proxy, could use share an example config please?
I am very interested in this as well! Anyone?
