### ISSUE TITLE
Host Blazor app under subpath, possible?

### ISSUE THREAD

**Issue by seriouz** [aspnet/Blazor#1543]
I have a Blazor app which is served by nginx. How is it possible to host it along with other apps on nginx like:

```
https://www.site.com/phpsite
https://www.site.com/aspnetapp
http://www.site.com/blazorapp1 
http://www.site.com/blazorapp2
```

I can access my dotnet apps via port directly (this is working):

```
https://www.site.com:4320/
https://www.site.com:4321/
https://www.site.com:4322/
```

When i am using url rewrite in nginx the files don't get loaded but the `index.html`.

```
  location / {
      rewrite /blazorapp1(.*) /$1 break;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $remote_addr;
      proxy_set_header   Host      $http_host;
      proxy_pass         https://www.site.com:4321;
  }
```

**Comment by SteveSandersonMS** [comment]
Try updating your base href, e.g.,

```
<base href="/blazorapp1/" >
```

... in index.html.

**Comment by floreseken** [comment]
@SteveSandersonMS isn't this also required in the hosting app?

` app.Map("/blazorapp1", child => { child.UseBlazor<Blazor.Program>(); });`

**Comment by seriouz** [comment]
@SteveSandersonMS We are using nginx as a reverse proxy to the aspnet served by kestrel (which runs in a docker container with exposed port).

**Comment by haavamoa** [comment]
Did you guys find a workaround for this? We are doing the exact same thing as you @seriouz
