### ISSUE TITLE
OnKeyPress does something weird with async code 

### ISSUE THREAD

**Issue by limefrogyank** [aspnet/Blazor#1561]
Perhaps I'm not understanding what Blazor is doing under the hood, but I'm getting a really weird effect from trying to invoke an asynchronous function within an OnKeyPress event handler.  

Basically, I have an input and a button.  The button will set some properties (`IsSearching`) and await a call to `Http.GetJsonAsync`.  When the download is finished, I process the items downloaded and turn `IsSearching` off.  

I wanted to be able to invoke this search method on an Enter keypress from the input.  So now I have this:
```
private async Task SearchAsync()
    {
        IsSearching = true;
        var remoteItems = await Http.GetJsonAsync<IEnumerable<RemoteClassItem>>($"api/remoteclassitems?searchTerm={SearchTerm}");
        List<ClassItem> Items = new List<ClassItem>();
        foreach (var item in remoteItems)
        {
            var classItem = item.ToClass();
            Items.Add(classItem);
        }
        SearchTerm = "";
        SearchResults = Items;
        IsSearching = false;
    }

    private async void OnKeyPress(UIKeyboardEventArgs args)
    {
        if (args.Key == "Enter" && !IsSearching)
        {
            await SearchAsync();
        }        
    }
```
1.  If I click the button, everything works fine and my items are populated on the page.
2.  If I hit enter from the input, I can see that the `GetJsonAsync` method is running and downloads the json data using the browser debugger.  However, everything stays disabled as if the await statement is never completed. 

I could have sworn I'm good with async/await.  But what is happening here?

**Comment by csnewman** [comment]
Have you tried adding a StateHasChanged call?

**Comment by SQL-MisterMagoo** [comment]
You are possibly hitting an error because your search term will be blank.
Binding (I'm guessing that's what you have done) search term to the input will only populate your property when the inputs onchange fires, so this happens when you click the button but not when you press enter 

You can work around this by wrapping your input in a form using method get and target _self, and make your button a submit type
See my BlazorChat repo for an example.

**Comment by uwefms** [comment]
Or you can do it like this:

`
<input class="form-control mr-sm-2" name="username" placeholder="Username" type="text" required onchange=@OnUsernameChanged oninput="(this.dispatchEvent(new CustomEvent('change', {bubbles: true})))" />
`

------

		protected void OnUsernameChanged(UIChangeEventArgs args)
		{
		    string values = args.Value.ToString();
			Username = values.ToString(); 
			ValidateLogin();
		    
		}

Not my Idea: 
https://www.codeproject.com/Articles/1245972/ASP-NET-Core-Blazor-Filtering-and-Sorting-using-En

**Comment by SQL-MisterMagoo** [comment]
Isn't that going to fire the on change event for every key press though?

**Comment by uwefms** [comment]
Yes - that's what I needed in my situation - maybe I missed the original intent. It was'nt a search input but the enter key.

**Comment by davidfowl** [comment]
Do you need StateChanged if OnKeyPress returns a Task instead of async void?

**Comment by Andrzej-W** [comment]
@limefrogyank I think that according to @davidfowl 's suggestion you should change your OnKeyPress handler to:
```c#
private async Task OnKeyPress(UIKeyboardEventArgs args)
{
    if (args.Key == "Enter" && !IsSearching)
    {
        return SearchAsync();
    }
}
```
In every `async` event handler you should have return type `Task` not `void`. I think that events are handled here:
https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor/Components/BlazorComponent.cs#L203

Then look here:
https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor/Components/BlazorComponent.cs#L180

When you return `Task` Blazor automatically:
- calls `StateHasChanged` when task is completed,
- correctly handles exceptions if any.

> The StateHasChanged call after awaiting the SearchAsync method worked. I'm curious why that was necessary in the KeyPress case, but not the ButtonClick case.

`onclick` calls `SearchAsync` directly and this function returns `Task`. `onkeypress` calls `OnKeyPress` which returns `void`. As far as I understand C# compiler `async` method with `void` return type returns `Task` which has `task.Status` always equal `TaskStatus.RanToCompletion`. `async` method with `Task` return type returns `Task` with correct status and Blazor can use `task.ContinueWith()`.

Hopefully everything I have written above is true but I'm not expert in Blazor internals.

**Comment by limefrogyank** [comment]
Ah, this all makes sense.  I believe I was too well conditioned to use the standard C# windows app that have all event delegates predefined to return void.  This is a little different, I guess.  And you're correct that the simple change to return a Task for the `OnKeyPress` handler would make it work without the extra `StateHasChanged` call.

Normally, in a UWP app, you'd have to use some kind of built-in _deferment_ to halt continuation so that you can do several asynchronous tasks.  

Thanks for the help.

**Comment by jucchytil** [comment]
Should the code below include an **await**?

```
private async Task OnKeyPress(UIKeyboardEventArgs args)
{
    if (args.Key == "Enter" && !IsSearching)
    {
        return await SearchAsync();
    }
}
```

**Comment by Andrzej-W** [comment]
Sorry @jucchytil , I have made a mistake. I have been thinking about synchronous event handler but to do it correctly we need to remove `async`. Here are two easy to test working examples, one with async and one with sync event handler:
```html
@page "/async"
<input oninput="(this.dispatchEvent(new CustomEvent('change', { bubbles: true })))" bind="@SearchTerm" class="form-control" onkeypress=@OnKeyPress />
<div>
SR: @SearchResult
</div>
```
```c#
@functions {
    string SearchTerm { get; set; }
    string SearchResult { get; set; }

    private async Task SearchAsync()
    {
        await Task.Delay(1000); // simulate long operation
        SearchResult = SearchTerm;
    }

    private async Task OnKeyPress(UIKeyboardEventArgs args)
    {
        if (args.Key == "Enter")
        {
            await SearchAsync();
        }
    }

    private Task OnKeyPress2(UIKeyboardEventArgs args)
    {
        if (args.Key == "Enter")
        {
            return SearchAsync();
        }
        else
        {
            return Task.CompletedTask;
        }
    }
}
```
Second solution is probably a little more efficient because C# compiler doesn't have to create a new "async context" for a method which is really synchronous. Tested in Blazor working in browser. I'm not sure if this is applicable to Blazor working on the server.

**Comment by jucchytil** [comment]
Thank you so much for your examples.  If you don't mind, I have a couple more questions:

Should the async version OnKeyPress
- be names OnKeyPressAsync?
- handle the else condition present in the sync version where it returns a Task.CompletedTask?

**Comment by Andrzej-W** [comment]
@danroth27 Maybe someone should add a new chapter in the doc and explain all nuances related to sync/async event handlers and StateHasChanged calls. Unfortunately English is not my native language and I'm not a proper person to write this myself. Read below to learn about the general idea.

@jucchytil I selected `OnKeyPress` and `OnKeyPress2` names to easily test both solutions (I can add or remove digit 2 in `onkeypress=@OnKeyPress`). There is convention to use Async at the end of async method name but this is only convention and not requirement. By the way you can use `onkeypress=@OnKeyPress` or `onkeypress="@OnKeyPress"` - both are valid syntax.

Now a few words about async and sync event handlers (please remember, I'm still learning, correct me if I'm wrong).

Here https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor/Components/BlazorComponent.cs#L203 we can see that Blazor calls `StateHasChanged ` immediately after invoking our event handler. This is enough for fully synchronous event handlers. Synchronous event handler should have return type `void`. Trivial example:
```c#
@functions{
    int counter;
    void OnClick()
        {
        counter++;
        }
}
```

With asynchronous event handlers problem is more complicated. Your code can look like this:
```html
<button class="btn btn-primary" onclick="@OnClickAsync">Button</button>
<div>Counter: @counter</div>
<div>Result: @result</div>
```
```c#
@functions{
    int counter;
    int serverCounter;
    int result;

    async Task OnClickAsync()
    {
        counter++;
        result = await GetSomethingFromServer();
    }
    async Task<int> GetSomethingFromServer()
    {
        await Task.Delay(1000);   // simulate slow client-server communication
        return ++serverCounter;
    }
}
```

Run this code, click the button and notice that `counter` is immediately incremented on the screen. Wait 1 second and you will see that `result` is incremented also. Blazor waits for task completion here:
https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor/Components/BlazorComponent.cs#L217
and calls `StateHasChanged` again.

If method is marked as `async Task` C# compiler makes some magic. This is **wrong** explanation, but hopefully easy to understand. Every time you await for something (and it is not ready immediately) your function returns to the caller. You don't have to add `return` statement. Compiler generates code which returns Task automatically. After 1 second your suspended function continues. You don't have to add return statement at the end - compiler does it automatically. You can think about async code like this but in reality compiler generates much more complicated code. If you are interested read this:
https://blogs.msdn.microsoft.com/seteplia/2017/11/30/dissecting-the-async-methods-in-c/

Here is a little more educational example where you can see task status:
```html
<button class="btn btn-primary" onclick="@OnClickAsync">Button</button>
<div>Counter: @counter</div>
<div>Result: @result</div>
<div>Task: @task?.Status.ToString()</div>
```
```c#
@functions{
    int counter;
    int serverCounter;
    int result;
    Task<int> task;

    async Task OnClickAsync()
    {
        counter++;
        task = GetSomethingFromServer();
        result = await task;
    }
    async Task<int> GetSomethingFromServer()
    {
        await Task.Delay(1000);   // simulate slow client-server communication
        return ++serverCounter;
    }
}
```

Here is yet another example, with synchronous event handler which calls asynchronous function:
```html
<button class="btn btn-primary" onclick="@OnClick">Button</button>
<div>Counter: @counter</div>
<div>Result: @result</div>
```
```c#
@functions{
    int counter;
    int result;

    Task OnClick()
    {
        counter++;
        if (counter % 2 == 0)
            return GetSomethingFromServer();
        else
            return Task.CompletedTask;
    }
    async Task GetSomethingFromServer()
    {
        await Task.Delay(1000);   // simulate slow client-server communication
        result++;
    }
}
```
Now `OnClick` is not marked as asynchronous but it calls asynchronous method. There is no compiler magic and we have to do everything manually. 

This time I have made all the above tests in Blazor working on the server. It looks that everything works equally well on the server and on the client.

Blazor is the first environment where I use async patterns - I'm still learning. This VS extension is very useful in my opinion:
https://marketplace.visualstudio.com/items?itemName=SemihOkur.AsyncFixer
