### ISSUE TITLE
How To Mix Mvc Pages With Blazor 

### ISSUE THREAD

**Issue by Sheko007** [aspnet/Blazor#1568]
i mean i will Create Web App Mvc How use Into This App Blazor
,,
And Check Input Validation In Blazor 
Like Model Pages and Models In Mvc.

Any One Have Way to Mix mvc-With Blazor In save app

**Comment by danroth27** [comment]
You can use an island of Blazor within MVC or Razor Pages by including the Blazor scripts. You can see an example of this here: https://github.com/danroth27/BlazorChat. We don't have an input validation system in Blazor yet, but the feature is tracked by #17.
