### ISSUE TITLE
Many developers seem to be lacking empathy and worse...

### ISSUE THREAD

**Issue by enetstudio** [aspnet/Blazor#1569]
As far as I understand, Server Side Blazor relates to Razor Components, right ? 
So, why in the world so many developers, here in github and elsewhere, use the phrase sever-side Blazor to mean something different than Razor Components; that is, they actually relate to the ASP.NET Core hosted Blazor. When I read stuff, I often find myself confused of their confusion, wasting so much energy just to understand what they are trying to convey. Often I find it hard to decipher and follow their intention just because they are negligent, perhaps even willfully negligent.

What can be done about this ? This is serious and can lead to much confusion and 'disasters' . I hope you guy won't dismiss this post as a mere fastidious nagging. Developers should be concise and use the phrase "Razor Components" to refer to Blazor application running on the server.

**Comment by roboriaan** [comment]
Maybe they've not heard about the new name or they don't understand the concept yet. A quick ask will do the trick if you're confused about what people are reffering to instead of becoming frustrated. Just a thought.

**Comment by RemiBou** [comment]
- The name changed just a few months ago, 
- Razor Component are not yet released  
- and it's still called server-side in the blazor doc (https://blazor.net/docs/host-and-deploy/hosting-models.html#server-side-hosting-model). 

So no problem to me, the good term will come up more when it will be released.

**Comment by SteveSandersonMS** [comment]
Thanks for the thoughts. Closing as hopefully the discussion is resolved.
