### ISSUE TITLE
async BlazorComponent Lifecycle methods return null

### ISSUE THREAD

**Issue by hutchcodes** [aspnet/Blazor#1576]
The async lifecycle events return null instead of a completed task. This means that when you override one of those methods and Visual Studio automatically adds a `base.OnInitAsync()` you get a null reference exception, but without any real hint about where it's coming from (I only figured it out with help from someone on gitter).

The answer in this case is to not call `base.OnInitAsync()` because the method is defined as
```
protected virtual Task OnInitAsync()
    => null
```

I think it would be better to return a completed task
```
protected virtual Task OnInitAsync()
    => Task.CompletedTask;
```

And I would be willing to sift through the solution looking for places where we're returning null and should be returning a completed Task, but don't want to submit a PR if there is some reason I don't understand that returning null there makes more sense despite the confusion it caused me.

**Comment by SteveSandersonMS** [comment]
Thanks for opening the issue to discuss it first!

Yes, I agree that returning `Task.CompletedTask` would be more conventional and would eliminate some possible issues here. If you're interested in writing a PR to change this, we'd be happy to take it!

One thing to watch out for is to be sure that this change doesn't cause extra thread-yields. For example, any upstream code that previously did `if (returnedTask != null) { await returnedTask; }` would need to be changed to only do the `await` if `returnedTask` was not already completed.

Closing as hopefully the question is answered, and we'll look out for your PR if you choose to submit one. Thanks!

**Comment by Andrzej-W** [comment]
@hutchcodes I had a problem with that a few weeks ago. It is not a natural behaviour that we cannot call base method. Hopefully you will be able to submit a PR.

**Comment by hutchcodes** [comment]
It's done and awaiting review :)
https://github.com/aspnet/Blazor/pull/1584
