### ISSUE TITLE
Standard BCL HttpClient

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#159]
For 0.0.5, our HttpClient is not the standard BCL one, because Mono for WebAssembly doesn't yet support it.

As soon as possible, we'd like to change to the standard `System.Net.Http.WebClient`, which basically means converting the existing implementation into a `WebRequestHandler` that can be used with `HttpClient`.

**Comment by SteveSandersonMS** [comment]
Implemented in 7148a17

**Comment by avillarubia** [comment]
WebClient is not supported says

blazor.webassembly.js:1 WASM: System.Net.WebException: An exception occurred during a WebClient request. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.

![image](https://user-images.githubusercontent.com/37901895/58266685-c4273580-7db4-11e9-92b6-b0554c62460a.png)

can someone help?

Thank you.

**Comment by danroth27** [comment]
@avillarubia Currently we only support HttpClient in client-side Blazor apps. If you're interested in WebClient support, please open an issue on the https://github.com/mono/mono repo.

**Comment by avillarubia** [comment]
@danroth27 thank you for the fast reply I appreciate that, I will try it.
