### ISSUE TITLE
Switching from client-side to server-side. CookieAuthentication behaviour

### ISSUE THREAD

**Issue by roboriaan** [aspnet/Blazor#1592]
Hi,

I'm using CookieAuthentication with a client-side blazor app. Works great.

When I switch the app to server-side "`services.AddServerSideBlazor`" everything works fine except the Authentication cookie  doesn't get created on the browser. Which I assume is expected behaviour? 

What seems strange is that the user at that point can still access the protected api until the browser is refreshed (manual F5). So it does live somewhere. I might be wrong but I reckon it's something to do when the signalR connection terminates and reconnects and that the cookie is created on another process?

Any ideas how I would go about getting the same behaviour on server-side?
I hope it makes sense. I'll try and explain better or submit a git sample if it doesn't make sense. 

TIA

**Comment by roboriaan** [comment]
To get the desired results I ended up going with JWT following this fantastic article :
https://medium.com/@st.mas29/microsoft-blazor-web-api-with-jwt-authentication-part-1-f33a44abab9d

Then a very simple JSInterop with local storage to store the token (of course some risks here).
Then middleware to deal with different status codes from the api and navigate the client.

Hope there's some value here for someone.

Cheers.

**Comment by danroth27** [comment]
It sounds like you were able to resolve your issue, so I'm going to go ahead and close this. I hope that's ok!
