### ISSUE TITLE
Server Side Blazor + Kestrel + Windows Auth = Crash

### ISSUE THREAD

**Issue by teeboy75** [aspnet/Blazor#1596]
I am trying to setup windows Auth using kesterel on blazor server side.I have the progam setup like this:

Blazor.Web.server

Program.cs
```csharp
     public static void Main(string[] args)
        {
            BuildWebHost(args).Run();            
        }
        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseHttpSys(
                                        options =>
                                        {
                                            options.Authentication.Schemes =
                                               AuthenticationSchemes.Negotiate | AuthenticationSchemes.NTLM; 
                                            options.Authentication.AllowAnonymous = false;                                          
                                        })
                .UseConfiguration(new ConfigurationBuilder()
                    .AddCommandLine(args)
                    .Build())
                .UseStartup<Startup>()
                .Build();
    }
```

Startup.cs
```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            // Adds the Server-Side Blazor services, and those registered by the app project's startup.
            services.AddServerSideBlazor<App.Startup>();
            services.AddHttpContextAccessor();
            services.AddTransient<App.HttpContextAccessor>();
            services.AddResponseCompression(options =>
            {
                options.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[]
                {
                    MediaTypeNames.Application.Octet,
                    WasmMediaTypeNames.Application.Wasm,
                });
            });
        }
```

Blazor.Web.App

Startup.cs
```csharp
 public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            // Since Blazor is running on the server, we can use an application service
            // to read the forecast data.
            services.AddSingleton<WeatherForecastService>();                        
        }
        public void Configure(IBlazorApplicationBuilder app)
        {
            app.AddComponent<App>("app");            
        }
    }
```
   
Program.cs

```csharp
public class Program
    {        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();            
        }

        public static IWebAssemblyHostBuilder CreateHostBuilder(string[] args) =>
            BlazorWebAssemblyHost.CreateDefaultBuilder()
                .UseBlazorStartup<Startup>();
    }

    public class HttpContextAccessor
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public HttpContextAccessor(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public HttpContext Context => _httpContextAccessor.HttpContext;
    }
```
   
    
Auth.cshtml

```html
    @using System.Net.Http
     @inject Blazor.Web.App.HttpContextAccessor HttpContext
     @page "/two-way-data-binding"

Logged in User: @HttpContext.Context.User.Identity.Name <br /> 
```

It errors when I navigate to Auth.cshtml with this exception.
Error:
```
System.ObjectDisposedException
  HResult=0x80131622
  Message=Safe handle has been closed
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.GetTokenInformation(SafeAccessTokenHandle TokenHandle, UInt32 TokenInformationClass, SafeLocalAllocHandle TokenInformation, UInt32 TokenInformationLength, UInt32& ReturnLength)
   at System.Security.Principal.WindowsIdentity.GetTokenInformation(SafeAccessTokenHandle tokenHandle, TokenInformationClass tokenInformationClass, Boolean nullOnInvalidParam)
   at System.Security.Principal.WindowsIdentity.get_User()
   at System.Security.Principal.WindowsIdentity.<GetName>b__46_0()
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass62_0.<RunImpersonatedInternal>b__0(Object <p0>)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at System.Security.Principal.WindowsIdentity.GetName()
   at System.Security.Principal.WindowsIdentity.get_Name()
   at Cloud.WebUI.App.Pages.TwoWayDataBinding.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
```

**Comment by cores-system** [comment]
@teeboy75, Replace AddTransien with AddScoped.
**Example**: https://github.com/aspnet/Blazor/issues/1554#issuecomment-429431848

**Comment by danroth27** [comment]
I believe this is a known issue when using SignalR with long polling (https://github.com/aspnet/SignalR/issues/2948), which has been fixed in ASP.NET Core 2.2.

To confirm, you could try [enabling client-side SignalR logging](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#javascript-client-logging) by modifying `bin/Debug/netstandard2.0/dist/_framework/blazor.server.js`.

What OS are you running on?

**Comment by teeboy75** [comment]
We are on server 2016. Will install 2.2 and confirm. Thank you.

**Comment by danroth27** [comment]
Which browser and browser version were you using when this happened? I'm just trying to understand why you might have ended up with long polling in stead of websockets. Adding @shirhatti and @anurse in case they have other ideas.

Regardless, let us know if using the latest preview of 2.2 solves the issue.

**Comment by teeboy75** [comment]
That is exactly what I thought. Is there a special setting to switch to long polling? I don't remember changing this setting..browser is chrome , I believe version 68. I am on vacation currently. Will be back Nov 6th. Will confirm then. Will try to submit github repro.

**Comment by danroth27** [comment]
Opened #1632 to track making it easier to enable client-side SignalR logging.

**Comment by enetstudio** [comment]
The issue has nothing to do with signalR . It is related, I believe, to the definition of the Http Context Accessor, and how it is used...

**Comment by teeboy75** [comment]
@enetstudio, if you have a working example  for windows auth with razor components and Kestrel,  can you share please?

**Comment by enetstudio** [comment]
@danroth27
   Note:
   1. Blzor is 'using' the IHttpContextAccessor defined in the custom class:
   
      @inject Blazor.Web.App.HttpContextAccessor HttpContext  
      Logged in User: @HttpContext.Context.User.Identity.Name <br /> 
	  
   2. Blazor.Web.App.HttpContextAccessor is added as transient:
     
	  services.AddTransient<App.HttpContextAccessor>();  
	  
      Which is not compitable with IHttpContextAccessor being Singleton
	 
   3. Actually there is no code that registers the IHttpContextAccessor in DI,
      and thus, it has no relationship to the HttpContextFactory or HttpContext,
	  always returning null, unless it finds in DI container the IHttpContextAccessor
      configured properly by services.AddHttpContextAccessor();	  
    
    Remove the custom class HttpContextAccessor
    Remove services.AddTransient<App.HttpContextAccessor>();  
	Inject a reference to IHttpContextAccessor instead of 
	@inject Blazor.Web.App.HttpContextAccessor HttpContext,
	and see if it works for you.
	
	Hope this helps...

**Comment by teeboy75** [comment]
I got this to work!
Reinstalled IIS on windows server. This reinstalled websockets support. Then, as @enetstudio  and @danroth27  suggested, removed references to custom "HttpContextAccessor" and just used Microsoft.AspNetCore.Http.IHttpContextAccessor. Also, another requirement is I wanted to host the blazor server and app on a "Service Fabric" cluster. It's all working now with service fabric + Kestrel + Windows Auth + Blazor.
Thx much.

**Comment by asvyat** [comment]
do you have repo with all the working code for Windows Auth?

**Comment by JunRamoneda** [comment]
@pattisapu01 Hi, do you have any sample code on how you got server-side blazor to work in service fabric.  I keep getting a bunch of errorrs using the blazor app generated from the blazor template
