### ISSUE TITLE
JSON serialization/deserialization APIs

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#160]
We need JSON handling for even the simplest apps (including our project template), so we have to have something for 0.0.5.

We'll probably bundle a minimal JSON serializer/parser inside `Microsoft.AspNetCore.Blazor`, and recommend that if people require anything more sophisticated they use a third-party package. The IL stripping will remove our built-in implementation on publish if it isn't actually getting called, so there's no runtime cost.

**Comment by Terricide** [comment]
This is a single file json library that I've used in my projects that works well.

https://github.com/facebook-csharp-sdk/simple-json

**Comment by SteveSandersonMS** [comment]
@Terricide Interesting - thanks! We already have MiniJSON (see [this](https://github.com/aspnet/Blazor/tree/dev/src/Microsoft.AspNetCore.Blazor.Browser/Interop/MiniJSON) and [this](https://github.com/aspnet/Blazor/blob/dev/src/Microsoft.AspNetCore.Blazor.Browser/Interop/Json.cs) in the project which is quite a lot smaller and simpler. I'm not sure about the pros/cons versus simple-json. Do you know how they compare?

**Comment by Terricide** [comment]
No sorry I've never used minijson. I've just used simplejson with a few fixes of my own for about 4 years now and it has been working well.

I've actually been using it in an app that is targeting .net 2.0 (not .net core 2.0)

**Comment by SteveSandersonMS** [comment]
OK, this is now in. Following @Terricide's recommendation, it does use SimpleJson internally (though it's marked internal, so we can always change the implementation later).

I tried the following:

 * MiniJSON: Very small (~3kb). Only has native support for deserializing to `Dictionary<string, object>`. We can add support for deserializing to arbitrary types (and we did so before) but that code hasn't been widely battle-tested. Underlying library is not in active development.
 * SimpleJson: Quite small (~9kb). Natively supports serializing/deserializing arbitrary types. Natively supports disabling Reflection.Emit usage, which should make it faster (Reflection.Emit creates slow code on non-JIT platforms).  Does not appear to be in active development.
 * LitJSON: Moderately small (~17kb). Natively supports serializing/deserializing arbitrary types. Is definitely still under active development. Unfortunately made some tests fail due to correctness issues like https://github.com/LitJSON/litjson/issues/43, hence not considering it any further.
 * Json.NET: Very large (~200kb). Natively supports everything and is under active development, but just too big to take as a built-in dependency.

The sizes quoted refer to how much bigger it makes `Microsoft.AspNetCore.Blazor.dll`, after gzip compression.

I did *not* do any perf benchmarking. If anybody is interested enough to compare the relative speeds of these libraries **when running on WebAssembly**, please let us know what you find!
