### ISSUE TITLE
blazor.boot.json not found

### ISSUE THREAD

**Issue by kingreatwill** [aspnet/Blazor#1600]
Often occurs
![image](https://user-images.githubusercontent.com/13087689/47349812-ff5e6a80-d6e6-11e8-8ce3-87abbd62adcb.png)
https://github.com/BuiltCloud/wcoder.com

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this.

To investigate this, we'd definitely need some repro steps. It's not something I've seen happen so may well be unique to your app setup. If you can provide steps that repro it, then we can investigate. I'll close this until there's any more info - hope that's OK!

**Comment by SteveSandersonMS** [comment]
Sorry, I’m afraid that doesn’t repro for me! I know that doesn’t sound helpful but there’s not much I can do to investigate, especially as this is the only report of the issue. It may well be something specific to your environment.
