### ISSUE TITLE
blazorlib template fails if -n parameter not used

### ISSUE THREAD

**Issue by MarkStega** [aspnet/Blazor#1604]
If you try to create a new blazorlib project using "dotnet new blazorlib" the contents are placed in the current directory rather than using the current directory name for the new project name per the dotnet new documentation.

**Comment by ghidello** [comment]
I believe that to change the destination folder you should use the -o option and then, if you not specify a project name with the -n option, the command will use the destination folder as project name.

**Comment by MarkStega** [comment]
It may work that way but "dotnet run --help" doesn't indicate the need for the "-o" parameter as a needed parameter.

**Comment by ghidello** [comment]
I'm not sure I understood your problem now. The -o option works for "dotnet new" not for "dotnet run" and is needed only if you want to create a new project in a folder different from the current directory.

**Comment by danroth27** [comment]
The `-o` parameter is not required. By default `dotnet new` will create the project in the current directory. It doesn't create a new directory unless you ask it to. For example, `dotnet new console` puts the new console project in the current directory just like `dotnet new blazorlib` does.
