### ISSUE TITLE
Server Side Blazor - Can I serve the "index.html" content from a Controller action or Razor page?

### ISSUE THREAD

**Issue by christiansparre** [aspnet/Blazor#1605]
Hi, I have been playing around trying to have Azure AD authentication in a Server Side Blazor app and have tried the following:

I made it work (sort of) using the "child app" approach that others have pointed to in other issues, like so

```
app.Map("/app", childApp =>
{
    childApp.UseAuthentication();
    childApp.UseServerSideBlazor<App.Startup>();
});
```
But using that approach I have to check if the user is authenticated in the App.cshtml `OnInit` method and while it works, I would like to simply not "start" the Blazor app if the user is not authenticated, but I can't really figure out if that is possible.

The other thing I have tried, to solve that, is having an MVC controller with an `/app` route where I would return the `index.html` content instead of it being served by a static file provider from the `wwwroot` folder. But that did not work as I immediately get the following error.

> The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

So I'm a little lost here on how to approach this. Is it possible or am I one the wrong track?

**Comment by Peter-Juhasz** [comment]
I'm sure its not the best approach, but I could make it work.

This is the pipeline setup:
```cs
//
app.UseAuthentication();

// mvc
app.UseMvc(options =>
{
    options.MapRoute("Admin", @"admin", new { area = "Admin", controller = "Home", action = "Index" });
    options.MapRoute("AdminSpa", @"admin/{*url:regex(^[^.]*$)}", new { area = "Admin", controller = "Home", action = "Index" }); //
});

// blazor
app.Map("/admin", branch =>
{
    branch.UseBlazor<Admin.Client.Program>();
});
```

This is the controller action:
```cs
[Authorize]
[Area("Admin")]
public class HomeController : Controller
{
    [HttpGet]
    [IssueAntiforgeryToken]
    public IActionResult Index()
    {
        return View();
    }
}
```

The `IssueAntiforgeryToken` is a custom attribute, it sets the CSRF token in a cookie with the response.

Hope it helps.

**Comment by christiansparre** [comment]
Thanks @Peter-Juhasz, are you using this for server side blazor? `branch.UseBlazor<Admin.Client.Program>();` looks like it's the web assembly version?

I have played around with it some more and found a way to get authentication working while still just serving the static `index.html` file. I have it here: https://github.com/christiansparre/BlazorServerSideAzureAd

The main part is the branched pipeline:

```csharp
app.Map("/app", childApp =>
{
    childApp.UseAuthentication();
    childApp.Use(async (context, next) =>
    {
        if (!context.User.Identity.IsAuthenticated)
        {
            context.Response.Redirect("/signin?redirectUri=" + context.Request.GetEncodedUrl());
            return;
        }
        await next();
    });
    childApp.UseServerSideBlazor<App.Startup>();
});
```
where I enable authentication and then check if each request is authenticated and if not then redirecting to a controller action that does the challenge and redirects back to the blazor app. It works, but I expect that the team will come up with a more integrated way of doing it down the line.

**Comment by Peter-Juhasz** [comment]
Our use case is a public blog-like website, where all the public pages are rendered server-side using regular MVC/Razor, while the admin area is more like an "app", so it is built as a SPA by Blazor. And these two areas are hosted in the same app at the end.

For authentication we use Azure Active Directory, but since it is handled by the Authorize attribute and then the built-in Identity module, the code is completely independent of the authentication provider, so you don't have to reimplement the redirection and all the other flows.

One thing I forgot to mention is that we don't use the static `index.html` from the Blazor project. That is a view in the host project rendered using MVC/Razor/cshtml. It may feel like it distracts the Blazor project, but it has a lot of advantages over a static file as well. For example, you can use tag helpers for asset versioning, SRI, environment switches and so on.

**Comment by danroth27** [comment]
@christiansparre Looks like you were able to answer you're own question. We are tracking adding a more integrated authentication and authorization story with issue #64.

**Comment by Fydar** [comment]
I am still quite new to Asp.Net Core (only been using it a year professionally), however, I am used to the traditional action filters. These don't apply to Blazor outside the scope of the SPA app. 

I found this is the only source on how I could "not run the Blazor app at all" and redirect the user to a sign-in page. This allows me to protect the DLLs that make up my shared code base from potential attackers who wish to reverse-engineer my dashboard. 

I feel like this could be made easier to find for anyone else with similar use cases. I initially thought this would be very easy to find online, but it has taken more at least a few hours.

Thanks for the valuable documentation!
