### ISSUE TITLE
build failing - webpack

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#161]
```
 > webpack

  'webpack' is not recognized as an internal or external command,
  operable program or batch file.
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! blazor.host.client@0.0.1 build: `webpack`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the blazor.host.client@0.0.1 build script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

  npm ERR! A complete log of this run can be found in:
  npm ERR!     C:\Users\..\npm-cache\_logs\2018-02-23T23_25_17_784Z-debug.log
C:\Users\..\source\repos\aspnet-community-demos\Blazor\src\Microsoft.AspNetCore.Blazor.Browser.JS\Microsoft.AspNetCore.Blazor.Browser.JS.csproj(32,5): error MSB3073: The command "npm run build" exited with code 1.
```

**Comment by grahamehorner** [comment]
> blazor.host.client@0.0.1 build:debug C:\DEV\Blazor\src\Microsoft.AspNetCore.Blazor.Browser.JS
  > webpack --mode development

  One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
   - webpack-cli (https://github.com/webpack/webpack-cli)
     The original webpack full-featured CLI.
   - webpack-command (https://github.com/webpack-contrib/webpack-command)
     A lightweight, opinionated webpack CLI.
  We will use "npm" to install the CLI via "npm install -D".
  Which one do you like to install (webpack-cli/webpack-command):
CSC : error CS1566: Error reading resource 'blazor./blazor.webassembly.js' -- 'Could not find a part of the path 'C:\DEV\Blazor\src\Microsoft.AspNetCore.Blazor.Browser.JS\dist\blazor.webassembly.js'.' [C:\DEV\Blazor\src\Microsoft.AspNetCore.Blazor.Browser.JS\Microsoft.AspNetCore.Blazor.Browser.JS.csproj]
  Microsoft.VisualStudio.LanguageServices.Blazor -> C:\DEV\Blazor\tooling\Microsoft.VisualStudio.LanguageServices.Blazor\bin\Debug\net461\Microsoft.VisualStudio.LanguageServices.Blazor.dll

**Comment by SteveSandersonMS** [comment]
With the latest sources, the build doesn't require any version of the Webpack CLI to be installed manually. I don't have the Webpack CLI installed as a global tool on my machine, yet it builds fine.

The build works by calling an `npm` script which uses the locally-installed webpack tool that is put there by `npm install`, which is also run automatically on the build.
