### ISSUE TITLE
websockets guidance

### ISSUE THREAD

**Issue by christoph68** [aspnet/Blazor#1610]
I absolutely love Blazor the way it glues c# with the web.
After some hours searching the web, I still am kind of blind about Blazor and Websockets.
Remark: I cannot use SignalR since I need to connect to an existing WSS-Server.
Websockets (Client) support is essential for many scenarios that favor Blazor over any other SPA.

In order to connect to any Websocket Server from a Blazor Client, what options are there now and in future? Thanks for helping explanations.

**Comment by danroth27** [comment]
Our expectation is that the underlying .NET runtime and BCL would implement support for websockets using the standard .NET APIs. This would be implemented by mono.wasm and is tracked by https://github.com/mono/mono/issues/9567. In the meantime you should be able to call into the browser websockets apis yourself using [JS interop](https://blazor.net/docs/javascript-interop.html)
