### ISSUE TITLE
[Suggestion] Make Blazor Library content such as images referenceable in using project

### ISSUE THREAD

**Issue by SamVogelskamp** [aspnet/Blazor#1613]
To my knowledge and experimentation there is no way to use content provided by a Blazor Library in the project it's referenced in, unless I'm missing some specification of tagHelpers that introduce this behavior.

To give an example I would like to be able to use an image located in the library's content folder by referencing to src="\<LibraryName>/content/\<image>"

**Comment by danroth27** [comment]
Blazor class library content should get added under the `dist/_content/<lib_name>` folder in the app, which is made available as static content. You should be able to reference library content from there. Ex `<img src="_content/BlazorLib1/background.png" />`.
