### ISSUE TITLE
Unable to install ASP.NET Core Blazor Language Services extension without admin rights

### ISSUE THREAD

**Issue by iSatishYadav** [aspnet/Blazor#1621]
I'm using a Corporate Machine and don't have admin rights to my Windows. I need to install [ASP.NET Core Blazor Language Services](https://marketplace.visualstudio.com/items?itemName=aspnet.blazor) extension but when I open the `Microsoft.VisualStudio.BlazorExtension.vsix` I get an error which says:
````
Supplying the /installas command line parameter requires that vsixinstaller is run as admin.
````
I'm not specifying any parameter, please help me out.

**Comment by danroth27** [comment]
Yeah, unfortunately running the Blazor VSIX does requires elevation. Once we get to the point where the Blazor tooling ships as part of Visual Studio, this will of course no longer be an issue. If you are unable to install the Blazor VSIX on your machine you should still be able to create and work with Blazor projects from the command-line using the .NET Core SDK. See the [Blazor getting started instructions](https://blazor.net/docs/get-started.html) for details on how to do this.
