### ISSUE TITLE
Make the default HttpMessageHandler implementation injectable

### ISSUE THREAD

**Issue by robertsundstrom** [aspnet/Blazor#1625]
As a developer, I sometimes want to be able to switch out the default implementation of HttpMessageHandler that is being used by HttpClient. One possible scenario is when I want to add logic for refreshing auth tokens once they have expired.

The default HttpClient should obtain an implementation of HttpMessageHandler (default: BrowserHttpMessageHandler) through dependency injection.

Support HttpClientFactory for more advanced options.

**Comment by danroth27** [comment]
You are free to do so today. The DI system is based on constructor injection. You can register your own `HttpClient` to override the default one and then register whatever `HttpMessageHandler` you want. For example:

```csharp

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<HttpMessageHandler, BrowserHttpMessageHandler>();
            services.AddSingleton<HttpClient>(sp => {
                var handler = sp.GetService<HttpMessageHandler>();
                var client = handler != null ? new HttpClient(handler) : new HttpClient();
                client.BaseAddress = new System.Uri(BrowserUriHelper.Instance.GetBaseUri());
                return client;
            });
        }
```

In the future we could look at resolving the underlying `HttpMessageHandler` from DI by default, but it's not something we currently plan to do.
