### ISSUE TITLE
Failed to start app with server-side blazor

### ISSUE THREAD

**Issue by RemiBou** [aspnet/Blazor#1628]
You can find my app here https://github.com/RemiBou/Toss.Blazor/tree/try-server-side. When launching the server side, I got my splash screen then it's blank. There is no error in the console, some small messages are exchanged in the websocket connection but nothing interesting.

**Comment by RemiBou** [comment]
https://pastebin.com/90HVgPkb

I think this has something to do with one of my service expecting an HttpClient

**Comment by danroth27** [comment]
Yes, that's expected. We don't register an HttpClient instance in DI when running server-side. You'll need to register the HttpClient you want to use yourself to run server-side.

**Comment by RemiBou** [comment]
Ok  thanks :)
