### ISSUE TITLE
File System Functionality Question

### ISSUE THREAD

**Issue by groogiam** [aspnet/Blazor#1636]
Could you please provide some detail on the current implementation of the System.IO.FIle and Directory classes? Based on some initial testing it looks like these are currently ephemeral storage and are lost when the page is reloaded. I'm guessing the file data is just persisted to some data structure in memory. If this is the case is there any plans to potentially patch the file system api's through to browser storage (local,session or indexeddb). similar to what enscripten does https://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html. Thanks.

**Comment by Suchiman** [comment]
This is using emscripten right now.
Essentially emscripten sets up a unix like virtual filesystem where all your assemblies are put (`/appBinDir`)  and then mono loads them from there and uses devices like `/dev/random`

**Comment by groogiam** [comment]
Thanks for the information. I was able to get the desired functionality working by simply mounting the IDBFS.

**Comment by danroth27** [comment]
@groogiam We don't actually handle the implementation of the file system APIs. That's all done by the mono folks. I believe they plan to do away with the stubbed out file system support that emscripten adds, but you should confirm with them. @marek-safar

**Comment by groogiam** [comment]
@marek-safar I'm not quite sure what you mean by this. Is there some documentation or an issue with more details about how this will function?
