### ISSUE TITLE
Singleton service property bound variable not updated in realtime

### ISSUE THREAD

**Issue by AppiePau** [aspnet/Blazor#1645]
I can't find a similar issue and I'll do my best to explain. The point is that I find the behavior unexpected and like someone to explain what I might be doing wrong or it's just  a bug.

So I was writing an authentication mechanism with JWT tokens (wich works!) and thought it might be useful to put the user data (id, name, token) into a singleton object called AuthorizationContainer and register it as a singleton service. So then it is globally available for data binding (local db not yet implemented):

````csharp
 public sealed class AuthenticationContainer
{
   public AuthenticationHeaderValue BearerToken { get; set; }
   public bool IsAuthenticated { get; set; }
}

public class Startup
{
   public void ConfigureServices(IServiceCollection services)
   {
      services.AddSingleton<AuthenticationContainer>();
   }
}
`````

The following code uses the container and after authenticating through a form, the user is redirected to the home page.

```cshtml
@inject AuthenticationContainer auth;
<ul class="nav flex-column">
<li class="nav-item px-3">
    <NavLink class="nav-link" href="" Match=NavLinkMatch.All>
        <span class="oi oi-home" aria-hidden="true"></span> Home
    </NavLink>
</li>
@if (auth.IsAuthenticated)
{
    <li class="nav-item px-3">
        <NavLink class="nav-link" href="organizations">
             <span class="fa fa-building" aria-hidden="true"></span> Buildings
         </NavLink>
    </li>
}
@if (!auth.IsAuthenticated)
{
    <li class="nav-item px-3">
        <NavLink class="nav-link" href="authentication">
            <span class="oi oi-key" aria-hidden="true"></span> Inloggen
        </NavLink>
    </li>
}
</ul>
````

After the user has been authenticated the IsAuthenticated property will be set to true, but nothing happens. Even after a redirect the menu items will not popup for the authenticated user. With some Angular experience I expect it to work.

Only after clicking manually on the home link, the items will apear. What is happening here? Does the framework not detect a property/reference change? Should I manually trigger an event (wich I would not prefer).

**Comment by Andrzej-W** [comment]
Each component has its own `StateHasChanged()` method. It's sometimes called by the framework, usually in response to some user action (for example mouse click). Your menu is probably defined in page layout  or some other component and your form is defined somewhere else (in different component). You should add event in your AuthenticationContainer and rise it each time state is changed. Then you should subscribe to this event in menu component and call `StateHasChanged()` there. You can find an example implementation here:
https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/FlightFinder
and specifically here:
https://github.com/aspnet/samples/blob/master/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Client/Services/AppState.cs#L52
and here
https://github.com/aspnet/samples/blob/master/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Client/Main.cshtml#L23

Compared to Angular it is a good performance optimization - your UI is not refreshed when it is not needed.

**Comment by AppiePau** [comment]
Thanks for pointing me into the right direction! After implementing the StateChanged() as suggested it does not work yet. I can see the event is being triggered and hooked by Blazor. I have injected the AppState into the AutenticationService that triggers the state changed event after logging in. All off that works. 

Let me show with some more code:

AuthenticationContainer, registered as a singleton service:
```csharp 
    public sealed class AuthenticationContainer
    {
        private UserModel user;

        public void SetUser(UserModel user)
        {
            this.user = user;
        }

        public AuthenticationHeaderValue BearerToken
        {
            get
            {
                return user != null ? new AuthenticationHeaderValue("Bearer", user.Token) : null;
            }
        }

        public bool IsAuthenticated { get { return (user?.Id ?? 0) > 0; } }

        public string FullName { get { return $"{user?.FirstName} {user?.LastName}"; } }
    }
```
The AppState as suggested fom the Flight demo, also singleton:
```csharp

    public sealed class AppState
    {
        public event Action OnChange;

        public void NotifyStateChanged()
        {
            var isEventHandled = OnChange != null;

            Console.WriteLine("AppState.NotifyStateChanged():" + isEventHandled); //// This says 'True' in the browser

            OnChange?.Invoke();
        }
    }
```
And hooking it up to the Blazor runtime:
```cshtml
@inject Services.AppState state

<Router AppAssembly=typeof(Program).Assembly />
@functions
{
    protected override void OnInit()
    {
        state.OnChange += StateHasChanged;
    }
}
````
All code behind is generated as expected and as mentioned, the evet is fired when the user is successfully loggen on. Like this:
```csharp
if (user != null)
{
    this.authContainer.SetUser(user);

    this.state.NotifyStateChanged();

    return new UserAuthenticationResult { IsSuccess = true };
}
````
And as a bonus, the Starup:
```csharp
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<AppState>();
            services.AddSingleton<CountryHttpService>();
            services.AddSingleton<AuthenticationService>();
            services.AddSingleton<AuthenticationContainer>();
            services.AddSingleton<HttpRequestService>();
        }

        public void Configure(IBlazorApplicationBuilder app)
        {
            app.AddComponent<App>("app");
        }
    }
````

**Comment by SteveSandersonMS** [comment]
Yes, @RemiBou is correct. Your code is calling `StateHasChanged` on the wrong component. You need to call it on the affected component, not the app root component, so subscribe to your event there.

**Comment by AppiePau** [comment]
Thanks guys for such quick support on the matter! My misunderstanding was based on an assumption of a top-to-down cascading model and some other wrong assumptions on the matter. 

Anyway, I ended up implementing this in the NavMenu.cshtml file:
```csharp

@functions {
    bool collapseNavMenu = true;

    protected override void OnInit()
    {
        base.OnInit();

        this.authService.UserAuthenticated += this.StateHasChanged;
    }

    void ToggleNavMenu()
    {
        collapseNavMenu = !collapseNavMenu;
    }

    public void Dispose()
    {
        this.authService.UserAuthenticated -= this.StateHasChanged;
    }
}
````

Then fixing some other issue makes the whole model work!
