### ISSUE TITLE
Ability to Sync Server generated Model to Client 

### ISSUE THREAD

**Issue by olavorn** [aspnet/Blazor#165]
I had an experience with SPA with model mapped entities to JS, using EntityFramework(but it can be any) that i'd like to share if it can be of any use.

Every change in the Entity Model Classes obviously needed to change the model mapping in the JS Client also in order to the requests and responses to work properly.  We achieved this by generating dynamically js models loaded during the startup request.  

_Example: Person class with "ClientShared" attribute and as so, It's properties could be "requested" via javascript with a specific controller._

```
    [ClientShared]
    public class Person
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
```
By requesting a json in the controller:
GET /System/InjectSharedModel resolving something like:

```
[ ["Person"]:{
Properties: [{ Name: "Id", Type: 'number', Key:true  }, {Name: "Name" , Type: 'string'}, {Name:'Age', Type: 'string'} ]
}]
```

By using this, we just needed two change spots: 1- Person entity on C#, 2 - The new html input on the client form (or else). All the rest was managed by this dynamic injection of javascript. 

This is only an example, there could be more uses, like validation, and so.

By reading Blazor, I think you could achieve this in three alternative ways,

1 - (Easier) Shared Model Class Library. One Dll that could be used in both Projects, Client and Server.
2 - Some sort of Attribute class could inject a shared class from server project to subscribers using some kind of dynamic wasm generation. (Like the mechanism above, but using wasm)
3 - A build process synchronization based on some Blazor specific task to bind target symbols from server.

These are only ideas, just in case :)

**Comment by SteveSandersonMS** [comment]
I'm hopeful that being able to share .NET assemblies between server and client will make a big difference here. If your model classes are in a shared assembly, then whenever you update those classes you're updating both the server-side data access code and the client-side logic implicitly. For example, you'll get compile-time errors if your client-side code is trying to refer to a property that's been renamed.

Let's see how this looks when there's more of an end-to-end application model for you to try out :)

**Comment by fileman** [comment]
in LightSwitch client model class was generated by server-side, but this method was required because Silverlight was a subset of .net framework.
I'm agree that share same assembly would be better for validation with data annotations, authorization (roles,policy), only view code need to be updated.

**Comment by olavorn** [comment]
The only issue (a big one maybe that occurred to me now) that should be considered when sharing an assembly with server logic is security, since this could be a way to easily map the database structure in case you use ORM mappers like Entity Framework somehow. 

In this scenario, alternatives 2 and 3 sounds better, since you can opt-in entities/properties you want to share with/send to client. With shared assembly you have no control of that.  

One have to keep in mind that client code, C# or Javascript, is still client code, so, untrustworthy by design.

**Comment by fileman** [comment]
In theory best practice is to share DTO assembly, but not all projects are developed with DDD... 
An attribute could be easy to use / develop and build with T4 engine or cli
