### ISSUE TITLE
Using D3.js with Blazor.

### ISSUE THREAD

**Issue by PaulOst** [aspnet/Blazor#1657]
@danroth27 @SteveSandersonMS I would like to incorporate the popular D3 library into a prototype blazor app. Is that possible using JS Interop? If so, how? Thanks in advance!

**Comment by Andrzej-W** [comment]
Everything is possible, it is only a matter of time and experience. I haven't seen any ready to use D3 example, but if you want to experiment yourself you can start with one of ChartJS projects:
https://github.com/muqeet-khan/BlazorComponents
https://github.com/mariusmuntean/ChartJs.Blazor
and then transform your knowledge to D3.

**Comment by danroth27** [comment]
It should be possible via JavaScript interop. You can read how to set it up here: https://blazor.net/docs/javascript-interop.html

**Comment by PaulOst** [comment]
Thanks, @danroth27 and @Andrzej-W!
