### ISSUE TITLE
VS Code hangs when setting bind property in nshtml files

### ISSUE THREAD

**Issue by rshillington** [aspnet/Blazor#1663]
Visual Studio Code: 1.28.2 (1.28.2)
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Steps to reproduce
1) Create a public class in a .cs file
2) add a public property in the class
3) create a page component in a .cshtml file
4) add `@inherits` and name the class
5) add a `<input type="text" bind="@prop"/>` element

Expected behaviour
VS Code should keep running.

Actual behaviour
After typing `@` the entire VS code environment freezes.  After a period of the time, the OS gives a dialog box saying the window has stopped responding, and offers to close, continue waiting, or reopen.

Workaround:
type the `@prop` string somewhere else, and then copy/paste it into place.

**Comment by tidyui** [comment]
Yes I've experienced this issue as well, although it keeps happening in regular asp.net core project as well so it has nothing to do with Blazor. I suggest opening an issue in the code repository for VS Code!

Best regards

**Comment by tidyui** [comment]
Also I have experienced the behavior with both `2.1.403` and `2.2.100-preview3-009430` so it's not directly related to your runtime either.

**Comment by SteveSandersonMS** [comment]
Thanks for the post. Since we don't currently have Blazor support in VS Code, it's not specifically expected to work. This should all start to work properly once VS Code gains Blazor support, which will hopefully be in the next month or two.

**Comment by danroth27** [comment]
This issue was moved to aspnet/Razor.VSCode#229
