### ISSUE TITLE
 'Router' cannot find any component with a route for '/todo'

### ISSUE THREAD

**Issue by cesarzapatawfm** [aspnet/Blazor#1667]
I'm following the tutorial https://blazor.net/docs/tutorials/build-your-first-blazor-app.html but when I add the todo component and try to navigate to it , i get an error on browser console. 
"Uncaught (in promise) Error: System.InvalidOperationException: 'Router' cannot find any component with a route for '/todo'."

Here is my Todo.cshtml page. 
```html
@page "/todo"

<h1>Todo</h1>
```
I tried rebuilding and restarting Visual Studio but still getting the error. The other pages that came in the templates index,counter and fetchdata are working fine. 

Any ideas?

**Comment by Lupusa87** [comment]
Probably you have mistake because it should work 100%. Can you share your project as repo we to check what is wrong?

**Comment by danroth27** [comment]
In particular I'd like to see you're project file.

**Comment by cesarzapatawfm** [comment]
Hello, Thank you for taking your time. 
I uploaded the project here https://github.com/cesarzapatawfm/BlazorTest

**Comment by ghidello** [comment]
Your Blazor.csproj file contains a couple of directive marking the Todo.cshtml to be ignored: try removing them directly or highlight the Todo.cshtml file in visual studio and mark it as Content instead of None.

**Comment by cesarzapatawfm** [comment]
> I can't find todo.cshtml.
> Are you sure you commited last changes?
> I guess in this repo there is only blazor template without any changes.
thanks  i commited and synced

**Comment by cesarzapatawfm** [comment]
> Your Blazor.csproj file contains a couple of directive marking the Todo.cshtml to be ignored: try removing them directly or highlight the Todo.cshtml file in visual studio and mark it as Content instead of None.

Great! that worked but I dont know how it got there. I'll keep a note for the future. thanks!
