### ISSUE TITLE
 table.deleteRow without JS

### ISSUE THREAD

**Issue by stas-sultanov** [aspnet/Blazor#1683]
Can't find in any example
how to delete table row or any dom element without JS inter-op :(

**Comment by danroth27** [comment]
Blazor handles most of the interactions with the DOM for you. Blazor components render into an in-memory representation of the DOM called a render tree. As components are updated the new rendered content is compared against the old content and the diff is then applied to the DOM very efficiently. This is similar to how other component based frameworks like Angular and React work. So, typically what you do in Blazor write your component rendering and event handling logic such that when the component is rerendered specific DOM elements are added or removed. 

For example, you might render each row in a table based on the items in a list. You could then have buttons that when clicked remove items from the list, which when the component is rendered again results in the corresponding table rows not getting rendered.

I hope this helps!

**Comment by Lupusa87** [comment]
Webassembly can't access dom directly yet but this feature should come in next versions. So for now only option to manipulate dom is js interop. You can do it direct or blazor will do it for you. Blazor way is better to keep integrity but in some case you maybe will use js.
