### ISSUE TITLE
Upgrading Blazor language service from 0.6 to 0.7 installs windows SDK

### ISSUE THREAD

**Issue by ctyar** [aspnet/Blazor#1687]
Upgrading Visual studio extension from 0.6 to 0.7 installs multiple versions of Windows SDK.
Is this intended?

![annotation 2018-11-16 142348](https://user-images.githubusercontent.com/1432648/48617406-a4e5c080-e9ab-11e8-9a7a-fdc55a948ad2.jpg)

**Comment by abhisheksiddhu** [comment]
@ctyar This is not intended, and personally I have never experienced it, might be a bug in VS

**Comment by SteveSandersonMS** [comment]
I think this is specific to the configuration of your VS instance. It doesn't happen on mine. Perhaps the VS installer has determined that you have an out-of-date Windows SDK so it wants to update it.
