### ISSUE TITLE
Support of custom component custom name

### ISSUE THREAD

**Issue by achmstein** [aspnet/Blazor#169]
Is there any way to change custom component name to follow html standards? for example changing `<MyDialog></MyDialog>` to `<my-dialog></my-dialog>`

**Comment by SteveSandersonMS** [comment]
The idea is that components are .NET types, so their names are .NET type names. This should be sensitive to the `@using` statements you're using, so for example you might write either

    <MyApp.MyNamespace.MyDialog />

or you could write:

    @using MyApp.MyNamespace
    <MyDialog />

... and would get an equivalent result. This is really convenient if you're pulling in packages of third-party componetns, where the namespacing lets you control exactly what types are in scope and intellisense can guide you to pick the applicable ones from each package.

The .NET type name `MyDialog` never ends up in the actual browser DOM so it's not violating any naming rules.
