### ISSUE TITLE
CascadingValue is always null

### ISSUE THREAD

**Issue by stsrki** [aspnet/Blazor#1691]
I'm trying to use a new feature in Blazor 0.7.0 but with no success. 

This is the code from my _parent_ `Fields` component.
```
<CascadingValue Value=this>
    <div class="field-body">
        @ChildContent
    </div>
</CascadingValue>
```

And in a _child_ component I have:

`[CascadingParameter] protected Fields ParentFields { get; set; }`

But whatever I do the `ParentFields` property is always null. I don't know what I'm missing. That's basically everything from the documentation.

**Comment by danroth27** [comment]
@stsrki To investigate this we need some more specific steps to reproduce the issue. Could you please show the usage of the Fields component with it's child content and the full definition of the child component? If you could actually share a simplified project that reproduces the issue that would be ideal.

**Comment by stsrki** [comment]
Sorry guys, it seems the problem was on my part. I have overlooked one `if `condition and forgot to surround the `ChildContent `with `CascadingValue`. Everything works now without any issue. You can close the issue :) thanks
