### ISSUE TITLE
index.html could be configurable

### ISSUE THREAD

**Issue by losmacko** [aspnet/Blazor#1694]
Currently there is no options to use diffrent index.html file to ex. production and development. It' ll be nice if this could be configurable.

**Comment by RemiBou** [comment]
You can handle it with your server using url rewriting in ASPNET Core for example or reverse proxy in your web server. Or even with conditions on your csproj file.

**Comment by SteveSandersonMS** [comment]
As part of our work on Razor Components we'll have a project template that uses server-side rendering for the initial HTML.
