### ISSUE TITLE
Use blazor without razor?

### ISSUE THREAD

**Issue by Thaina** [aspnet/Blazor#170]
I am more fond of angular/vue template syntax. I just want to write C# in place of javascript. So now I was planning that I would make a wrapper to access blazor from vue 

But should I do that? Would it bad for blazor engine to do receive high js workload?

**Comment by SteveSandersonMS** [comment]
I don't know exactly how that could be achieved or what the performance characteristics would be. You might want to look at using Mono for WebAssembly directly rather than using Blazor. Our goal for Blazor is to make Razor+C# a really effective end-to-end SPA platform.

**Comment by Thaina** [comment]
@SteveSandersonMS I have seen blazor was more complete in toolchain to compile C# in html SPA project than pure mono wasm. So I think this would be easier to utilize everything from blazor except razor

And honestly I have seen razor have many feature like angular and vue just difference in syntax. So I think I could utilize thing that you has implement for razor to bridge with any frontend framework. It would set thing blazed wildly for C# adoption

**Comment by Thaina** [comment]
@SteveSandersonMS Sorry for bother you but do we have the purely blank blazor project? I mean the one with only startup `index.html` and `Program.cs` without any `cshtml` and so I could make custom layout engine or bridging with other layout engine

**Comment by SteveSandersonMS** [comment]
We don't have a template for it, but you can create a new standalone Blazor app and delete the Blazor components that you don't want.
