### ISSUE TITLE
blazor update 0.6 to 0.7

### ISSUE THREAD

**Issue by auc31** [aspnet/Blazor#1710]
hi

we have upgrated all project in our 0.6 blazor solution but when we execute (F5) the page stay on "LOADING...." text, not load the blazor site

have you got a idea ?

**Comment by vertonghenb** [comment]
Anything in the console / error output?

**Comment by auc31** [comment]
hi thanks for your answer 

this our ouptut :

Sol1.Server> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
Sol1.Server>       User profile is available. Using 'C:\Users\Administrateur\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Sol1.Server> Hosting environment: Development
Sol1.Server> Content root path: C:\Users\Administrateur\OneDrive\DEV\Sol1_Blazor2018.11\Sol1\Sol1.Server
Sol1.Server> Now listening on: http://127.0.0.1:33594
Sol1.Server> Application started. Press Ctrl+C to shut down.
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Sol1.Server>       Request starting HTTP/1.1 DEBUG http://localhost:57845/  0
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Sol1.Server>       Request starting HTTP/1.1 GET http://localhost:57845/  
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Sol1.Server>       Request finished in 28.9415ms 200 
Sol1.Server> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
Sol1.Server>       The file /index.html was not modified
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Sol1.Server>       Request finished in 250.5212ms 304 text/html
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Sol1.Server>       Request starting HTTP/1.1 GET http://localhost:57845/css/site.css  
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Sol1.Server>       Request starting HTTP/1.1 GET http://localhost:57845/css/bootstrap/bootstrap.min.css  
Sol1.Server> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
Sol1.Server>       The file /css/site.css was not modified
Sol1.Server> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
Sol1.Server>       The file /css/bootstrap/bootstrap.min.css was not modified
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Sol1.Server>       Request finished in 8.5065ms 304 text/css
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Sol1.Server>       Request finished in 10.3204ms 304 text/css
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Sol1.Server>       Request starting HTTP/1.1 GET http://localhost:57845/css/open-iconic/font/css/open-iconic-bootstrap.min.css  
Sol1.Server> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
Sol1.Server>       The file /css/open-iconic/font/css/open-iconic-bootstrap.min.css was not modified
Sol1.Server> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Sol1.Server>       Request finished in 3.8506ms 304 text/css

**Comment by NikolayIT** [comment]
Anything on the browser console (F12)?

**Comment by auc31** [comment]
thanks for interest

we found solution

int the index.html

the script file change

   in v0.6 => <script type="blazor-boot"></script>-->
   in v0.7 => <script src="_framework/blazor.webassembly.js"></script>

best regards

**Comment by abhisheksiddhu** [comment]
@auc31 @SteveSandersonMS @danroth27 since the issue is resolved, can we mark this as closed
