### ISSUE TITLE
Using Templated components and Cascading components together throws compile time errors

### ISSUE THREAD

**Issue by ivanchev** [aspnet/Blazor#1711]
Using the [TabStrip sample](https://gist.github.com/SteveSandersonMS/f10a552e1761ff759b1631d81a4428c3), if you add a RenderFragment TabTemplate property, you cannot set both <Tab> and <TabTemplate> inside the TabSet:
`
<TabSet>
    <TabTemplate>Template</TabTemplate>
    <Tab Title="First tab">
        <h4>First tab</h4>
        This is the first tab.
    </Tab>
    ...
`
Setting either one by itself works fine. Is this an intended limitation?

**Comment by SQL-MisterMagoo** [comment]
@ivanchev If you have two RenderFragments, you would need to specify them both

```
<TabSet> 
  <TabTemplate>Template</TabTemplate>
  <ChildContent>
    <Tab Title="First Tab"> <h4>First tab</h4> This is the first tab. </Tab> ...
  </ChildContent>
</TabSet>
```

This is how it knows what content belongs to which Parameter.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @SQL-MisterMagoo!
