### ISSUE TITLE
Events between two components

### ISSUE THREAD

**Issue by JulienM28** [aspnet/Blazor#1714]
I have two components:

one selectlist and one "View"

The view is populated from datas depending on which element is selected in the select list.

I seen It's possible to raise events from parents to children and inverse, but How to raise events between two components who are not parented ?

Thanks.

**Comment by enetstudio** [comment]
In an SPA application, as far as I got it, there is a single Html page; in Blazor this page, named Index.Html, residing in the wwwroot folder. There is also a root Component, currently named Main, which is rendered into the Index page. The Main Component may contain the rest of your Components hierarchically: Think of a tree view. So you see all the Components are begotten or parented by the Main Component, They all belong to the same family of Blazor Components, and are all related to each other directly or indirectly. 

Best resources to understand communication between Components in Blazor:
* FlightFinder sample: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor
*  https://github.com/aspnet/Blazor/issues/887#issuecomment-393223792

Hope this helps... if you would need specific help, please show code...

**Comment by Lupusa87** [comment]
you can use ref to capture both component references, you will invoke event when change happens, subscribe for this event and call second component's public method. Or you can save bot components instances and invoke public methods when you need. You can use many ways for that goal (state, services and etc) key is here event raising and component instances to access them. For example I have two chess board on page and they play between eachother, one is saying second that move made and sends move description. These two components have not parent or child relation.
https://lupblazordemos.z13.web.core.windows.net/ChessPage

**Comment by shawty** [comment]
I've done this in my JWT/LOB example by using my ApplicationState singleton as a mediator.
https://github.com/shawty/blazor.jwttest

Basically I have a function in my Appstate, and I have a public event delegate.

Since most parts of my app, inject my appstate class to check for things like logged in status, anything that wants to know when a successful login is made, attaches to the LoginSuccessful event in the class.

When something logs in, it calls Login on the AppState class, and the app state then raises it's own LoginSuccessful event, which any interested listeners respond to.

**Comment by enetstudio** [comment]
@Lupusa87: "These two components have not parent or child relation."

But still they are related to each other on account of both being siblings.  In such a case, it is best to use a mediator object, as @shawty suggests, in the form of a parent, that enables communication between its two children.

**Comment by Lupusa87** [comment]
You can do as you think better. I achieved my goal this way and agree that there can be many better ways.

**Comment by JulienM28** [comment]
Thank you all for your aanswers.

I'll try it right now.

**Comment by JulienM28** [comment]
@Lupusa87 your website is reported as phishing by our virus protection.
You may fix this.

**Comment by shawty** [comment]
> 
> 
> @Lupusa87 your website is reported as phishing by our virus protection.
> You may fix this.

HA ha ha ha, that's hilarious.  :-)  That looks like it's an alised Azure domain, which means your software thinks Azure is a Phishing site...

Best laugh I've had all morning.

**Comment by Lupusa87** [comment]
Someone else told me ssme but I don't know how can I fix it and why your antivirus is reporting problem.
Here is source https://github.com/Lupusa87/LupusaBlazorProjects
If you can provide more details please open issue in this repo.
Thank you.

**Comment by longinos10** [comment]
I did something similar with event handler

**Comment by SteveSandersonMS** [comment]
Thanks for all the answers!
