### ISSUE TITLE
.cshtml losing format layout

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#1717]
when using the current solution Components.sln the .cshtml files lose the layout/structure @functions code and intellisence

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience. We're aware of many cases where `.cshtml` formatting goes wrong and are working on making this more robust.

**Comment by grahamehorner** [comment]
Good to know your on the case, and know about this, the team is doing great work loving it all and happy to give feedback in this and experiment with ideas
