### ISSUE TITLE
Question: Is in Visual Studio debugging planned for Client Side Blazor? 

### ISSUE THREAD

**Issue by TheColonel2688** [aspnet/Blazor#1720]
Is in Visual Studio debugging planned for Client side Blazor? In other words: the ability to have visual studios attach to the blazor app process in the browser rather than using the Chrome debug UI.

**Comment by enetstudio** [comment]
@Lupusa87: nd then anytime switch to client side, which will require only one code line change in your project.

@Lupusa87, perhaps you can help me with this: You are not the first person to say the above. Even the creators of Blazor have said it. So now let me ask you this: In BrowserHttpMessageHandler.SendAsync method is this if block:
if (JSRuntime.Current is MonoWebAssemblyJSRuntime mono)
            {
                mono.InvokeUnmarshalled<int, byte[], string, object>(
                    "Blazor._internal.http.sendAsync",
                    id,
                    request.Content == null ? null : await request.Content.ReadAsByteArrayAsync(),
                    Json.Serialize(options));
            }
            else
            {
                throw new NotImplementedException("BrowserHttpMessageHandler only supports running under Mono WebAssembly.");
            }
I do not understand how I can use HttpClient on both Client Blazor and then switch to server-side Blazor... Could you please explain what I've been missing.

**Comment by enetstudio** [comment]
@Lupusa87: nd then anytime switch to client side, which will require only one code line change in your project.

@Lupusa87, perhaps you can help me with this: You are not the first person to say the above. Even the creators of Blazor have said it. So now let me ask you this: In BrowserHttpMessageHandler.SendAsync method is this if block:
`if (JSRuntime.Current is MonoWebAssemblyJSRuntime mono)
            {
                mono.InvokeUnmarshalled<int, byte[], string, object>(
                    "Blazor._internal.http.sendAsync",
                    id,
                    request.Content == null ? null : await request.Content.ReadAsByteArrayAsync(),
                    Json.Serialize(options));
            }
            else
            {
                throw new NotImplementedException("BrowserHttpMessageHandler only supports running under Mono WebAssembly.");
            }`
I do not understand how I can use HttpClient on both Client Blazor and then switch to server-side Blazor... Could you please explain what I've been missing.

**Comment by enetstudio** [comment]
@Lupusa87: nd then anytime switch to client side, which will require only one code line change in your project.

@Lupusa87, perhaps you can help me with this: You are not the first person to say the above. Even the creators of Blazor have said it. So now let me ask you this: In BrowserHttpMessageHandler.SendAsync method is this if block:
```
if (JSRuntime.Current is MonoWebAssemblyJSRuntime mono)
            {
                mono.InvokeUnmarshalled<int, byte[], string, object>(
                    "Blazor._internal.http.sendAsync",
                    id,
                    request.Content == null ? null : await request.Content.ReadAsByteArrayAsync(),
                    Json.Serialize(options));
            }
            else
            {
                throw new NotImplementedException("BrowserHttpMessageHandler only supports running under Mono WebAssembly.");
            }
```
I do not understand how I can use HttpClient on both Client Blazor and then switch to server-side Blazor... Could you please explain what I've been missing.

**Comment by ysmoradi** [comment]
Http client's constructor accepts HttMessageHandler. You can pass an instance of HttpClientHandler to that, so it won't use BrowserHttpMessageHandler.

**Comment by Lupusa87** [comment]
I think this snippet is complicated, you can send data over http with simpler way. If you need this particular code to work I can't help without research and not sure it has sense for me, sorry.

**Comment by enetstudio** [comment]
@Lupusa87, the if block check whether we are using WebAssembly ( that is, Blazor client) or not ( that is, we are using server-side Blazor).

@ysmoradi, that sounds quite reasonable, but how can I do that ? The following method, defined in the BrowserServiceProvider class, uses BrowserHttpMessageHandler to create a singleton HttpClient object.
```
  private void AddDefaultServices(ServiceCollection serviceCollection)
        {
            serviceCollection.AddSingleton<IUriHelper>(BrowserUriHelper.Instance);
            serviceCollection.AddSingleton(new HttpClient(new BrowserHttpMessageHandler())
            {
                BaseAddress = new Uri(BrowserUriHelper.Instance.GetBaseUri())
            });
        }
```
Do you know how can I  pass an HttpMessageHandler to the HttpClient constructor instead of BrowserHttpMessageHandler ?

**Comment by janaka** [comment]
VS Code support also please!

**Comment by Lupusa87** [comment]
@enetstudio DualMode has different use case, I believe it is intended automatically to switch user to server side blazor if browser not supports webassembly or if client wants for some reason to switch mode manually. It is great without any doubt.

Here question was about debugging when developer seats and writes application.

I personally have SSB project where I actively develop my app (using full debugging) and periodically update CSB version for that project (which takes less than minute).

Good look to everyone.

**Comment by SteveSandersonMS** [comment]
Yes, we do expect to have VS/VSCode debugging for the Mono WebAssembly runtime eventually. No specific ETA though.

**Comment by TheColonel2688** [comment]
> 
> 
> Yes, we do expect to have VS/VSCode debugging for the Mono WebAssembly runtime eventually. No specific ETA though.

Is there an Issue tracking this?

**Comment by SteveSandersonMS** [comment]
Mono issues are tracked at https://github.com/mono/mono
