### ISSUE TITLE
VisualStudio command Edit.FormatDocument breaks the indention

### ISSUE THREAD

**Issue by mynkow** [aspnet/Blazor#1724]
When I am in VS and execute the command Edit.FormatDocument (CTRL+E,D) this happens= >

https://gyazo.com/209c7bc8d065dcd7eef421f780e2682f

**Comment by Andrzej-W** [comment]
It is annoying, but there is simple workaround: remove space between `@functions` and `{`. Unfortunately the correct formatting is that after Ctrl+E,D with space before `{` or with `{` in a new line. We are writing C# code and it should be formatted like this:
```c#
@functions
{
    bool collapseNavMenu = true;
    void ToggleNavMenu()
    {
        collapseNavMenu = !collapseNavMenu;
    }
}

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience. We're aware of many cases where `.cshtml` formatting goes wrong and are working on making this more robust.
