### ISSUE TITLE
Server Side Blazor First Client Receiving Second Client's Requests

### ISSUE THREAD

**Issue by cyberjaws** [aspnet/Blazor#1726]
Server Side Blazor:
Create a data service that connects to RabbitMQ and register the data service as a singleton.
Connect a client and register for a callback event from the data service.
Make a request to the data service. Request gets sent over MQ. Method returns.
...wait for x ms...
Response come back over RabbitMQ and fires an event in the data service.
Event fires in client 1, check the results against a clientId created at startup, fire a JSInterop method on the client to update an image if the clientId matches the Id in the result.
With one client connected, the image comes through no problems. 
With a second client connected the image gets returned to the first client and the correct clientId / image combo doesn't make it to the second client.
Thoughts?

**Comment by SteveSandersonMS** [comment]
>  fire a JSInterop method on the client

My guess is that you're using `JSRuntime.Current`. Don't, because that always refers to the current user's request. Do the following instead in your component:

```
@inject IJSRuntime jsRuntime;
```

... and then use `jsRuntime` to issue the JS interop call instead. That way you'll be sending the info to each client separately.

**Comment by ransagy** [comment]
Maybe this is something to note in the documentation on the various changes between Client and Server sided Blazor, perhaps even in the templates.

**Comment by cyberjaws** [comment]
That was it! Brilliant.
