### ISSUE TITLE
How to distinguish components

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/Blazor#1730]
If one includes two different components in their application in different namespaces with the same name. 
Path/To/Firstone/SomeComponent.cshtml
Path/To/AnotherOne/SomeComponent.cshtml

And in MyLayout.cshtml I would like to use

```
<SomeComponent />  // From AnotherOne
```

  Blazor seems to find the first one.  And I don't know how to clarify the namespace.

Nor does it give me an ambiguous compile error.

**Comment by danroth27** [comment]
Current there really isn't a way, but the plan is that you will be able to use normal namespaces to do this. So, `@using` would work, or you will be able to explicitly specify the full component name: `<Path.To.AnotherOne.SomeComponent />`. This is tracked by https://github.com/aspnet/Blazor/issues/1315

**Comment by StevenTCramer** [comment]
@danroth27 Thanks!  Sorry I didn't see #1315
