### ISSUE TITLE
USB Access

### ISSUE THREAD

**Issue by MelbourneDeveloper** [aspnet/Blazor#1748]
When do we get C# USB access over wasm?

**Comment by danroth27** [comment]
You should be able to call any browser API from C#  using [JavaScript interop](https://blazor.net/docs/javascript-interop.html). You can then create a NuGet package that anyone can use to call the same API. Many community packages exist for various browser APIs (see https://blazor.net/community).

If you're looking for the platform to provide these browser API wrappers then you should file an issue on https://github.com/mono/mono/issues.

**Comment by Lupusa87** [comment]
https://github.com/BlazorExtensions/WebUSB
