### ISSUE TITLE
Page reload after onClick - if button inside <form> tag

### ISSUE THREAD

**Issue by Yvahajatiana** [aspnet/Blazor#1751]

**Comment by michaelvolz** [comment]
If you use the `Form` tag, your page will be submitted to the server. Just remove it. You don't need it, except you want to submit your form to the server this way. Normally you don't.

**Comment by RyoukoKonpaku** [comment]
If you need the form tag in any way. Just make the button `<button type="button" ></button>` to signify it that it's not a submit button.

**Comment by Yvahajatiana** [comment]
@michaelvolz , @RyoukoKonpaku  Thank you!
It's working now!
