### ISSUE TITLE
Version for package `Microsoft.AspNetCore.Blazor.Cli` could not be resolved after installing VS2019 Preview

### ISSUE THREAD

**Issue by mynkow** [aspnet/Blazor#1755]
Today I have installed VS2019 Preview and when I tried to run my Blazor App using VS2017 the log under `ASP.NET Core Web Server` says => `Version for package 'Microsoft.AspNetCore.Blazor.Cli' could not be resolved.`

Can I do do anything to make the Blazor app working again?

EDIT:
Unistalling VS2019 did not help.

Recently I have updated to VS 15.9.3

File => New Project => Blazor template produces the same error

Reinstalling the `ASP.NET Core Blazor Language Services` did not help.

**Comment by mynkow** [comment]
This is my current dotnet sdk list
```
C:\Users\mynkow>dotnet --list-sdks
1.0.0 [C:\Program Files\dotnet\sdk]
1.0.3 [C:\Program Files\dotnet\sdk]
1.0.4 [C:\Program Files\dotnet\sdk]
1.1.0-preview1-005098 [C:\Program Files\dotnet\sdk]
1.1.0 [C:\Program Files\dotnet\sdk]
2.0.0-preview1-005977 [C:\Program Files\dotnet\sdk]
2.0.0-preview2-006497 [C:\Program Files\dotnet\sdk]
2.0.0 [C:\Program Files\dotnet\sdk]
2.0.2 [C:\Program Files\dotnet\sdk]
2.1.4 [C:\Program Files\dotnet\sdk]
2.1.105 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.300 [C:\Program Files\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]
2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
2.2.200-preview-009648 [C:\Program Files\dotnet\sdk]
```

Creating a global.json made the project working again:

```
{
  "sdk": {
    "version": "2.1.500"
  }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mynkow.
We could reproduce the issue you're describing.

**Comment by mkArtakMSFT** [comment]
We'll update this thread when we'll know how to work around this problem.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, can you please look into this? Thanks!

**Comment by danroth27** [comment]
I was able to reproduce this on my machine. I have both .NET Core 2.2 and 3.0 Preview 1 installed. If I try to use 3.0 Preview 1 I see this error. If I use global.json to pin to 2.2 then the error goes away.

**Comment by SteveSandersonMS** [comment]
I'm afraid I've been unable to repro the issue described. What I tried:

 * Installed VS2019 preview, which implicitly installs the dotnet `2.1.600-preview-009426` SDK
    * ... then tried running Blazor apps from the command line under both the regular 2.1 SDK and the `2.1.600-preview-009426` SDK that comes with VS2019 pre 1. Both worked.
    * ... then tried running Blazor apps from VS2017, using both the regular 2.1 SDK and the `2.1.600-preview-009426` SDK that comes with VS2019 pre 1. Both worked.
 * Installed the 3.0 preview 1 SDK (`3.0.100-preview-009812`)
    * ... then tried running Blazor apps from the command line using the `3.0.100-preview-009812` SDK. Worked.
    * ... then tried running Blazor apps from VS2017 using the supported 2.1 SDK and the `2.1.600-preview-009426` SDK that comes with VS2019 pre 1. Both still worked.
    * ... then tried running Blazor apps from VS2017 using the `3.0.100-preview-009812` SDK. This does **not** work (VS refuses to open the project, saying "Expected imports are missing"). But this is completely unrelated to Blazor. VS2017 can't create/open *any* .NET Core projects with the 3.0 preview SDKs, which I understand is expected since VS2017 doesn't recognize that the 3.0 SDKs even exist. The 3.0 preview release notes say you must use it with VS2019.

So to investigate this any further I'd need more details about how to reproduce it. Just installing VS2019 preview isn't enough.

Assigning to @danroth27 for more repro details.

**Comment by danroth27** [comment]
Yeah, it looks like SDK `2.2.200-preview-009648` is installed by VS 2019 when you select the option to install .NET Core 2.2 in the workload options (although it's strange that the 2.2 option is unchecked in your screenshot).

But even after installing `2.2.200-preview-009648` through VS2019, I still can't reproduce this issue any more. New Blazor projects run cleanly for me.

Can you confirm that restoring NuGet packages for the Blazor project succeeds?

**Comment by mynkow** [comment]
Hmm, I am also not able to reproduce it anymore BUT I have installed netcore 2.2 since that moment. Packages are restored properly.

I am closing this and I hope we never get back to this issue. 

Thank you all
