### ISSUE TITLE
BlazorTooling - $(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#177]
The blazor tooling solution fails to build when using VSSDK is missing from framework path - ...sdk\2.1.300-preview2-008261\Microsoft\VisualStudio\**v**15.0\**VSSDK**\Microsoft.VsSDK.targets ?

Q: should this build; is there anything extra that needs installing? and/or is the generated path correct?

**Comment by SteveSandersonMS** [comment]
Hmm, I'm not certain how and when that solution is meant to be built, or what the prerequisites are. @rynowak?

**Comment by rynowak** [comment]
Unfortunately you have to build the `BlazorTooling.sln` with old stuff - VS developer command prompt and desktop MSBuild. This is a limitation of VSIX projects, and sadly there's no workaround for this 😢 

This is why we split it into two solutions.

**Comment by SteveSandersonMS** [comment]
Thanks for clarifying, @rynowak!
