### ISSUE TITLE
is it possible to use sqlite with blazer?

### ISSUE THREAD

**Issue by DharmarajPandi** [aspnet/Blazor#1774]

**Comment by rynowak** [comment]
Please do not log issues here. This repo is used only for Blazor infrastructure purposes.

 All Blazor code, features, and issues are tracked at https://github.com/aspnet/AspNetCore.

 You can use the `feature-blazor` label to filter issues: https://github.com/aspnet/AspNetCore/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-blazor
