### ISSUE TITLE
How can I get scroll position in scroll view?

### ISSUE THREAD

**Issue by thainbreese** [aspnet/Blazor#1783]
Hi

I am going to build a scroll view component without using JS interop.
The view and scroll bar is separated so I want to know the scroll position in the scroll bar.
How can I know the scroll position in onscroll event?

**Comment by iAmBipinPaul** [comment]
Please do not log issues here. This repo is used only for Blazor infrastructure purposes.

All Blazor code, features, and issues are tracked at https://github.com/aspnet/AspNetCore.

You can use the `feature-blazor` label to filter issues: https://github.com/aspnet/AspNetCore/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-blazor

**Comment by danroth27** [comment]
This issue was moved to aspnet/AspNetCore#7357
