### ISSUE TITLE
We can disable issues for this repo and have a rest :)

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/Blazor#1789]
People still open issues here so maybe better to disable issues and don't waste time for porting new issues from here to aspnetcore.

 What is point to keep opening issues available?

  https://help.github.com/articles/disabling-issues/

![untitled](https://user-images.githubusercontent.com/40779557/52990912-4bd95e80-33d8-11e9-84d4-d43f85ea0694.png)

**Comment by chucker** [comment]
My guess is this will break read-only access to _existing_ issues.

**Comment by danroth27** [comment]
> My guess is this will break read-only access to _existing_ issues.

Correct, that is the concern.

I think I have now updated all places that currently point people to the Blazor issue tracker to instead point to the https://github.com/aspnet/aspnetcore repo instead. Let me know if I've missed any!

**Comment by Lupusa87** [comment]
@danroth27 Ok, you know better :)

> Let me know if I've missed any!

 Blazor [gitter](https://gitter.im/aspnet/Blazor) room is referenced to this repo and we see activities from here.

 Probably people seeing some activity automatically open new issues here.

 If you can reference aspnetcore repo to gitter will be great to prevent this, also to follow activities on new repo.

 Can it be possible we to follow filtered activities, ex label area-mvc?
