### ISSUE TITLE
Smarty/smartjs syntax would be awesome

### ISSUE THREAD

**Issue by peon501** [aspnet/Blazor#1793]
Smarty/jsmart syntax would be awesome.
(Its just an idea)

**Comment by seriouz** [comment]
Replacing Razor with another templating engine eg Smarty, is way to much work and Blazor is not the right project to adress this issue.

**Comment by danroth27** [comment]
@peon501 Thanks for the suggestion! We don't have plans to support other templating engines in Blazor. But maybe this would a be a good community extension?

Since we don't have any plans here I'm going to go ahead and close this. I hope that's ok!
