### ISSUE TITLE
Microsoft.AspNetCore.Authentication.AzureAD.UI not working with Blazor NET Core 3.0

### ISSUE THREAD

**Issue by ltatham** [aspnet/Blazor#1797]
Creating a new Blazor app with .Net Core 3.0 server I'm unable to use Azure AD authentication because I can't successfully add the Microsoft.AspNetCore.Authentication.AzureAD.UI package on the Client project.  Trying to add the preview version fails because of the netstandard version of the client. If I install the 2.2 version I get a build/link error: MSB3073.

**Comment by brunopbarrote** [comment]
You should post it on Asp.net repo, not here, as you can read on README.
