### ISSUE TITLE
Where can I get Steve's Samples from NDC London 2019?

### ISSUE THREAD

**Issue by SWATOPLUS** [aspnet/Blazor#1798]
Where can I get Steve's Samples from NDC London 2019?
@SteveSandersonMS 

I am looking for samples from here:

https://www.youtube.com/watch?v=Qe8UW5543-s

I am looking for AOT samples. Yes, I know that it's terrible alpha, but I need it for my blazor presentation.

**Comment by iAmBipinPaul** [comment]
Here 
https://github.com/aspnet/Blazor/issues/74#issuecomment-469105878

**Comment by SteveSandersonMS** [comment]
AoT demo is here: https://github.com/SteveSandersonMS/il2wasm

**Comment by SWATOPLUS** [comment]
@SteveSandersonMS Is threre any way to run il2wasm project with new version of Blazor? Version 0.9 has no driver.c adapter for mono runtime, so aot-loader.js fails on blazor 0.9 when it tries to export "mono_wasm_object_new". Is it possible to rewrite aot-loader.js with newest versions of blazor/mono?

**Comment by SteveSandersonMS** [comment]
@SWATOPLUS https://github.com/stevesandersonms/il2wasm accepts PRs if you want to submit one, but `il2wasm` is not in any way a supported repo so there's no expectation that it will get updated. Hopefully within a month or two we might start getting the real Mono AoT support into the real repo.
