### ISSUE TITLE
Blazor with  MVC - RazorPage<T>' exists in both ...

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#180]
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
Generated Code

The type 'RazorPage<T>' exists in both 'Microsoft.AspNetCore.Blazor, Version=0.0.5.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by SteveSandersonMS** [comment]
To report a bug, could you please specify repro steps? Thanks.

**Comment by grahamehorner** [comment]
to repo this issue, create an ASP.NET Core Web Application using the View Model Controller template; add the blazor server package from myget; add blazor client project reference then add the app.UseBlazor( ) after the app.UseMvc in the host.

**Comment by SteveSandersonMS** [comment]
Thanks for the clarification. Fixed in 94a2157
