### ISSUE TITLE
Is there any multi-level js calls?

### ISSUE THREAD

**Issue by lvdiev** [aspnet/Blazor#1800]
Sorry but I'm not sure if any was facing below problem.
I'm integrating here map js libs with Blazor, when I call a js function using JsRuntime, this js method calls another js function itself. But that seems impossible.
Please let me know is it possible at the moment. Thanks.

**Comment by danroth27** [comment]
You should be able to call into arbitrary javascript from a Blazor app. The JS function you call should be able to call other JS functions as well. If you're seeing issues with this it's probably with the JS code.

Also, please note that we've moved all the Blazor code and issues to the https://github.com/aspnet/aspnetcore, so all new Blazor issues should be opened there.
