### ISSUE TITLE
Error with Blazor Local Template oram i Missing something?

### ISSUE THREAD

**Issue by PeterJD** [aspnet/Blazor#1805]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet "C:\Users\liudm\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview5-19227-01\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json "obj\Debug\netstandard2.0\BlazorLocal.dll" --references "C:\Users\liudm\source\repos\BlazorSol\BlazorLocal\obj\Debug\netstandard2.0\blazor\bootjson-references.txt" --embedded-resources "C:\Users\liudm\source\repos\BlazorSol\BlazorLocal\obj\Debug\netstandard2.0\blazor\embedded.resources.txt" --linker-enabled --output "C:\Users\liudm\source\repos\BlazorSol\BlazorLocal\obj\Debug\netstandard2.0\blazor\blazor.boot.json"" exited with code -2147450730.	BlazorLocal	C:\Users\liudm\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview5-19227-01\targets\Blazor.MonoRuntime.targets	633

**Comment by danroth27** [comment]
Hi @PeterJD,

I'm sorry your having issues with the default Blazor template!

Could you please share the output of `dotnet --info` with us?

**Comment by PeterJD** [comment]
resolved this issue:- is this good error reporting ?
The above out put is Chinese the error code bares on relationship to the error.  
So what was the error?
upgrade?

The specified framework 'Microsoft.NETCore.App', version '3.0.0-preview5-27626-15' was not found

Install-Package Microsoft.NETCore.App -Version 3.0.0-preview5-etc.....

**Comment by PeterJD** [comment]
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  2.2.201 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010046 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010050 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010067 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:

**Comment by PeterJD** [comment]
I upgraded preview 5 on future investigation discovered a possible reason for the application not functioning correctly unable to set SDK to preview 5 
Like
Tools -->option ->Project and solutions-->.NET Core but there is no check box to allow you to use 
preview?
Is this true in the community Addition of VS 2019 you are not able to set Previews 5 etc SDK?
Kind regards
Peter

**Comment by IvanJosipovic** [comment]
You need to use the Preview version of Visual Studio 2019 with Blazor.

**Comment by PeterJD** [comment]
Yes I am using Visual Studio Community  2019 preview
Should I use professional? 
is the preview version free?
Visual Studio Community  2017 does allow for the above settings

Peter

**Comment by danroth27** [comment]
@PeterJD If you're using the Visual Studio Preview version then it will pick up preview .NET Core SDKs by default. It's only the stable version of Visual Studio that requires you to opt into support for preview .NET Core SDKs.

So after upgrading to .NET Core 3.0 Preview 5 and using the latest preview version of Visual Studio, are you still seeing this issue?

**Comment by PeterJD** [comment]
Yes, 
Have downloaded Piza project which again shows the the same error?
so is there some thing wrong with my settings
kind reards
Peter

**Comment by PeterJD** [comment]
May be the fact Im using Win 10 home addition be an issue?

**Comment by danroth27** [comment]
> May be the fact Im using Win 10 home addition be an issue?

No that should be fine.

Could you please share the updated output of `dotnet --info` and the version of Visual Studio that you are using?

**Comment by PeterJD** [comment]
Hi just starting afresh, playing around with the app given a different result
Peter

**Comment by danroth27** [comment]
> playing around with the app given a different result

Hopefully a better result? 😃

**Comment by PeterJD** [comment]
Hi 
I used the same project has before where the errors being reported had changed 
from 
app.UseBlazor<Client.Startup>(); in error
To
app.UseBlazorDebug(); in error

I thoght at this point is every thing scrambled, so decided to create a new template and try this
and WOW no errors so am terribly pleased about this situation. 

hopefully I can impletement the Pizza app successful, then implement the conference planner.

Do you now of any good examples of DDD CQRS?

All being well all is functioning correctly, I would like to thank you (and your team) for your kind help and support.
Kind regards
Peter

**Comment by danroth27** [comment]
I'm happy to hear things are now working for you! 

I'm not familiar with any specific examples of doing DDD or CQRS with Blazor, but there are a bunch of community based sample apps listed on https://github.com/AdrienTorris/awesome-blazor that you can try looking through or join the Blazor Gitter at https://gitter.im/aspnet/blazor and see if anyone there has tried out those patters. 

Good luck!
