### ISSUE TITLE
Hot reload with blazor ?

### ISSUE THREAD

**Issue by Amine-Smahi** [aspnet/Blazor#1810]

**Comment by danroth27** [comment]
We will have auto-rebuild support initially. True hot reload is harder and we're still discussing how it can be enabled. This is tracked by https://github.com/aspnet/AspNetCore/issues/5456, so I'm going to go ahead and close this one.

For future reference, all Blazor work is now tracked in the https://github.com/aspnet/aspnetcore repo.
