### ISSUE TITLE
Custom DataAnnotation ValidationAttribute error message is not showing

### ISSUE THREAD

**Issue by PKYADAV** [aspnet/Blazor#1824]
**Model Definition:**
        
        [DbRequired]
        [Display(Name = "USER NAME", Prompt = "ENTER USER NAME")]
        public string User_Name
        {
            get { return GetValue(() => User_Name); }
            set { SetValue(() => User_Name, value); }
        }

        [Display(Name = "PASSWORD", Prompt = "ENTER PASSWORD")]
        [DataType(DataType.Password)]
        [DbRequired]
        public string User_Password
        {
            get { return GetValue(() => User_Password); }
            set { SetValue(() => User_Password, value); }
        }

**ValidationAttribute:**

public class DbRequired : RequiredAttribute
    {
        DataContext db;
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
                if ((value == null || value.ToString() == string.Empty || value.ToString() == "0"))
                {
                    return new ValidationResult("USER NAME IS REQUIRED FIELD !");
                }
                else
                {
                    return ValidationResult.Success;
                }
        }
    }

When using builtin **Required** then working fine but when overriding **RequiredAttribute** then error message not displayed:
![image](https://user-images.githubusercontent.com/4301382/60683555-f64cac80-9eb5-11e9-9bdf-8fdd4d935105.png)

**Comment by pelhamrj** [comment]
@PKYADAV Did you find the solution to this? Running into the same issue.

**Comment by PKYADAV** [comment]
> @PKYADAV Did you find the solution to this? Running into the same issue.

Yes, just pass the member name in validation context in below line: 
return new ValidationResult("USER NAME IS REQUIRED FIELD !"); 

Please try and let me know, if any issue. Will post source code reference.

**Comment by pelhamrj** [comment]
@PKYADAV Thank you for the help! I ended up ditching DataAnnotations out of frustration with custom attributes, and am now using FluentValidation. I appreciate such a quick response! 😄

**Comment by PKYADAV** [comment]
Hii @pelhamrj,
If your requirement is static then Fluent Validation is best option but if your requirement is dynamic then you need to write custom validation attribute.

**Comment by MasihAkbari** [comment]
> > @PKYADAV Did you find the solution to this? Running into the same issue.
> 
> Yes, just pass the member name in validation context in below line:
> return new ValidationResult("USER NAME IS REQUIRED FIELD !");
> 
> Please try and let me know, if any issue. Will post source code reference.

this is works for me but why? if i don't know the member name how can i solve it?

**Comment by PKYADAV** [comment]
Can you share more information and scenario on that you want to achieve?

**Comment by MasihAkbari** [comment]
> Can you share more information and scenario on that you want to achieve?

well, in asp.net project when I used custom data annotation attributes, I didn't need to explicitly put input name in returning of `ValidationResult` but now in blazor projects, if I don't do this, custom annotations won't work

**Comment by cveld** [comment]
At least in Blazor Server 3.0 we can confirm the same behavior that @dev-masih is reporting.
We also find this confusing behavior. Ideally the system should be defaulting to the field that the validator is attached to if an explicit list of one or more fields is omitted.

**Comment by jadennis** [comment]
We were trying to use custom validation in Blazor Server 3.0. We were not having any success until we found this issue. Just wanted to share a clear example of what works for us in case it helps anyone.   

`return new ValidationResult("REQUIRED FIELD !", new [] { validationContext.MemberName });`
