### ISSUE TITLE
How to validate the EditForm before click the submit button?

### ISSUE THREAD

**Issue by BerlyChristopher** [aspnet/Blazor#1831]
While placing the Input text component inside the EditForm, we can validate the form after clicking the submit button. How can we validate the component inside the edit form without clicking the submit button?

Can anyone suggest a possible solution?

**Comment by PeterHimschoot** [comment]
I'm working on a blog post explaining how to do this. I'll try to get it
done tomorrow.

Peter Himschoot
Author of Blazor Revealed

**Comment by danroth27** [comment]
@BerlyChristopher The EditorForm will setup an `EditContext` as a [cascading value](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#cascading-values-and-parameters), which you should be able to call `Validate()` on. See https://docs.microsoft.com/aspnet/core/blazor/forms-validation for more details.

**Comment by PeterHimschoot** [comment]
As promised:
https://blogs.u2u.be/peter/post/disabling-the-submit-button-in-blazor-with-validation

I think there is a small bug in EditForm because the EditContext property
is null when you use Model.

**Comment by danroth27** [comment]
> I think there is a small bug in EditForm because the EditContext property
is null when you use Model.

Please file an issue on the https://github.com/aspnet/aspnetcore repo and we'll take a look.

**Comment by PeterHimschoot** [comment]
Hi Dan,

Done that already  https://github.com/aspnet/AspNetCore/issues/12238

I'll even supply a PR :)

Peter
