### ISSUE TITLE
Please verify the issue #1500

### ISSUE THREAD

**Issue by apayero** [aspnet/Blazor#1839]
bootstrap.min.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
site.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
blazor.webassembly.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND

all was ok publish with priview 6 in azure content "static web site", but now did not work.   With error above.

**Comment by apayero** [comment]
The requested content does not exist.
HttpStatusCode: 404
ErrorCode: WebContentNotFound
RequestId : 9911deb3-801e-0024-540b-46c328000000
TimeStamp : 2019-07-29T12:44:28.0000588Z

this is the display in the page.

**Comment by SeppPenner** [comment]
From the [README](https://github.com/aspnet/Blazor/blob/master/README.md):

> The [sources](https://github.com/aspnet/AspNetCore/tree/master/src/Components) and [issues](https://github.com/aspnet/aspnetcore/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-components) for Blazor have moved to the [ASP.NET Core repo](https://github.com/aspnet/aspnetcore).

> New issues and PRs should be posted at the [ASP.NET Core repo](https://github.com/aspnet/AspNetCore).

> Please don't post new issues or PRs in this repo.

> For information about using Blazor, see [blazor.net](https://blazor.net).

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @SeppPenner!

@apayero If you still think there's a problem, could you please report it to https://github.com/aspnet/AspNetCore/? Thanks.
