### ISSUE TITLE
WebSockets on Apache 

### ISSUE THREAD

**Issue by lKinderBueno** [aspnet/Blazor#1882]
Hi,
Is it possible to have an explanation on how to implement websockets request on apache ?
I have the issue that counter is not working on demo blazor server side and I have to enable websockets (mod_proxy_wstunnel on apache), but I can't figure out what to add on apache configuration

**Comment by lKinderBueno** [comment]
Solved:

`<VirtualHost *:80>
  ServerName www.iptveditor.tk
  ProxyPreserveHost On
  ProxyPass / http://127.0.0.1:5000/
  ProxyPassReverse / http://127.0.0.1:5000/
 
  RewriteEngine on 
  RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC] 
  RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC] 
  RewriteRule /(.*) ws://127.0.0.1:5000/$1 [P]

  ErrorLog <errorLogLocation>/<errorLogFilename>.log
  CustomLog <errorLogLocation>/<customErrorLogFilename>.log common
</VirtualHost>`

**Comment by donhuvy** [comment]
Thank you, your comment is also helpful for the problem at here https://stackoverflow.com/questions/58196221/asp-net-core-3-blazor-run-on-localhost-of-server-ok-but-run-outside-server-err

With Apache 2.4, In `httpd-vhosts.conf`

```xml
<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:5000/
    ProxyPassReverse / http://127.0.0.1:5000/
    ServerName demo.bkit.vn
    ErrorLog ${APACHE_LOG_DIR}webapp1-error.log
    CustomLog ${APACHE_LOG_DIR}webapp1-access.log common
	
	RewriteEngine on
	RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
	RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
	RewriteRule /(.*) ws://127.0.0.1:5000/$1 [P]
</VirtualHost>
```
my Blazor website works.
