### ISSUE TITLE
HttpClient

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#19]
- [ ] Implement browser compatible message handler

**Comment by betimd** [comment]
Could we utilize new 2.1 features - httpclientfactory?

**Comment by danroth27** [comment]
Blazor will support .NET Standard 2.0, so anything that targets .NET Standard 2.0 and can reasonable work in a browser should be fine. We will have support for dependency injection (https://github.com/aspnet/Blazor/issues/80) through which you should be able to get an `HttpClient`. Whether this will be based on the new `HttpClientFactory` is still under investigation, but that's certainly something we are considering.

**Comment by goaty92** [comment]
Does Webassembly offers a way to do networking or will this be Javascript interop? If it's Javascript how will this be implemented with Fetch APIs and/or XHR? My understanding is different browsers support 'fetch' APIs to different extends.

**Comment by danroth27** [comment]
HttpClient will be based on JavaScript interop. Presumably we will use Fetch where we can and fallback to XHR as needed. Regardless, Blazor apps won't have to worry about these details.

**Comment by SteveSandersonMS** [comment]
Just as a note for when we do this properly later, here's an example of implementing an equivalent to HttpClient manually: https://github.com/aspnet/Blazor/issues/142#issuecomment-366941817.

**Comment by SteveSandersonMS** [comment]
Done enough for 0.0.5. Related work items:

 * Add enough JSON support to be useful: https://github.com/aspnet/Blazor/issues/160
 * Switch to standard BCL HttpClient: https://github.com/aspnet/Blazor/issues/159

**Comment by Tealons** [comment]
Just for my understanding: why is HttpClient based on a javascript interop? Does webassembly not support http requests? Is that something to be changed in the future? Or will there be limitations in what webassembly can support in comparison with javascript? From what I read, I thought that webassembly could support everything that javascript is offering?

**Comment by danroth27** [comment]
@Tealons To access browser functionality from WebAssembly you use JavaScript interop. For most browse rAPIs we will provide prebuilt .NET APIs that handle the JavaScript interop for you. Third parties can also provide their own implementations. I'm not aware of any plans for WebAssembly to support a different model.

**Comment by miroslavp** [comment]
Not sure if this is related, but here's what I have found.

https://developer.mozilla.org/en-US/docs/WebAssembly/Concepts

"_By itself, WebAssembly cannot currently directly access the DOM; it can only call JavaScript, passing in integer and floating point primitive data types. Thus, to access any Web API, WebAssembly needs to call out to JavaScript, which then makes the Web API call. Emscripten therefore creates the HTML and JavaScript glue code needed to achieve this._"

**Note:** There are future plans to [allow WebAssembly to call Web APIs directly.](https://github.com/WebAssembly/gc/blob/master/README.md)

**Comment by Tealons** [comment]
@danroth27 & @miroslavp Thanks for the explanation. I was hoping that JavaScript could be elimination completely with WebAssembly. However, it seems we will need it to under the hood for the time being.

**Comment by Tealons** [comment]
@miroslavp I found the following thread with help of your comment. It contains a nice explanation in more detail what currently is possible and maybe will be possible in the future: https://github.com/WebAssembly/design/issues/1126

**Comment by danroth27** [comment]
@Tealons While it's true that the Blazor runtime does use some JavaScript under the covers, it's mostly transparent to you when doing Blazor development. You can use HttpClient like any other .NET API and the fact that it's using JavaScript under the covers is an implementation detail.

I would also say that it's not a goal for Blazor to eliminate JavaScript. Instead our goal is to introduce .NET as a simple and productive alternative for client-side web development. I think this is similar to how managed runtimes like .NET/Java/Python made development easier for a variety of scenarios, but didn't eliminate native development in C/C++. Each of these technologies has their place.
