### ISSUE TITLE
Developing Azure DevOps extension in Blazor 

### ISSUE THREAD

**Issue by tomview** [aspnet/Blazor#1909]
Perhaps users here are interested to follow the discussions on ["Developing Azure DevOps extension using Blazor"](https://github.com/aspnet/AspNetCore/issues/14794#issue-503576929)

**Comment by pranavkm** [comment]
Hi @tomview, issues filed in this repo are not tracked. If you think there's an issue to investigate, please file a new issue in https://github.com/aspnet/AspNetCore
