### ISSUE TITLE
Built in push notification system / service planned?

### ISSUE THREAD

**Issue by oppahansi** [aspnet/Blazor#211]
Hi,

is there anything planned towards Blazor having a built in push notification system / service?

I hope I am not asking not quite clever questions here, I am a bit unfamiliar with push notification systems and from what I have seen so far there are multiple ways to implement it.

I have seen examples of how SignalR or PushSharp was used to implement it but maybe it would be cool to have such functionality built in to make it as easy as possible to use and not rely on additional dependencies?

Cheers

**Comment by SteveSandersonMS** [comment]
Great question!

We're keen to ensure that SignalR works well for Blazor client apps (see #20). To your point, it is another dependency, but I'd hope that if the APIs line up well enough then there's no significant friction - you just install SignalR via NuGet and carry on with your work :)
