### ISSUE TITLE
Allow arbitrary attributes on component tag helpers

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#214]
Currently you can't write `<NavLink href="/url">Click me</NavLink>`, because `href` isn't defined explicitly as a param on `NavLink` and we treat it as a compiler error.

However we should allow all attributes, because components can retrieve all their params at runtime and do things will them. For example, `NavLink` passes through all unrecognised params onto the `<a>` tag it renders.

**Comment by SteveSandersonMS** [comment]
Implemented in #227

**Comment by michaelvolz** [comment]
The idea is excellent. 
At the moment I still can't add additional attributes to my components without error. 
`System.InvalidOperationException: Object of type '<componentname>' does not have a property matching the name '<attribute-name>'.`

Is this by design?

**Comment by Andrzej-W** [comment]
@michaelvolz I haven't used Blazorstrap and I don't know if it is up-to-date, but you can look here
https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/DynamicElement.cs
Example usage of DynamicElement
https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/BlazorButton.cshtml
Maybe @chanan can help.

**Comment by michaelvolz** [comment]
@Andrzej-W I just meant this, no more:

> However we should allow all attributes, because components can retrieve all their params at runtime and do things will them.

**Comment by chanan** [comment]
BlazorStrap is indeed up to date (At the time of writing this comment its Blazor 0.7). However, DynamicElement isn't the the code I would use (And now that I look at it I will update it). The latest recommendation from @SteveSandersonMS is here: https://github.com/aspnet/Blazor/issues/1659#issuecomment-437944981
I implemented this in my project Blazorous to incorporate some of the ideas from the previous way and you can find it here: https://github.com/chanan/Blazorous/blob/master/src/Blazorous/Dynamic.cs

Hope some of that helps.
