### ISSUE TITLE
Azure Function Proxy - Blazor

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#215]
I've compiled and uploaded a Blazor application to Azure blob storage and configured a Azure Functions Proxy to allow the download of the files; however the browse is failing to execute the resulting downloaded assemblies ?  I'm unable to find out why this may be ?

**Comment by veikkoeeva** [comment]
@grahamehorner Just to be sure, have you checked what the browser developer tools indicate? Also, the various browsers seem to indicate errors at varied level of detail, so you might want to try them all (I've found in general Firefox gives the most information).

**Comment by danroth27** [comment]
Without the error output from the browser there's not much we can do here. If you could please provide the browser output (what got downloaded, console error output, etc.) we'd be happy to take a look.
