### ISSUE TITLE
JSON parsing doesn't handle DateTimeOffset with timezone

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#218]
Currently for `DateTimeOffset`, SimpleJson has:

    DateTimeOffset.ParseExact(str, Iso8601Format, CultureInfo.InvariantCulture, ...

But the `Iso8601Format` value doesn't allow for timezone offsets, so it can't `ParseExact`.

We should amend SimpleJson for `DateTimeOffset` in the same way we did for `DateTime` to make it more flexible about incoming formats.

**Comment by danroth27** [comment]
@JamesNK What if we had a dev who was really good at JSON parsing and wanted to make the web a better place . . . 😃

**Comment by JamesNK** [comment]
What's a JSON?
