### ISSUE TITLE
C# expressions in attributes with hyphens don't compile

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#219]
In a cshtml file, try `<div data-something="@someValue"></div>`

**Comment by rynowak** [comment]
I imagine this is a bug in the node writer logic. If you think we're close to removing support for the temporary `<c:Foo>` syntax, I'd prefer to do that first.

I have a PR out for https://github.com/aspnet/Blazor/issues/214 now.

**Comment by rynowak** [comment]
I can confirm that this does reproduce easily though

**Comment by SteveSandersonMS** [comment]
@rynowak I know this is assigned to you, and maybe you're addressing it as part of the `bind` work, but would it be OK if I put in a fix for this? It would help with some sample stuff I'm doing.

**Comment by rynowak** [comment]
Go ahead, I don't think I can get to this before monday

**Comment by davidnmbond** [comment]
Has this one been closed because there is a temporary workaround?  If so, it should be re-opened.

This still doesn't compile:

	<span class="input-group-text" data-container="body" data-toggle="popover" data-placement="left" data-content="@HelpText">?</span>

**Comment by rynowak** [comment]
Hi @davidnmbond - we know of an issue specifically with `data-` attributes that we're tracking at https://github.com/aspnet/Blazor/issues/297

You can work around that for now by using `data_`. 

If that doesn't resolve your problem please open a new issue and provide details so we can investigate.
