### ISSUE TITLE
Http GetJson does not support List<T> as the cast type

### ISSUE THREAD

**Issue by xximjasonxx** [aspnet/Blazor#225]
Example code:
```csharp
Results = await Http.GetJsonAsync<List<TweetResult>>($"/api/Tweets/{parameters["term"]}");
```

This crashes with the following error:
WASM: [System.Reflection.TargetParameterCountException] Number of parameters specified does not match the expected number.
MonoPlatform.ts:169:28

Changing it to:
```csharp
Results = await Http.GetJsonAsync<TweetResult[]>($"/api/Tweets/{parameters["term"]}");
```

Corrected the problem.

Cheers.

**Comment by CXuesong** [comment]
It seems that there are some problems with `PocoJsonSerializerStrategy.DeserializeObject` when constructing `List<T>`. Let me propose a PR for it.

**Comment by xximjasonxx** [comment]
Cheers. I can test it if you want.
