### ISSUE TITLE
Fix build warnings with custom Razor SDK

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#240]
@pranavkm, were you looking at this? Were you able to repro it based on the sample I sent? Thanks!

```
C:\Users\username\Desktop>dotnet new blazor -o blazorapp2
The template "Blazor (standalone)" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on blazorapp2\blazorapp2.csproj...
<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(25,3)>: warning MSB4011: "<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props>" cannot be imported again. It was already imported at "<C:\Users\username\.nuget\packages\microsoft.net.sdk.razor\2.1.0-preview2-30230\Sdk\Sdk.props (18,3)>". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj]
<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(27,3)>: warning MSB4011: "C:\Users\username\.nuget\packages\microsoft.net.sdk.razor\2.1.0-preview2-30230\Sdk\Sdk.props" cannot be imported again. It was already imported at "C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj". This is most likely a build authoring error. This subsequent import will be ignored.
<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.targets(14,3)>: warning MSB4011: "<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets>" cannot be imported again. It was already imported at "<C:\Users\username\.nuget\packages\microsoft.net.sdk.razor\2.1.0-preview2-30230\Sdk\Sdk.targets (14,3)>". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj]
<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.targets(16,3)>: warning MSB4011: "C:\Users\username\.nuget\packages\microsoft.net.sdk.razor\2.1.0-preview2-30230\Sdk\Sdk.targets" cannot be imported again. It was already imported at "C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj". This is most likely a build authoring error. This subsequent import will be ignored.
<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(25,3)>: warning MSB4011: "<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props>" cannot be imported again. It was already imported at "<C:\Users\username\.nuget\packages\microsoft.net.sdk.razor\2.1.0-preview2-30230\Sdk\Sdk.props (18,3)>". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj]
<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(27,3)>: warning MSB4011: "C:\Users\username\.nuget\packages\microsoft.net.sdk.razor\2.1.0-preview2-30230\Sdk\Sdk.props" cannot be imported again. It was already imported at "C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj". This is most likely a build authoring error. This subsequent import will be ignored.
<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.targets(14,3)>: warning MSB4011: "<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets>" cannot be imported again. It was already imported at "<C:\Users\username\.nuget\packages\microsoft.net.sdk.razor\2.1.0-preview2-30230\Sdk\Sdk.targets (14,3)>". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj]
<C:\Program Files\dotnet\sdk\2.1.300-preview2-008315\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.targets(16,3)>: warning MSB4011: "C:\Users\username\.nuget\packages\microsoft.net.sdk.razor\2.1.0-preview2-30230\Sdk\Sdk.targets" cannot be imported again. It was already imported at "C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj". This is most likely a build authoring error. This subsequent import will be ignored.
  Restoring packages for C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj...
  Restoring packages for C:\Users\username\Desktop\blazorapp2\blazorapp2.csproj...
  Generating MSBuild file C:\Users\username\Desktop\blazorapp2\obj\blazorapp2.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\username\Desktop\blazorapp2\obj\blazorapp2.csproj.nuget.g.targets.
  Restore completed in 443.31 ms for C:\Users\username\Desktop\blazorapp2
```

**Comment by pranavkm** [comment]
Just got around to looking at it. Like @rynowak said, the issue is that `Microsoft.NET.Sdk.Web` already has an implicit reference to `Microsoft.NET.Sdk.Razor`. Adding an additional Sdk reference to a specific version of the Razor Sdk produces the build warnings. Making the warnings go away would require changing the Web.Sdk to add some conditional import behavior. We could address that in preview2 if this is a scenario we want to support. Microsoft.NET.Sdk would have the same issue if it was explicitly imported along with Web.Sdk. 

The alternative which is what I'd sort of originally designed before the advent of Sdk resolvers was to replace the Sdk reference with a `PackageReference` to `Microsoft.NET.Sdk.Razor` package

`<PackageReference Include="Microsoft.NET.Sdk.Razor" Version="2.1.0-preview2-30230" PrivateAssets="All" />`. This should use the right Razor Sdk and you wouldn't see the warning.

cc @vijayrkn

**Comment by SteveSandersonMS** [comment]
OK great - thanks! I'll change the templates to use PackageReference for that.

**Comment by pranavkm** [comment]
Wanted to confirm something - are you going to require the 2.1.0-preview2 sdk? Referencing the package by itself would not work if you're targeting the RTM (2.0.0) sdk.

**Comment by danroth27** [comment]
For our 0.1.0 release we can only require a .NET Core SDK version that has shipped in some way. .NET Core 2.0 SDK would be ideal. Requiring 2.1 Preview1 would be fine. Requiring 2.1 Preview2 doesn't work, because it hasn't shipped yet.

**Comment by pranavkm** [comment]
Ok. So having it specifically import the Sdk, the way it's currently doing is the only way to make this work. The PackageReference doesn't help with shipped Sdks.

**Comment by rynowak** [comment]
>  .NET Core 2.0 SDK would be ideal. 

This will not be possible. It has to be preview1 or newer because that's the version that knows how to acquire SDKs via nuget.

**Comment by danroth27** [comment]
Preview1 is fine. How should acquisition of the Razor SDK work for 0.1.0? Right now our templates pull packages from MyGet, but typically for an official preview we pull from NuGet. Presumably the version of the Razor SDK we need isn't on NuGet yet, correct?

**Comment by rynowak** [comment]
The Razor SDK that has all of the features we need will ship in preview2. Beyond that, I don't have a lot of clarity to offer you. This work all depends on other things that are being worked on.

**Comment by danroth27** [comment]
@Eilon @DamianEdwards Could we push a preview1 version of the Razor SDK to NuGet in advance of shipping preview2?

**Comment by Eilon** [comment]
I leave it to @DamianEdwards . I have no particular issue with it, but I'd like to understand in technical terms what we would have to do to make that happen.

**Comment by SteveSandersonMS** [comment]
@pranavkm Am I understanding correctly then that the `<PackageReference>` workaround isn't a viable way to make all the build warnings disappear? Can you propose any other way we can avoid all those build warnings?

**Comment by pranavkm** [comment]
If you're referencing the preview1 Sdk, you wouldn't see the warning. Since that seems to be the Sdk we're attempting to target, the template in it's current format should work. Once preview2 Sdk becomes available, we'd tell users to install it and remove the explicit reference to the Razor Sdk. Does that help?

**Comment by SteveSandersonMS** [comment]
@pranavkm I'm not doing a great job of understanding this. Could you suggest what you think we should change in the code, for example as a PR?

**Comment by SteveSandersonMS** [comment]
Reopening. Although the warnings aren't present when you build with Korebuild, they are still present when you build an actual Blazor app outside this repo.

@pranavkm Any chance you could look at this further? If you know what's going on, are you able to suggest a specific change to the code (either in Blazor itself, or in the project templates) that eliminates the slew of warnings? Or is there some specific version of the .NET SDK that people need to install (I'm using 2.1.300-preview2-008322 and do get the warnings)?

If you want a repro case, you can use the same project I emailed to you before, optionally updating the Blazor package references to an up-to-date version such as 0.1.0-preview1-10092.

**Comment by SteveSandersonMS** [comment]
This is now resolved for the preview1 SDK. There's a separate issue (#273) for the equivalent for preview2.

**Comment by salahuddin-thetasolutions** [comment]
> Preview1 is fine. How should acquisition of the Razor SDK work for 0.1.0? Right now our templates pull packages from MyGet, but typically for an official preview we pull from NuGet. Presumably the version of the Razor SDK we need isn't on NuGet yet, correct?

**Comment by Eilon** [comment]
**Hi, it looks like you are   posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:

1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem.
