### ISSUE TITLE
Latest code containins IE 11 unsupported changes

### ISSUE THREAD

**Issue by vibeeshan025** [aspnet/Blazor#260]
Previuosly the documents stated that the blazor will work with old browsers using a fallback mechanism to work using ASM.js., but last few releaes doesn't work on IE11 or some old chrome versions.

Please define what are the minimum supported versions of browsers, or is it going to be supported in the futures.

**Comment by SteveSandersonMS** [comment]
We will support IE11, as there's nothing fundamental to Blazor that won't work there.

All that's missing is polyfills to cover things that IE11 lacks, such as `Promise` and newer `Math` functions like `fround` and `imul`. We'll add something to the templates later that makes it easy to bring in those polyfills, but it's not something we're focused on during the current phase.
