### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by dbettin** [aspnet/Blazor#264]
Sorry if this doesn't belong here.  This is a nascent project. It would be great to start building a community around it. 

- Weekly standups
- Slack Channel
- Blog
- ????

**Comment by SteveSandersonMS** [comment]
Totally. We do already have a Gitter page at https://gitter.im/aspnet/Blazor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge and will consider some of the other items as we go on.

For standups and blog, we're part of ASP.NET so are putting things on the ASP.NET blog and giving updates in the ASP.NET community standup. We might consider different, dedicated channels as things go on also.

@danroth27 Anything to add here?

**Comment by danroth27** [comment]
We certainly are interested in creating a community and ecosystem around Blazor and we appreciate any suggestions folks have. 

For real-time chat with the community and the team we are using [Gitter](https://gitter.im/aspnet/blazor).

Weekly updates might be a bit much for us to take on at this point, but we do plan to use the [ASP.NET Community Standup](https://live.asp.net) and the [ASP.NET team blog](https://blogs.msdn.microsoft.com/webdev) to provide updates.

All of our planning and progress on Blazor is being handled publicly on GitHub. We plan to do the same for the [Blazor docs](https://github.com/aspnet/Docs/issues/5678).

If you have more ideas, let us know!

**Comment by stavroskasidis** [comment]
Maybe after the project reaches a preview/rc/beta/whatever state, there could be a "Blazor Community Standup" or something. Maybe not weekly, but at least something regular (e.g. every month or 2-3 weeks)

**Comment by SteveSandersonMS** [comment]
Lots of good ideas here - thanks!

Please feel free to continue the discussion. I'll mark the issue closed since it's not an outstanding work item to be tracked, but that doesn't stop anyone from posting.
