### ISSUE TITLE
Blazor project template fails to build: Unable to find package Microsoft.AspNetCore.SpaServices.Extensions

### ISSUE THREAD

**Issue by ncarandini** [aspnet/Blazor#267]
### Repro steps:
Install Visual Studio 2017 15.6.2
Install the latest .NET Core SDK nightly from https://github.com/dotnet/cli
Install Blazor extension from MyGet
Create Blazor app

### Result:
Restore failed, but oddly enough the build process succeeded.

### Here is the Output list:
NU1101: Unable to find package Microsoft.AspNetCore.SpaServices.Extensions. No packages exist with this id in source(s): https://dotnet.myget.org/f/blazor-dev/api/v3/index.json
NuGet package restore failed. Please see Error List window for detailed warnings and errors.

#### After rebuilding:
1>------ Rebuild All started: Project: WebApplication1, Configuration: Debug Any CPU ------
1>C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj : warning MSB4241: The SDK reference "Microsoft.NET.Sdk.Razor" version "2.1.0-preview2-30230" was resolved to version "2.1.300-preview2-008354" instead.  You could be using a different version than expected if you do not update the referenced version to match.
1>C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj : warning MSB4240: Multiple versions of the same SDK "Microsoft.NET.Sdk.Razor" cannot be specified. The SDK version "2.1.300-preview2-008354" already specified by "C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj" will be used and the version "2.1.0-preview2-30230" will be ignored.
1>C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj : warning MSB4240: Multiple versions of the same SDK "Microsoft.NET.Sdk.Razor" cannot be specified. The SDK version "2.1.300-preview2-008354" already specified by "C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj" will be used and the version "2.1.0-preview2-30230" will be ignored.
1>C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(25,3): warning MSB4011: "C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk.Razor\Sdk\Sdk.props (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj]
1>C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props(27,3): warning MSB4011: "C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk.Razor\Sdk\Sdk.props" cannot be imported again. It was already imported at "C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj". This is most likely a build authoring error. This subsequent import will be ignored.
1>C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj : warning MSB4240: Multiple versions of the same SDK "Microsoft.NET.Sdk.Razor" cannot be specified. The SDK version "2.1.300-preview2-008354" already specified by "C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj" will be used and the version "2.1.0-preview2-30230" will be ignored.
1>C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.targets(14,3): warning MSB4011: "C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk.Razor\Sdk\Sdk.targets (14,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj]
1>C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.targets(16,3): warning MSB4011: "C:\Program Files\dotnet\sdk\2.1.300-preview2-008354\Sdks\Microsoft.NET.Sdk.Razor\Sdk\Sdk.targets" cannot be imported again. It was already imported at "C:\git\BlazerLab\WebApplication1\WebApplication1\WebApplication1.csproj". This is most likely a build authoring error. This subsequent import will be ignored.
1>You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://docs.microsoft.com/en-us/dotnet/core/tools/global-json
1>WebApplication1 -> C:\git\BlazerLab\WebApplication1\WebApplication1\bin\Debug\netstandard2.0\WebApplication1.dll
1>Writing index to: C:\git\BlazerLab\WebApplication1\WebApplication1\obj\Debug\netstandard2.0\blazor\index.html
1>Blazor Build result -> 37 files in C:\git\BlazerLab\WebApplication1\WebApplication1\bin\Debug\netstandard2.0\dist
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

#### Please note that the rebuild process succeeded!
This is really odd, why the build succeeded if the NuGet restore failed?

#### In fact, starting with F5, the browser is launched but after a small wait we receive an error:
HTTP Error 502.5 - Process Failure

**Comment by ncarandini** [comment]
Uhm... maybe I can't use the VS 2017 15.6.2 with latest dotnet SDK.
On the .NET Core SDK 2.1.300-preview1 download page it states: To use .NET Core 2.1 with Visual Studio, you'll need Visual Studio 2017 15.7 Preview 1 or newer.
So this should be true also for the newer version "2.1.300-preview2-008354" that is served at the time of writing. by the nightly build from https://github.com/dotnet/cli.

**Comment by ncarandini** [comment]
Closed too early, I've installed the VS 2017 Preview 15.7.0 Preview 1 and I have the same results.

**Comment by danroth27** [comment]
I hit this issue as well helping someone setup their machine. The restore failed for the Razor SDK and the SpaServices package.

**Comment by danroth27** [comment]
I suspect this is due to an issue with the `<RestoreSources>` change we recently made to the project files.

**Comment by ncarandini** [comment]
Thanks @danroth27, I'll wait for a fix, I can't wait to try Blazer with Bootstrap 4 on an experimental project I'm working on, I really do like Blazor.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this! Have reverted the offending change.

**Comment by ncarandini** [comment]
Hi @SteveSandersonMS, sorry to report the issue has not been solved.

#### This is what I did to try it as clean as possible:
- Removed the latest .NET Core SDK nightly (Preview 2)
- Cleaned my NuGet Packages local cache (`C:\Users\<user>\.nuget\packages`)
- Installed .NET Core SDK 2.1.300-preview1
- Updated ASP.NET Core Blazor Language Services
- Created a brand new Blazor app

#### Result:
The package restore failed and so did the build, with 3 errors about packages not found, 1 duplicate error and 1 warning.

#### Error list:
Error	NU1101	Unable to find package Microsoft.AspNetCore.Blazor.Cli. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
Error	NU1101	Unable to find package Microsoft.AspNetCore.Blazor.Build. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
Error	NU1101	Unable to find package Microsoft.AspNetCore.Blazor.Browser. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

Error		Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'App.cshtml'; 'Pages\Counter.cshtml'; 'Pages\FetchData.cshtml'; 'Pages\Index.cshtml'; 'Pages\_ViewImports.cshtml'; 'Shared\MainLayout.cshtml'; 'Shared\NavMenu.cshtml'; '_ViewImports.cshtml'

Warning	NU1603	WebApplication1 depends on Microsoft.AspNetCore.Razor.Design (>= 2.1.0-preview2-30230) but Microsoft.AspNetCore.Razor.Design 2.1.0-preview2-30230 was not found. An approximate best match of Microsoft.AspNetCore.Razor.Design 2.1.0-preview2-30281 was resolved.

### Partial Workaround
I've solved the 3 errors about packages not found adding a new source for NuGet Packages:
`https://dotnet.myget.org/F/blazor-dev/api/v3/index.json`.

But this didn't solved the duplicate content error.
So I do think this issue should be reopened.

Thanks for all your work, can't wait to test it even more when I'll be able to build again.

**Comment by SteveSandersonMS** [comment]
@ncarandini Thanks for reporting this! Resolved with https://github.com/aspnet/Blazor/pull/325

**Comment by SteveSandersonMS** [comment]
@ncarandini Thanks for the update.

It seems we will have to go back to the `RestoreSources` in the `.csproj` files. The workaround of moving the `NuGet.config` into the solution directory doesn't work in this case because of an issue with `dotnet new` creating two `.sln` files. We'll write this up separately and try to get that fixed.

I don't know why some people have had issues with the `RestoreSources` mechanism, but I'll try to repro any possible issues before we release.

**Comment by SteveSandersonMS** [comment]
@ncarandini Thanks again for letting us know. In the end we didn't find any good solution that would let us keep the packages on an external feed (e.g., MyGet), so for the 0.1.0 release we opted to push the packages to NuGet.org instead. This should take care of people who just want to build Blazor apps using the project templates.

Our `dev` branch continues to point to `MyGet` so it will continue to require a restore from the command line. However that should be OK because people always have to run `build.cmd`/`build.sh` for their first build anyway when working on `Blazor.sln` itself.

**Comment by ncarandini** [comment]
Hi @SteveSandersonMS thanks and good to know, as I'm writing right now a post on how to install Blazor.

**Comment by austinwil24** [comment]
Including <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" /> in the Server csproj fixed my issue with 502.5 error
