### ISSUE TITLE
Strange behavior in events

### ISSUE THREAD

**Issue by uazo** [aspnet/Blazor#275]
Example:

    @for( var page = FirstPage; page <= LastPage; page++ )
    {
    	<li class="@(this.Values.CurrentPage==page ? "active" : "page-item")">
    		<a href="javascript:;" class="page-link" @onclick(() => InvokePageChanged(page))>@(page+1)</a>
    	</li>
    }

The value of "Page" in InvokePageChanged is always "LastPage".

The only way to make it work is:

    @for( var page = FirstPage; page <= LastPage; page++ )
    {
    	int current = int.Parse(page.ToString());
    	<li class="@(this.Values.CurrentPage==page ? "active" : "page-item")">
    		<a href="javascript:;" class="page-link" @onclick(() => InvokePageChanged(current))>@(page+1)</a>
    	</li>
    }

**Comment by rstropek** [comment]
As far as I can see, only your working solution turns the lambda function invoking `InvokePageChanged` into a closure capturing the value of `page`. See e.g. [this StackOverflow post](https://stackoverflow.com/questions/271440/captured-variable-in-a-loop-in-c-sharp) for a more detailed description of the topic.

Does that help?

**Comment by uazo** [comment]
I had already tried with

    @for( var page = FirstPage; page <= LastPage; page++ )
    {
    	int current = page;
    	<li class="@(this.Values.CurrentPage==page ? "active" : "page-item")">
    		<a href="javascript:;" class="page-link" @onclick(() => InvokePageChanged(current))>@(page+1)</a>
    	</li>
    }

but it does not work..

the only way is to turn it into a string.
Maybe some optimization of the compiler?

**Comment by rstropek** [comment]
Hmm, I tried that and it worked:

```cs
@for (var page = 0; page <= 5; page++)
{
    var helper = page;
    <button @onclick(() => InvokePageChanged(helper))>@(helper)</button>
}

@functions {
    void InvokePageChanged(int page)
    {
        Console.WriteLine(page);

    }
}
```

I also expected it to work because the generated code looks like that:

```cs
...
for (var page = 0; page <= 5; page++)
{
    var helper = page;
    ...
    builder.AddAttribute(13, onclick(() => InvokePageChanged(helper)));
    ...
}
...
```

**Comment by SteveSandersonMS** [comment]
Yes, I also just tried that and confirmed it works OK. There's no need to do the conversion to string and back again.

The necessity to declare a variable inside your loop is just how C# lambdas work - they bind to a variable, not to the value that was in the variable when the lambda was constructed. [The StackOverflow that @rstropek linked to](https://stackoverflow.com/questions/271440/captured-variable-in-a-loop-in-c-sharp) is a good source of info about this.
