### ISSUE TITLE
WASM: Mono: Warning: Degraded allocation.

### ISSUE THREAD

**Issue by uazo** [aspnet/Blazor#276]
Whats about?

    WASM: Mono: Warning: Degraded allocation.  Consider increasing nursery-size if the warning persists.
    WASM: Mono: GC_MINOR: (Nursery full) time 1.20ms, stw 1.20ms promoted 147K major size: 1152K in use: 427K los size: 1024K in use: 528K
    WASM: Mono: GC_MINOR: (Nursery full) time 0.50ms, stw 0.50ms promoted 12K major size: 1472K in use: 777K los size: 1024K in use: 885K

what does it mean?

**Comment by SteveSandersonMS** [comment]
It just means the GC ran. It's not a problem. The phrasing is a bit scary so at some point we'll discuss changing this with the Mono folks.

**Comment by kumpera** [comment]
I assume the interesting line is the first one.

`WASM: Mono: Warning: Degraded allocation.  Consider increasing nursery-size if the warning persists.`

This signals that the GC young generation got full and we're scheduling a collection on the next animation frame. This warning is a collateral of how we implemented GC support on mono.
It's definitely misleading and I'll change the runtime so it doesn't show up.

**Comment by adospace** [comment]
In my tests anyway seems that just after Mono signals this warning the entire application is deallocated/GCed  from memory and restarted.
I mean, if I put a `Console.WriteLine("Program.Main")` in Program.Main(args) this is the log I see:
```
WASM: Program.Main
WASM: Load UserService
WASM: ...other console messages
WASM: Mono: Warning: Degraded allocation.  Consider increasing nursery-size if the warning persists.
WASM: Mono: GC_MINOR: (Nursery full) time 0.80ms, stw 0.80ms promoted 174K major size: 1888K in use: 1223K los size: 2048K in use: 961K
WASM: .. some other console messages
WASM: Program.Main <------ APP IS RESTARTED!
WASM: Load UserService
WASM: etc...
```
This of course causes many issues: i.e. DI singleton services are disposed losing their state.
Do you have any hint?

**Comment by kumpera** [comment]
@adospace It makes sense to investigate you issue, but I'm not so sure that the GC is the culprit here.

**Comment by adospace** [comment]
Problem is reproducible running this sample project (https://github.com/adospace/blazor-realworld-example-app), verified on edge, chrome and FF.

**Comment by adospace** [comment]
@kumpera given the status of Blazor (still in preview) I suppose that it's even possible that issue (app restarting) is caused by an exception/error caused by user code (mine) not properly reported. 
I mean completely unrelated with mono.
