### ISSUE TITLE
question: C# library to WebAssembly for usage in JS/TS

### ISSUE THREAD

**Issue by eriklieben** [aspnet/Blazor#287]
Is it also possible to use Blazor to generate a web assembly file that could be used from the browsers JavaScript? Without the Blazor SPA bootstrap, router code, etc?

Like for example: if I have a C# lib that contains string check functions that I use in my dotnet Core webAPI and I want to share that logic (without writing it once in TS and once in C#) with my app that runs a JavaScript SPA so that my app is able to function as PWA and perform the string check logic without sending it back to the server for checking (for example in the case where I am offline and can't ask the server to perform the string check logic because it's unreachable).

Thanks,

Erik

**Comment by mattyas** [comment]
Funny, I had the exact same thought today, would it be possible to set up Blazor as a service/component or other way so that you car reach it from JS/TS.  The step to move an existing app to Blazor is a big one, the step to reuse the shared logic between frontend and backend is not as big and would be a great benefit.

**Comment by grahamehorner** [comment]
I do believe that I've seen a few open source tools that take ILASM and convert them to WASM but I've not personally tried these; I'll hunt a link out for you

**Comment by grahamehorner** [comment]
FYI, https://github.com/kg/ilwasm

**Comment by mattyas** [comment]
It looks like we should be able to talk to Blazer from TS/JS, just need to figure out exactly how to get a function from a .NET Standard dll. https://developer.mozilla.org/en-US/docs/WebAssembly/Exported_functions

**Comment by grahamehorner** [comment]
@mattyas have a look at the findMethod & callMethod in the Browse.JS projects

**Comment by SteveSandersonMS** [comment]
Yes, it's totally possible to call .NET from JS (using the `findMethod`/`callMethod` APIs that @grahamehorner mentioned), and to avoid doing normal Blazor app rendering (by not putting any logic in your `Program::Main` method).

There isn't a way of stripping out the Blazor code itself, but TBH, the size of the Blazor libraries is pretty much negligible compared to the much larger overhead of bringing in an entire .NET runtime anyway.

Bear in mind that bringing in a Mono/WebAssembly runtime will add a minimum of about 700KB to your app size, so until we optimise this much further, it's not ideal for most library scenarios. It makes more sense for complete apps, which is the scenario Blazor is focused on.
