### ISSUE TITLE
Question: does the dev branch actually work?

### ISSUE THREAD

**Issue by uazo** [aspnet/Blazor#289]
first of all, thank you very much for the excellent work you are doing!

Given that I'm using VS 15.6.2 (not the 15.7 Preview 1, I can not install a preview in my machine used for production), the App.cshtml is generated in this way

            builder.AddContent(0, "\n");
            builder.OpenElement(1, "router");  
            builder.AddAttribute(2, "appassembly", "typeof(StandaloneApp.Program).Assembly");
            builder.CloseElement();
            builder.AddContent(3, "\n");

the result is a blank page ...

Starting build.cmd instead the result is the expected one

            builder.AddContent(0, "\n");
            builder.OpenComponent<Microsoft.AspNetCore.Blazor.Routing.Router>(1);
            builder.AddAttribute(2, "AppAssembly", typeof(StandaloneApp.Program).Assembly);
            builder.CloseComponent();
            builder.AddContent(3, "\n");

**Comment by SteveSandersonMS** [comment]
Sorry, but 15.7 is strictly required. The Blazor tooling hooks into new APIs added in 15.7.

**Comment by uazo** [comment]
OK thank you very much. I'll wait for it to come out of the preview...

**Comment by rynowak** [comment]
@uazo - I'm curious to know - is there a reason why using the preview is a problem for you?

The tooling is very much a work in progress and we expect to continue to make it better for a long time, which means that the non-preview support for Blazor in VS is going to age pretty rapidly.

**Comment by uazo** [comment]
as he read

"This release is not "go-live" and not intended for use on production computers or for creating production code."

my it manager does not want ..
