### ISSUE TITLE
Catch all route in Routing

### ISSUE THREAD

**Issue by struks93** [aspnet/Blazor#290]
Hi, maybe I'm missing it somewhere, but I did not see a raised issue regarding this before. Are there any thoughts of a wildcard like routing implementation for `404` pages and the like? My idea was something along the likes of a reserved wildcard decorator in routing table that kicks in if no other route is valid and a template with, let's say, `@page "*"` is present. But maybe there is something in the works already :).

**Comment by SteveSandersonMS** [comment]
It's a good point - thanks for raising it!

There are several routing features we'll want to add, so I've filed a new issue to track them all: #293. Closing this one in favor of that one.
