### ISSUE TITLE
Question: How is edit & continue supposed to work?

### ISSUE THREAD

**Issue by gingters** [aspnet/Blazor#299]
Hi, I'm currently looking into Blazor, and in the NDC prototype video I saw that it *should* be possible to edit a component, save it, and at saving have Roslyn compile and update the assembly directly in the background and then a simple browser-reload should execute the changed component.

However, I don't seem to be able to replicate this workflow with my local installation.
I even tried to manually recompile the project, but the dev server does not seem to pick up the new assembly when I reload in the browser. So to see my changes I deed to stop and restart the dev server.

So my question is, what am I missing here?

Additional info: I installed 15.7.0 Preview 1 of VS and installed the Blazor tooling vsix compiled from the develop branch into that. So all I did is based on the VS preview build.

**Comment by struks93** [comment]
I think that live reloading is not working at the moment - [Issue #5](https://github.com/aspnet/Blazor/issues/5), but it looks like it should be resolved soon in [PR #193](https://github.com/aspnet/Blazor/pull/193)

**Comment by SteveSandersonMS** [comment]
That's correct - live reloading just isn't implemented yet. It won't be included in the upcoming 0.1.0 release, but we are regarding it as a priority to add as soon as we can after that.

**Comment by SteveSandersonMS** [comment]
> I even tried to manually recompile the project, but the dev server does not seem to pick up the new assembly when I reload in the browser.

It should certainly update after you have recompiled. Maybe you have a browser caching issue. Could you try opening your browser's dev tools and checking the "disable cache" button, and then reloading while you have cache disabled?

Firefox:
![image](https://user-images.githubusercontent.com/1101362/37659567-3f149cfc-2c48-11e8-9a56-2f6ee2ea14c0.png)

Chrome:
![image](https://user-images.githubusercontent.com/1101362/37659595-4fa0b0a6-2c48-11e8-8acf-6c8199f608fa.png)

Edge:
![image](https://user-images.githubusercontent.com/1101362/37659638-69550420-2c48-11e8-97e8-6b5556df141b.png)

**Comment by gingters** [comment]
Ah, that helped indeed. So while the dev server is running, I now can edit the components, save & recompile, and reload the browser to see the changes. Great.
But yes, a real live-reload like demoed on the prototype would be super powerful.
