### ISSUE TITLE
Blazor extension error in VS

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#308]
When working with the Blazor standalone template I ran into the following error in VS.

![blazor-extension-error](https://user-images.githubusercontent.com/1874516/37694818-6afd2886-2c87-11e8-8832-59697e0eff90.png)

[ActivityLog.zip](https://github.com/aspnet/Blazor/files/1832064/ActivityLog.zip)

[BlazorApp1.zip](https://github.com/aspnet/Blazor/files/1832065/BlazorApp1.zip)

Blazor VSIX version: 15.6.610118

@rynowak

**Comment by rynowak** [comment]
/cc @alexgav - can you take a look at this? 

System.TimeoutException: The operation has timed out.&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.ContainedLanguage.Server.ProjectKServerContainedLanguageSupport.OnIdle(Object sender, EventArgs e)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

This is coming from WTE.

I'm not sure what might be causing your idle support to timeout...

**Comment by rynowak** [comment]
@danroth27 is this on 15.7-preview1?

**Comment by danroth27** [comment]
I believe so. I haven't seen it happen again though.

**Comment by danroth27** [comment]
@alexgav Looks like a VS issue. Can you take a look?

**Comment by Rick-Anderson** [comment]
I hit this several times/week with VS Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035


VisualStudio
2018/06/25 23:40:21.386
809
ERROR
System.TimeoutException: The operation has timed out. at Microsoft.VisualStudio.Html.Package.ContainedLanguage.Server.ProjectKServerContainedLanguageSupport.OnIdle(Object sender, EventArgs e) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by Rick-Anderson** [comment]
@alexgav  this has nothing to do with Blazer. I get this exception working with Razor Pages and no Blazer. Should we close and move this issue?

**Comment by SteveSandersonMS** [comment]
OK, will close. Thanks!
