### ISSUE TITLE
Using the .net core runtime

### ISSUE THREAD

**Issue by greatjack1** [aspnet/Blazor#315]
Was wondering why Balzor is using the heavyweight mono runtime instead of just compiling the .net core runtime to wasm?

**Comment by ChristianWeyer** [comment]
This has been discussed in #286

**Comment by SteveSandersonMS** [comment]
Also for more background on interpreted vs AOT compilation, please see http://blog.stevensanderson.com/2018/02/06/blazor-intro/#running-net-in-the-browser
