### ISSUE TITLE
[Question] How to "Post" on Blazor?

### ISSUE THREAD

**Issue by jonathanperis** [aspnet/Blazor#317]
Hi all!

Please, make an example to us on how to post information on method. The Counter example and FetchData are get examples. Please, guide us making an example posting information on click buttons

Cheers!

**Comment by SteveSandersonMS** [comment]
Please see https://github.com/aspnet/samples/blob/master/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Client/Services/AppState.cs#L35

**Comment by rstropek** [comment]
I also have an example on [learn-blazor.com](https://learn-blazor.com/architecture/rest-api/#sample). It demonstrates HTTP `GET`, `POST`, and `DELETE`.
