### ISSUE TITLE
VSIX metadata issues

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#318]
- [x] Add any remaining license link
- [ ] If possible, prevent installation into VS 15.6 or lower (currently it doesn't stop you, but then won't work)

**Comment by danroth27** [comment]
@rynowak Can you help me out with this?

**Comment by SteveSandersonMS** [comment]
Done in #322.

We can't stop the installation on VS15.6 (the mechanism for doing that doesn't appear to work) so will have to rely on documenting the 15.7 requirement.
