### ISSUE TITLE
Packaging and distribution

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#32]
We need to decide how Blazor is packaged and distributed. Do you only get it through project templates? NuGet? NPM? Something else?

**Comment by gulbanana** [comment]
there will likely be demand for dotnet cli templates

**Comment by dsaf** [comment]
Ideally it would be nice not to have any Node.JS on my machine.

**Comment by greatjack1** [comment]
I think a dotnet cli templates with it being shipped as a nuget package is the way to go

**Comment by danroth27** [comment]
Yes, we are tracking adding project templates, including CLI templates, with https://github.com/aspnet/Blazor/issues/7.

This issue is tracking considering alternative distribution channels for Blazor.

**Comment by dsaf** [comment]
NuGet is absolutely a must in my opinion. Project templates are also good for quick stuff like prototyping, introductory tutorials, public conference presentations etc. Then again I don't know how the whole thing will work together. Also how will WASM-packages be distributed by the general web-dev community? As long as there is a possibility of granular control and frequent updates of references/dependencies more experienced developers should be happy.

**Comment by grahamehorner** [comment]
IMHO NuGet is the correct package and deployment system for Blazor components as the resulting compilation output a set of .net assemblies and a number of assorted assets files, I do think however that the package will need to possibly be distinguished by some meta tagging to differentiate for other packages especially in a large gallery

**Comment by chassq** [comment]
Please via NuGet and project templates. I guess you should support npm but I also want to eventually do away with node and typescript one day if that is ever possible. Keeping new versions of them in sync with the various node-modules has become a PITA... IMHO....

**Comment by danroth27** [comment]
We will have NuGet packages, CLI templates, and Visual Studio extensions.
