### ISSUE TITLE
View/View logic separation

### ISSUE THREAD

**Issue by luetm** [aspnet/Blazor#330]
Will there be a similar system in components like in Angular2, that you can separate the HTML, CSS and logic parts? At the moment, we need to put the logic and the html into the .cshtml, right?

Thanks for the preview, we are exited!

**Comment by RyoukoKonpaku** [comment]
You can right now via ```@implements``` directive.
usage should be like this:
```
// cshtml
@implements CodeBehindClass // Class that will contain login
// View markup
```

Although at the moment you can't use the same name for the class and cshtml since Blazor doesn't support partial classes yet due to design time problems on #294

**Comment by luetm** [comment]
Thanks! We could just use a suffix, like HomeVM or something that makes sense, so I don't think its a dealbreaker that the name can't be identical.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @RyoukoKonpaku!

**Comment by rstropek** [comment]
@luetm Thank you for that question. It motivated me to write [an article+sample on learn-blazor.com about separating view and view-logic](https://learn-blazor.com/architecture/view-logic-separation/). Hopefully, it will help people who are new to Blazor. In the next days, I plan to add more content on this topic.
