### ISSUE TITLE
Question: is it possible to use it as lightweight C# to WASM translator?

### ISSUE THREAD

**Issue by MaceWindu** [aspnet/Blazor#331]
Let's assume we have some complex C# logic, that we need both on server and client and right now our options are:
- expose it as server API. Not viable on extensive use
- duplicate implementation in js and get maitenance nightmare

So, my question is: does blazor support no-ui-stuff-lightweight-mode, or  it will allways bundle razor stuff with runtime?

**Comment by gingters** [comment]
Currently Blazor brings the full Mono client-side .NET Runtime with it (even with all the mono UI stuff you can't even use in the Browser).
Later on, when at some point the Mono linker is capable of stripping off the unused IL or even AOT compilation is implemented, that could be something for your use case.

**Comment by ChristianWeyer** [comment]
Adding to what @gingters said, today you can use mono-wasm as an experimental approach to compile your C# libs to WASM.
See here:
https://github.com/mono/mono/blob/master/sdks/wasm/sample.html
https://github.com/mono/mono/blob/master/sdks/wasm/sample.cs

**Comment by SteveSandersonMS** [comment]
Thanks for the answers!

**Comment by danroth27** [comment]
@gingters We're actually already using the Mono linker to strip unused IL when you build your Blazor app. You can see it happening in the build output. However, we aren't trimming the WASM file yet, and we have some ideas on how to do even more aggressive IL trimming.
