### ISSUE TITLE
Simplify directory structure for hosted template in VS

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#332]
Currently the hosted template produces an unnecessary extra layer in the directory hierarchy:

 * YourApp/
   * YourApp.sln
   * YourApp/             *-- unnecessary*
     * YourApp.Client/
     * YourApp.Server/
     * YourApp.Hosted/

It's different if you run the template from the command line (the Client/Server/Hosted dirs are peer-level with the `.sln`).

To fix this, we need to use the `"isMultiProjectTemplate": true` option in the vs-2017.3 host file. However support for this flag doesn't yet exist in VS, so we should wait until it does before adding it (so we can verify the effect is what we want).

**Comment by rynowak** [comment]
From @phenning 


> By the way, this did make it in for Visual Studio 15.7 Preview 3.

> Add the following to the vs host file. additionalWizardParameters is an additional property bag that the One ASP.NET dialog will pass back to the Wizard code on template creation.

>These parameters are not passed to the template, but instead are intended to control behaviors that potentially apply to all types of templates.  It is akin to specifying wizard parameters directly in vstemplate files – which would be the typical standalone template developer customer scenario.
```
"additionalWizardParameters":
  {
      "$isMultiProjectTemplate$": "true"
  }
```

We can add this to our manifest at any time, and it will start working in VS eventually.

**Comment by SteveSandersonMS** [comment]
@danroth27 If we just put it at the top of the priority list then one of us (probably me) will hopefully get to it by 0.2.0.
