### ISSUE TITLE
Include third party notices in required packages

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#335]
We now have a generic third party notices file for both the repo and our built packages. We should include it in all the packages that carry third party dependencies: 
- VSIX
- template package
- Microsoft.AspNetCore.Blazor.Build
- Microsoft.AspNetCore.Blazor.

**Comment by danroth27** [comment]
@SteveSandersonMS I think we should just get this done. Moving into 0.6.0.

**Comment by SteveSandersonMS** [comment]
@danroth27 Is there an established pattern for how we include TPN in NuGet packages? Just as some extra file within the zip archive, even though nobody would see it? Or do you intend this to be one of those "accept licenses" prompts when installing the package?

**Comment by danroth27** [comment]
@SteveSandersonMS  I think it just needs to be included as content. See https://github.com/aspnet/KestrelHttpServer/commit/c4bf10d6e9d77f75fd2a413c87a6186ac52d3c69 for an example. @Eilon may know more.

**Comment by danroth27** [comment]
Adding @ChrisSfanos as well to advise.

**Comment by Eilon** [comment]
Yes, what Kestrel did in that old commit is fine. It just needs to be in a place where a person can find it. There's definitely no need to "accept" it because it's *not* part of the license. It's just providing attribution to other projects.

**Comment by ChrisSfanos** [comment]
Agree with @Eilon - typically in the same folder/location as the license file(s) is optimal

**Comment by Eilon** [comment]
BTW in the case here the license is just a link, it's not embedded, so it can't be in the same folder. But somewhere in the NUPKG is fine, ideally ending up on disk expanded wherever the NuGet store is on disk. It doesn't need to go to the user's *project*.

**Comment by SteveSandersonMS** [comment]
Great - that's exactly how we've done it in #1441. It is a file in the `.nupkg` but not in any way that interferes with the build or shows up in consuming projects.
