### ISSUE TITLE
Component libraries

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#340]

**Comment by muqeet-khan** [comment]
Prior to 0.1.0, I could create a simple Blazor component library as NetStandard 2.0 with the following:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="0.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Razor.Extensions" Version="0.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.0-preview2-30230" />
    <PackageReference Include="Microsoft.NET.Sdk.Razor" Version="2.1.0-preview2-30230" />
  </ItemGroup>
</Project>
```

Currently cannot compile unless I do not link on build by: 

`<BlazorLinkOnBuild>False</BlazorLinkOnBuild>`

Building without the flag throws error as following:

`Error	MSB3073	The command "dotnet "C:\Users\username\.nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\../tools/illink/illink.dll" -c link -u link -t --verbose  -d "C:\Users\username\.nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\../tools/mono/bcl/" -d "C:\Users\username\.nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\../tools/mono/bcl/Facades/" -o "C:\Users\username\Source\Repos\SamplePageAPI\SamplePageAPI\obj\Debug\netstandard2.0\blazor/linker/" -x "C:\Users\username\.nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Users\username\Source\Repos\SamplePageAPI\SamplePageAPI\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\username\.nuget\packages\microsoft.aspnetcore.blazor\0.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\username\.nuget\packages\microsoft.aspnetcore.blazor.razor.extensions\0.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Razor.Extensions.dll" -a "C:\Users\username\.nuget\packages\microsoft.aspnetcore.razor.language\2.1.0-preview2-30230\lib\netstandard2.0\Microsoft.AspNetCore.Razor.Language.dll" -a "C:\Users\username\.nuget\packages\microsoft.codeanalysis.common\2.6.1\lib\netstandard1.3\Microsoft.CodeAnalysis.dll" -a "C:\Users\username\.nuget\packages\microsoft.codeanalysis.csharp\2.6.1\lib\netstandard1.3\Microsoft.CodeAnalysis.CSharp.dll" -a "C:\Users\username\.nuget\packages\microsoft.codeanalysis.razor\2.1.0-preview2-30230\lib\netstandard2.0\Microsoft.CodeAnalysis.Razor.dll" -a "C:\Users\username\.nuget\packages\system.appcontext\4.3.0\lib\netstandard1.6\System.AppContext.dll" -a "C:\Users\username\.nuget\packages\system.buffers\4.3.0\lib\netstandard1.1\System.Buffers.dll" -a "C:\Users\username\.nuget\packages\system.collections.concurrent\4.3.0\lib\netstandard1.3\System.Collections.Concurrent.dll" -a "C:\Users\username\.nuget\packages\system.collections.immutable\1.3.1\lib\netstandard1.0\System.Collections.Immutable.dll" -a "C:\Users\username\.nuget\packages\system.diagnostics.stacktrace\4.3.0\lib\netstandard1.3\System.Diagnostics.StackTrace.dll" -a "C:\Users\username\.nuget\packages\system.dynamic.runtime\4.3.0\lib\netstandard1.3\System.Dynamic.Runtime.dll" -a "C:\Users\username\.nuget\packages\system.io.filesystem.primitives\4.3.0\lib\netstandard1.3\System.IO.FileSystem.Primitives.dll" -a "C:\Users\username\.nuget\packages\system.linq\4.3.0\lib\netstandard1.6\System.Linq.dll" -a "C:\Users\username\.nuget\packages\system.linq.expressions\4.3.0\lib\netstandard1.6\System.Linq.Expressions.dll" -a "C:\Users\username\.nuget\packages\system.objectmodel\4.3.0\lib\netstandard1.3\System.ObjectModel.dll" -a "C:\Users\username\.nuget\packages\system.reflection.emit\4.3.0\lib\netstandard1.3\System.Reflection.Emit.dll" -a "C:\Users\username\.nuget\packages\system.reflection.emit.ilgeneration\4.3.0\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll" -a "C:\Users\username\.nuget\packages\system.reflection.emit.lightweight\4.3.0\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll" -a "C:\Users\username\.nuget\packages\system.reflection.metadata\1.4.2\lib\netstandard1.1\System.Reflection.Metadata.dll" -a "C:\Users\username\.nuget\packages\system.reflection.typeextensions\4.3.0\lib\netstandard1.5\System.Reflection.TypeExtensions.dll" -a "C:\Users\username\.nuget\packages\system.runtime.numerics\4.3.0\lib\netstandard1.3\System.Runtime.Numerics.dll" -a "C:\Users\username\.nuget\packages\system.security.cryptography.openssl\4.3.0\lib\netstandard1.6\System.Security.Cryptography.OpenSsl.dll" -a "C:\Users\username\.nuget\packages\system.security.cryptography.primitives\4.3.0\lib\netstandard1.3\System.Security.Cryptography.Primitives.dll" -a "C:\Users\username\.nuget\packages\system.text.regularexpressions\4.3.0\lib\netstandard1.6\System.Text.RegularExpressions.dll" -a "C:\Users\username\.nuget\packages\system.threading\4.3.0\lib\netstandard1.3\System.Threading.dll" -a "C:\Users\username\.nuget\packages\system.threading.tasks.extensions\4.3.0\lib\netstandard1.0\System.Threading.Tasks.Extensions.dll" -a "C:\Users\username\.nuget\packages\system.threading.tasks.parallel\4.3.0\lib\netstandard1.3\System.Threading.Tasks.Parallel.dll" -a "C:\Users\username\.nuget\packages\system.threading.thread\4.3.0\lib\netstandard1.3\System.Threading.Thread.dll" -a "C:\Users\username\.nuget\packages\system.valuetuple\4.3.0\lib\netstandard1.0\System.ValueTuple.dll" -a "C:\Users\username\.nuget\packages\system.xml.readerwriter\4.3.0\lib\netstandard1.3\System.Xml.ReaderWriter.dll" -a "C:\Users\username\.nuget\packages\system.xml.xdocument\4.3.0\lib\netstandard1.3\System.Xml.XDocument.dll" -a "C:\Users\username\.nuget\packages\system.xml.xmldocument\4.3.0\lib\netstandard1.3\System.Xml.XmlDocument.dll" -a "C:\Users\username\.nuget\packages\system.xml.xpath\4.3.0\lib\netstandard1.3\System.Xml.XPath.dll" -a "C:\Users\username\.nuget\packages\system.xml.xpath.xdocument\4.3.0\lib\netstandard1.3\System.Xml.XPath.XDocument.dll" -a "C:\Users\username\Source\Repos\SamplePageAPI\SamplePageAPI\obj\Debug\netstandard2.0\SamplePageAPI.dll"" exited with code 1.	SamplePageAPI	C:\Users\username\.nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\Blazor.MonoRuntime.targets	429	`

With the following exception:
```
1>Fatal error in IL Linker
1>Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Blazor.AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Blazor.AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=null'
1>   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
1>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
1>   at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.LoadReferencesStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

**Comment by SteveSandersonMS** [comment]
Done in #492
