### ISSUE TITLE
Working in VS Code

### ISSUE THREAD

**Issue by dlr1** [aspnet/Blazor#344]
This is not an issue but a question.
Can we develop in VS Code, if so what would be the minimum installs required to create/build/Run blazor application.
Thanks

**Comment by dcvsling** [comment]
i already tried it,
i use vs to generate project ( net core base ), vscode default launch and task , then it's work
like this image
![image](https://user-images.githubusercontent.com/16910731/37853166-5e2ef4ea-2f20-11e8-801c-c6278d2004f6.png)

**Comment by dlr1** [comment]
Thanks for the reply. I see you got it working, Could you give me details of what you installed (.net core, razor extensions, extensions for VS Code).

**Comment by jt2** [comment]
You can follow this guide https://blogs.msdn.microsoft.com/webdev/2018/03/22/get-started-building-net-web-apps-in-the-browser-with-blazor/

I don't now if vs code has some extra support but you can do:
dotnet new -i Microsoft.AspNetCore.Blazor.Templates
dotnet new blazor -o BlazorApp1
cd BlazorApp1
dotnet run

**Comment by dlr1** [comment]
ok, thanks

**Comment by janaka** [comment]
Can somebody confirm there's support for debugging a standalone blazor app in VS Code?
