### ISSUE TITLE
Stopping Blazor in Visual Studio

### ISSUE THREAD

**Issue by greatjack1** [aspnet/Blazor#345]
Small issue in tooling, Im running the latest preview version of visual studio with the Blazor language extension and whenever I press the stop button to stop debugging a Blazor app, I see that although visual studio claims to have stopped it, the console window is still open and the web page is still being served until I manually close the window.

Just a small issue, nothing major, but should be noted none the less

**Comment by mikanyg** [comment]
The readme for the preview states that debugging Blazor apps in VS does not work, so I am sure thats one of the reasons.

**Comment by danroth27** [comment]
This isn't actually a behavior specific to Blazor projects. This is the way ASP.NET Core web projects behavior in general when running the project as a standalone app outside of IIS Express. Once the server process is started it isn't terminated even when you stop the debugger. You have to shut it down manually.
