### ISSUE TITLE
index.html is not regenerated under bin when wwwroot/index.html is changed

### ISSUE THREAD

**Issue by yowl** [aspnet/Blazor#355]
### Title
index.html is not regenerated under bin when wwwroot/index.html is changed

### Functional impact
Changes made to index.html are not propogate to the output as expected

### Minimal repro steps
Create a new project, run it,
Modify the index.html in any way, e.g. change the title.
Ctrl-F5
Title has not changed.
Clean.Rebuild, Title does change

### Expected result
Title should change without having to Clean

### Actual result
Title does not change

**Comment by fbcoder** [comment]
I notice the same when running from cli (in docker container, can give more details if needed). It's any change to the code for me. When executing dotnet run the project seems to be build (I can see the compiled views with new text in obj folder). Changes are only visible when running:
`dotnet clean && dotnet run`

**Comment by fredrik-lundin** [comment]
I noticed the same problem. From Visual Studio, doing a `rebuild` instead of a simple `build` will update the `index.html` file (no explicit `clean` needed).

**Comment by javiercn** [comment]
Fixed
