### ISSUE TITLE
Question: Send cookies

### ISSUE THREAD

**Issue by aguacongas** [aspnet/Blazor#357]
Hi Guys,

I try to port a sample application I wrote to Blazor (it's just a chat actualy). 
The application is not hosted by the chat server, I use CORS. The server is hosted on [heroku](https://chatle-server.herokuapp.com).  
In this application, user are able to login throught third parties providers so I need to send authentication to the server on the callback page.

How can I do that ?

The application code is [there](https://github.com/aguacongas/Chatle.Blazor).
The server code is [there](https://github.com/aguacongas/chatle).

**Comment by floreseken** [comment]
looks like this is not possible yet, just as sending extra headers..

**Comment by floreseken** [comment]
Oh wait.. headers are possible:

```
            HttpRequestMessage req = new HttpRequestMessage(HttpMethod.Get, "\api\test");
            req.Headers.Add("auth", "jdfhkjhfd");

            http.SendAsync(req);
```

So you could fix it yourself that way..

**Comment by aguacongas** [comment]
I tried but it doesn't work, I can't read cookies I received.  
But I finaly found a solution, I need to override sendAsync function to set credentials in `fetch` function :  

``` ts
async function sendAsync(id: number, method: string, requestUri: string, body: string | null, headersJson: string | null, credentials: boolean | null) {
    let response: Response;
    let responseText: string;
    try {
        response = await fetch(requestUri, {
            method: method,
            body: body || undefined,
            headers: headersJson ? (JSON.parse(headersJson) as string[][]) : undefined,
            credentials: credentials ? "include" : undefined
        });
        responseText = await response.text();
    } catch (ex) {
        dispatchErrorResponse(id, ex.toString());
        return;
    }

    dispatchSuccessResponse(id, response, responseText);
}
```

Do you agree if I submit a PR with this feature ?  
I plan to add a default option to send credentials in BrowserHttpMessageHandler and add HTTP extensions methods overriding this setting

**Comment by aguacongas** [comment]
You can review the code of [this commit](https://github.com/aguacongas/Blazor/commit/578fa332860575ee9ca916d790d37081f21fe2a9)

**Comment by aguacongas** [comment]
@danroth27 Did you have the time to review that ?

**Comment by danroth27** [comment]
Not yet - will take a look later this week.

**Comment by SteveSandersonMS** [comment]
There's more discussion in #399 so I'll close this issue in favour of that PR.
