### ISSUE TITLE
VS Blazor editor

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#36]
- [x] Make Razor code generation extensible (external)
- [x] Component intellisense completions (at design time build)
- [x] Blazor extending Razor code generation (including tooling)

**Comment by veikkoeeva** [comment]
@danroth27 What would be needed for this? I took a look at the [How to contribute](https://github.com/aspnet/Blazor/blob/dev/CONTRIBUTING.md) section and didn't spot what's needed compile the code into WASM modules. I'm guessing the process is described at https://github.com/lrz/mono-wasm. Is this true? If so, I could add a note of it to the contribution guide. It appears (offline chatting) more than a few people are pondering the process.

**Comment by danroth27** [comment]
@veikkoeeva The only WASM code currently is the .NET runtime itself, which is provided by our friends on the Mono team and is checked in here: https://github.com/aspnet/Blazor/blob/dev/src/mono/dist/unoptimized/wasm/mono.wasm. 
This .NET runtime can then be used to run normal .NET assemblies in the browser. Blazor is a web UI framework implemented as normal .NET assemblies. If you're interested in how the Mono runtime is built into WebAssembly you'll need to look at the [Mono repo](https://github.com/mono/mono).

**Comment by SteveSandersonMS** [comment]
@rynowak No rush to respond today, but do you think this is done enough that we should mark this high-level issue as done?

**Comment by rynowak** [comment]
Yep. Closing
