### ISSUE TITLE
Stopping the debugger doesn't close the server

### ISSUE THREAD

**Issue by wischi-chr** [aspnet/Blazor#361]
I created a new BlazorTestApp (followed steps from the readme.md).

After pressing "Stop Debugging" I expected it to close chrome (which indeed happened) and the server-part (console-window) which kept running.

Is that intended behaviour or a bug?

**Comment by SIkebe** [comment]
@wischi-chr Intended behaviour for now.
https://github.com/aspnet/Blazor/issues/345#issuecomment-375849654

**Comment by wischi-chr** [comment]
OK thanks for the info ;-)
