### ISSUE TITLE
Windows Defender flags file as virus in repo download.

### ISSUE THREAD

**Issue by robzelt** [aspnet/Blazor#365]
The file: Blazor-dev/src/mono/tools/binaries/illink/illink.dll is quarantined on download.

**Comment by Eilon** [comment]
@robzelt thanks for the report.

@SteveSandersonMS - let's follow up on Monday on this. If we believe it's a false positive we can work with the Windows Defender team to address this.

**Comment by SteveSandersonMS** [comment]
@Eilon I'm ready to follow up on this any time now. Yes I agree this must be a false positive. If you know how to notify the Windows Defender team about that, it sounds like that's what we should do.

**Comment by Eilon** [comment]
@SteveSandersonMS - I sent an email seeking info on it, you're CC'ed.

**Comment by Eilon** [comment]
@robzelt ah that's great to hear!
