### ISSUE TITLE
Tooling for JavaScript interop

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#37]
- [ ] Tooling to generate strongly typed C# wrappers for JavaScript libraries (ex based on TypeScript definitions)

**Comment by RehanSaeed** [comment]
Could you also use JSDoc to achieve the same thing? I believe TypeScript does this to infer some basic type information.

**Comment by grahamehorner** [comment]
or even use eslint https://medium.com/javascript-scene/you-might-not-need-typescript-or-static-types-aa7cb670a77b :)

**Comment by grahamehorner** [comment]
https://github.com/Retyped/Retyped

**Comment by ebekker** [comment]
Unfortunately, the Retyped tooling is not OSS at this time, so not much we can leverage there.  But Fable has support, and although it's F#, there's pby lots that can be adapted from there:  https://github.com/fable-compiler/ts2fable

**Comment by grahamehorner** [comment]
@ebekker I’ve connected with the developers of Retyped and they are moving to open sourcing the tools and resulting generated c# code, they have replied with interest in blazor

**Comment by danroth27** [comment]
Closing as this is being handled by https://github.com/mono/TsToCSharp
