### ISSUE TITLE
Suggestion - Make Blazor MVVM Friendly

### ISSUE THREAD

**Issue by pmoorelegistek** [aspnet/Blazor#374]
I know that code re-use between desktop/mobile and web is not necessarily the top priority for this project, but there seems to be tremendous opportunity here for just that and I don't think it would detract much - if any - from the main vision.

The most obvious addition would be to have an `ICommand Command` property in `BlazorComponent`s and tie it to `onclick`. This is already doable by making my own `MVVMButton` component and it really works great:

```
<button @onclick(() =>
        {
            this.Command?.Execute(null);
        })>
    @Label
</button>

@functions {
    private ICommand _command;
    public ICommand Command
    {
        get => _command;
        set => _command = value;
    }

    public string Label { get; set; }
}
```

Even this one step is a huge leap toward re-using view models between Blazor and WPF/UWP/Xamarin.Forms apps. 

Wondering if this is an idea the team would be interested in exploring and if so I'd be interested in starting a fork and contributing.

**Comment by plamen-i** [comment]
Even with this approach you will continue to write ASP.NET Razor-style code.

For MVVM support and complete code reuse (XAML/MVVM), see [https://github.com/praeclarum/Ooui](https://github.com/praeclarum/Ooui).

**Comment by danroth27** [comment]
Our goal with Blazor is target a broad audience with Web developers, so we're specifically not targeting compatibility with WPF/UWP/Xamarin.Forms. We are also trying to give the you the flexibility to use the patterns you want without baking too much in the framework. So you should be able to implement MVVM patterns on top of Blazor's core concepts (much like you are doing already). It doesn't sound like you are blocked with this, and we don't plan to do more in this direction.

**Comment by pmoorelegistek** [comment]
Hi Daniel - very true, you seem to have made this puppy more than flexible enough to handle MVVM and probably other patterns without backend changes. I won't pester you with PRs then but I will definitely start working on some MVVM-friendly components that build on your core work. In any event, well done and cheers.

**Comment by danroth27** [comment]
>  I will definitely start working on some MVVM-friendly components that build on your core work

That sounds great! Let us know when you have something you'd folks to try out and we'd be happy to help promote.

**Comment by touseefbsb** [comment]
would definitely apprecite any kind of MVVM stuff in blazor, if the framework itself doesnot make this happen within the framework and someone else decides to fork blazor and make it mvvm that would also be a good option. mvvm is not limited to uwp/wpf apps it is pretty much everywhere these days even in web frameworks most frameworks follow this approach as it has obvious benefits for testing and seperation of concerns.

**Comment by pmoorelegistek** [comment]
I don't imagine forking will be necessary. Daniel is right, they are making it extremely versatile. I'm looking at Blazor principally as a bridge between C# and the DOM. The full blown frameowrks are going to be built on top of this, not instead of.

**Comment by touseefbsb** [comment]
@pmoorelegistek  maybe you are right that full frameworks maybe built on top of this but I hope Microsoft themselves make a MVVM framework on top of this bcz that would be officially supported and more stable for developers to just use it built into Visual studio instead of tracking a community framework and hoping it follows latest standards.

**Comment by legistek** [comment]
@danroth27 another conversation made me think of this thread. As you've said and I agree it's good for Blazor to be flexible. However what do you think about a couple of small, targeted items -

(1) Add `ICommand Command` and `object CommandParameter` properties to `BlazorComponent` and have button, checkbox, and maybe a few other components invoke `Command` with `CommandParameter` when they're clicked
(2) Have `BlazorComponent` implement `INotifyPropertyChanged` and add a `protected virtual void OnPropertyChanged` method for overriding and calling by internal setters.

These would go a really long way, most importantly avoiding us having to make a derived version of every common component just to implement an MVVM pattern.

Would you consider a PR for just these?
