### ISSUE TITLE
Changes to wwwroot/index.html not reflecting in rendered page

### ISSUE THREAD

**Issue by mykeels** [aspnet/Blazor#378]
### Reproduction Steps:

- I make changes to the `wwwroot/index.html` file by removing the bootstrap CSS and JS references, and changing the `site.css` reference to `app.css`
- I stop the `dotnet run` program with CTRL+C and restart it

### Expectation:

- No more bootstrap references, and `app.css` is loaded.

### What I get:

- Same `index.html` as before I made the changes.

I find that the actual `dist` file in `bin/Debug/netstandard2.0/dist/index.html` still contains the default html, regardless of what changes I make to the `wwwroot/index.html` file.

Is there a special way to adjust for changes to the `wwwroot/index.html` file? 

### My Setup

I am running DotNet 2.1.101 on a Mac OS X

**Comment by miroslavp** [comment]
Same on Windows

**Comment by RyoukoKonpaku** [comment]
PR #375 seems to have fixed that. Though I do not know if it's already pushed the updated package for it on myget/nuget.

**Comment by floreseken** [comment]
See https://github.com/aspnet/Blazor/issues/355

**Comment by floreseken** [comment]
No not pushed yet

**Comment by chassq** [comment]
Until then I am doing a clean/rebuild to get the changes...

**Comment by danroth27** [comment]
Thanks for reporting this! This should be addressed now as part of the fix for #355

**Comment by mykeels** [comment]
When will this fix be updated on nuget? @danroth27 

Also, how do I get the fix? 

Will running `dotnet new -i Microsoft.AspNetCore.Blazor.Templates` again be enough?

**Comment by danroth27** [comment]
We plan to release 0.2.0 with this fix in about two weeks. To update the templates in VS you'll need to update the Blazor VSIX. To update the templates on the command-line you'll need to use `dotnet new -i`. We should also have nightly build available within the next couple of days.
