### ISSUE TITLE
Publish live version of Flight Finder sample

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#387]
We have https://blazor-demo.github.io. We should also have a live version of [Flight Finder](https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/FlightFinder)

**Comment by flash2048** [comment]
@danroth27 Hello 
I published **Flight Finder** sample here: http://blazor-flight-finder.azurewebsites.net/

**Comment by humbersoft** [comment]
The app crashes with "A problem repeatedly occurred on "http://blazor-flight-finder.azurewebsites.net"" on iOS 11.3. I have no clue why. The other sample runs without problems.

**Comment by vertonghenb** [comment]
@humbersoft Not only on iOS, same issue on a Mac Book Pro using Safari
Safari Version: Version 11.1 (13605.1.33.1.2)

**Comment by danroth27** [comment]
> The app crashes with "A problem repeatedly occurred on "http://blazor-flight-finder.azurewebsites.net"" on iOS 11.3.

@SteveSandersonMS ?

**Comment by SteveSandersonMS** [comment]
Interesting. I suspect this might be to do with the build flags we're using for Mono but will have to investigate.

**Comment by danroth27** [comment]
> The app doesn't load on IE 11 (Windows 10).

Currently that's expected. We do fall back to asm.js for browsers that don't support webassembly but there are still some additional polyfills that we need to add to get Blazor to work in IE11.

**Comment by danroth27** [comment]
Moving this to Blazor.Docs: https://github.com/aspnet/Blazor.Docs/issues/56#issuecomment-384782446
