### ISSUE TITLE
Publish VSIX to gallery when 0.1.0 is final

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#39]
- [x] Project templates (based off of CLI templates)
- [ ] Item templates
- [x] Razor tooling extension
- [ ] Publish to VS Gallery as per @Eilon's suggestion (maybe @danroth27 could own the gallery listing)

**Comment by rynowak** [comment]
Empty VSIX is in 👍

**Comment by danroth27** [comment]
Thanks! @alexgav is going to look at stubbing out the CLI templates

**Comment by SteveSandersonMS** [comment]
Update: Thanks to various people's contribution, we are now building working VSIXes that include both the project templates and the new language service bits.

Leaving this issue open until we upload a preview version to VS Gallery.

**Comment by SteveSandersonMS** [comment]
Closing because this is now covered in #296.
