### ISSUE TITLE
install the templates and they don't in the list ?

### ISSUE THREAD

**Issue by syeerzy** [aspnet/Blazor#390]
> dotnet new -i Microsoft.AspNetCore.Blazor.Templates

it runs without any errors or warnnings.

Restoring packages for /Users/XXX/.templateengine/dotnetcli/v2.1.300-preview1-008174/scratch/restore.csproj...
  Installing Microsoft.AspNetCore.Blazor.Templates 0.1.0.
  Generating MSBuild file /Users/XXX/.templateengine/dotnetcli/v2.1.300-preview1-008174/scratch/obj/restore.csproj.nuget.g.props.
  Generating MSBuild file /Users/XXX/.templateengine/dotnetcli/v2.1.300-preview1-008174/scratch/obj/restore.csproj.nuget.g.targets.
  Restore completed in 480.47 ms for /Users/XXX/.templateengine/dotnetcli/v2.1.300-preview1-008174/scratch/restore.csproj.

and it list the templates...i cant find the new installing blazor template. 
even i run this again  

> dotnet new -l

 why and how can i fix it? 

macOS 10.13.3 with bash 3.2
and the newest preview dotnet core sdk

**Comment by danroth27** [comment]
@kichalla Can you try out installing the blazor templates on a mac and see if you can reproduce this?

**Comment by fredrik-lundin** [comment]
Make sure you are picking _ASP.NET Core 2.0_ instead of _ASP.NT Core 2.1_
![image](https://user-images.githubusercontent.com/5526934/37954187-44953f6c-31a5-11e8-90c3-ac8362faaf76.png)

**Comment by syeerzy** [comment]
@fredrik-lundin  im install the templates in the shell command on a mac.

it's not support by the VisualStudio for Mac,  No these selections.

**Comment by fredrik-lundin** [comment]
Oh, sorry, I read too quickly!

**Comment by AdrienTorris** [comment]
Try this command before reinstall the template : `dotnet new --debug:reinit`

```
dotnet new --debug:reinit
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.0.5-* --nuget-source https://dotnet.myget.org/F/blazor-dev/api/v3/index.json
```

The both Blazor templates should be in the template list after that.

**Comment by SteveSandersonMS** [comment]
The `reinit` might help. Also you might want to use the following exact command, which has been verified to work: https://github.com/aspnet/Blazor/issues/425#issuecomment-377156798

Closing as this is known to work, but please let us know if you have repro steps that show a problem. Thanks!
