### ISSUE TITLE
New Project Blazor Template Can't Seen.

### ISSUE THREAD

**Issue by nsrtky** [aspnet/Blazor#393]
When creating new web project expected to see Blazor as project type but cant.
![image](https://user-images.githubusercontent.com/12385044/37954702-4895602e-31af-11e8-9a95-9b2118130be1.png)

I am going to share screen view of VS Enterprise version below.

![image](https://user-images.githubusercontent.com/12385044/37954591-f5411b2a-31ae-11e8-9c38-f63497d34077.png)

**Comment by floreseken** [comment]
Are you sure it's installed correctly?
Can you also share a screenshot of the "Extensions and updates" window?

**Comment by nsrtky** [comment]
Yes after Tools>Extentions and Updates> Blazor its worked. I am closing this iseues.
