### ISSUE TITLE
Question: How is Blazor differen from a typcal web site ?

### ISSUE THREAD

**Issue by teneketo** [aspnet/Blazor#411]
Apart from (if I'm reading correctly) it runs entirely on the client's device and not my server, other than that it looks pretty much the same, or am I missing something huge and painfully obvious ?

**Comment by chrissainty** [comment]
In terms of basic looks, you're correct. It does look the same as the other SPA templates in Visual Studio. Blazor is an SPA type web framework after all. What I think you're missing is the fact that it is C# code running in your browser to rending that UI and make it interactive. And that is the really impressive part.

**Comment by rstropek** [comment]
The fact that it runs on the client is the **big** difference. Here are some aspects to consider:

* App can use local processing power, you do not rely on doing all logic on the server (reduces e.g. latency, reduces necessary resources in the cloud, etc.)
* App can work without a server (e.g. work offline in a progressive web app)
* App cannot directly access backend services (e.g. DB), has to use e.g. web apis for that
* Auth works differently
* ...

However, you are right that it looks very similar to Razor on the server. That means that devs can reuse their existing skills and partly reuse existing C# codebases.

**Comment by teneketo** [comment]
@rstropek now that you put it that way it doesn't sound too bad actually. I'd still prefer to trust server-side to the server rather than the average user's machine, who most likely runs IE  on an 8 year computer, if I could afford it.

**Comment by rstropek** [comment]
You could consider https://electronjs.org/ so that you do not have to rely on the user's browser. You will bring your own Chromium. Therefore, you only have to test for one target environment.
