### ISSUE TITLE
Add F# lang support

### ISSUE THREAD

**Issue by libary** [aspnet/Blazor#414]
Very interested in this project, but I also would like to have support for F # as my main programming language.

**Comment by danroth27** [comment]
You should be able to use any .NET Standard class libraries including libraries written in F# in your Blazor app. You should also be able to write your app logic in F#. The only restriction is that Razor is C# based and there is no plans to change that. I believe @panesofglass was playing around with F# and Blazor as well: https://github.com/panesofglass/blazorapp. Let us know if you hit any issues!

**Comment by panesofglass** [comment]
I found F# to be completely supported based on some very minimal testing. I haven't tried tuples, records, etc., but I doubt they are forbidden. Nice work, @danroth27!

**Comment by panesofglass** [comment]
@danroth27, out of curiosity, is there a way to write the syntax tree of whatever Razor compiles into?

**Comment by danroth27** [comment]
@panesofglass Not sure what you mean . . . Razor compiles into C#, but I'm guessing you're not asking for the C# syntax tree . . .

**Comment by panesofglass** [comment]
Just wondering if it would be possible to write a data structure that compiles into the same target as Razor. Could you write plain C# code that did the same as the Razor syntax, i.e. no Razor files, just C#?

**Comment by danroth27** [comment]
@panesofglass The generated code is all under the obj folder in the Blazor project. Look for the `.g.cs` files.

**Comment by Alex2357** [comment]
> but it reinforces the feeling that F# is a second class citizen and .net=C#. 

I'm just trying to move to F# for the last year and see that many people saying this. I can't make a decision what to use for my project SAFE stack or Blazor. Have you tried any of those in a real project?

**Comment by panesofglass** [comment]
@Alex2357 you could try https://github.com/fsbolero/Bolero. I would think that would work with SAFE stack, but it has better integration with WebSharper.
