### ISSUE TITLE
Blazor Components in class libraries

### ISSUE THREAD

**Issue by vibeeshan025** [aspnet/Blazor#415]
Just like the below feature in ASP.net core, we need a similar mechanism in Blazor.
Post by @danroth27 
https://blogs.msdn.microsoft.com/webdev/2018/03/01/asp-net-core-2-1-razor-ui-in-class-libraries/

This helps us lot in reusing our code bases.

**Comment by muqeet-khan** [comment]
I believe this is already being tracked by #340

**Comment by vibeeshan025** [comment]
If this is a duplicate, Can I delete this issue.

**Comment by danroth27** [comment]
Thanks for the suggestion! We are planning to work on support component libraries for our next update. Tracked by #340.
