### ISSUE TITLE
Failing StandaloneApp sample with IIS static hosting

### ISSUE THREAD

**Issue by guardrex** [aspnet/Blazor#418]
* IIS 10 (running IIS locally on Win10)
* StandaloneApp sample
* Project seems to restore, compile, and publish normally (`dotnet publish -c Release`)
* Pointing IIS at the *publish* output (seeking to host statically; permissions configured for IUSR access to *StandaloneApp* folder and app pool access to the *publish* folder)
* *web.config* is stock (produced by the build)
* Assets seem to be available and loading normally in the browser
* No messages in Console
* *index.html* loads
* **Loading ...** message appears, then disappears
* Nothing else happens (all browsers exhibit the same behavior)
* Same behavior when executing `dotnet run` from the project's folder

![capture](https://user-images.githubusercontent.com/1622880/38043037-8a313aa4-327b-11e8-8892-4793c1930633.PNG)

```html
<html><head>
    <meta charset="utf-8">
    <title>Blazor standalone</title>
    <base href="/">
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="css/site.css" rel="stylesheet">
</head>
<body>
    <app>
<router appassembly="typeof(StandaloneApp.Program).Assembly"></router>
</app>

    <script src="css/bootstrap/bootstrap-native.min.js"></script>
    <script src="_framework/blazor.js" main="StandaloneApp.dll" entrypoint="StandaloneApp.Program::Main" references="BlazorApp.dll,Microsoft.AspNetCore.Blazor.Browser.dll,Microsoft.AspNetCore.Blazor.dll,Microsoft.Extensions.DependencyInjection.Abstractions.dll,Microsoft.Extensions.DependencyInjection.dll,mscorlib.dll,netstandard.dll,System.Core.dll,System.Diagnostics.StackTrace.dll,System.dll,System.Globalization.Extensions.dll,System.Net.Http.dll,System.Runtime.Serialization.Primitives.dll,System.Security.Cryptography.Algorithms.dll" linker-enabled="true"></script><script defer="" src="_framework/wasm/mono.js"></script>

</body></html>
```

**Comment by keithwill** [comment]
In the template I'm using the router attribute has a capital R for the first letter, not a lowercase one, and the Router element is inside of a .cshtml file that matches the app element. If the Router is normally found in a .cshtml file, then I wouldn't expect it to work when put into the root HTML file instead. 

The app element might look like a Blazor component element, but I think its just a mounting point for the Blazor application. What is in your App.cshtml if your router element is inside of your index.html?

**Comment by guardrex** [comment]
Yes, everything seems correct at the outset.

*App.cshtml* has ...

```cshtml
<!--
    Configuring this stuff here is temporary. Later we'll move the app config
    into Program.cs, and it won't be necessary to specify AppAssembly.
-->
<Router AppAssembly=typeof(StandaloneApp.Program).Assembly />
```
> If the Router is normally found in a .cshtml file, then I wouldn't expect it to work when put into the root HTML file instead.

That's apparently what *starts* to happen tho. The "**Loading ...**" content of the deployed *index.html* file (in the `<app>` element) is displayed in the browser but then is removed and the **<router ...>** element is getting swapped in there (I'm showing the *index.html* file after that happens). Then .... nothing ... nothing happens. The app doesn't load.

**Comment by floreseken** [comment]
I guess this is ralated to: https://github.com/aspnet/Blazor/issues/307

**Comment by guardrex** [comment]
One (possibly silly) mistake I may have made is relying upon the fact that the project publishes *without building the repo* according to the README. Perhaps, a simple lack of assets is dogging me here and that the missing bits don't affect publish. I'll check in a few hours and see what's what.
