### ISSUE TITLE
Problems Publishing FlightFinder Client to AzureWebsites 

### ISSUE THREAD

**Issue by JonnyGibson** [aspnet/Blazor#428]
https://blazordemojg.azurewebsites.net/

I cloned the flightcenter demo locally,  which worked well,  i then published the client as an app to azurewebsites.

i get the following error which i can't get to the bottom of.  any ideas?

_`Application 'MACHINE/WEBROOT/APPHOST/<app name>' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'dotnet .\FlightFinder.Client.dll', ErrorCode = '0x80004005 : 80008081.`_

**Comment by SteveSandersonMS** [comment]
You can't just publish that specific client project on its own, as it relies on the server. If you publish the server project it should work.

**Comment by JonnyGibson** [comment]
thanks steve.   i actually deployed it from azure  github deployments and it worked.    Loving blazor, there's a lot of potential
