### ISSUE TITLE
End-to-End prerequisites and instruction/guide

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#429]
Please provide more detailed instruction with regards to end-to-end prerequisites for both windows/linux build platforms;    

especially from us selenium NOOBs like me ;)

Windows 10
- installed Java 8
- installed Chrome

- ran `npm install -g selenium-standalone` from command line in repo folder
- ran `selenium-standalone start` from command line - failed ?

**Comment by SteveSandersonMS** [comment]
We do have fairly detailed instructions in the main readme doc at https://github.com/aspnet/Blazor#blazor. If you find that any steps are missing, please let us know.

In this case you appear to have missed the `selenium-standalone install` step as detailed at https://github.com/aspnet/Blazor#run-end-to-end-tests.

**Comment by grahamehorner** [comment]
@SteveSandersonMS that was a bit odd, I've reinstalled npm and all now works ? maybe a reference on the documentation about this; I'll raise the issue with node.js
