### ISSUE TITLE
Blazor Logo

### ISSUE THREAD

**Issue by xamlsharp** [aspnet/Blazor#430]
Iconography and imagery moves sentiment and beguiles the rational self. Although not a committed product, Blazor still requires some of the charms of its forebears. It needs to carve out its comely stature; it needs a logo.

Here is one idea: Rising up like a phoenix through the fire, Blazor disperses the heat of competing languages by creating a single source of light within the dark chaos of web-development.

![blazor_example](https://user-images.githubusercontent.com/22227916/38090681-b09eddc8-33a6-11e8-9734-cc189bfcaa24.png)

**Comment by davidnmbond** [comment]
Bold, Italic, Papyrus font?  Sorry, no.
Agreed that a logo would be good, and that fire should be part of it.
Something more like this:

https://www.google.co.uk/search?q=fire+icon&safe=active&source=lnms&tbm=isch

**Comment by jrote1** [comment]
My pitch
![image](https://user-images.githubusercontent.com/4202486/38095506-8a81922c-3368-11e8-87c2-703277f2208f.png)

**Comment by SteveSandersonMS** [comment]
It's fun to see these ideas :) More please, with bonus points for satire...

@xamlsharp I also agree that genuinely we will want a logo at some point, and your concepts are cool. In practice this is something that Microsoft would most likely produce internally. It's theoretically possible that a logo could be accepted as a contribution, but I don't think I've ever seen that happen in reality in any other product.

I'll close this but please feel free to continue posting serious or comic suggestions.

**Comment by AWulkan** [comment]
@davidnmbond Agreed. Or alternatively something minimalistic with a razor (if it can be done in a good way). Since Blazor = Browser + Razor.

**Comment by jrote1** [comment]
![blazor](https://user-images.githubusercontent.com/4202486/38097242-c4810454-336c-11e8-8e05-1cc501661d1f.png)

**Comment by jrote1** [comment]
Willing to sell this badass one for £1 billion 😆 
![blazor](https://user-images.githubusercontent.com/4202486/38098846-ef893ae6-3370-11e8-93f0-ba8ddfa5f7e2.png)

**Comment by davidnmbond** [comment]
Kerning on the "E"?  Needs a shift to the left.  I like it though.

Here's my submission

`<img src="https://memegenerator.net/img/instances/68131816/burn-all-the-javascript.jpg" />`

**Comment by danroth27** [comment]
![dotnet-bot-blazor](https://user-images.githubusercontent.com/1874516/38106719-bfaf460c-3344-11e8-99d0-256bcbe1a9b4.png)

**Comment by xamlsharp** [comment]
@davidnmbond Forget the font - it's the concept that's important. By the way, I like your idea of having JS burn (though, I don't think Microsoft will light that wick given all the time and energy that they've put into it over the last decade).

Personally, I think @danroth27 has pitched the best example so far.

@SteveSandersonMS  Of course, I wasn't suggesting that the community would be permitted to foster a logo for Blazor. Rather, my intent was only to help the community rhapsodize the technology's public perception and to engage the community by means of story-telling.

![b_example](https://user-images.githubusercontent.com/22227916/38123420-3fdb533c-341e-11e8-908f-a1fd0e3a64c7.png)

**Comment by davidnmbond** [comment]
@xamlsharp sorry about the font comment - Papyrus and Comic Sans are brothers ;-)

Much prefer this revision of yours - simpler, etc.  Only thing I'd say is that most logos need to fit into a square and/or circle these days (icons etc.)  I'd still like to see JavaScript burn, though.

Also agree with your comment that we're not going to get to choose the logo, but branding IS important.

**Comment by AWulkan** [comment]
I think the logo should be very simple and minimalistic, similar to this (just a random logo found online):
![blaze](http://www.blazethread.com/wp-content/uploads/2017/10/logo-color-1.png)

**Comment by SteveSandersonMS** [comment]
Just a friendly reminder for anyone posting here that we’re not seriously designing an actual logo in this thread. Hope that’s ok!

**Comment by grahamehorner** [comment]
hear would be my two cents worth :D an ode to the Gu 
![men-blazer-suit-jacket-slim-fit-fashion-blaser-masculine-high-quality-casual-red-blazer-jacket-for](https://user-images.githubusercontent.com/3924941/38154017-9b5a7d02-3467-11e8-9464-3f8d47d54506.jpg)

**Comment by ebekker** [comment]
You should launch the "The Red Blazor Tour:  Still Just an Experiment" when you hit 1.0.
