### ISSUE TITLE
Add Blazor templates for ASP.NET Core 2.1

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#441]
Looks like there is quite a bit of drop off in the number of people that successfully create a Blazor template after getting the VSIX. One hypothesis is that they can't find the templates. Currently the Blazor templates only show up if you select .NET Core and ASP.NET Core 2.0 in the "New ASP.NET Core Web Application" dialog. It would help if the Blazor templates showed up when the .NET Framework is selected and for ASP.NET Core 2.1.

**Comment by danroth27** [comment]
Add additional `framework` option for 2.0, and the associated conditions to pull in the right package versions in your csproj.

For full framework, the template needs to:
1. Define `TargetFrameworkOverride`: https://github.com/dotnet/templating/blob/d18c42fe62ca500bfd1afbaa7a6382180dff52ef/template_feed/Microsoft.DotNet.Common.ProjectTemplates.1.x/content/ClassLibrary-CSharp/.template.config/template.json#L33
1. Hide it from the CLI: https://github.com/dotnet/templating/blob/d18c42fe62ca500bfd1afbaa7a6382180dff52ef/template_feed/Microsoft.DotNet.Common.ProjectTemplates.1.x/content/ClassLibrary-CSharp/.template.config/dotnetcli.host.json#L4
1. Support it in the template content: https://github.com/dotnet/templating/blob/d18c42fe62ca500bfd1afbaa7a6382180dff52ef/template_feed/Microsoft.DotNet.Common.ProjectTemplates.1.x/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj#L4-L5.

**Comment by chrissainty** [comment]
@danroth27 I'm happy to have a go at this one. Is it just a case of updating the various json files in the .template.config folders for each of the two templates and the .csproj files?

**Comment by danroth27** [comment]
We think so, but we'll have to test to make sure. Feel free to have a go at it!

**Comment by chrissainty** [comment]
I'm about there with the changes. I've just got one question. In the [BlazorHosted.CSharp.Server.csproj](https://github.com/aspnet/Blazor/blob/512a15eb74514d87c3b84abb1a5d77c2e45b4389/src/Microsoft.AspNetCore.Blazor.Templates/content/BlazorHosted.CSharp/BlazorHosted.CSharp.Server/BlazorHosted.CSharp.Server.csproj#L4) file the project is targeting netstandard2.0 and not netcoreapp2.0 is there a specific reason for this?

**Comment by danroth27** [comment]
@chrissainty The server project is an ASP.NET Core project that runs on .NET Core, so it targets `netcoreapp2.0`. The client project is a Blazor app, which currently should target `netstandard2.0`.

**Comment by chrissainty** [comment]
@danroth27 Apologies my copy of that file was targeting `netstandard2.0` not `netcoreapp2.0` hence the question.

**Comment by danroth27** [comment]
@SteveSandersonMS  I think this one is done, correct?
