### ISSUE TITLE
Bug - Type mismatch error in ternary expression

### ISSUE THREAD

**Issue by BalazsArva** [aspnet/Blazor#446]
I'm filing a bug. Consider the following simple code:

    @page "/test"

    <style type="text/css">
        .box {
            margin:3em;
        }
        .bg-blue {
            background:#0094ff;
            color:#fff;
        }
    </style>

    @for (int i = 0; i < 10; ++i)
    {
        bool addExtraCssClass = false;

        <div class="box @(addExtraCssClass ? "bg-blue" : "")">
            <p>Test</p>
            <button type="button" @onclick(() => { addExtraCssClass = !addExtraCssClass; }) >
                Make it @(addExtraCssClass ? "blue" : "regular")!
            </button>
        </div>
    }

In this code, the `@(addExtraCssClass ? "bg-blue" : "")` lines cause a compile time error:

> Error	CS0029	Cannot implicitly convert type 'string' to 'bool'

**Comment by RyoukoKonpaku** [comment]
For now one way of making it work is to change how the ```class``` attribute is done, as the compiled razor class seems to be incorrect when doing that for conditional classes.
Here's how to make it work for now:
```
<div class=@((addExtraCssClass ? "bg-blue" : "") + "box")>
        <p>Test</p>
        <button type="button" @onclick(() => { addExtraCssClass = !addExtraCssClass; }) >
            Make it @((addExtraCssClass ? "blue" : "regular"))!
        </button>
</div>
```

**Comment by rstropek** [comment]
Try using double parenthesis (see also [data binding on learn-blazor.com](https://learn-blazor.com/pages/data-binding/#one-way-data-binding)): `<p class="note @((NoteIsActive ? "highlight" : ""))">This is a note</p>`

**Comment by SteveSandersonMS** [comment]
Thanks for reporting it! Now fixed.
