### ISSUE TITLE
Feature: Dynamic bind?

### ISSUE THREAD

**Issue by floreseken** [aspnet/Blazor#456]
Is there something planned like a (as I like to call it) dynamic bind? Or is this maybe already possible?

For example in Javascript (Aurelia in this case) I'm able to do this:

``` <mdfield value.bind="formObject[objectPropertyName]"></mdfield>```

I use this to dynamically create forms from server data.
I don't how this is possible in Blazor right now, but would love to see it as a feature.

**Comment by SteveSandersonMS** [comment]
It’s C#, so you can access object properties in exactly the same way as in other C# code. If it’s a dictionary, you can iterate through it easily. If not, you can use reflection.
