### ISSUE TITLE
Update to AngleSharp 0.9.9.2

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#458]
It looks like https://github.com/AngleSharp/AngleSharp/issues/636 was fixed and released in [AngleSharp 0.9.9.2](https://www.nuget.org/packages/AngleSharp/0.9.9.2). Can we switch to this release and stop building our own tweaked version?

**Comment by SteveSandersonMS** [comment]
Maybe. @rynowak, do we still need it to have a customised name?

**Comment by rynowak** [comment]
If we're going to ship it in VS, there's a small risk that it will conflict with something else, which is unlikely to break unless Anglesharp has made binary-incompatible changes.

I say we try it for the next release and see what happens.

**Comment by SteveSandersonMS** [comment]
This was completed in #883
