### ISSUE TITLE
Dependency injection crashes if you try to inject two instances of the same type

### ISSUE THREAD

**Issue by rstropek** [aspnet/Blazor#462]
If you create a component that injects multiple instances of the same type, it compiles fine but throws an exception during runtime. Example:

```
@inject MyTransientService Transient
@inject MyTransientService Transient2
```

**Comment by SteveSandersonMS** [comment]
Thanks for reporting it. It's a bug in Mono, reported as https://github.com/mono/mono/issues/7944

**Comment by galvesribeiro** [comment]
Just to add more to the issue, I have the same problem using JSON.Net with Blazor.

To repro, call `Newtonsoft.Json.JsonConvert.SerializeObject(new { CurrentCount = currentCount });` and you will have the same problem.

![image](https://user-images.githubusercontent.com/4714040/38290539-1b316b9c-37b2-11e8-9ed7-bb8c57f92808.png)
