### ISSUE TITLE
Question on Blazor configuration (.blazor.config)

### ISSUE THREAD

**Issue by guardrex** [aspnet/Blazor#469]
RE: The remark in https://github.com/aspnet/Blazor/blob/0b3b84f1db4c628bd5c37a16c9c22f236e85d3ad/src/Microsoft.AspNetCore.Blazor.Server/BlazorConfig.cs ...

> TODO: Instead of assuming the lines are in a specific order, either JSON-encode the whole thing, or at least give the lines key prefixes (e.g., "reload:<someuri>") so we're not dependent on order and all lines being present.

... and just generally the notion of using a custom configuration loader ... I'm curious (and I don't see an open or closed issue on this): Why isn't the OOB config system used (i.e./e.g., *blazorsettings.json* and a built new config builder with `.AddJsonFile("blazorsettings.json")`?

**Comment by SteveSandersonMS** [comment]
That file isn’t for user configuration. It’s a system-generated file for controlling how the client app gets hosted in a server app. 

Basically, you can ignore that file entirely.

**Comment by PtwHub** [comment]
Upgraded to 0.3.0, clean, rebuild. No errors but Runtime: FileNotFoundException: Could not find file 'C:\_d\_h\app1\cliotweb1.Server\bin\Debug\netcoreapp2.0\app1.Server.blazor.config'.

trying to figure... any tips appreciated.
