### ISSUE TITLE
Blazor client class Program not public

### ISSUE THREAD

**Issue by fileman** [aspnet/Blazor#472]
the "Program" class created by new Blazor project (not hosted) not set as public on VS 15.7preview2 - Blazor 0.1.0 ... I can't find other issue for this, I hope is not a duplicate.

**Comment by fileman** [comment]
even with myget 15.7.10160 vsix

**Comment by danroth27** [comment]
Looks like this is only the case for the standalone Blazor template. 

@SteveSandersonMS I assume this isn't intentional?

**Comment by fileman** [comment]
@danroth27 @SteveSandersonMS Solved with PR #574 if and when is merged

**Comment by SteveSandersonMS** [comment]
@danroth27 I just checked, and the default new console app also *doesn't* use the `public` modifier on either the `Program` class or its `static Main` method. So to be consistent with that, don't you think we should instead *remove* the public modifier from the "Hosted" template?

**Comment by SteveSandersonMS** [comment]
Oh wait, I remember why it’s there. In the hosted template, it has to be public so the server middleware can reference it. Yes let’s update the standalone in case people try to add it as a reference from a server project.

**Comment by fileman** [comment]
Yes, this is my case, I've used standalone project to an existing webapi project
