### ISSUE TITLE
CSHTML file parser not recognizing HTML within comments as comments

### ISSUE THREAD

**Issue by tomdowdell** [aspnet/Blazor#477]
CSHTML file comments that happen to include HTML cause problems. Ideally, anything wrapped within a comment is treated as a comment.

I observed this while creating JS functions to dynamically construct elements. I'd temporarily paste working HTML code in a comment and use it as a template to write the code.
```
<
<script>
	window.Blazor.registerFunction("foo", function (parentId, index, newChildId, nativeStyle) {

		// code here

	**/*
	 <div id="e_x" class="mylist" style="margin:20px">
	  <input class="xText" value="wango"/>
	  <div id="xArrow" class="arrow"></div>
		<div>abc</div>
	  </div>
	</div>
	 */**

	})
</script>
>
```

**Comment by rynowak** [comment]
Can you make sure the formatting of your post is correct now that I added the backticks to mark it as code?

Comments in Razor are delimited with `@* ...comment text here *@`. Does that help?

**Comment by SteveSandersonMS** [comment]
Closing because based on @rynowak's comments, this appears to be working as expected.

@tomdowdell If you disagree, could you please report this to http://github.com/aspnet/razor?
