### ISSUE TITLE
HttpClient enhancements - binary data

### ISSUE THREAD

**Issue by SvenEV** [aspnet/Blazor#479]
Currently `HttpClient` cannot be used to retrieve binary data such as images. The response content appears to get truncated at zero bytes when the HTTP response is returned from JS back to .NET. In some cases, requests just fails with "SCRIPT7017: Memory index is out of range" (Edge) or "RuntimeError: memory access out of bounds" (Chrome) without anything being returned.

I found a TODO regarding this issue in the code (see below). Anyway, I think this should be tracked and I hope this isn't a duplicate.

https://github.com/aspnet/Blazor/blob/a9c45fe78ac18b6bd524904b40896c249f9f09c0/src/Microsoft.AspNetCore.Blazor.Browser.JS/src/Services/Http.ts#L32-L47

**Comment by SteveSandersonMS** [comment]
Thanks @SvenEV - it's good to have an issue to track this. So, starting a list of possible future enhancements:

* Reading binary data
* Streaming responses

**Comment by rockfordlhotka** [comment]
Also byte arrays. I ran into this last night, and changed my code to base64 encode the data, but it would be more efficient to just pass the binary byte array like on other platforms.

**Comment by yowl** [comment]
Also posting binary data that is not from files, e.g. binary serializing DTOs as Json is not the most efficient for large datasets.

**Comment by yowl** [comment]
And consuming    Content-Type: application/msbin1 web services would be helpful for large data transfer apps.

**Comment by RemiBou** [comment]
- different model depending on response code (bad request won't send the same paylone as ok)

Don't know if it's in the scope of this issue

**Comment by SteveSandersonMS** [comment]
@rockfordlhotka `byte[]` is now handled for both sending and receiving thanks to #815

**Comment by gojanpaolo** [comment]
Hello, I would just like to ask if you someone could provide an example on how to use this newly added feature to upload files from the client and send it to the server? I'm completely new to web development so any help would be greatly appreciated. Thanks!

**Comment by smartprogrammer93** [comment]
@gojanpaolo
An easy google search would lead you to this.

https://remibou.github.io/Upload-file-with-Blazor/
Try it out and let me know if you need help

**Comment by gojanpaolo** [comment]
@smartprogrammer93 yes I found that. But it needs JS Interop. I thought this merged PR solved not having to use JS Interop during file upload?

**Comment by smartprogrammer93** [comment]
@gojanpolo

No need for steing builder. The code you see is a bit outdated. The response you will get is probably a string so T should be a string. I am not sure if you can use byte array instead

**Comment by gojanpaolo** [comment]
@smartprogrammer93 Please see updated https://github.com/aspnet/Blazor/issues/479#issuecomment-498920109. I tried to follow the blog as best I can but it still doesn't seem to work.

**Comment by smartprogrammer93** [comment]
@gojanpaolo

I read the code again. And in this case, T should be a string builder. But i am pretty sure if you change the js code to return the content right away instead of a data object with a content property inside it, it could work with steing

**Comment by danroth27** [comment]
@gojanpaolo If you're still hitting problems with using HttpClient to send/receive binary data in Blazor please open a new issue in the https://github.com/aspnet/aspnetcore repo with the steps and code needed to reproduce the issue and we'll take a look.

**Comment by gojanpaolo** [comment]
@smartprogrammer93  thanks for the suggestions, I tried using StringBuilder instead but doesn't work too. Not sure how to change the js code, it's too foreign for me.

@danroth27 Thank you for responding. I think the issue I'm having is more on how to get file uploading work in client-side blazor. As commented above, it looks like I need to use JSInterop, but I have no experience in javascript. I was hoping there's a way to do it in C#.
