### ISSUE TITLE
Are there plans for permitting TCP communication from the users browser to their network?

### ISSUE THREAD

**Issue by StingyJack** [aspnet/Blazor#481]
This was something that could be done in silverlight, and was necessary for some printers and other industrial devices. Its basically "open a tcp socket and send text as unicode". Is something like this in the plans for Blazor?

**Comment by floreseken** [comment]
Blazor is running in the browser sandbox and cannot do more than javascript can network wise. So technically this is not possible.

**Comment by SteveSandersonMS** [comment]
Thanks for answering @floreseken!

**Comment by jsakamoto** [comment]
@StingyJack This topic is not related "Blazor", by the way, if those industrial devices can be talking via websocket, then your systems may be integrated with "Blazor" SPA, I think.

You can also create your own adapter native programs that talks with Blazor SPA via HTTPS and convert those communicatiosns to talking with other devices via traditional TCP text protocol.
