### ISSUE TITLE
Allow Blazor entry method to pre register .net methods

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#483]
It would be good if the Blazor entry point could pre-register common .net methods so that interop methods can be cached at load time and prior to calling them

**Comment by grahamehorner** [comment]
I'm thinking that the boot.ts could possibly look for an optional file on the server that simply holds a list of assembly names, namespace.type and methods, these are loaded into the client platform cache 

```
const registeredAssemblies: { [identifier: string]: number } = {}; 
const registeredClasses:    { [identifier: string]: number } = {}; 
const registeredMethods:    { [identifier: string]: MethodHandle } = {}
```
using a function/promise that iterates over the list using the findMethod

The idea would be to allow ahead of time loading of the .net methods and hopefully give a performance boost

**Comment by SteveSandersonMS** [comment]
What would make that faster than caching them on demand?

**Comment by grahamehorner** [comment]
I’m thinking that if a developer knows that a method(s) in a application will be called, then pre loading the handles on start will make sure that these are available and also catch any issues where a assembly is loaded but is missing a required method

**Comment by SteveSandersonMS** [comment]
Since I'm unclear that it would help (or that there's a problem to be solved), I'll close this for now. However if anyone wants to continue discussion on this thread please feel free!
