### ISSUE TITLE
uBlock Origin prevents the demo app from loading

### ISSUE THREAD

**Issue by AWulkan** [aspnet/Blazor#485]
The [demo app](https://blazor-demo.github.io/) fails to load when using uBlock Origin (popular ad blocker) on Chrome. I don't know if it's anything you can solve, but it's worth knowing about.

Successful load:
![success](https://i.imgur.com/ddE13ra.png)

Failed load:
![fail](https://i.imgur.com/VPtiuI8.png)

Chrome version: 65.0.3325.181 (Official Build) (64-bit)

**Comment by benaadams** [comment]
Do you have a custom block list, or have blocked github.io before? Works ok for me:

![image](https://user-images.githubusercontent.com/1142958/38334764-2e39296c-3854-11e8-8218-0f75be4d39e5.png)

**Comment by AWulkan** [comment]
@benaadams No custom list, and I have not blocked Github before.

Hmm, weird that it works for you, but not me.

**Comment by benaadams** [comment]
Hmmm... still works

I see `github.io/*.wasm$third-party` in Easy privacy, but that doesn't seem to be blocking it for me

**Comment by AWulkan** [comment]
@benaadams I tried disabling just the EasyPrivacy list and it works. But when I enable it and update to the latest version it blocks the Blazor app.

Have you added any personal whitelisting or other settings? I'm using the default settings.

**Comment by benaadams** [comment]
> I tried disabling just the EasyPrivacy list and it works.

Might be the `github.io/*.wasm` rule blocking 
`https://blazor-demo.github.io/_framework/Mono/dist/wasm/mono.wasm` then?

**Comment by benaadams** [comment]
Strange thing to block...

**Comment by AWulkan** [comment]
@muqeet-khan Thanks, I tried those links now and they both work for me. So the filter specifically blocks wasm files on Github.

**Comment by AWulkan** [comment]
I now tested on another computer at a different location and I still can't access the blazor demo due to the filter. So the issue should affect millions of uBlock Origin users running with the default settings as far as I can see.

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know. I'll fold this issue into #172 since it fits the general theme of badly-behaved third-party software interfering based on URLs.

I expect if we have to we could just serve the wasm file without any filename extension - it won't make any difference to the browser.
