### ISSUE TITLE
Layout Engine

### ISSUE THREAD

**Issue by ChicagoDave** [aspnet/Blazor#49]
Replace Razor with XAML compiling to OpenGL.

**Comment by grahamehorner** [comment]
I would like to see XAML support also, but think that Razor is still very relevant and more light weight and IMHO wouldn’t replace Razor but add XAML.

**Comment by SteveSandersonMS** [comment]
Thanks for the idea! It sounds very ambitious :)

For clarity, though, XAML is definitely not what we're initially trying to achieve here. Our goal is to build a programming model that uses normal web concepts (HTML and CSS) alongside .NET code.

If anyone's keen to do XAML, you are welcome to try to build that on the general client-side .NET stack we're offering.

**Comment by grahamehorner** [comment]
FYI https://github.com/praeclarum/Ooui may also be of interest to those people wishing to use xaml as a UI design language inside a browser

**Comment by JeffMushmo** [comment]
I went ahead and started building a Xaml engine that runs natively in the browser. You can check it out here: [https://github.com/XamlEngine/Samples](https://github.com/XamlEngine/Samples)
