### ISSUE TITLE
@bind and @onchange on the same element doesn't work

### ISSUE THREAD

**Issue by FredBlondel** [aspnet/Blazor#524]
I've try to set both @bind  and @onchange but onchange is not thrown
Ex:
```
            @foreach (var todo in todoList)
            {
                <tr>
                    <td><input @bind(todo.Done) type="checkbox" @onchange(a => LastChecked(todo)) /> </td>
                    <td>@todo.Name</td>
                </tr>
            }
```

Separatly, evething works fine, ie:
`<input type="checkbox" @onchange(a => LastChecked(todo)) />`

Or

`<input @bind(todo.Done) type="checkbox"  />`

**Comment by humbersoft** [comment]
I think the current bind approach only allows one event handler for the Javascript onchange event. So one is replacing the other. Then @bind syntax after transpiling to C#, will attach a event handler to the javascript onchange event.  

The new syntax coming in the 0.2 release will allow you to attach to different events which may help you. I am not sure if it will allow more than one event handler like what you want to do here.

**Comment by SteveSandersonMS** [comment]
As @humbersoft mentions, the `@bind` and `@onchange` syntaxes are about to be replaced.

With the new `bind=` and `onchange=` syntax, you'll still not be able to use `bind` and `onchange` together, but we'll document how you get to combine the effects of both if you want. And if this turns out to be problematic for people we'll find a way of letting them be used simultaneously.

**Comment by FredBlondel** [comment]
Ok, thanks for your anwsers.

So, I think if iwant to bind an element to an item, and be notified by any changes, I have to bind the object, and make the bound object "observable". I'm I right ?

**Comment by SteveSandersonMS** [comment]
@FredBlondel You do something like:

    <input value=@MyProperty onchange=@(eventArgs => { MyProperty = eventArgs.NewValue; DoSomethingElse();  }) />

or

    <input value=@MyProperty onchange=@HandleMyPropertyChange />

with

    void HandleMyPropertyChange(UIChangeEventArgs evt)
    {
        MyProperty = evt.NewValue;
        DoSomethingElse();
    }

Note that I might be misremembering the precise method/property names, but this is the shape of it.

**Comment by FredBlondel** [comment]
Ok, thanks !

**Comment by mashbrno** [comment]
In *preview3* there is `Value` property at `UIChangeEventArgs` instead of `NewValue`.

**Comment by baartho** [comment]
This issue is still happening. Is there a foreseeable fix?

**Comment by bearlylegible** [comment]
Still experiencing this issue

**Comment by danroth27** [comment]
@baartho @bearlylegible As @stevesandersonms mentioned [above](https://github.com/aspnet/Blazor/issues/524#issuecomment-380415799) this is not considered a bug. If you want to set the value and hook onchange then you need to use the suggested syntax.

**Comment by bearlylegible** [comment]
@danroth27 my mistake I misunderstood the previous response.

**Comment by cedwards-telis** [comment]
I keep forgetting about this and running in to it again.

I'd say that if possible it would be a worthwhile enhancement to chain the events.  I can see how it might causes difficulties however,

**Comment by mashbrno** [comment]
Or to cause a compile error when used both.

Dne čt 22. 8. 2019 18:05 uživatel cedwards-telis <notifications@github.com>
napsal:

**Comment by desalbres** [comment]
Hello, I had the same problem:

The following code fixed the issue:

<InputText value="@value" @onchange="change" class="form-control"></InputText>

@code {
    [Parameter]
    public string value { get; set; }    
    [Parameter]
    public EventCallback<string> valueChanged { get; set; }    
    void change(UIChangeEventArgs evt)
    {       
        valueChanged.InvokeAsync(evt.Value.ToString());     
    }
}

Then I can use the component:

   <CustomTextbox @bind-value="@user.Title" ></CustomTextbox>

**Comment by DataJuggler** [comment]
Microsoft needs to rethink having bind and onchange. The suggested approach here doesn't in Rc1.

I need to know when the list changes, so I can perform save.

I can't figure out how to save To Do list items or if the list changes.

BindingList didn't work either, or at least my ListChanged event never fired.

**Comment by hfmm99** [comment]
Here there's a workaround for this:

**HTML:**
`<input type="search" class="form-control" placeholder="Search..." @bind="SearchTerm" />`

**C#:**
```
    private string searchTerm;
    public string SearchTerm
    {
        get { return searchTerm; }
        set { searchTerm = value; Search(); }
    }
```
