### ISSUE TITLE
Uploading/Reading files?

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/Blazor#527]
Hi,

does any best practice for uploading files into a Blazor-Application exist?
I guess, using the IFormFile Interface from AspNetCore.Http will not work?

Regards, Sascha

**Comment by SteveSandersonMS** [comment]
It's not something we've built anything special for. In general you can use arbitrary HTML elements inside a Blazor component, so you can use `<input type=file>` to do normal full-page-refresh uploads.

Submitting the file to the server via an `HttpClient` request isn't currently supported, though I'll add it to the tracking issue #479.

**Comment by RemiBou** [comment]
@SteveSandersonMS now that the linked issue is closed, any thought on how we culd achieve file upload without full page refresh ?

**Comment by SteveSandersonMS** [comment]
You can use `HttpClient` to do a POST or PUT request containing the data you need. If you want to get that data from an `<input type=file>`, you'd have to get the binary data via something like https://stackoverflow.com/a/32556944 using JS interop.

**Comment by creeeeeg** [comment]
Could you use something like [IFormFile ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iformfile?view=aspnetcore-2.1) to get access to the [CopyTo, CopyToAsync,OpenReadStream] methods without having to go out to the JS interop?

I'm not really sure, just wondering... Blazor newbie here.

**Comment by SteveSandersonMS** [comment]
@RemiBou Is that really a blocking problem? The data transfer is all local to the process and in memory. The buffer is going to have to be copied regardless (to get from the JS memory space into the .NET heap), so if that happens via base64 representation it's not really a major difference. The base64 representation will consume an extra ~30% memory but for file uploads the total amount of data is typically huge, and it's not like that extra data is being sent over the network.

**Comment by RemiBou** [comment]
Ok got it thanks

**Comment by RemiBou** [comment]
I managed to do it, you can find the details here https://remibou.github.io/Upload-file-with-Blazor/

**Comment by rathga** [comment]
Just checking in on this given we are 10 months down the road :) @RemiBou @SteveSandersonMS is RemiBou's solution still the best way of going about this for now?

**Comment by SteveSandersonMS** [comment]
The JS interop APIs have changed (e.g., there's no more `RegisteredFunction`), but the overall principles still look good.

**Comment by Tirumalesh8686** [comment]
"https://github.com/RemiBou/Toss.Blazor"

Im trying to run the code from above link.....I resolved most of the errors but still there is a error coming up saying 
Severity	Code	Description	Project	File	Line	Suppression State
Error:	Could not find file 'D:\User\\Toss.Blazor-master\Toss.Client\bin\x64\Release\netstandard2.0\Toss.Client.dll'.	Toss.Server	C:\Program Files\dotnet\sdk\3.0.100-preview8 013656\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets	54	

Can u help me resolve this???

**Comment by Tirumalesh8686** [comment]
Im getting the above mentioned error when im trying to build Toss.Server....

When im building the Toss.Client...I got the folowing warnings...

NETSDK1080	A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference.	Toss.Tests.E2E	C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	154	


NETSDK1080	A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference.	Toss.Tests
	C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	154

**Comment by Tirumalesh8686** [comment]
"https://github.com/RemiBou/Toss.Blazor"

All required files are from the above link..........
(And Im using ASP.Net Core 3.0 preview8)

**Comment by RemiBou** [comment]
I think this is not the right place for this issue, can you post it on the Toss repo ? I'll have a look. Thanks @danroth27
