### ISSUE TITLE
How to do Forms Validation on Blazor?

### ISSUE THREAD

**Issue by jonathanperis** [aspnet/Blazor#529]
Is it possible in Blazor's current implementations to do form validations as in ASP.NET Core?

**Comment by rstropek** [comment]
Blazor does not contain specific functions for form validation. However, with its existing [data binding](https://learn-blazor.com/pages/data-binding/) features, you should be able to implement any validation logic. Are you missing specific features?

**Comment by danroth27** [comment]
We do plan to add some additional features around forms and validation. These are tracked by #17

**Comment by PeterHimschoot** [comment]
I've written a blog on forms validation: https://blogs.u2u.be/peter/post/blazor-forms-validation Maybe this gets you started.
