### ISSUE TITLE
VS 2017 Preview 3 does not load blazor template projects

### ISSUE THREAD

**Issue by chassq** [aspnet/Blazor#530]
Updated to VS 2017 15.7.0 Preview 3 and Blazor projects had errors loading. I assume I need to wait for a new update to the language extension VSIX? I think the road map said should be this week for next Blazor preview release?

**Comment by RichardC64** [comment]
I updated too but:
No errors loading existing 0.1 project.
No errors creating a new Blazor project
No errors creating a new Blazor + Server project.

What kind of errors do you have?

**Comment by chassq** [comment]
See the attached ActivityLog.Setup.xml. I think this was recorded on the first opening of a Blazor solution after the update to Preview 3 of VS 2017. However, since then I have closed VS 2017 and restarted the VM and now the projects open just fine.
[ActivityLog.Setup.zip](https://github.com/aspnet/Blazor/files/1895057/ActivityLog.Setup.zip)

This activity log seems to contain many warnings and errors related to registry collisions..

Let me know if I can provide anything else.

**Comment by DNF-SaS** [comment]
Here also no problems with 15.7.0 Preview 3 and Blazor.
Initial Install was made using 15.7.0 Preview 2.

**Comment by chassq** [comment]
Ok going to close for now. Seems like maybe an isolated issue to my installation...

**Comment by SIkebe** [comment]
@chassq I also have no problem with preview 3.
Please let us know if you find out anything!
