### ISSUE TITLE
Interop with another wasm module?

### ISSUE THREAD

**Issue by roozbehid-ic** [aspnet/Blazor#534]
I have an application that call C++ dynamic library.
I managed to compile that C++ library using emscripten (still confused about static vs dynamic)
But it seems dllimport does not work for using it with wasm modules?
Is there anyway to do that?

**Comment by danroth27** [comment]
@kumpera

**Comment by SteveSandersonMS** [comment]
@roozbehid-ic It's best to raise this in the Mono repo because it's a question about an underlying Mono capability. Hope that's OK!
