### ISSUE TITLE
Add dependency from Blazor.Build -> Razor.Design

### ISSUE THREAD

**Issue by rynowak** [aspnet/Blazor#548]
Discussed this in gitter, it's not clear from looking at our templates which version of `Razor.Design` is supposed to match a given build of the Blazor packages, because we use `PrivateAssets=All`.

I think instead we should use `PrivateAssets=None` and bake a package reference in `Blazor.Build`, then we can remove `Razor.Design` from the template and rely on transitivity.

@SteveSandersonMS  any reason why we shouldn't do this in `dev`?

**Comment by SteveSandersonMS** [comment]
Sounds good to me!

**Comment by rynowak** [comment]
Great, I'll take this one then.

**Comment by rynowak** [comment]
79a620a

**Comment by rynowak** [comment]
Tagging this an an enhancements. We will need to add to the release notes that users can remove the package reference to Razor.Design.

**Comment by SteveSandersonMS** [comment]
@rynowak Will you be rolling this back following the email discussion?

**Comment by rynowak** [comment]
No. The email discussion is related to issue #662 and whether we depend on 2.1.0-RC.

We currently depend on 2.1.0-preview2-final

**Comment by rynowak** [comment]
I've deleted my comment on #662 about us using the RC in 0.3.0 because apparently that's not possible.
