### ISSUE TITLE
Unable to build source code

### ISSUE THREAD

**Issue by babula38** [aspnet/Blazor#549]
Steps to reproduce:-

1. clone the repo.
2. Vs2017 preview 3 is installed.
3. execute the build.cmd.
4. open the solution in Visual studio.
5. try to build.
**tried multiple time to clone the repo and build but no luck. The last thing is pending Reinstall, vs2017 preview again and try.**

![github](https://user-images.githubusercontent.com/4153708/38635891-5ff4c944-3de4-11e8-926e-1f6f6b2f0110.PNG)

**Comment by talha-sayed** [comment]
What's the output from build.cmd? Was it successful?

I just performed a clean build and it builds successfully for me without errors in Visual Studio.

**Comment by talha-sayed** [comment]
Never mind. I was on an older commit. I got the latest and I am facing the same issue as you now.

**Comment by rynowak** [comment]
If those errors are coming from the template projects you safely just unload those. (right click -> unload)

![image](https://user-images.githubusercontent.com/1430011/38640032-e457772a-3d87-11e8-9543-d9b6806b3f14.png)

@SteveSandersonMS do you have a fix in mind for this? Options I can think of:
- Add the Blazor feed to the top level nuget.config
- Remove the projects from the solution since they aren't supposed to build anyway - the content would still be part of the solution since it's include by the template project

**Comment by bastienJS** [comment]
@babula38  I just wanted to create the same issue, but then I saw you have the same problems as I :-)
How did you fix the first error in your top screenshot, about the unable to find package microsoft.aspnetcore.blazor.cli ?

**Comment by rynowak** [comment]
Building the Blazor repo will require that the copy of `dotnet` installed by the repo is on your path.

Visual Studio using the PATH environment variable to determine which `dotnet` to use, and then uses `dotnet` to determine which SDK to use. If you're getting issues loading a project can you please right click and try Reload Project? This should hopefully produce some kind of error message or output in the output window.

**Comment by SteveSandersonMS** [comment]
This will be resolved by #559

**Comment by babula38** [comment]
@bastienJS I have removed the template, E2E test,MonoSanity,Mono and BasicTestApp projects from the  solution  to make it compile. 
@rynowak  below is the error i am getting when trying to reload the MonoSanity client.
![load error](https://user-images.githubusercontent.com/4153708/38767017-65b2d036-3ff8-11e8-85f0-f84f17b96f14.PNG)

**Comment by bastienJS** [comment]
@rynowak  I hope its ok that I post the versions of donet on my path because I get the same error as @babula38 

![image](https://user-images.githubusercontent.com/5945955/38830593-23240f3e-41bd-11e8-9f81-52ed4cf767d3.png)

**Comment by SteveSandersonMS** [comment]
@bastienJS You need to have `2.1.300-preview2-008533`, which should be downloaded and used automatically if you run `build.cmd` from the solution root. Then you need to launch VS from the command prompt that has `2.1.300-preview2-008533`, not just from your taskbar or similar.

**Comment by rynowak** [comment]
I'm planning to update the repo instructions with the setup that most ASP.NET Core team members ues.

**Comment by dlr1** [comment]
I am using the following and seems tow work. Are these combinations legit?
```
 <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.0-preview2-final" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Browser" Version="0.3.0-preview1-10220" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.3.0-preview1-10220" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.3.0-preview1-10220" />
  </ItemGroup>
```

**Comment by rynowak** [comment]
I've update the documentation regarding building the repo. https://github.com/aspnet/Blazor/blob/dev/README.md#building-the-repo

And using CI builds https://github.com/aspnet/Blazor/blob/dev/README.md#using-ci-builds-of-blazor

Please check those out and let us know if there's anything else we need to do to help

**Comment by rynowak** [comment]
> I am using the following and seems tow work. Are these combinations legit?

**Comment by rynowak** [comment]
can you post the content of `artifacts\logs\vsix-restore.rsp` ?


Something is generating the wrong command

**Comment by rynowak** [comment]
My guess is that something isn't quoted correctly

**Comment by rynowak** [comment]
@bastienJS - I pushed a change to dev that I think should solve your issue. let me know if this helps.
