### ISSUE TITLE
Code Behind files (.cshtml.cs) support

### ISSUE THREAD

**Issue by jonathanperis** [aspnet/Blazor#55]
Hello! 

What do you think of a code separation model as it is currently used in ASP.NET Core Razor Pages? But instead of having HTTP Request Handlers (OnGet, OnPost) A class structured to use the methods that will be called from the View (HTML pages, CSHTML)

**Comment by SteveSandersonMS** [comment]
You can use the @inherits directive to achieve this. Just inherit from a class that itself inherits from `BlazorComponent`. Then your "code behind" class can override the lifecycle methods like "OnParametersUpdated" and others that we haven't yet implemented like "Init".

**Comment by SteveSandersonMS** [comment]
Oh no wait - we haven't implemented @inherits in the Blazor Razor compiler yet. But that will be how it's done.

**Comment by SteveSandersonMS** [comment]
Added https://github.com/aspnet/Blazor/issues/57 to be clearer about where we are with basic Razor features.
