### ISSUE TITLE
Add compiler error if there's a <script> element inside a component

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#552]
This addresses a usability issue. We often hear of people trying to put `<script>` elements inside components and being surprised about the effects.

It's almost always a mistake to put a `<script>` element inside a component, because fundamentally, components are about adding and removing things dynamically inside the DOM. `<script>` elements don't work that way, in that once they are added, their effects can never be removed. Similarly, trying to use C# expressions inside a `<script>` content will not work as expected (we can't replace the effects of already-registered JS once the expression changes value). The *only* scenario I can think of where a `<script>` element does something vaguely useful inside a component would be for some kind of debug logging, e.g., `<script>console.log('rendering now')</script>`, but that's not what anyone's been doing AFAIK. What developers really should do is put `<script>` elements into their `index.html`, where they will behave as expected.

**Proposed solution**

We'll make it a compiler error to have `<script>` inside a Blazor component. The error message will say something like:

*Script tags should not be placed inside components because they cannot be updated dynamically. To fix this, move the script tag to the 'index.html' file or another static location. For more information see http://some/link*

... and the help docs that we linked to will also say something like:

*If you need to override this, add an attribute named "suppress-error" with value "BL9992" to the <script> tag, but only if you know what you are doing, as in most cases it would be a mistake to do this*.

**Comment by SteveSandersonMS** [comment]
No, definitely an error! You can't have local scripts, that's the whole point 😃

**Comment by tjbortz1s** [comment]
Lets say I want to write a "Canvas" component that has a bunch of Csharp calls to javascript functions.  Would there be a way to go about doing that?

**Comment by SteveSandersonMS** [comment]
@tjbortz1s Yes, use the existing .NET->JS interop APIs. This doesn't involve putting a `<script>` tag inside your component. `<script>` tags go in `index.html`.

**Comment by aguacongas** [comment]
@SteveSandersonMS it could be an issue to integrate [web components](https://www.webcomponents.org/) if we cannot use local script, what you think ?  
Are you going to provide a way to create blazor components library with a mecanism to auto load those library's javascripts ?

**Comment by SteveSandersonMS** [comment]
@aguacongas Yes, we’ve already implemented a mechanism for creating redistributable packages of components that can load custom JS automatically. There’ll be full info about that in the 0.2.0 release blog post and docs, which we’re now targeting for Monday :smile:

**Comment by aguacongas** [comment]
great

**Comment by dotnetnoobie** [comment]
**implemented a mechanism for creating redistributable packages of components**

Does that mean you can make something like a select/dropdown component as an example, then pack it something like a NuGet package to share/reuse?

**Comment by SteveSandersonMS** [comment]
Yes

**Comment by Knudel** [comment]
Thank you Suchiman, that would indeed solve my problem.

**Comment by lakani** [comment]
i'm trying this, but its not working with me , am i missing something ???

my \wwwroot\index.html

`<script type="blazor-boot">
        
    // Register a very simple JavaScript function that just prints
    // the input parameter to the browser's console
    Blazor.registerFunction('say', (data) => {
        console.dir(data);

        // Your function currently has to return something. For demo
        // purposes, we just return `true`.
        return true;
    });

    </script>`


and my \Pages\FetchData.cshtml

`<button onclick=@CallJS>Call JavaScript</button>

@functions {
WeatherForecast[] forecasts;


private async void CallJS()
{
    // Simple function call with a basic data type
    if (RegisteredFunction.Invoke<bool>("say", "Hello"))
    {
        // This line will be reached as our `say` function returns true
        Console.WriteLine("Returned true");
    }

    // Call our function with an object. It will be serialized (JSON),
    // passed to JS-part of Blazor and deserialized into a JavaScript
    // object again.
    RegisteredFunction.Invoke<bool>("say", new { greeting = "Hello" });

    // Get some demo data from a web service and pass it to our function.
    // Again, it will be turned to JSON and back during the function call.
    //var customers = await Http.GetJsonAsync<List<Customer>>("/api/Customer");
    //RegisteredFunction.Invoke<bool>("say", customers);
}
`

**Comment by Suchiman** [comment]
@lakani the `Blazor.registerFunction` part must be in a script block following `blazor-boot`, don't touch `blazor-boot`

**Comment by lakani** [comment]
it works 💯

**Comment by sethi-ishmeet** [comment]
Thank you everyone for all the information you provided. 

I would like to know if there's a way we can only load the JS libraries based on the component? For example, let's say a specific JS file is only valid for one component. How can I possibly load the JS file when that specific component is called? 

We have a huge project with about 100 JS files, most of which specific to a single view. We would like to reuse them until we completely migrate to Blazor eventually. If I load all the JS files in `index.html`, I am concerned about the load time and performance issues that it would lead to.

**Comment by SteveSandersonMS** [comment]
@sethi-ishmeet I'd recommend writing a small bit of JS that loads other JS files, and then calling it from your components via the JS interop APIs.

On the other hand, it's worth trying to estimate how big your bundles would be if you just put them all into one file, e.g., using WebPack. You might find that because of compression, the combined size of all 100 JS files is much less than 100 times their average size. If the whole set with compression is < 100KB, for instance, you're probably much better just loading them all up front.

**Comment by sethi-ishmeet** [comment]
Thank you @SteveSandersonMS I think that'd solve our purpose.

**Comment by PaulNWms** [comment]
What is the best practice for inserting [MathJax ](https://www.w3.org/Math/MJ/Overview.html) into a component?  If you're not familiar, MathJax is a meta-language that looks like

`$$\cos(\theta) = \frac{a \cdot b}{\|a\| \cdot \|b\|}$$`

which is really syntactic sugar for something like

`<script type="math/tex">\cos(\theta) = \frac{a \cdot b}{\|a\| \cdot \|b\|}</script>`

This script block is then evaluated to (extremely verbose) [MathML](https://www.w3.org/TR/MathML3/) when a _static_ page is loaded.

I understand it's always possible to generate the MathML in a static page, and then paste that output into my component (which is what I've been doing).  But to keep the maintenance straightforward, I would prefer to be able to insert MathJax directly into my component using the $$…$$ syntax.

**Comment by danroth27** [comment]
@PaulNWms This issue is closed. I recommend posting a new issue with your question on https://github.com/aspnet/aspnetcore/issues so we can track your scenario.

**Comment by iAmBipinPaul** [comment]
It will be better to have new issue link on this template 

https://github.com/aspnet/AspNetCore/issues/new/choose

![image](https://user-images.githubusercontent.com/9201481/53543252-2b34a580-3b4a-11e9-9694-49eaa4dd7795.png)

**Comment by danroth27** [comment]
@iAmBipinPaul Good idea!

**Comment by danroth27** [comment]
@iAmBipinPaul Actually, it looks like the issue template does point folks to the https://github.com/aspnet/aspnetcore repo already.

**Comment by iAmBipinPaul** [comment]
@danroth27 I see.

May be we can have  something like this on template and it will show URL there directly.
```---
name: DO NOT LOG ISSUES HERE 
about:  Click here to create new issue  https://github.com/aspnet/AspNetCore/issues/new/choose
---
```
