### ISSUE TITLE
Pasting code into cshtml files results in unresponsive visual studio

### ISSUE THREAD

**Issue by srowan** [aspnet/Blazor#556]
### Title
Whenever I paste code into cshtml files, the IDE becomes unresponsive and disallows saving / editing for several seconds.   

### Functional impact
Makes it unreliable to copy/paste in cshtml files

### Minimal repro steps
1) Copy a line of code
2) Paste the line of code
3) Attempt to perform actions such as saving the file, control+z, or typing.   

### Expected result
IDE performs actions

### Actual result
Nothing happens, or the action happens some number of seconds later.

### Further technical details
Visual studio version: 15.7.0 Preview 3.0

I have a fresh install of .net core, vs 15.7 preview, and blazor and I'm working through the getting started tutorials.   

This happens even in a new instance of visual studio, on a freshly created blazor project.

**Comment by srowan** [comment]
Actually, this also happens when I create an ASP.net core application - so I suspect it's unrelated to blazor (or possibly even just my local install somehow).   I will close this out.

**Comment by srowan** [comment]
If anyone else gets this issue - I was able to fix it by disabling "format on paste" for html

`Tools -> Options -> Text Editor -> Html -> Advanced "Format on Paste" set to "False" `

**Comment by rynowak** [comment]
Yes, this is unrelated to Blazor. We expect this to be fixed in the next preview of VS. Thanks for the report.

**Comment by davidbmasterson** [comment]
srowan  thanks for the format on paste fix , it has been driving me made for a couple of weeks now  thanks again
