### ISSUE TITLE
Cannot update index.html 

### ISSUE THREAD

**Issue by ericgrantholland** [aspnet/Blazor#557]
After playing with index.html, I seem to get into a weird state where my changes to wwwroot/index.html do not propagate over to the debug folder(debug/netstandard2.0/dist). Only way to make changes is to edit the debug/netstandard2.0/dist/index.html file directly. Tried to delete index.html in the dist folder only to have the out-of-date index.html file come back from somewhere upon building in VS.

**Comment by dotnetnoobie** [comment]
I have had this same issue and seen a few people talking about it

What I had to do to make/force the index.html page to update was close VS and then I deleted all the **bin** and **obj** folders in all the 3 projects for a Client-Server Blazor app 

Then reopen and compile and it seems to update it..

This also seems to work when you get errors in **compiler** (like [pagename].g.cs files that are created by VS or the compiler?)  generated files and even when you have deleted the file from your project it does not disappear and causes an error, so I do the same process as above and it cleans them out

**Comment by rstropek** [comment]
I think this is a duplicate: #355 Should be fixed with 0.2.0 I think.

**Comment by SteveSandersonMS** [comment]
Yes, should be fine in 0.2.0. But if you have specific repro steps you could let me know and I’d verify it with 0.2.0. Thanks!
