### ISSUE TITLE
Task.Run() blocking main thread

### ISSUE THREAD

**Issue by struks93** [aspnet/Blazor#560]
Hi, I might be messing something up, but I was trying to do some CPU intensive work on background thread using `Task.Run()`, but it was still blocking the main thread (and UI). I'm using dotnet version `2.1.200-preview-007474` and the blazor template from `Microsoft.AspNetCore.Blazor.Templates`
My test page looks something like this:

```cs
@page "/async"

<h3>Test UI blocking</h3>
<input type="text" @bind(input)>

<hr>

<h3>Test UI blocking</h3>
<input type="text" name="" id="" placeholder="type here to test UI blocking">
<button type="button" class="btn btn-primary" @onclick(async () => await IterateAsync())>IterateAsync</button>

@functions
{
    string input = string.Empty;
    async Task IterateAsync()
    {
        Console.WriteLine($"Got input: {input}");
        if (int.TryParse(input, out var num))
        {
            await Task.Run(() => Iterate(num));
        }

        StateHasChanged();
    }

    private void Iterate(int num)
    {
        Console.WriteLine($"Iterating from 0 to {num.ToString()}");
        if (num < 0)
            num = num * -1;

        var j = 0;
        for(int i = 0; i < num; i++)
        {
            j = i;
        }
        Console.WriteLine("Done");
    }
}
```

**Comment by rstropek** [comment]
Mono on WASM is currently single-threaded and I don't think this will change in the near future. However, you can do async programming. There is a discussion in #139 about whether to run Blazor in a background thread without blocking the UI. Maybe this discussion is interesting for you.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @rstropek!

**Comment by SteveSandersonMS** [comment]
For anyone else reading, the basic principle is that async I/O works fine, but you can't do multiple streams of CPU-blocking work in parallel. Just like has always been the case in browsers and Node.

**Comment by struks93** [comment]
Thanks for the answer, this cleared things up a bit for me 👍 .
