### ISSUE TITLE
Format Document command adds incorrect identation

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Blazor#569]
When you call `Edit\Advanced\Format Document` it does this

``` HTML
@page "/counter"
    <h1>Counter</h1>

    <p>Current count: @currentCount</p>

    <button @onclick(IncrementCount)>Click me</button>

    @functions {
    int currentCount = 0;

    public int IncrementAmount { get; set; } = 1;

    void IncrementCount()
    {
        currentCount += IncrementAmount;
    }
    }
```

All the lines after first a moved 1 tab forward

**Comment by danroth27** [comment]
You're correct that this issue isn't specific to Blazor. I'm told by the VS folks that the next preview update for VS2017 15.7 should address these issues.

**Comment by RyoukoKonpaku** [comment]
@danroth27 that sounds great. Although it's minor it does kinda throw me off when doing Razor MVC in general, so I guess this is good news overall 😄
