### ISSUE TITLE
Binding to objects

### ISSUE THREAD

**Issue by dlr1** [aspnet/Blazor#576]
Will the Bind syntax allow us to bind to objects instead of just primitive types. It throws an error
"Error: System.ArgumentException: 'bind' does not accept values of type WebApplication1.Pages.Customer. To read and write this value type, wrap it in a property of type string with suitable getters and setters."
Here is my code
```
 <select class="form-control" bind="SelectedCustomer">
        @foreach(var item in Customers)
        {
            <option value="@item">@item.Name</option>
        }
    </select>
```

**Comment by floreseken** [comment]
The syntax is: @bind(SelectedCustomer) (for 0.1)

**Comment by dlr1** [comment]
I am using last friday's build
``` 
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.0-preview2-final" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Browser" Version="0.3.0-preview1-10206" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.3.0-preview1-10206" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.3.0-preview1-10206" />
  </ItemGroup>
```

**Comment by rstropek** [comment]
You can check the current status of supported types in https://github.com/aspnet/Blazor/blob/dev/src/Microsoft.AspNetCore.Blazor/Components/BindMethods.cs

**Comment by SteveSandersonMS** [comment]
This could make sense for “select”, but would not for any other type of form control. 

We *might* do it for select at some point, but it will depend on what usage patterns arise and what level of community demand there is. 

Thanks for the suggestion!

Closing as it’s not a planned work item for the time being.

**Comment by brzezinol** [comment]
How to bind select to object which is dictionary item.
For example :
new DictionaryItemModel(){
 Id = 981, /* hidden id */
 Description = "Some visible desc with utf chars"
}

<select id="select-box" @bind="@SeletedDictionaryItem">
    @foreach(var item in Lista){
        <option value=@item.Id>@item.Description</option>
    }
</select>

The only samples I saw is using only description.
It is impossible to bind and search using description bcause it is antiprogramming :)
