### ISSUE TITLE
Does validation is already in framework?

### ISSUE THREAD

**Issue by babula38** [aspnet/Blazor#584]
Validation is not reflecting in the UI.

- Create a ```<input type="number" @bind('some property')/>```

- try to write some text
Expected:- it should some validation error.

**Comment by RyoukoKonpaku** [comment]
It isn't implemented yet, you can track the issue here #17.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @RyoukoKonpaku!

**Comment by babula38** [comment]
Great
