### ISSUE TITLE
TDD with Blazor

### ISSUE THREAD

**Issue by Doan-Van-Tuan** [aspnet/Blazor#585]
I think all code should be testable in a seamless way using popular test frameworks such as xUnit or NUnit.
Is there any provision for that in Blazor? Can I develop my web app with Blazor with TDD easily, seamlessly without heavy framework such as Selenium?

**Comment by SteveSandersonMS** [comment]
#13 covers this. The plan is to provide a unit test helper library that lets you run your components inside unit tests (e.g., with xUnit, etc.), triggering events and making assertions about the rendered output.

**Comment by Doan-Van-Tuan** [comment]
Thanks, @SteveSandersonMS,
This is awesome. This is the first time I'm excited about an UI framework in quite some time. Really looking forward for this Blazor!
