### ISSUE TITLE
Question- It is not clear how I would integrate with existing java script libraries like angular

### ISSUE THREAD

**Issue by jvelezc** [aspnet/Blazor#588]
Hello All:

As you all know there are a ton of JS libraries i.e. kendo, devexpress, and all sorts of NPM plugins with tons of pre-baked in functionality.  What is the integration story or leveraging the good work from the community in Blazor. Should blazor team be considering how to leverage  Angular and instead of competing a technology how one could leverage both frameworks?

**Comment by dlr1** [comment]
I did not try, but you should be able to use Angular Elements feature (V6) and should be able to drop them like regular html elements

**Comment by brunopbarrote** [comment]
On [Learn Blazor](https://learn-blazor.com/architecture/interop/) there is a sample using a simple auto complete from Telerik KendoUI, maybe it could help you find out.

**Comment by SteveSandersonMS** [comment]
It’s not yet implemented, but #15 covers the need to be able to pull in packages from NPM.
