### ISSUE TITLE
Localhost Not accessible after upgrade

### ISSUE THREAD

**Issue by Amine-Smahi** [aspnet/Blazor#590]
After upgrading blazor from 0.1 to 0.2 and executing the default project on Visual Studio 2017 (15.7) , The default browser opens and ask to download an app from the Windows store.

![image](https://user-images.githubusercontent.com/24621701/38890278-d880fa98-4278-11e8-8321-af057022a45f.png)

**Comment by SteveSandersonMS** [comment]
That’s super weird. It certainly doesn’t happen for me. Do you have any repro steps based on Blazor I stalked into a clean machine?

**Comment by Amine-Smahi** [comment]
reinstalling the dotnet sdk fixed the issue
