### ISSUE TITLE
Dotnet version not updating

### ISSUE THREAD

**Issue by Amine-Smahi** [aspnet/Blazor#592]
After downloading and installing the dotnet  version 2.1.300-preview2-008533 from the official Microsoft website , i noticed that the dotnet version number doesnt update it always say 2.1.300-preview1-008174 , i tryed to install it again but stil get the same results , so i cant get the latest blazor update ( v0.2 )

![image](https://user-images.githubusercontent.com/24621701/38892326-d71fef64-427e-11e8-9e5b-49b9c35fce0a.png)

**Comment by floreseken** [comment]
Have you edited your global.json according to the upgrade instructions?

**Comment by danroth27** [comment]
@Amine-Smahi Typically the .NET Core SDK is installed under program files. I'm wondering which dotnet.exe is being run. Do you possibly have multiple dotnet.exe files on the path?

The other thing to check is if you have a global.json file up the folder hierarchy that's pinning you to an older SDK version.

**Comment by Amine-Smahi** [comment]
@danroth27 i didnt install the dotnet sdk , im using the portable version ( .zip ) so when calling the dotnet.exe i only call the the .exe in the curent directory witch is the dotnet v2.1.300-preview2-008533 but it always show me the v2.1.300-preview1-008174

**Comment by danroth27** [comment]
Yeah, I think you're still getting a different version of the SDK that happens to be on the PATH. Try specifying a path to the dotnet.exe that you want to run. Something like this if you happen to be in the same folder: `.\dotnet.exe --version`

**Comment by danroth27** [comment]
I'm going to go ahead and close this issue as there is nothing blazor specific here. But feel free to ask further questions here.

**Comment by sabuncu** [comment]
@floreseken said:
> Have you edited your global.json according to the upgrade instructions?

Where are those instructions? The release notes link for SDK 2.1.3 is broken:

https://github.com/dotnet/cli/releases/tag/v2.1.300-preview2-008530 

https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.0-preview2.md    (404 Page)

**Comment by sabuncu** [comment]
@danroth27 Thank you so much. :)
