### ISSUE TITLE
Blazor.net needs a valid certificate

### ISSUE THREAD

**Issue by zbecknell** [aspnet/Blazor#595]
Blazor.net looks great, but currently the certificate is not valid for the domain.  You're probably already aware of this, but I just wanted to put an issue out there for it.  Hopefully you will also consider using HSTS as well once a valid certificate is in place.

**Comment by danroth27** [comment]
Yup, it's just a GitHub Pages site right now, so we're waiting for them to light up HTTPS support for us.

**Comment by zbecknell** [comment]
Good stuff!
