### ISSUE TITLE
Add GetBoundingClientRect

### ISSUE THREAD

**Issue by jirisykora83** [aspnet/Blazor#599]
I am want to make simple slider in Blazor and currently i need support for onmousemove/ontouchmove event etc (i know it is already proposed).

But also i need to somehow get size to DOM element. In react is possible to mark DOM like:

`<div ref="slider"></div>`

and then

```
_someMethod() {
   const x =  this.refs.slider.getBoundingClientRect().left;
}
```

It is any "simple" way how i can achieve similarly behavior in Blazor?

**Comment by zbecknell** [comment]
You can use the [JavaScript Interop](http://blazor.net/docs/components/index.html#javascripttypescript-interop) to achieve this:

```cshtml
<script>
    Blazor.registerFunction('getLeftPositionForElement',
        function (elementId) {
            return document.getElementById(elementId).getBoundingClientRect().left;
        });
</script>
```

And then call it from C#:

```csharp
public static int GetLeftPositionForElement(string elementId)
{
    return RegisteredFunction.Invoke<int>("getLeftPositionForElement", elementId);
}
```

I believe the Mono team is working on creating functionality to more easily interact with standard JS.

**Comment by SteveSandersonMS** [comment]
Thanks for answering @zbecknell!

Additionally in #1 we plan to introduce a syntax for referencing rendered elements directly without needing to give them an ID.
