### ISSUE TITLE
If I open www.blazor.net I get a weird site..

### ISSUE THREAD

**Issue by floreseken** [aspnet/Blazor#600]
Notice the www prefix.. brings you to a totally different site.. are you guys aware of this?

**Comment by SteveSandersonMS** [comment]
@floreseken Thanks for letting us know!

@danroth27, do you have the rights to update the DNS config for this?

**Comment by 4deeptech** [comment]
I believe it just needs to have the index.html file set as default document.

**Comment by danroth27** [comment]
This should be fixed now.

**Comment by floreseken** [comment]
Yes, works for me
