### ISSUE TITLE
www.blazor.fr

### ISSUE THREAD

**Issue by stephane3434** [aspnet/Blazor#601]
Hello,

The website http://blazor.net is very good,

We just want to inform you that we started the website www.blazor.fr for developers in French language.

The first step was to reference important links to use Blazor, and only use Blazor to develop the website by hosting it under IIS / Windows. The next version will be responsive.

The next step is to put a lot of code samples and keeping the links to the original sites. 

We would like to make a toolbox with "code ready" to use to save time.

Then, from this experience of website we want to design a CMS with Blazor in OpenSource.

We hope you like it.

Give us the links you want to publish.

Stephane

**Comment by Daddoon** [comment]
Salut Stéphane,

Actually, this is not an issue, i don't know if it's really the good section to post.
But i like the idea!

Guillaume

**Comment by aguacongas** [comment]
Bonjour Stéphane,

Is this an open source project we can contribute to ?

Olivier

**Comment by yougane** [comment]
Thank you for creating this website for the francophone .NET community ! But as Daddoon noted, this not an issue. It would be more appropriate to post this on reddit or similar.
After reading the content of the website I noticed many typos and mistakes (in every single page). I hope you'll revise the content and correct them :) Or if this an open source project I'll gladly help.

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know about this @stephane3434! I hope you're successful with your new site.

Closing as it's not an issue to be tracked, but thanks again for the info.
