### ISSUE TITLE
Blazor development depending on WebAssembly progress ?

### ISSUE THREAD

**Issue by michaelongithub** [aspnet/Blazor#617]
Hi
if one looks at http://webassembly.org/docs/future-features/ or https://wasm.news it is for the layman difficult to see, if there is real progress after mvp.
Since I am not an expert in these matters at all I wonder:
Does the Blazor group know what the state of these developments is, maybe even contributing to it?
Is future Blazor development or its finalisation as a real product dependent on wasm being developed further?
How do you assess the risk, if wasm stagnates or even looses general interest as a consequence of no visible further developement.

Very interested to hear Your take on that. Even if I misjudge the situation completely.
Thanks for info
Cheers,Michael

**Comment by danroth27** [comment]
Various folks from the .NET team and Mono team are participating in the WebAssembly group on new features and enhancements. Some of these features would help improve the experience of running .NET in the browser. However, we don't believe Blazor is blocked on any of these additions - we can have a good experience with only the existing WebAssembly support.

**Comment by rstropek** [comment]
@michaelongithub Do you know [this video on the future of WASM](https://youtu.be/D3Kf7HZyOrQ)? I found it quite interesting.

**Comment by michaelongithub** [comment]
thanks, for the hint, very interesting.
