### ISSUE TITLE
Why is Node.js required?

### ISSUE THREAD

**Issue by nathanielcook** [aspnet/Blazor#62]
One of the purposes of this project is to enable .NET fans to get away from Javascript, right? Why is Node.js required? It seems like it might be harder to convince Node fans to use .NET if .NET's web framework(s) rely on Node. This is a legitimate question by the way; I'm not just trolling.

**Comment by danroth27** [comment]
Node is only required as part of the build system for the Blazor project. Bootstrapping the Blazor runtime and interacting with core browser functionality is handled in JavaScript. At runtime Blazor itself has no dependency on Node and has no dependency on any particular server-side framework.
