### ISSUE TITLE
Computed disabled attribute does not rerender.

### ISSUE THREAD

**Issue by mellamokb** [aspnet/Blazor#624]
I have tested a simple form concept.  There is a checkbox called "Active", which when you check the following fields become enabled.

```
    <div class="form-group row">
        <label class="form-check-label col-sm-4" for="Active">Is Active</label>
        <div class="col-sm-8">
            <input class="form-check-input" type="checkbox" name="Active" id="Active" bind="Active" />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-form-label col-sm-4" for="Minimum">% Minimum</label>
        <div class="col-sm-8">
            <input class="form-control" style="width:160px;" type="text" name="Minimum" id="Minimum" bind="MinimumStr" disabled="@(!Active)" />
        </div>
    </div>
```

However, the rendering of being disabled only works on initial load, based on the default checked status of Active checkbox.  When you check or uncheck the Active box, it doesn't update the disabled status of the Minimum textbox, even if you hook into the Active setter and manually call StateHasChanged().

**Comment by aguacongas** [comment]
You cannot bind to a DOMElement directly, you need to have a property declare in `@function` block  
Your code should be: 

``` html
<div class="form-group row">
        <label class="form-check-label col-sm-4" for="Active">Is Active</label>
        <div class="col-sm-8">
            <input class="form-check-input" type="checkbox" bind="@active" />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-form-label col-sm-4" for="Minimum">% Minimum</label>
        <div class="col-sm-8">
            <input class="form-control" style="width:160px;" type="text" name="Minimum" id="Minimum" bind="MinimumStr" disabled="@(!active)" />
        </div>
    </div>

@functions {
 bool active;
}

```

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @aguacongas!

**Comment by mellamokb** [comment]
Sorry, I wasn't providing the full source so as not to distract from the issue.  I do have a functions block with the relevant properties defined.  Please try to build the sample and you will see the issue.  Thanks!

**Comment by SteveSandersonMS** [comment]
Thanks so much for reporting this! I've tracked it down to a bug in the attribute diffing algorithm.

For now you'll need to use the workaround by @aguacongas above. We'll have a fix in the next version.

**Comment by SteveSandersonMS** [comment]
Will be fixed by #633, so closing in favour of that.

**Comment by WojcikMM** [comment]
This is still No working ... please reopen,

**Comment by SteveSandersonMS** [comment]
@WojcikMM Since this issue was closed with the view that it was fixed, and many aspects of the technology have moved on since then, if you think there is a problem could you please open a new issue? Please be sure to state what version of the framework you're using, and provide a clear and minimal repro example stating what you think should happen and what happens instead.
