### ISSUE TITLE
Packing javascript with a component

### ISSUE THREAD

**Issue by MihaMarkic** [aspnet/Blazor#627]
Is scenario where I'd create a component including its javascript counterpart and pack it into NuGet library supported?

**Comment by SteveSandersonMS** [comment]
Yes, please see *Build reusable component libraries* in this post: https://blogs.msdn.microsoft.com/webdev/2018/04/17/blazor-0-2-0-release-now-available/

**Comment by MihaMarkic** [comment]
Hi @SteveSandersonMS,

Read that but it doesn't say if it is possible and how to include a javascript. A scenario I imagine is to create a reusable javascript-c# interop component.

**Comment by SteveSandersonMS** [comment]
Sorry if it was unclear. In that blog post, the following section describes JS interop and how the component library bundles JS for this purpose. So yes, it is supported :)

**Comment by floreseken** [comment]
Also, if you do a:

`dotnet new -i Microsoft.AspNetCore.Blazor.Templates`

and then:

`dotnet new blazorlib`

You will get a perfect example.

**Comment by MihaMarkic** [comment]
Indeed, a good example. I'm curious though, who and when exactly invokes exampleJsInterop.js to register the methods. Do I have to place the component somewhere? Or the scripts in /content directory are automatically run?

**Comment by SteveSandersonMS** [comment]
@MihaMarkic I think you should try it out and see how it works. The blog post provides steps for how to try out a library project.

**Comment by dotnetnoobie** [comment]
@MihaMarkic you may also like to look at this example

**Comment by MihaMarkic** [comment]
@SteveSandersonMS From what I see I think you run every .js in the component library when app starts, am I correct?

**Comment by MihaMarkic** [comment]
Perhaps one more question. How does one control casing of json when calling a registered function (RegisteredFunction.Invoke<T>)?
Let's say I have a class 

```
class Tubo
{
  public string Value { get; }
}
```
I'd like to get camelCased json, like:

> { value: "xxx" }

**Comment by MihaMarkic** [comment]
FYI [here](https://github.com/MihaMarkic/BlazorReduxDevToolsExtension) it is what I'm working on.

**Comment by danroth27** [comment]
@MihaMarkic It's an unfortunate limitation of our JSON serialization support that the casing currently has to match. We should just change the default behavior.

**Comment by danroth27** [comment]
@MihaMarkic Also, have you seen https://github.com/torhovland/blazor-redux? It looks similar to what you are attempting.

**Comment by RyoukoKonpaku** [comment]
@danroth27 how about a defaultContractResolver that can be set at Program.cs to let SimpleJson know how to serialize data from the app? This is how Json.Net deals with such and I think i'd be a great addition overall since most Json APIs use camelCase for most of the part.

**Comment by danroth27** [comment]
Honestly, I think we should just make it the default behavior without requiring additional configuration.

**Comment by MihaMarkic** [comment]
@danroth27 Saw it mentioned. Mine is just an interop bridge, nothing else, intentionally to keep it as simple as possible. So it can be used anywhere without redundant code.
It is also a piece of my cross platform redux implementation, not limited to blazor.
