### ISSUE TITLE
HttpClient.PostJsonAsync appears not to fetch from http apis

### ISSUE THREAD

**Issue by NeilMacMullen** [aspnet/Blazor#634]
Using Blazor 0.2.1 the following code fails to retrieve information:

    var url = TrackService.ServiceUrl(TrackService.TsService.Echo);
    var req = new EchoRequestDto {Echo = "hello world"};
    var resp = await _httpClient.PostJsonAsync<EchoResponseDto>(url, req);

when the url is http rather than https.  The same service (and dtos) can be used from a .net framework application using WebClient.  The code above does work for other services which are https.  Unfortunately I haven't yet found a service which can be tested over both http and https so don't have a direct comparison.  The error returned is....

> 
System.Net.Http.HttpRequestException: TypeError: Failed to fetch. at Microsoft.AspNetCore.Blazor.Browser.Http.BrowserHttpMessageHandler+<SendAsync>d__8.MoveNext () <0x1dede30 + 0x0039a> in <08ceae4b872f4f8d8ccefc410a9a8971>:0 --- End of stack trace from previous location where exception was thrown --- at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () <0x1ddb2a8 + 0x0017e> in <ddfe03af15f14d3e8b54c58c0b39de11>:0 --- End of stack trace from previous location where exception was thrown --- at Microsoft.AspNetCore.Blazor.HttpClientJsonExtensions+<SendJsonAsync>d__6`1[T].MoveNext () <0x1d7ab60 + 0x00100> in <8a8022566b074cca8a70e10050945cdd>:0 --- End of stack trace from previous location where exception was thrown --- at BlazorWeb.TestClass+<GetDevices>d__3.MoveNext () <0x1d70a98 + 0x00154> in <304208b16f254ea3b31504e888d5b249>:0 TypeError: Failed to fetch.

**Comment by danroth27** [comment]
From the browser you can only make HTTP requests to the server of origin *unless* the endpoint has enabled support for [cross-origin resource sharing (CORS)](http://www.w3.org/TR/cors/). Please ensure the endpoint you are sending the request to supports CORS (i.e. it sends back the CORS headers).

**Comment by danroth27** [comment]
I'm going to close this issue, but if the problem turns out not be CORS please reopen it and let us know.

**Comment by NeilMacMullen** [comment]
Thanks dan - the target endpoint here is an azure webrole on which I've done no special configuration so I suspect your suggestion here (i.e. user error on my part) is the actual problem! I will close...

**Comment by NeilMacMullen** [comment]
Just for completeness, I can confirm the issue was caused by CORS rather than https.  I created a new Azure wep-app and confirmed that toggling the CORS control in the portal on/off made the blazor app succeed/fail.
