### ISSUE TITLE
Should we use .NET Core 2.0 or 2.1 for Blazor app? Doc inconsistency?

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/Blazor#638]
On this page [https://blazor.net/docs/get-started.html](https://blazor.net/docs/get-started.html) it is written that we have to install .NET Core **2.1** Preview 2 SDK. Then in "create your first project" in step 2 it is written: Make sure .NET Core and ASP.NET Core **2.0** are selected at the top.

**Comment by danroth27** [comment]
Either is fine. You can use the 2.1 SDK to build 2.0 apps, or if you want to play with the 2.1 preview you can do that too.
