### ISSUE TITLE
Can't name a tag the same name as an html element

### ISSUE THREAD

**Issue by chanan** [aspnet/Blazor#647]
I created a Button component (upper case "B") and placed the following html in it:

```html
<button type="button" class="btn btn-primary">Primary</button>
```

Placed the Button in a page: `<Button />`

When the page was rendered I got an error that Button doesn't have a property named type. (first attribute in the button html above).

Workaround: renamed Button to something else.

Fix: Perhaps Blazor should only allow lower case html tags and upper case custom tags (like react)

**Comment by RyoukoKonpaku** [comment]
Seems to be a Blazor Razor compiler bug, strangely enough it should be able to differentiate a component and a normal html element though.

**Comment by SteveSandersonMS** [comment]
@rynowak Can tag helpers differentiate by case?

**Comment by babula38** [comment]
@chanan thanks for logging the issue, even i am having the same issue.

**Comment by rynowak** [comment]
> Can tag helpers differentiate by case?

Nope, they are defined as case-sensitive.

**Comment by AWulkan** [comment]
Isn't this a pretty bad idea anyway? I mean, HTML is case insensitive, so you should never name something the same as an existing HTML element.

**Comment by chanan** [comment]
Not agreeing or disagreeing, just explaining. The way React works, all html elements must be lower case and all custom elements must be Capital case. This allows you to import Button from custom UI library and mix and match (if you needed to) html button tag and the custom Button tag you imported. 

Not advocating for one or another, but it is nicer than using and rendering MyCustomButton because a custom elements can't be named Button.

**Comment by danroth27** [comment]
This is a limitation of how Razor works currently and we don't have any immediate plans to change it, so I'm going to go ahead and close this issue. Hope that's ok!
