### ISSUE TITLE
input tag doesnt allow ChildContent

### ISSUE THREAD

**Issue by chanan** [aspnet/Blazor#648]
This works:
`<button onclick="@_onclick" type="button" class="@className">@ChildContent</button>`

This does not:
`<input onclick="@_onclick" type="button" class="@className">@ChildContent</input>`

The error:
Found a malformed 'input' tag helper. Tag helpers must have a start and end tag or be self closing.

**Comment by Daddoon** [comment]
I don't think having child elements in the input html tag is even a valid case.

According to [w3schools](https://www.w3schools.com/tags/tag_input.asp):

> Tips and Notes
> Note: The <input> element is empty, it contains attributes only.

**Comment by chanan** [comment]
My bad, sorry.
