### ISSUE TITLE
Need the concept of react context

### ISSUE THREAD

**Issue by chanan** [aspnet/Blazor#650]
I need to be able to send properties down to child components that the user of my library supplies. For example:
```
<Dropdown>
        <DropdownToggle>Dropdown</DropdownToggle>
        <DropdownMenu>
            <DropdownItem Href="#">Action</DropdownItem>
        </DropdownMenu>
</Dropdown>
```

In this example, Dropdown holds a a variable IsOpen that needs to be passed down to DropdownToggle and DropdownMenu. In react this is done by setting context in Dropdown and having the child components read the context.

Is there a current of passing down properties to child elements, or can a similar concept of context be added to Blazor?

**Comment by dotnetnoobie** [comment]
Bind Value to Child Component

https://learn-blazor.com/pages/data-binding/#bind-value-to-child-component

**Comment by SteveSandersonMS** [comment]
This is something I've considered in the past and didn't yet get to a satisfactory conclusion about. I'll add this to #1 for tracking.
