### ISSUE TITLE
UI don't get updated on long run process

### ISSUE THREAD

**Issue by thild** [aspnet/Blazor#651]
I'm working on a graph search project coded in C# that uses cytoscape.js to render the graphs, paths, and highlighted nodes. I want to render the paths and highlight the nodes in a step-by-step fashion. When a node is visited, an event is raised from the lib and captured by a Blazor component that interop with cytoscape.js. However, apparently the UI thread is blocked until the end of the Blazor rendering cycle even calling StateHasChanged on every event. Can I call async methods from UI?

This is my run method on Index.cshtml.

```
void Run()
{
    Graph graph = GraphIO.Read(GraphFile);
    var dijkstra = new Dijkstra(graph);
    dijkstra.Visited = (key) => {
        System.Threading.Thread.Sleep(1000);
        Interop.MarkNode(key);
        StateHasChanged();
    };
    var result = dijkstra.Process(0, 9); //result contains the shortest path
    Result = result.ToString();
    Interop.DrawPath(result);
}

```

**Comment by Daddoon** [comment]
I'm not pretty sure of the behavior of the browser, by using the System.Threading.Thread.Sleep method. Instead of Sleeping the thread can you try instead:

1. Try to use Task.Delay
2. OR use the timer library and execute the callback when your timer fire.

As from [this stackoverflow thread](https://stackoverflow.com/a/20084603/1417492)

> Use Thread.Sleep when you want to block the current thread.
> 
> Use Task.Delay when you want a logical delay without blocking the current thread.

**Comment by thild** [comment]
Thanks @Daddoon,
I've tried with Task.Delay and async anonymous delegate, but the problem was on my Process method that wasn't async. I changed the signature of this method and now is working.
In my library:
```
public delegate Task NodeVisitedHandler(uint key);
public event NodeVisitedHandler NodeVisited;

public virtual async Task<DijkstraResult> ProcessAsync(uint from, uint to)
{
    //...
    await OnNodeVisited(current.Key);
    //...
}

protected async virtual Task OnNodeVisited(uint current)
{
    if (this.NodeVisited != null)
    {
        foreach (var d in this.NodeVisited.GetInvocationList().Cast<NodeVisitedHandler>())
        {
            await d.Invoke(current);
        }
    }
}
```
In cshtml:
```
async void Run()
{
    Graph graph = GraphIO.Read(GraphFile);
    var dijkstra = new Dijkstra(graph);
    dijkstra.NodeVisited += async (key) => {
        await Task.Delay(1000);
        Interop.MarkNode(key);
        StateHasChanged();
    };
    var result = await dijkstra.Process(0, 9); //result contains the shortest path
    Result = result.ToString();
    Interop.DrawPath(result);
}
```

**Comment by SteveSandersonMS** [comment]
Glad you solved it!
