### ISSUE TITLE
Obsolete <nobr> HTML element in Shared/SurveyPrompt.cshtml

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/Blazor#652]
I'm using ASP.NET Core Blazor Language Services version 15.7.10242. I have created a new project: Blazor (ASP.NET Core Hosted). In SurveyPrompt.cshtml file I see `<nobr>` HTML element. According to this page [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr) it is obsolete. Recommended solution is `<span style="white-space: nowrap">Long line with no breaks</span>`

Real question is: do you really need this behaviour (nowrap)?

**Comment by SteveSandersonMS** [comment]
We don't *need* it, but it helps to make the line wrapping look better at smaller screen sizes.

I'll replace it with `<span class='text-nowrap'>`.
