### ISSUE TITLE
Optimize the BCL

### ISSUE THREAD

**Issue by javiercn** [aspnet/Blazor#66]
The work here is to:
- [x] Setup illink on the project.
- [x] Run the linker through the app.
- [ ] Determine what references are left behind on the app and what of those things are potential candidates to strip.

**Comment by javiercn** [comment]
So far I've been able to run this on StandaloneApp and I've been able to trim the BCL to
![image](https://user-images.githubusercontent.com/6995051/35951253-7b369318-0c2f-11e8-8ccf-b9a02a239cdc.png)

The command that i've used is
```
illink.exe -a .\Microsoft.AspNetCore.Blazor.Browser.dll \
 -a .\Microsoft.AspNetCore.Blazor.dll -a .\StandaloneApp.dll \
-d .\dist\_framework\_bin\ -c link -out .\optimized --skip-unresolved true
```

mscorlib is by a large margin the biggest assembly here. Zipping the remaining files leaves them at around 590K

![image](https://user-images.githubusercontent.com/6995051/35951454-5622d4b4-0c30-11e8-997a-729f2aeda4d6.png)

![image](https://user-images.githubusercontent.com/6995051/35951492-6d18a81a-0c30-11e8-90e5-92c79ce34816.png)

Above is the remaining namespaces left on the assembly.

The next step is to determine what of those things can go away and see how much we save.

**Comment by grahamehorner** [comment]
@javiercn IMHO anything that would in essence be anything that would break outside the browser sandbox? things like Win32, file IO etc. these could be placed with interop with browser APIs which could save quite a bit of space ;)

loving the work on this now it's an official project of research; can't wait to see what the teams direction is on the feature roadmap @SteveSandersonMS +1

**Comment by javiercn** [comment]
Done 59635331601dc8496c7cd5958552dec24d1b0ffd.
https://github.com/aspnet/Blazor/issues/245 Tracks further improvements
