### ISSUE TITLE
Blazor lib projects JS may need access to 'platform ready' event

### ISSUE THREAD

**Issue by galvesribeiro** [aspnet/Blazor#674]
While experimenting the new Blazor library projects (which is awesome btw) we've hit a wall when using Blazor APIs.

To repro just create a blazor library project and at the .js file, call this:

```
const callbackMethod = Blazor.platform.findMethod(
  assemblyName,
  namespace,
  typeName,
  methodName
);
```

Add this project to a Blazor app project and just run it.

![image](https://user-images.githubusercontent.com/4714040/39224046-7ec5e3a8-481b-11e8-8c04-5f062af6059c.png)

The project build actions looks like is adding the content properly to the index.html as the scripts are added _after_ mono.js import...

![image](https://user-images.githubusercontent.com/4714040/39224087-b8d3a81e-481b-11e8-86fc-8c0df4986583.png)

So, how to workaround this?

It looks to me that all `Blazor.xxx` objects are properly defined in JS except the `Blazor.platform.xxxx`...

**Comment by dotnetnoobie** [comment]
Take a look at this answer it might show you solution to your problem

https://github.com/aspnet/Blazor/issues/641#issuecomment-383297550

**Comment by galvesribeiro** [comment]
@dotnetnoobie 

If I do that, that means for every call of the callback, I'm doing "reflection" again to discover the method before invoking it. Not ideal. If the JS interpreter was smart and aware of C# world (which I dont believe), that method could be inlined as it is pure/constant and will always return the same value but, that is not the case.

@SteveSandersonMS 

Basically I'm trying to workaround the current lack of Promise <> Task interop so I can use async JS properly doing something similar to what is discussed on this post https://joonasw.net/view/csharp-await-and-js-promises-in-blazor. 

By making a classlib and leveraging its ability to load the scripts after mono.js being loaded, we expect that the types got available to the rest of the app. In this particular case, we are not invoking .Net before .Net calls it. We are just finding the method reference and registering some JS functions which use that method reference to call the .Net world. If you look at the example on that post, it works because on 0.1.0 it was possible to have the `<script>` tag on components. Now that it doesn't, the _correct_ way should have a `blazorlib` project with that so it can be loaded at runtime right after blazor and mono bootstrap.

The funny thing is that `Blazor.registerFunction` works perfectly in that situation. It is like Blazor is loading before mono itself.

**Comment by SteveSandersonMS** [comment]
I think this is really the same thing as #280, so I'll close as a duplicate.
