### ISSUE TITLE
the name @onclick  does not exist in current context

### ISSUE THREAD

**Issue by MangeshPersonal** [aspnet/Blazor#680]
I am using the button but i am getting error as @onclick does not exist in current context 

please help

**Comment by dlr1** [comment]
It should be something like this
```
<button onclick="@AddComp">Add component</button>
```

**Comment by MangeshPersonal** [comment]
i was missing the Event Argument in the function Thanks dlr1 for the comment  
<button onclick="@GetFruits">Click Me</button>
 void GetFruits(UIMouseEventArgs e)
            {
                Fruits.Add("Apple");
                Fruits.Add("Mango");
                Fruits.Add("Grapes");
            }

This worked for me

**Comment by davidlsharp1** [comment]
Nevermind.  I had unnecessary quotes.

This was covered here:

https://github.com/aspnet/Blazor/issues/923

onclick=@(() => GetSurvey(survey.Id))

**Comment by Andrzej-W** [comment]
@davidlsharp1 Strictly speaking problem is **not** related to quotes. If you want to pass your own parameters you have to use lambda expression and that is real problem in original post. You can write:
`onclick="@(() => GetSurvey(survey.Id))"`
and it will work
Some examples are available here:
https://blazor.net/docs/components/index.html#event-handling

**Comment by davidlsharp1** [comment]
Thanks @Andrzej-W   I appreciate the help.

**Comment by horseyhorsey** [comment]
@davidlsharp1 

I just came across similar issue populating a table with button.

If you don't use a lambda then the "onclicks" are invoked when the table is populated.
