### ISSUE TITLE
Unable to build Blazor: Input too long

### ISSUE THREAD

**Issue by marcusbooyah** [aspnet/Blazor#682]
This is similar to #554 

My project has a long list of references, not embedded resources and I'm getting the same error as #554.

I think the fix is the same as #561 but for references.

**Comment by marcusbooyah** [comment]
I have fixed this, will submit PR now

**Comment by Daddoon** [comment]
You may try to link your PR in this thread for cross reference ?

**Comment by marcusbooyah** [comment]
#683

**Comment by SteveSandersonMS** [comment]
Fixed with #683
