### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by daveabrock** [aspnet/Blazor#687]
Hey all! I am loving this project and would love to help! Of course, I read through the [contributing guide](https://github.com/aspnet/Blazor/blob/dev/CONTRIBUTING.md) so would be happy to look at any issues or make suggestions, but is there anything that newbies to Blazor could review? If not, I can just play with it and help where I can!

**Comment by SteveSandersonMS** [comment]
Great to hear!

I'd suggest either looking through the issues backlog and/or the `// TODO` comments in the code and finding something that looks approachable and interesting to you. It's often best to first post an issue describing what you're planning to do if you want to get feedback on whether your approach fits into the wider plans.

Thanks!
