### ISSUE TITLE
Expose getRegisteredFunctions from Blazor javascript module

### ISSUE THREAD

**Issue by alexfdezsauco** [aspnet/Blazor#688]
Should be possible expose the getRegisteredFunctions from Blazor javascript module.

This could be useful in custom interop solutions like this one for promises:

https://joonasw.net/view/csharp-await-and-js-promises-in-blazor

doesn't require 'host' the functions in the window object. Just use the same approach to register the function to be called.

The implementation could be this one:

`let promise = Blazor.getRegisteredFunction(fnName)(data)`

instead this one:

`let promise = window[fnName](data);`

BWT, could Blazor include a solution like this one https://joonasw.net/view/csharp-await-and-js-promises-in-blazor to call promise (async/await).

**Comment by SteveSandersonMS** [comment]
We're specifically trying to avoid doing that, as it would prevent libraries from encapsulating their functions if they want to. It would effectively force everything to be public.

Instead, the intention is that libraries who want to make their functions public should expose that in some namespace using normal JavaScript conventions.

On the async/promises conversion, yes, definitely! I think @javiercn is already working on this from the JS->.NET direction, and we'll do the other direction soon too.

**Comment by alexfdezsauco** [comment]
I understand your point in some way, but `Razor.registerFunction` is public, but I have no way to find a registered function for custom function invoke approach. That is the reason why I requested also make public 'getRegisteredFunction' (the function exists but is not exposed) in order to use the same approach to register a function.

`Razor.registerFunction('PromiseFunction', function() {
   return new Promise(resolve, reject) {
           ......
   };
})`

then anyone can find or discover such function

`var promiseFunction = Razor.getRegisteredFunction('PromiseFunction')`
