### ISSUE TITLE
[Feature Request] Generate JavaScriptInterop using Roslyn

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#689]
IMHO It would be a great if Blazor used Roslyn to dynamically create in memory implementation of JavaScriptInterop based of c# abstract classes, eg.

`
namespace someJavascriptNamespace {
public abstract class someJavaScriptInterop { 
public abstract bool someJavaScriptMethod(string stringParameter, bool boolParameter);
...
}
}

/// use roslyn to generate and compile the code that calls/invokes the javascript  
TJavaScriptInteropDefinition GenerateImplementation<TJavaScriptInteropDefinition>( );
`
/// calling the generated implementation 
var result = GenerateImplementation<TJavaScriptInteropDefinition>( )
.someJavaScriptMethod("",true);

**Comment by SteveSandersonMS** [comment]
Are you suggesting we'd do this at runtime? We definitely can't do runtime codegen using Roslyn inside the browser - there's no compiler infrastructure there, and it would be incredibly heavyweight if there was.

We're looking at build-time codegen for interop. Closing as I think this is covered already, but please let me know if you think I'm misunderstanding.

**Comment by grahamehorner** [comment]
@SteveSandersonMS I was thinking this could be done at runtime server side, as this would also allow for dynamic loading of scripts and associated generated Interpol assemblies.
