### ISSUE TITLE
Norton 360 Insight Antivirus warnings

### ISSUE THREAD

**Issue by Vladimitrius** [aspnet/Blazor#69]
I've  just unpacked the project and got a wave of warnings from Norton File Insight (antivirus).
I don't know if its really an issue but I think that would help if somebody else report the proj as false positive at Symantec support (https://submit.symantec.com/false_positive/).

Somebody else had a problem with antivirus during the project install?

**Comment by SteveSandersonMS** [comment]
I'm not sure what you mean by "unpacked the project" (it's a Git repo) but in any case I think you'll have to take this up with your antivirus vendor. Thanks for posting though, in case anyone else sees the same.
