### ISSUE TITLE
Bootstrap 4 component library

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#690]

**Comment by chanan** [comment]
I have a component library partially done for Bootstrap4: https://github.com/chanan/BlazorStrap

**Comment by carlosalcantara2668** [comment]
they have MODAL SMALL and others, but
How can it be modified or the width and length of the modal windows?

**Comment by chanan** [comment]
@carlosalcantara2668 Are you asking a question about https://github.com/chanan/BlazorStrap? If so, you should open an issue in that repo.

I am not 100% sure what you are asking, but in BlazorStrap you can always supply your own class to further style a tag, and also supply "Style" attributes if you wish.

**Comment by SteveSandersonMS** [comment]
Closing as the original Bootstrap component library idea is not something we're working on in the immediate future, especially now BlazorStrap is available.
