### ISSUE TITLE
Project templates

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#7]
- [ ] Standalone
- [ ] Enable HTTP compression

**Comment by danroth27** [comment]
Includes developing .NET Core CLI project templates and making them available in VS.

**Comment by SteveSandersonMS** [comment]
Note: project needs to target `netstandard2.0` rather than `netcoreapp2.0`, so we will have to figure out whatever changes to the build config make this possible.

**Comment by SteveSandersonMS** [comment]
> Note: project needs to target netstandard2.0 rather than netcoreapp2.0

This is now done

**Comment by grahamehorner** [comment]
Please consider adding ResponseCaching of the WebAssembly as default to the template

**Comment by SteveSandersonMS** [comment]
Done as `dotnet new` templates.

> Includes developing .NET Core CLI project templates and making them available in VS.

That's covered by #39 now.

> Please consider adding ResponseCaching of the WebAssembly as default to the template

By default ASP.NET respects the browser's HTTP cache control headers for static files including these.

**Comment by grahamehorner** [comment]
Please consider adding templates for creating interop libraries

**Comment by weitzhandler** [comment]
Thank you very much!
Are the templates only available in VS 15.7 Preview? Or else?

**Comment by danroth27** [comment]
@weitzhandler The templates are available from the command-line (`dotnet new`), or from VS. To get Blazor tooling support in VS you need the [latest preview of VS (15.7)](https://www.visualstudio.com/vs/preview) and you need to install the Blazor VSIX. We are also looking at support for VS for Mac. We'll have more formal instructions on using the templates once we have a preview release for folks to try out, but if you want to try out a nightly build you can find instructions at https://aka.ms/install-blazor.

**Comment by danroth27** [comment]
@grahamehorner You should probably open a separate issue for creating templates for interop libraries, but I suspect we will handle that scenario with docs and samples instead of a template.

**Comment by Thaina** [comment]
Do we have a way to create blazor project from vscode?

**Comment by SIkebe** [comment]
@Thaina You can use blazor cli
https://blogs.msdn.microsoft.com/webdev/2018/03/22/get-started-building-net-web-apps-in-the-browser-with-blazor/

```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates
dotnet new blazor -o BlazorApp1
cd BlazorApp1
dotnet run
```

**Comment by Thaina** [comment]
@SIkebe Thank you very much
