### ISSUE TITLE
Request: A global method call to rerender all components

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/Blazor#704]
My Redux/Flux library (Blazor.Fluxor) can have its state set via a Chrome plugin (Redux Dev Tools), so it is possible to change state without first having any user interaction on the page.

As my debugger tool uses an AddMiddleware approach this means there is no component, and having all components in an app descend from base class would be an incorrect approach (see below)

What I need is to be able to either iterate all correct component instances and call StateHasChanged on them, or have some kind of global method to call that will instruct all components to re-bind.

My other option is to require users of my library to descend from a common component, but I don't think that's appropriate because 1) The feature in my library is an optional middleware 2) It is only intended to be used in debug mode 3) If library coders must force our users to use our own BlazorComponent descendant classes for their components then those users won't be able to use multiple libraries together.

**Comment by SteveSandersonMS** [comment]
The preferred way to achieve this would be to have a component base class that listens for a global "rerender" event.

Currently we wouldn't want to force all components everywhere to do this, as the intent is to allow components to be encapsulated if they want to be.

> My other option is to require users of my library to descend from a common component, but I don't think that's appropriate because...

I recognise the tension with that. Hopefully some of the comments I posted in #1163 will tie in with this.

**Comment by floreseken** [comment]
Please look at this blogpost http://flores.eken.nl/blazor-custom-component-with-2-way-databinding/
There I us a globalstate for the same purpose..
