### ISSUE TITLE
After run Blazor project i see empty browser window

### ISSUE THREAD

**Issue by VladislavFurdak** [aspnet/Blazor#706]
There are that i see:
![issue1](https://user-images.githubusercontent.com/4522419/39411134-b07cae82-4c0c-11e8-9547-da1640d61787.png)
![issue2](https://user-images.githubusercontent.com/4522419/39411135-b09efc3a-4c0c-11e8-8c9b-0c3533c5fa56.png)
![issue3](https://user-images.githubusercontent.com/4522419/39411136-b0be0fd0-4c0c-11e8-86cf-ab6ee11093ff.png)

But as i understand empty project after "Loading..." label should show something
Also, when i tried to run any sample projects written in Blazor, i got the same thing
Also, i have installed VS 2017 of earlier edition on my PC.

**Comment by twarenius** [comment]
What does ”dotnet —version” give you?

**Comment by VladislavFurdak** [comment]
2.1.300-preview1-008174

**Comment by cmc19** [comment]
I had the same issue when I forgot to install [.NET Core 2.1 Preview 1 SDK](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview1).

**Comment by twarenius** [comment]
I think you should install version 2.1.300-preview2-008533.

**Comment by SIkebe** [comment]
@cmc19 See here.
https://blogs.msdn.microsoft.com/webdev/2018/04/17/blazor-0-2-0-release-now-available/

**Comment by VladislavFurdak** [comment]
It works, thanks!

**Comment by asprich** [comment]
I have everything mentioned above, but I'm still just getting a blank page. There's app tag with an empty router tag.

**Comment by danroth27** [comment]
@asprich Could you please open a separate issue with the details of your project and environment so that we can investigate?
