### ISSUE TITLE
Only white page after loading

### ISSUE THREAD

**Issue by tojak** [aspnet/Blazor#710]
I updated my visual studio (community) preview version to 15.7 preview 5.
The dotnet-sdk version is 2.1.300-preview1.

Blazor version is 0.2.1.0.

When running the template app (that comes with visual studio) I get the "Loading ..."-Screen and than a white page. Breakpoints are not reached. Whats wrong? Is it blazor? Is it my system-configuration?

P.S.: Starting an old app with blazor version 0.1.0.0 still works.

**Comment by rynowak** [comment]
The best place to look would probably be your browser's console. Any errors you hit loading the page would be logged there

**Comment by floreseken** [comment]
You should be running preview2 of the sdk.

**Comment by tojak** [comment]
The rendered HTML is:

`<html><head>
    <meta charset="utf-8">
    <title>Barbuda.Boards</title>
    <base href="/">
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="css/site.css" rel="stylesheet">
</head>
<body>
    <app>
<router appassembly="typeof(Program).Assembly"></router>
</app>
    <script src="css/bootstrap/bootstrap-native.min.js"></script>
    <script src="_framework/blazor.js" main="Barbuda.Boards.dll" entrypoint="Barbuda.Boards.Program::Main" references="Microsoft.AspNetCore.Blazor.Browser.dll,Microsoft.AspNetCore.Blazor.dll,Microsoft.Extensions.DependencyInjection.Abstractions.dll,Microsoft.Extensions.DependencyInjection.dll,mscorlib.dll,netstandard.dll,System.Core.dll,System.dll,System.Net.Http.dll" linker-enabled="true"></script><script defer="" src="_framework/wasm/mono.js"></script>
</body></html>`

The browser console says nothing. Same with the blazor console.

**Comment by SIkebe** [comment]
@tojak As @floreseken said above, you should use dotnet core SDK 2.1.300-preview2-008533.
https://blogs.msdn.microsoft.com/webdev/2018/04/17/blazor-0-2-0-release-now-available/

**Comment by tojak** [comment]
I am currently downloading and installing it. I will tell you if it works. Thanks. 

Problem was, that I tried to download the latest version of the sdk preview yesterday and it dowloaded preview 1 ...

**Comment by tojak** [comment]
After downloading and installing preview 2 it still shows a white page. 

Do I have to configure the usage of preview 2? Where can I do this? Sorry for the dumb question.

**Comment by SIkebe** [comment]
Is there a `global.json` which specifies dotnet core SDK version?

**Comment by tojak** [comment]
The global.json looks like this:

{
  "sdk": {
    "version": "2.1.300-preview2-008533"
  }
}

**Comment by tojak** [comment]
Now it works. I restarted the studio cleaned the build and rebuilt it and got it working. Thanks.

**Comment by SIkebe** [comment]
Glad to hear that!
