### ISSUE TITLE
unable to set [Parameter] value, inaccessible due to protection level

### ISSUE THREAD

**Issue by dlr1** [aspnet/Blazor#724]
I am using version "0.3.0-preview1-10261". 
Setting the Parameter value works when it is done inline, but not through code.

I have a component "MyComp"
```
<input bind="@Name" />
@functions{
    [Parameter]
    string Name { get; set; }
}
```
I use it like  below.
```
<MyComp ref="mycomp" Name="testing"></MyComp>
@functions{
    MyComp mycomp;

    protected override void OnAfterRender()
    {
        base.OnAfterRender();
      //  mycomp.Name = "this is a test";
        
    }
}
```

**Comment by danroth27** [comment]
@rynowak

**Comment by rynowak** [comment]
This is explicitly intended. Setting a component parameter directly like this when using `ref` is not the intended way to manipulate its settable surface area, you're supposed to use the markup. 

There's some explanation for this here: https://github.com/aspnet/Blazor/pull/685 - @SteveSandersonMS might be able to provide more detail

**Comment by SteveSandersonMS** [comment]
Yes, the whole efficient rendering process is based around a predictable data flow down the hierarchy of components. Parameters must be passed declaratively. It's the same with similar SPA frameworks.
