### ISSUE TITLE
Add "Blazor Page" template to VS templates for 'Add New' dialog in VS

### ISSUE THREAD

**Issue by conficient** [aspnet/Blazor#732]
Not an urgent requirement, but a "Blazor Page" template would be nice in the "Add New" dialog in VS.

At present I just copy existing pages and rename them.

**Comment by brunopbarrote** [comment]
You mean ItemTemplate

**Comment by lohithgn** [comment]
as of now i do Add New Item > Razor View in VS ... :)

**Comment by SteveSandersonMS** [comment]
Duplicate of #23
