### ISSUE TITLE
Razor syntax highlighting/intellisense not working

### ISSUE THREAD

**Issue by InnovationGB** [aspnet/Blazor#737]
Currently I need to copy my code to C# files in order to gain intellisense and syntax highlighting. Is this not currently supported in Blazor?

**Comment by dlr1** [comment]
Did you update the VSIX?

**Comment by InnovationGB** [comment]
the blazor extension? Yes.

**Comment by rynowak** [comment]
Sorry this isn't working for you, could you provide a little more information?

Is this visual studio?
Did you have a working configuration before 0.3 and it no longer works? (or are you trying the tools for the first time?)
Screenshot?
Project file?

**Comment by godrunner** [comment]
I had a similar issue here with a brand new install of the Visual Studio pre-release in a test Windows 10 Pro build 1803 VM. I installed it to have a look at Blazor (I am very impressed!) and I was not getting syntax highlighting/intellisense either for Blazor code. I didn't pay much attention figuring it was likely a known issue. 

Today, I had another look and everything seems to be ok, so I guess the VM just needed to be restarted.

**Comment by InnovationGB** [comment]
So I have solved my issue, Although I had installed BlazorExtension-2.vsix through the downloadable file, I needed to go into my Nuget packages and install the extension to the project.

**Comment by SteveSandersonMS** [comment]
Glad you solved it.
