### ISSUE TITLE
supported products only for Microsoft.VisualStudio.Community

### ISSUE THREAD

**Issue by jwaller2040** [aspnet/Blazor#744]
I tried to install Microsoft.VisualStudio.BlazorExtension.vsix to my Visual Studio Professional 2017 but the error says it's only supporting Visual Studio Community. Why?

[VSIXInstaller_de52d3d4-1758-4b62-9137-e2ba46f40268.log](https://github.com/aspnet/Blazor/files/1972611/VSIXInstaller_de52d3d4-1758-4b62-9137-e2ba46f40268.log)

**Comment by danroth27** [comment]
@rynowak

**Comment by rynowak** [comment]
```
5/3/2018 12:43:29 PM - Microsoft VSIX Installer
5/3/2018 12:43:29 PM - -------------------------------------------
5/3/2018 12:43:29 PM - vsixinstaller.exe version:
5/3/2018 12:43:29 PM - 15.6.152+ge95e4dd1ce
```

What's your visual studio version? The installer is showing a 15.6 version number

**Comment by danroth27** [comment]
It should work on all VS SKUs. I have it installed on VS Enterprise. We'll take a look.

**Comment by danroth27** [comment]
@jwaller2040 Can you confirm that you have the latest preview of VS2017 15.7 installed? The Blazor VSIX requires the latest VS preview release. You can install it from https://visualstudio.com/vs/preview.

**Comment by jwaller2040** [comment]
![2018-05-03_16-10-42](https://user-images.githubusercontent.com/10502566/39603019-921ab168-4eec-11e8-8e76-441cca5438da.png)

**Comment by jwaller2040** [comment]
I thought it said 15.6.7? Wasn't aware of 15.7. I'll look

**Comment by jwaller2040** [comment]
It says that's the highest I can get...
![2018-05-03_16-13-37](https://user-images.githubusercontent.com/10502566/39603171-0a660316-4eed-11e8-9304-0435b16ba854.png)

**Comment by jwaller2040** [comment]
![2018-05-03_16-25-37](https://user-images.githubusercontent.com/10502566/39603600-a3a1728a-4eee-11e8-9be2-a514066912c5.png)

**Comment by touseefbsb** [comment]
@jwaller2040  you have to install preview as a separate installation, like I can see in ur latest comment, then you can install blazor extension in ur preview version of VS 2017 and then use it in that :)

**Comment by jwaller2040** [comment]
Okay, I guess the 15.6.7 and 15.7 were confusing for me. I will correct this and close if I can. Thanks for the quick help
