### ISSUE TITLE
Bootstrap Tool tip is not working

### ISSUE THREAD

**Issue by babula38** [aspnet/Blazor#748]
Hi this is blazor issue or i am doing something wrong. Even i tried working with Modal pop up even that did not work either. 
Html code in one of the component.
```html
 <a href="#" data-toggle="tooltip" title="Tooltip on top" id="idname">
                <span class="glyphicon glyphicon-plus"></span>
  </a>
```
this is in one of the js file test.js
```jquery
$(function () {
    $('#idname').tooltip();
    console.log("tool tip added");
});
```
below is the sequence of  files in index.html
```html
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link href="css/task.css" rel="stylesheet" />
</head>
<body>
    <app>Loading...</app>
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/test.js"></script>
    <script type="blazor-boot">
    </script>
</body>
```
**Note:- bootstrap version is v3.3.7, jquery version is v1.12.4**
I took the same files and same htmls to another project WebForm project for testing and it is working fine there.

**Comment by maraf** [comment]
Problem is with test.js, it binds to `DOMReady` event, but Blazor renders later.
You need to register your tooltip after blazor component renders, via javascript interop.

In your component, you can override `OnAfterRender` and call javascript function to initialize tooltips.
You can also look at how I solved showing bootstrap modals in [ModalBase.cs](https://github.com/maraf/Money/blob/master/src/Money.UI.Blazor/Components/Bootstrap/ModalBase.cs#L37-L51) and [Modal.cshtml](https://github.com/maraf/Money/blob/master/src/Money.UI.Blazor/Components/Bootstrap/Modal.cshtml). 
_Note: It's built using Blazor v0.2.0, so there is no OnAfterRender._

**Comment by SteveSandersonMS** [comment]
Yes, that's a limitation of the Bootstrap JS, which affects all SPA frameworks not only Blazor.

I'd recommend following @maraf's advice.
