### ISSUE TITLE
WASM: WASM doesn't support threading

### ISSUE THREAD

**Issue by StephanHartmann** [aspnet/Blazor#75]
I have a scenario where I like to have a socket connection in my c# part.
When new data arrives the html should be updated.
I tried to simulate this using a simple timer.
This results in a error message
`WASM: WASM doesn't support threading`

I don't need a timer in my code, but when there is no threading,
will asynchronous socket connections work properly?

**Comment by grahamehorner** [comment]
@StephanHartmann async is a promise/callback and doesn't necessarily need threading

**Comment by StephanHartmann** [comment]
I implemented the timer this way ...
` timer = new Timer(TimerCallback, null, 5000, 1000);`
For my understanding ...
The problem is not the TimerCallback - Function, but the fact that the timer uses threading to do his timing job, right ?

**Comment by grahamehorner** [comment]
@StephanHartmann yes; that's correct, timers use threading; a possible work around could be create a javascript timer, and call into the C# code from the javascript

**Comment by StephanHartmann** [comment]
ok, thank you

**Comment by SteveSandersonMS** [comment]
If you want to be called back after a timeout, `Task.Delay` should work.

Note that Mono WASM will be single-threaded, at least for the forseeable future. So you can do async, but only one execution thread will proceed concurrently and others will be queued. It's the same model that JavaScript has always used.

**Comment by jtheisen** [comment]
@SteveSandersonMS  I assume that it's even the same thread that WASM and Javascript uses, correct? (ie no synchronization needs to be considered)

**Comment by SteveSandersonMS** [comment]
Yes
