### ISSUE TITLE
Protecting against CSRF ?

### ISSUE THREAD

**Issue by RemiBou** [aspnet/Blazor#754]
Currently every api call on a controller action with an attribute ValidateAntiForgeryTokenAttribute (https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.validateantiforgerytokenattribute?view=aspnetcore-2.0) will give a 400.

How can we implement the sending / creation of the token on client side so our serverside is protected against CSRF ?

**Comment by SteveSandersonMS** [comment]
For now you'll need to solve this in whatever way you would for other SPA apps (e.g., React, Angular, etc.).

Eventually we will probably include built-in helpers for this but I'm afraid it will be a while before we get to it.

**Comment by aguacongas** [comment]
@RemiBou If you want, I've a sample [Chatle.Blazor](https://github.com/aguacongas/Chatle.Blazor) where you can see how I send anty CSRF headers and cookies.  
I used a specific [HttpMessageHandler](https://github.com/aguacongas/Chatle.Blazor/blob/dev/src/Chatle.Blazor/Services/ChatleHttpMessageHandler.cs)   
And in [Program](https://github.com/aguacongas/Chatle.Blazor/blob/dev/src/Chatle.Blazor/Program.cs) class, I set the `HttpMessageHandler` the DI and the fetch options to include credentials.
