### ISSUE TITLE
Securing app DLL against hackers

### ISSUE THREAD

**Issue by arc95** [aspnet/Blazor#755]
Hi all. I was just posting to the gitter and someone mentioned that DLL's can be reverse-engineered. How big a threat is this? What measures can we take to protect against this kind of threat?

What security features does Blazor have? Thank you.

**Comment by chrissainty** [comment]
This is no different to any current JavaScript SPA framework. Nothing you send to the client should be sensitive. I can’t see how Blazor could do anything to stop some one looking at your Dlls at the end of the day they have to have them for your app to run.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @chrissainty!
