### ISSUE TITLE
Pass ElementRef to callback from js to blazor?

### ISSUE THREAD

**Issue by MihaMarkic** [aspnet/Blazor#758]
Would it work if I pass element to Blazor.platform.callMethod that accepts ElementRef?
IOW from javascript to blazor (.net) method.
I'm trying to figure out from what DOM a callback originated.
So far I've been using unique Id attributes.

**Comment by SteveSandersonMS** [comment]
Currently unique IDs are the only option. Later on we'll implement a general mechanism for passing JS objects to .NET.

**Comment by MihaMarkic** [comment]
@SteveSandersonMS I assume both js and dom objects. Do you have an issue for this item, so I can track it?
