### ISSUE TITLE
question: Bound parameter value

### ISSUE THREAD

**Issue by dlr1** [aspnet/Blazor#761]
I have a component("mycomp"). I am just writing the value of parameter and expect the values to be in sync. what am I missing?
```
<div class="row" style="height:100px;width:300px;">
    bound charttype value:@ChartType
    <br />
    ChartTypeInMethod: @ChartTypeInMethod
</div>


@functions{
    [Parameter]
    string ChartType { get; set; }

    string ChartTypeInMethod { get; set; }
    public void MyMethod()
    {
        ChartTypeInMethod = ChartType;
    }
}
```
I am using the above component in another page like below
```
<div class="row">
    <mycomp ChartType="@ChartType" ref="comp1"></mycomp>   
    <div>
        <input type="radio" name="charttype" checked="@(ChartType=="bar")" value="bar" onchange="@((e)=>charttypeChanged(e))"/>bar
        <input type="radio" name="charttype" checked="@(ChartType=="line")" value="line" onchange="@((e)=>charttypeChanged(e))" />line
    </div>
</div>

@functions{        
    string ChartType { get; set; }
    mycomp comp1;
    
    void charttypeChanged(UIChangeEventArgs e)
    {
        ChartType = e.Value.ToString();        
        comp1.MyMethod();
    }
}
```

**Comment by SteveSandersonMS** [comment]
Please see *Component Attributes* on this page for information on the supported syntax: https://blazor.net/docs/components/index.html

Also the following post might be helpful: https://github.com/aspnet/Blazor/issues/743#issuecomment-386548638

**Comment by dlr1** [comment]
Just to clarify, I am not talking about the values not being updated.
The scenario is.
1. I click the radiobutton say "bar",
             onchange will be called 
                    ChartType  will be updated the parameter in the component is updated.
                    MyMethod of the component is called, there I set another variable value to the parameter value. I expect both of them to be same.

**Comment by SteveSandersonMS** [comment]
Blazor doesn't know you've changed the state inside `mycomp` unless it calls `StateHasChanged`.

**Comment by dlr1** [comment]
StateHasChanged has no effect
