### ISSUE TITLE
pointer events as not handled and oncontextmenu event type is wrong

### ISSUE THREAD

**Issue by attilah** [aspnet/Blazor#763]
I found out that [pointer](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) events are not handled by Blazor 0.3.0.

When I was about to add them, I saw that Blazor already have a ```UIPointerEventArgs``` class and it is associated with the [onContextMenu](https://github.com/aspnet/Blazor/blob/dev/src/Microsoft.AspNetCore.Blazor/Components/EventHandlers.cs#L44) handler, which is by the specs does not make sense, since it is a [mouse](https://developer.mozilla.org/en-US/docs/Web/Events/contextmenu) event.

If I see it correctly the only changes needed to support pointer events are:

Eventhandlers.cs:

```c#
    // Pointer events
    [EventHandler("gotpointercapture", typeof(UIPointerEventArgs))]
    [EventHandler("lostpointercapture", typeof(UIPointerEventArgs))]
    [EventHandler("pointercancel", typeof(UIPointerEventArgs))]
    [EventHandler("pointerdown", typeof(UIPointerEventArgs))]
    [EventHandler("pointerenter", typeof(UIPointerEventArgs))]
    [EventHandler("pointerleave", typeof(UIPointerEventArgs))]
    [EventHandler("pointermove", typeof(UIPointerEventArgs))]
    [EventHandler("pointerout", typeof(UIPointerEventArgs))]
    [EventHandler("pointerover", typeof(UIPointerEventArgs))]
    [EventHandler("pointerup", typeof(UIPointerEventArgs))]
```

EventForDotNet.ts:

```js
case 'gotpointercapture':
case 'lostpointercapture':
case 'pointercancel':
case 'pointerdown':
case 'pointerenter':
case 'pointerleave':
case 'pointermove':
case 'pointerout':
case 'pointerover':
case 'pointerup':
  return new EventForDotNet<UIPointerEventArgs>('pointer', { Type: event.type });
```

All the other places because of the ```oncontextmenu``` handler already having the pieces for pointer events.

Would you like to have a PR or you will copy these to the appropriate places?

**Comment by rynowak** [comment]
Hmm - you're right about contextmenu.

I was working from this list: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L3475 - which is inconsistent with the MDN docs. My gut is that mozilla's docs are more trustworthy.

Feel free to send a PR, that would be helpful.

If you need an unblocker on this based on 0.3 you can handle arbitrary events using `UIEventArgs`. Our mappings for these are just to help with strong typing and intellisense.

**Comment by attilah** [comment]
Yes, MDN is better as a source of truth :-)

Actually I was not able to handle arbitrary events, since when I declared my markup as:

```<Button onpointerdown=@"OnActivate" />``` compiler complained about cannot convert the delegate to string.

But it is not a blocker, I just exclude this event for now.

**Comment by galvesribeiro** [comment]
> <Button onpointerdown=@"OnActivate" /> compiler complained about cannot convert the delegate to string.

It is supposed to be `onpointerdown=@OnActivate` or `"@OnActivate"`
not `@"OnActivate"`

**Comment by rynowak** [comment]
Yes, I agree with @galvesribeiro - it should be possible to handle **any** event with the current approach. What's missing is the data.

**Comment by rynowak** [comment]
A pr adding the event payloads would be awesome if it includes some E2E tests where possible/practical 😍 

Regarding the browser APIs, it's clear it would be good that **somebody** build these kind of interop libraries and ship them. Long term it's not clear to us if we want Blazor to own them, or if they will be part of some other layer of the stack (like Mono). My suggestion for now would be to create a separate repo/package and put that on nuget. We'd be happy to link to it, and point folks in that direction. Example:

**Comment by attilah** [comment]
![image](https://user-images.githubusercontent.com/230432/39648129-48508490-4f96-11e8-984d-9ac6724667b6.png)

You see the squiggles, the error is this:

```Cannot convert method group 'OnActivate' to non-delegate type 'object'. Did you intend to invoke the method?```

**Comment by rynowak** [comment]
What's the signature of `OnActivate` look like? You might need to do something like `@((Action<UIEventArgs>)OnActivate)`

**Comment by attilah** [comment]
@rynowak based on my time in the [Orleans](https://github.com/dotnet/orleans) team, I know that once you lift something into the product and don't have the resources to maintain/test it, it is not the best for the customers, because they expect some level of support, etc.

We've talked with @galvesribeiro and ```window``` and ```document``` objects can be lifted to Blazor in many different (opiniated) way, but these are so fundamental pieces of browser interop that some level of baseline would be good from Microsoft ;-) yeah, maybe not at this point, but later.

**Comment by attilah** [comment]
@rynowak OnActivate is a generic event handler in the base class, works with the other events:

```protected void OnActivate(UIEventArgs e) { }```


The proposed cast syntax did not help.

**Comment by galvesribeiro** [comment]
> A pr adding the event payloads would be awesome if it includes some E2E tests where possible/practical 

Will work on that as soon as I get the first release of BlazorMaterial out on nuget. The initial release will be interoping with Google's JS. After that, we will try to drop the JS and use only C# and that is why I asked about event data.

> Regarding the browser APIs, it's clear it would be good that somebody build these kind of interop libraries and ship them.

Ok, got it. Will do that then. Thanks

**Comment by attilah** [comment]
@rynowak for me don't waste time on this ;-) if that's something that should work, then fine!
