### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by StephanHartmann** [aspnet/Blazor#78]
Is there a (planned) binding between C# Properties / ViewModel and the HTML UI fields?

In the MonoSanity Sample binding is done with plain javascript.
Will there be a Blazor mechanism, or should we use something like Knockout or other frameworks for Binding?

**Comment by grahamehorner** [comment]
@StephanHartmann IMHO Blazor at some point would use ViewModel and attribution to generate/link html components rendered to the browser with the Blazor properties/events/code; and would including ViewModel validation attributes, but it's worth keeping in mind that it's very very early in development/research stages so it I'm sure wont be anytime soon; unless @SteveSandersonMS has anything hidden up his sleeves ❓

**Comment by SteveSandersonMS** [comment]
This is already implemented - it's one of the most core parts of the system. Like most new SPA platforms these days, each time we have notification that a component's state has changed, it re-renders to produce a new render tree, which is then diffed against the previous render tree and the changes are applied to the UI elements. It's a very widely used system that performs great and enables simple, productive code patterns.

**Comment by StephanHartmann** [comment]
@SteveSandersonMS wow, that sounds great ...I hadn't expected that yet :)
What we (ok, I) would need (like to see)  is a simple sample 
which shows how the developers want us to use it  ...

**Comment by SteveSandersonMS** [comment]
@StephanHartmann At the moment we're focused on the implementation rather than any samples. In another month or so we'll move to a more usage-centric mode where we ship packages, templates, and have reasonable samples. In the meantime if you want to be a super-early pioneer please do dig in, but you'll have to read the sources and figure out the internals yourself :)
