### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by simonziegler** [aspnet/Blazor#781]
Hi,

As I experiment, I would like to see if I can enforce Https communication between the Blazor Client and Server. Is there a way to do this please? Sorry if this is a basic question.

Simon

**Comment by aguacongas** [comment]
You can enforce it on server side probably

**Comment by simonziegler** [comment]
Hi Oliver, thanks for the quick response.

I should have been clearer with my question. I managed to enforce HTTPS server side, and then there was just no communication thereafter. I have been doing this with the basic WeatherForecast template and setting breakpoints in the SampleDataController.cs file. With HTTPS: no breaks it. When I remove the HTTPS enforcement: breakpoints hit and everything works as it should.

So my question should have been: how do I use HTTPS client side?

Thanks!

**Comment by MihaMarkic** [comment]
@simonziegler Did you check requests in browser's development tools?

**Comment by simonziegler** [comment]
@MihaMarkic, sorry, but as I'm very new to web programming (only working on a prototype before hiring a team to build the real thing), I don't really know how to do what you suggest, and where it gets me. I think for the prototype I'm going to ignore HTTPS. It would be nice, but it isn't really necessary.

Thanks!
