### ISSUE TITLE
The demo app displays nothing in the browser.

### ISSUE THREAD

**Issue by Marcel-B** [aspnet/Blazor#783]
Hello, everybody.

When I start the demo project, the browser opens, but it is nothing displayed (only **Loading...** for a few seconds) . It looks like everything (e.g. .net dll's, blazor.js, mono.js and mono.wasm) is loaded correctly into the browser. There are no visible errors or exceptions. In the windows cmd are also no errors, only green info messages.
In the "Inspektor" I only see inside the body tags:

`<router appassembly="typeof(Program).Assembly"></router>`

_(Visual Studio 2017 Preview Professional on Windows 10, Blazor v0.3.0, Mozilla Firefox)_

**Comment by floreseken** [comment]
Did you install dotnet core 2.1 preview 2?

**Comment by SIkebe** [comment]
'dotnet --info' output?

**Comment by Marcel-B** [comment]
Version: 2.1.200-preview-007597

Microsoft .NET Core Shared Framework Host:
Version 2.0.7

A fresh install, maybe 3 hours old.

**Comment by SIkebe** [comment]
You need 2.1.300-preview2-008533 or later.
See here for more info.
https://blogs.msdn.microsoft.com/webdev/2018/05/02/blazor-0-3-0-experimental-release-now-available/

**Comment by Marcel-B** [comment]
This is the link I've downloaded [VisualStudio 2017 Preview](https://www.visualstudio.com/de/vs/preview/). Then I'have downloaded the Blazor template inside VisualStudio.

**Comment by Marcel-B** [comment]
Allright. It was the wrong sdk version. Version 2.1.300 has fixed the issue. Thx! Great work, Blazor is rerally nice.
