### ISSUE TITLE
Proposal: Optimize render tree build & diff with lazy RenderFragments

### ISSUE THREAD

**Issue by GoldenCrystal** [aspnet/Blazor#788]
# Summary

I noticed that components that produce a lot of HTML elements tend to become noticeably slow.

You can observe this on the linked page if you click on the button at the bottom a few times : https://unicode-browser.azurewebsites.net/blocks/CJK%20Unified%20Ideographs
What you should observe is that at some point, even the spinner takes time to appear.
(Likely because Blazor is re-rendering the whole table for each small update)

# Rationale

Today, it seems we are able to separate updates of the DOM by enclosing parts of the application in a component.
However, splitting a page in many small components only for the purpose of rendering optimization tends to be very tedious, and maybe not doable at all in some cases.

The idea here is to provide a way for avoiding to re-render semi-static content everytime the ````BuildRenderTree```` is called.

# Proposal

I propose that Blazor would provide a mechanism in-between ````RenderFragment```` and ````BlazorComponent````.
Let's say that we provide to ````RenderTreeBuilder```` a ````RenderFragment```` that is tagged with a **unique** string ID (e.g. a GUID string in some cases).

The API could look like this:

````csharp
class RenderTreeBuilder
{
    // …
    public void AddLazyContent(int sequence, string id, RenderFragment fragment) { /* … */ }
    // …
}
````

The idea is that you generate a unique ID so as to let the render tree diff builder to identify your specific fragment (and detect addition/removal of said fragment), but the lazy fragment is only rendered once, when it is newly added in the render tree.
(NB: It may be rendered subsequently if it is removed, then added back later)

## Caveats

Developers would have to stay aware that the lazy content will be evaluated outside of the ````BuildRenderTree```` method (hence its lazyness), and remember to be careful about closures.
However, it might not be that different from ````RenderFragments```` generated outside of the ````BuildRenderTree```` method.

### For Razor codegen

Code generation for cshtml could take advantage of this in cases like these:
````html
<table>
    <!-- This part is static -->
    <thead>
        <tr>
            <th>Foo</th>
            <th>Bar</th>
        </tr>
    </thead>
    <!-- End of the static part -->

    <!-- This contains dynamic content -->
    <tbody>
        @foreach (var item in Items)
        {
            <tr><td>@item.Foo</td><td>@item.Bar</td></tr>
        }
    </tbody>
    <!-- End of the dynamic content -->
</table>
````

There, the codegen could determine that ````table > thead````, unlike ````table > tbody````, is purely static content and generate a lazy fragment (with a statically generated string ID) that would span the whole ````thead```` tag and would only be evaluated once.

Thus, when the developer requests the page to refresh, the whole markup for the table header wouldn't have to be re-generated, and only the parts related to the dynamically-generated ````tbody```` would be rebuilt. (That obviously includes the enclosing ````table```` element, which contains the ````tbody````, itself containing the dynamic content)

### For manually generated components

Developers could use lazy content for parts of the document that are dynamic, at their own risk, thus avoiding the cost of rebuilding the whole render tree when they only need to update a small part of a document.

### For manually generated components

It might be even better if lazy fragments could be forcefully re-rendered, thus blurring the lines with components even more.
I am not sure how this would be best achieved, however. Maybe by calling a method based on the string ID ?

### For components

It would be great if there was a way to indicate that an element should be treated as lazy, even tough it contains fragments of C#. (Maybe something like a ````blazor-lazy```` attribute ?)
This would allow more flexibility in the design of pages/components, without having to resort to manually built render trees.

**Comment by DNF-SaS** [comment]
We also have massive performance problems when rendering many components. (not 100% sure, if there's a true causality between performance and component-count)

**Comment by DNF-SaS** [comment]
Here's part of Chrome's debug log of a page rendering 107 Elements with each around 5 sub-elements (none of them are doing CPU-intense work).
Maybe it helps hunting this issue:

```
WASM: Mono: GC_MINOR: (Nursery full) time 4.30ms, stw 4.40ms promoted 934K major size: 4784K in use: 4021K los size: 2048K in use: 1618K - MonoPlatform.ts:195
[Violation] 'setTimeout' handler took 3109ms - mono.js:1
WASM: BASE(Browse) ENTER: True - ShouldRender @ ComponentBase.cs:102 - MonoPlatform.ts:195
WASM: 107 x Returning cached DbSpecificWithAuth - ExecuteAsync @ CommunicationService.cs:92 - MonoPlatform.ts:195
[Violation] 'click' handler took 7107ms
WASM: Mono: GC_MINOR: (Nursery full) time 1.80ms, stw 1.90ms promoted 452K major size: 7344K in use: 6577K los size: 2048K in use: 1775K - MonoPlatform.ts:195
WASM: 9 x BASE(ElementFrame) ENTER: True - ShouldRender @ ComponentBase.cs:102 - MonoPlatform.ts:195
[Violation] 'setTimeout' handler took 1504ms - mono.js:1
WASM: Mono: GC_MAJOR_SWEEP: major size: 10640K in use: 20719K - MonoPlatform.ts:195
WASM: Mono: GC_MAJOR: (LOS overflow) time 9.10ms, stw 9.20ms los size: 2048K in use: 52K - MonoPlatform.ts:195
WASM: 98 x BASE(ElementFrame) ENTER: True - ShouldRender @ ComponentBase.cs:102 - MonoPlatform.ts:195
[Violation] 'setTimeout' handler took 8870ms - mono.js:1
```

**Comment by floreseken** [comment]
The json serializer? I've noticed this also.. above a few 100 entries it seems to get slow indeed.. up to a 100 its fast.

**Comment by DNF-SaS** [comment]
@floreseken Yes. Deserializing in non-wasm environment of our test-json takes about 10ms, the same code runs about 120ms in blazor. If you have a lot of components each deserializing a lot of JSON, it really gets ugly.

**Comment by floreseken** [comment]
Yes. But i'm pretty sure there must be room for improvement.. so I'm confident it will be fixed in the future..

**Comment by DNF-SaS** [comment]
I suppose AoT will speed it up a lot.
We can only hope that Blazor leaves the experimental status soon.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion, @GoldenCrystal!

This is a pretty cool idea. As it happens, however, we already have a plan that will hopefully provides the same benefits this offers without the complication of another thing that developers need to learn about:

 * For large blocks of static HTML, we plan to change the compiler to collapse it all into a single node. So you can have arbitrarily much static HTML without any extra per-element render cost. This will greatly reduce the number of rendering operations per typical component.
 * For dynamic content where you really want the "render only once" behavior mentioned here, the built in system already exists, which is to factor it out into a separate component. Having to pass params into it forces the developer to be aware of exactly what data constitutes the input for the rendering process, and guarantees that it re-renders when those specific properties change.

> However, splitting a page in many small components only for the purpose of rendering optimization tends to be very tedious, and maybe not doable at all in some cases.

To make it easier and faster, the ultimate goal is to have very simple IDE refactorings that let you highlight a block of markup and choose *Extract component*, just like you can *Extract method* from a block of C# source.

I'll close this because I think we already have this covered in the plan. Hope that's OK!

**Comment by Andrzej-W** [comment]
@GoldenCrystal I have checked your example app and noticed that it works reasonably fast in Firefox and Edge but it is **much slower** in Chrome.
