### ISSUE TITLE
it is not work in IE11 or FireFox59.0.3

### ISSUE THREAD

**Issue by w8w8w8** [aspnet/Blazor#789]
when I test use IE11 , it is not work,  show "promise" undefined.
can you help me? or how to fix this bug

**Comment by SteveSandersonMS** [comment]
You need some extra polyfills to make it work on IE11 or other old browsers, but it's not a scenario we're focusing on at the moment so I don't have the exact details. Perhaps anyone who's made this work might post info.

The underlying runtime doesn't require WebAssembly (it falls back on asm.js for older browsers) but we do assume other recent APIs such as `Promise` are available, hence the need for polyfills on older browsers.

**Comment by ericwj** [comment]
Would it be useful to keep this open with a proper tag and let people comment how to fix this?

I tried several polyfills but either I get other JavaScript errors or with babel-polyfill I get complaints about Uri format from EnsureBaseUriPopulated. That is FlightFinder ported to 0.4.0 in IE11 on Win10.

**Comment by Suchiman** [comment]
There is https://github.com/Daddoon/Blazor.Polyfill which worked for me in some experiments.

**Comment by danroth27** [comment]
@daddoon would you like to add https://github.com/Daddoon/Blazor.Polyfill to three community page on https://blazor.net?

**Comment by Daddoon** [comment]
Hi everybody!

I was not even aware that there were a Community page.
Yes i think it would be great to add my repo in this page.

You may also consider my Blazor hosted in Xamarin support project.

- [Blazor.Polyfill](https://github.com/Daddoon/Blazor.Polyfill)
- [Blazor.Xamarin](https://github.com/Daddoon/Blazor.Xamarin)

Note, even if my Blazor.Polyfill project was mainly for IE11 support, it's also my codebase, when having to manage some inconsistent behavior on some Mobile browsers (Safari UIWebview/Safari WkWebView, Chrome etc...).

**Comment by danroth27** [comment]
@Daddoon Cool, go ahead and submit a PR then on the https://github.com/aspnet/blazor.docs repo to add links to these projects to the Community page on https://blazor.net and we'll help you get it merged.

**Comment by Daddoon** [comment]
I was not aware (again!) that the doc was hosted on Github. Sorry @danroth27  for the inconvenience.
I just made the PR, thanks for the tips!
