### ISSUE TITLE
Required Component Parameters

### ISSUE THREAD

**Issue by schotime** [aspnet/Blazor#791]
Given that 0.3 added the `[Parameter]` attribute. Could it also take a boolean that says its a required parameter and must be passed otherwise compilation fails.

```cs
@functions {
   [Parameter(true)]
   string Title;
}
```

**Comment by Andrzej-W** [comment]
It is planed. Read #709.

**Comment by SteveSandersonMS** [comment]
Yes, we have it in mind to do this. Now added to #1 for tracking.
