### ISSUE TITLE
Circularly dependent layouts cause lockups

### ISSUE THREAD

**Issue by csnewman** [aspnet/Blazor#793]
Layouts that are circularly dependent are not handled gracefully and instead causes a browser lockup.

### Example 1
**SomeLayout**
```
@inherits BlazorLayoutComponent
@layout SomeLayout
```

### Example 2
**LayoutA**
```
@inherits BlazorLayoutComponent
@layout LayoutB
```

**LayoutB**
```
@inherits BlazorLayoutComponent
@layout LayoutA
```

### Example 3
**SomeLayout**
```
@inherits BlazorLayoutComponent
```

**_ViewImports**
```
@layout SomeLayout
```

**Comment by SteveSandersonMS** [comment]
This is exactly equivalent to having method A which calls method B which calls method A again, without any clauses to stop the infinite recursion. So locking up the CPU is the expected outcome, at least for now.

I appreciate this is a case where we *could* detect cycles and abort with a nice error message. Eventually we may want that sort of thing if it becomes a common issue. For now I'd suspect it would be quite rare for someone to do this, so I'd rather not direct efforts to solving it. Hope that's OK!

**Comment by csnewman** [comment]
I admit most of these examples are quite contrived, however I came across the _ViewImports one when quickly messing around. It was instantly obvious to me what the cause was, however I imagine this style of recursion could happen quite easily when someone is messing around for the first time. But this isn’t really a concern until the framework goes mainstream anyways, as I assume anyone who is testing the framework in its current state would be able to see what happened without much thought.

**Comment by SteveSandersonMS** [comment]
I agree!
