### ISSUE TITLE
Loading issue when built with dotnet core 2.1 RC

### ISSUE THREAD

**Issue by tallichet** [aspnet/Blazor#798]
Since I have updated to dotnet core 2.1 RC released yesterday, I am no able to run the blazor app I build and run.

Is there some known issues?

**Comment by floreseken** [comment]
Also tried this, and it works for me. What is the error?

**Comment by rynowak** [comment]
Hi @tallichet - there are no known issues with Blazor and the RC. It would be great if you could post some more information about the kind of problems that you are having.

**Comment by rynowak** [comment]
What about other browsers?

**Comment by tallichet** [comment]
dotnet --version returns **2.1.200** for the solution and both projects

same issues with Firefox and chrome. Both giving not information in the console.

Do you have other idea on how to "debug" it.

Please note I have the exact same problem when building with dotnet.exe or visual studio

**Comment by floreseken** [comment]
2.1.200 is the wrong version. You need 2.1.300 Preview2-008533

**Comment by floreseken** [comment]
Please make sure you have a global.json to pin your version

**Comment by tallichet** [comment]
Ok. This means it does not work yet with the RC version, right?

**Comment by floreseken** [comment]
Please place a global.json in your solution folder with this content:

`{
  "sdk": {
    "version": "2.1.300-rc1-008673"
  }
}
`

And run `dotnet --version` again in your project folder.

**Comment by floreseken** [comment]
If it doesn't return the RC version, please make sure .net core 2.1 RC is correctly installed.

**Comment by tallichet** [comment]
Ok, It's works. Thanks to all of you. Seem the 2.1.200 version is a bit misunderstanding (on my side).

Sorry!

**Comment by floreseken** [comment]
Great,

**Comment by danroth27** [comment]
@tallichet we've seen quite a few folks end up with the wrong version of the sdk installed and we'd like to understand better how that happens so that we can make the experience better. Could you please share with us some details on how you ended up with the wrong version? You seemed pretty sure you had the 2.1 RC installed. Is there maybe a bad link someplace? Or some confusing instructions?

Thanks for this feedback and thanks for trying out Blazor!

**Comment by tallichet** [comment]
@danroth27 in my opinion, the root cause is the sdk version misunderstanding.


When i've read about the RC being live ready, I go to the dotnet core sdk download page and see **2.1.200** and understood it as dotnet core 2.1 version. Then, I when I've got issues, I checked the dotnet --version and see the 2.1.200... and i was thinking: _ok, it's core 2.1!_


From my discussions here and there, I know the versions difference between _dotnet core_ and _dotnet sdk_ is a key problem for most of developers

**Comment by Suchiman** [comment]
Yeah that .NET Core 2.0 is `2.1.200` and 2.1 is `2.1.300` tripped everyone over i've seen here and on gitter so far, but at least we'll now have synchronized version numbers again, starting with 2.1

**Comment by floreseken** [comment]
I think the difference between the runtime and the sdk is not clear to everyone (and the fact they have misaligned version numbers)
