### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#80]

**Comment by SteveSandersonMS** [comment]
Done

**Comment by grahamehorner** [comment]
Please consider extending Dependency Injection to support registration of TypeScript/JavaScript interop and/or styles; so when the .NET assembly is injected any associated TypeScript/JavaScript and/or style the interop requires/uses by the implementation is injected into the browser dynamically.

**Comment by danroth27** [comment]
@grahamehorner Since this issue is closed you should file a new issue with your request.
