### ISSUE TITLE
Bind multiple values from input box 

### ISSUE THREAD

**Issue by ulkaio** [aspnet/Blazor#805]
I have a multiple select input box 

```
<select multiple="multiple" bind=state.states>
  <option value="AL">Alabama</option>
  <option value="WY">Wyoming</option>
  <option value="WY">Washington</option>
</select>
```

I like to access the value selected via state.states but I am getting empty here. What is the right way to do this. Thanks.

**Comment by Andrzej-W** [comment]
According to doc correct syntax for binding is `bind="@state.states"`.
Currently select multiple doesn't work - it return only first selected item #809.
You have value "WY" for two last items.

**Comment by SteveSandersonMS** [comment]
Thanks for raising this, @ulkaio. I think #809 now covers this, so I'll close in favour of that.

**Comment by ulkaio** [comment]
Thanks @SteveSandersonMS  for workaround now, I used JavaScript interop to get the selected values.
