### ISSUE TITLE
Browser Culture & other environment variables

### ISSUE THREAD

**Issue by frankabbruzzese** [aspnet/Blazor#807]
It would be very useful to have informationon about the runtime environment, such as browser culture, in an Environment class. In particular the CurrentCulture might be set automatically to the browser culture, so that dates and numbers might be automatically displayed according to the Browser culture.
(I know this is easily achieved by calling some JavaScript environment filling function, but....)

It would be nice to have also information on the supported tags, so that "smart components" might automatically revert to widget when an Html5 input is not supported (Html5 input support is far from being complete on the mainstream browsers...also among the ones that support WebAssembly).

**Comment by SteveSandersonMS** [comment]
We're tracking the localization items in #60 

> It would be nice to have also information on the supported tags

That's something that a third-party JavaScript feature detection library would probably do best. We won't have the resources to maintain a database of which browsers support which features, or how to do feature detection in each of them. Third-party JS libraries specifically exist for this use case, so it will be best to invoke them via JS interop.
