### ISSUE TITLE
Missing function: schedule_background_exec

### ISSUE THREAD

**Issue by cgravill** [aspnet/Blazor#81]
Great to see more activity on this!

I tried out with some .net code we like to run client-side and was pleasantly surprised to see that it worked without change. However, when I run the same function a few times I get a warning schedule_background_exec followed by an abort:

![image](https://user-images.githubusercontent.com/1099725/35987362-5c2e06e4-0cf3-11e8-9ce4-034d2fbf3152.png)

Is this likely to be a memory issue? I can find schedule_background_exec in the mono source but it looks like the version in Blazor (library_mono.js) is older: https://github.com/mono/mono/commit/d5ebaad99dfe2b3bed1fbf7b30ecb0ba9c3252ed#diff-342565351091ae5f9ac0212cc298e1f5

**Comment by SteveSandersonMS** [comment]
If you have a small repro, could you post it? There's a good chance this will just go away on its own when we update Mono, but it would be nice to check.

**Comment by cgravill** [comment]
Sounds good. You can reproduce this by replacing RepeatString in MonoSanityClient:

```csharp
var result = new StringBuilder();

for (var j = 0; j < 10000; j++)
{
    var innerResult = new StringBuilder();

    for (var i = 0; i < count; i++)
    {
        result.Append(str + j.ToString());
    }
}

return result.ToString();
```

then if you click once it works, a second time it fails.

It's not just the repeat, if you replace the parameter from "Hello" something longer, e.g. "Missing function: schedule_background_exec" it fails within one call.

**Comment by SteveSandersonMS** [comment]
As predicted, this problem went away on its own when I updated Mono. I guess they fixed it by adding this line: https://github.com/aspnet/Blazor/blob/1d79e72167ff22cead24ff16b0ace79c18a77d82/src/mono/incoming/library_mono.js#L14

Thanks again @cgravill for posting the really clear repro :)

**Comment by cgravill** [comment]
Thanks @SteveSandersonMS that's excellent and much appreciated. The update works for our actual code too - compilers with bigger code examples. It also worked with some of our optimisation code based on Math.NET which is pretty impressive!
