### ISSUE TITLE
One Time Binding

### ISSUE THREAD

**Issue by neerajbharti** [aspnet/Blazor#816]
Add support for one time binding, such that once the binding has been evaluated and set, it does not take part in future refreshes of the component. 
This will be helpful in gaining some performance where we know that some of the data is not going to change during the life cycle of the component. For example some json content fetched from server which needs to be rendered in a table and we know this data will not change for very long time.

**Comment by SteveSandersonMS** [comment]
The approach we're using is that components are the unit of re-rendering. So if there's part of a component you only want to be rendered once, you can factor that out into a child component. The child component will only get re-rendered when its parameter values change.

**Comment by neerajbharti** [comment]
Thank you for reply Steve
