### ISSUE TITLE
Dependency Injection for dynamic Dependency Injection

### ISSUE THREAD

**Issue by keyneom** [aspnet/Blazor#819]
I'm new to Blazor so perhaps this is already supported but not documented functionality, but is there a way to inject the ServiceProvider itself so that a component or service can resolve dependencies dynamically?

If this isn't already possible, it'd be great to be able to do so!

**Comment by RemiBou** [comment]
This pattern is called the service locator pattern and is often viewed as an antipattern. 

But given this code :
https://github.com/aspnet/Blazor/blob/a9c45fe78ac18b6bd524904b40896c249f9f09c0/src/Microsoft.AspNetCore.Blazor.Browser/Services/BrowserServiceProvider.cs

It's not injected by default, so you have to reimplement the interface so the class inject itself on the serviceCollection.

**Comment by danroth27** [comment]
Blazor uses the same DI system as ASP.NET Core, which supports injecting the `IServiceProvider`. This works:

```
@inject IServiceProvider Services

@functions {
    WeatherForecast[] forecasts;

    protected override async Task OnInitAsync()
    {
        var client = Services.GetRequiredService<HttpClient>();
        forecasts = await client.GetJsonAsync<WeatherForecast[]>("/sample-data/weather.json");
    }
}
```

**Comment by keyneom** [comment]
Wow, left for work, come back and an answer already. Thanks @danroth27 (and Microsoft)! That was fast, I'm excited about the direction things are headed!
