### ISSUE TITLE
Integrate illink with the build pipeline

### ISSUE THREAD

**Issue by javiercn** [aspnet/Blazor#82]
We want to do illink as part of either build/publish to trim the BCL based on what your app -uses.
- [ ] Create a nuget package with the illinker tool.
- [ ] Consume the illinker as part of our build process.
- [ ] Update our MSBuild targets to run the linker on the application after build.

**Comment by arkadiuszwojcik** [comment]
Isn't that already done by: ILLink.Tasks package as described in: [linker instructions](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md) ?

**Comment by SteveSandersonMS** [comment]
@javiercn This is done, right? I'll mark it as closed, but if this was meant to be left open because there's still some outstanding work, please reopen or let me know!

**Comment by javiercn** [comment]
Yeah, that is correct. I missed it while going through the issues. Thanks!
