### ISSUE TITLE
No way to bind <input readonly />

### ISSUE THREAD

**Issue by davidnmbond** [aspnet/Blazor#825]
There is no way to bind an input readonly attribute to a bool.

This results in the following code abomination:

```
@if (Readonly)
{
    <input readonly type="@InputType" class="form-control" aria-describedby="emailHelp" placeholder="@Placeholder" value="@Value" onchange="@ItChanged" />
}
else
{
    <input type="@InputType" class="form-control" aria-describedby="emailHelp" placeholder="@Placeholder" value="@Value" onchange="@ItChanged" />
}
```

**Comment by mihail-shishkov** [comment]
To generalize this:
the following construct

 `<input type="text" @(true ? "readonly" : "") />`

results in 

`Error	BL9980	Expressions like 'true ? "readonly" : ""' inside of a tag must be part of an attribute. Previous releases of Blazor supported constructs like '@onclick(...)' or '@bind(...)'.These features have been changed to use attribute syntax. Use 'onclick="@..."' or 'bind="..." respectively.
`

**Comment by mihail-shishkov** [comment]
This is working fine
```
 <input type="text" readonly=@true/>
 <input type="text" readonly=@false/>
```

**Comment by davidnmbond** [comment]
(facepalm) - you're right - thanks Mihail!
