### ISSUE TITLE
where does blazor stand with web components?

### ISSUE THREAD

**Issue by touseefbsb** [aspnet/Blazor#828]
reference : https://www.youtube.com/watch?v=7CUO7PyD5zA

web components aim to standardize the UI for web irrespective of how we do web development I just want to know whether brazor will be in sync to that so we can take advantage of that standardized web components and widges at one place, instead of being over whelmed by a lot of ways to build ui widgets.

**Comment by SteveSandersonMS** [comment]
Blazor lets you run any client-side JavaScript that you want, so you can use any WebComponent inside a Blazor app.

However Blazor components are not themselves WebComponents, just like React components aren't WebComponents, and Angular components aren't WebComponents, and Vue components aren't WebComponents. The reason for this is that each framework provides its own distinct features and benefits.

**Comment by kwaclaw** [comment]
Angular Elements are web components., and the reason they are part of Angular is that web components are part of the HTML standard and therefore recognized by the browser without help from any framework.

I don't see how parts of the HTML standard can be ignored by Blazor.

**Comment by Sellorio** [comment]
I too am interested in a feature similar to Angular Elements that would allow Blazor components to be 'compiled' in some way into native Web Components which can be easily shared amongst different projects that use different technologies for UI development. My company is only just now moving towards standardising to Angular as our UI but if Blazor could be used in parallel then we could switch to that without conflicting with other teams.

**Comment by nickrandolph** [comment]
@SteveSandersonMS is there any support planned within Blazor for web components (both consuming and creating a web component in Blazor)? With the direction that React and Angular are going, Blazor will need to support the web component standard if it's to be a viable SPA alternative.

**Comment by kwaclaw** [comment]
Looking more into web assembly, the problem seems to be that the current
spec has no provision for DOM access other than interacting with JavaScript.

Such a direct DOM API seems to be planned for a future version of the spec.

**Comment by veikkoeeva** [comment]
Maybe use Worker DOM as described at https://github.com/ampproject/worker-dom. Some maybe interesting techniques are described at https://www.loxodrome.io/post/easier-web-workers/. I could imagine caching Blazor WASM in worker and using something like COMLink to offload things (jointly with webcomponents) could become interesting.
