### ISSUE TITLE
Serving static files using Blazor routing

### ISSUE THREAD

**Issue by ericgrantholland** [aspnet/Blazor#830]
Is it possible to serve static files that are stored in the root folder(.PDF,.DOCX,.TXT, etc)?

**Comment by floreseken** [comment]
Or do you mean the razor pages root folder?

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @floreseken. And yes, `wwwroot` is the conventional place to put static content that you just want to serve as-is.
