### ISSUE TITLE
Blazor Hosting multiple wasms/assemblies

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#84]
Please consider allowing the Blazor host to support multiple assemblies; currently the app.UseBlazor(...) only allows one assembly, allowing multiple assemblies would cater for cultures that have a RTL layout and/or require larger display area for localisation of text etc.

**Comment by SteveSandersonMS** [comment]
Blazor lets you reference as many assemblies as you want. Just reference them from your Blazor client application. You still only need one entry point in `app.UseBlazor`. If there are scenarios where this doesn't work, could you let us know what aspect of it is insufficient?

As for localisation, we're tracking that in #60.
