### ISSUE TITLE
Bootstrap 4 Templates Update to v4.1.1

### ISSUE THREAD

**Issue by dotnetnoobie** [aspnet/Blazor#847]
The current Blazor templates are Bootstrap 4.0.0
the latest bootstrap is currently v4.1.1

Any chance of updating the templates to use the latest version of Bootstrap 4 to save having to manually update it every time you make a new project?

**Comment by SteveSandersonMS** [comment]
If the changes are reasonably small, we'd be happy to take a PR for it.

If it's a complex change we would rather not chase every Bootstrap update, since during the current phase our capacity is limited and we need to focus on core Blazor improvements instead. Hope that's OK.

**Comment by dotnetnoobie** [comment]
From what I gather it's really just bug fixes that have been found, so it would just be a case of updating the files with no changes to the actual template 

https://blog.getbootstrap.com/2018/04/30/bootstrap-4-1-1/

We’re a few weeks out from v4.1 and we have our first patch release of Bootstrap 4! It’s a straightforward set of bug fixes and build tool quality of life updates.

Here’s a quick rundown of some of the changes:

Added validation styles for file inputs
Improved printing of dark tables
Suppressed that text-hide deprecation notice by default
Fixed an issue where Collapse wasn’t working in Internet Explorer
Cleaned up some JS globals and improve coverage
Bumped dependencies, namely Jekyll
Fixed docs issue with incorrect name for our monospace font utility
Checkout the full v4.1.1 ship list and GitHub project for the full details. Up next will be v4.1.2, another patch release to address the next set of CSS and JS bugs you’ve help share with us since v4 launched.
