### ISSUE TITLE
Routing with query string parameter not working.

### ISSUE THREAD

**Issue by babula38** [aspnet/Blazor#849]
I tried to use to get the parameter from the querystring to but it is not happening.

if router support querystring could you please past the syntax to declare and use it

**Comment by babula38** [comment]
suppose the url is **/test?query=abc**

@page "/test/{query}"

**Comment by floreseken** [comment]
Then your url should be **/test/abc**

and include this in your functions:

`
[Parameter]`
`private string query {get;set;)
`

**Comment by babula38** [comment]
@floreseken this is happening perfectly. but my requirement is to get from the querystring.
i tried 

```html
<a href=/test?query=abc/>

```
Component code is below
```csharp
 @page "/test"

[parameter]private string query{get;set;}
```
in the above case routing is happening but parameter binding is not happening.

**Comment by floreseken** [comment]
Not sure if this is supported at this moment.

**Comment by Andrzej-W** [comment]
It is tracked here #293

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @Andrzej-W!

**Comment by hippieZhou** [comment]
if I want add querystring in `NavLink` component, such as :

```bash
<NavLink class="nav-link" href="/fetchdata?query=@item.tostring()">
                    @item
</NavLink>
```

what shoul I do ?

**Comment by thancock14** [comment]
I don't know if this is a good idea or not but this is what I have done for server-side to extract the Query from my url when the page renders.
Since the OnInitializedAsync runs twice the first time the real absolute URL query is available. but the second time it's not.
so:
 static string queryStringFromFirstRender = null;
 string QueryString;
    protected override async Task OnInitializedAsync()
    {
        if (queryStringFromFirstRender != null)
        {
            QueryString = queryStringFromFirstRender;
            await RunSomething(QueryString);
            queryStringFromFirstRender = null;
        }
        var Query = httpContextAccessor.HttpContext.Request.Query;
        queryStringFromFirstRender = Query["q"];
    }
