### ISSUE TITLE
Console.Log

### ISSUE THREAD

**Issue by nbarkhina** [aspnet/Blazor#85]
Is there an API to call Console.Log directly from the .NET side? Or do you always need to use the InvokeJS technique I saw in the Sample app that has to match a registered function? Like how would I just run some JS from C# is there an easy way to do that?

Thanks

**Comment by SteveSandersonMS** [comment]
Just use `System.Console.WriteLine` - it will write to the browser console.

**Comment by SteveSandersonMS** [comment]
> Like how would I just run some JS from C# is there an easy way to do that?

For now, use the registered function approach. If you end up with use cases where it's not a good solution, please let us know.

Later on, we hope to have a library of standard C# wrappers around standard browser APIs.
