### ISSUE TITLE
Detect component parameter name errors at compile time

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/Blazor#864]
Let's assume I have a component with parameter and I use it in some cshtml file like this:
```html
<MyComponent ParamName="something"></MyComponent>
```
Intellisese works correctly and it is easy to write correct parameter name. Now let's assume I want to do some refactoring and I'm changing parameter name (in MyComponent source code) to something else.

First, I would like to have the possibility to press `<Ctrl>+<.>` and select Rename. Unfortunately this doesn't work in cshtml files :cry: So it is easy to introduce some errors in code and those errors are not detected at compile time - we get runtime exception. It is not what we want. Blazor should be better than JavaScript.

**Comment by dotnetnoobie** [comment]
If I remember correctly from one of the "Build" videos refactoring in .cshtml files is coming soon (maybe with aspnet core 2.1, can't remember exactly)

not sure if this will apply to Blazor apps / components or not

**Comment by conficient** [comment]
Blazor's cshtml editor is built on Razor's so it should in theory get the benefit

**Comment by SteveSandersonMS** [comment]
Yes, we do expect future Razor refactoring enhancements to apply to Blazor to enable renames like that.

As for detecting the incorrect parameter name, this is tracked as *Controlling whether arbitrary non-declared parameters can be passed* in issue #1.
