### ISSUE TITLE
awaitable method group

### ISSUE THREAD

**Issue by iambipinpaul** [aspnet/Blazor#87]
Not able to call `async` method as `<button @onclick(await ClickeMe)>ClickMe</button>`.

**Comment by davidfowl** [comment]
Try onclickAsync

**Comment by SteveSandersonMS** [comment]
It will (probably) be onclickAsync but it's not implemented yet.

**Comment by iambipinpaul** [comment]
@SteveSandersonMS is there any open issue tracking this ?

**Comment by SteveSandersonMS** [comment]
@iambipinpaul #1
