### ISSUE TITLE
error CS1617: Invalid option '7.3' for /langversion

### ISSUE THREAD

**Issue by timnazar** [aspnet/Blazor#871]
```
precious:~ timnazar$ dotnet new blazor -o thoughts
The template "Blazor (standalone)" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on thoughts/thoughts.csproj...
  Restoring packages for /Users/timnazar/thoughts/thoughts.csproj...
  Restore completed in 168.01 ms for /Users/timnazar/thoughts/thoughts.csproj.
  Generating MSBuild file /Users/timnazar/thoughts/obj/thoughts.csproj.nuget.g.props.
  Generating MSBuild file /Users/timnazar/thoughts/obj/thoughts.csproj.nuget.g.targets.
  Restore completed in 465.43 ms for /Users/timnazar/thoughts/thoughts.csproj.

Restore succeeded.

precious:~ timnazar$ cd thoughts
precious:thoughts timnazar$ dotnet run
CSC : error CS1617: Invalid option '7.3' for /langversion. Use '/langversion:?' to list supported values. [/Users/timnazar/thoughts/thoughts.csproj]

The build failed. Please fix the build errors and run again.

```
The newly created project is failed on compiling. what's wrong?

**.net core version: 2.1.4
os: macOS 10.13.4**

**Comment by timnazar** [comment]
i'm running from the terminal :C
![screen shot 2018-05-22 at 11 12 26 pm](https://user-images.githubusercontent.com/5828436/40381641-abe2fcd0-5e15-11e8-8dd2-7c3203c82326.png)

**Comment by danroth27** [comment]
```
precious:thoughts timnazar$ dotnet --version
2.1.4
```

You need to install the [.NET Core 2.1 RC1 SDK](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1).

**Comment by danroth27** [comment]
@timnazar We've actually seen quite a few people run into this issue where they don't have the required .NET Core SDK installed. We're trying to figure out how we can make this requirement clearer. Can you share any details about how you might have missed this step? Which installation steps were you following? Was anything missing or unclear?

**Comment by rolandh** [comment]
I installed net core 2.1 and it broke net framework 2.0 and also stopped any compiler newer than 7.0 from working. I can select 7.3 but I get this error when trying to build with it. I believe it is the net core installer that is breaking this.

**Comment by danroth27** [comment]
@rolandh Is it just Blazor apps that are broken or any .NET Core app? If it's the later, you should probably report your issue on https://github.com/dotnet/sdk/issues.
