### ISSUE TITLE
netstandard1.4 compatibility

### ISSUE THREAD

**Issue by Nymeria25** [aspnet/Blazor#881]
Hi,

Is Blazor compatible with netstandard1.4 at all?

Kindest regards.

**Comment by SteveSandersonMS** [comment]
The core is `netstandard2.0`. I'm not sure what specific 2.0 capabilities it requires. If you wanted to try forking and changing to `netstandard1.4` or earlier, it would be interesting to know what problems this causes and whether we could reasonably downgrade the netstandard requirement.

**Comment by danroth27** [comment]
@Nymeria25 And to be clear, you can run .NET Standard 1.4 libraries in a Blazor app. Blazor app's run on a .NET runtime that supports .NET Standard 2.0, which is backwards compatible with older version of .NET Standard.
