### ISSUE TITLE
string constant for @page directive

### ISSUE THREAD

**Issue by shumas** [aspnet/Blazor#885]
Hi!
Looks logical (and useful), if it'll be possible to use const strings in page directive- as it compiles to the route attribute (where you can use constants).

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion.

It's not something we have a specific plan to do, as it might be nontrivial to change the Razor tooling to allow this.

However if it becomes a common feature request we'll certainly consider it. Hope that's OK!
