### ISSUE TITLE
Call unregistered JavaScript functions

### ISSUE THREAD

**Issue by mahdi-ninja** [aspnet/Blazor#889]
I know that Blazor currently uses a registered function approach, but I'm not sure why exactly this is required. I think It'd be nice if we could call arbitrary JavaScript functions without having to register them first. 

I have implemented a simple workaround for this. Please take a look and let me know if this something that you may want to implement (of course in a proper way) in Blazor. If not, can you please tell me why it's a bad idea and is there any reason for me not to use this approach?

In my implementation, I have a C# helper method called `JavaScriptInterop.Invoke` which can be used like this:
```csharp
// Call console.log without registering it
// JS call: console.log({"str": "Hello", "f": 1.23, "b": false});
// returns null
JavaScriptInterop.Invoke<object>("console.log", new { str = "Hello", f = 1.23, b = false });

// Method with variable number of params
// JS call: Math.max(3, 4.3, 5.1);
// returns 5.1
JavaScriptInterop.Invoke<double>("Math.max", 3, 4.3, 5.1);

// Access properties (doesn't have to be method call)
// JS call: Math.PI
// returns: 3.141592653589793
JavaScriptInterop.Invoke<double>("Math.PI");

// Invalid reference
// JS call: doesn't call anything
// returns null
JavaScriptInterop.Invoke<object>("invalid.ref");
```

And here's how I implemented it
* Helper method `JavaScriptInterop.Invoke` to call registered JS function `invokeUnregistered`
```csharp
public static class JavaScriptInterop
{
    public static TRes Invoke<TRes>(string identifier, params object[] args)
    {
        return RegisteredFunction.Invoke<TRes>("invokeUnregistered", new { identifier, args });
    }
}
```
* Registering a generic JS function invoker `invokeUnregistered`
```html
<script type="blazor-boot"></script>
<script>
    Blazor.registerFunction('invokeUnregistered', data => {
        var ref = data.identifier
            .split('.')
            .reduce((prev, curr) => prev && prev[curr], window);
        return ref instanceof Function ?
            ref.apply(null, data.args) :
            ref;
    });
</script>
```

PS: This could also be implemented as a dynamic class, so that the call will look something like this:
```csharp
//this will be translated to JavaScriptInterop.Invoke<double>("Math.max", 1, 2, 3);
var max = JavaScript.Math.max(1, 2, 3).As<double>();
```

**Comment by Andrzej-W** [comment]
In my opinion it is not bad to have this functionality to quickly test something. On the other hand in real application I prefer registration. Usually I have plenty of places where I want to call some function and registration gives me strongly typed arguments and return values. I don't have to use string to specify function name (I do it only once during registration). With plenty of strings it is only matter of time to introduce some hard to find errors.

**Comment by mahdi-ninja** [comment]
@Andrzej-W Just a quick note that `RegisteredFunction.Invoke` doesn't give you strongly typed args and return values either.

**Comment by Andrzej-W** [comment]
@mahdi-ninja I wrap `RegisteredFunction.Invoke` like this
```C#
public static void Focus(this ElementRef elementRef)
        {
            RegisteredFunction.Invoke<object>("Js.ExampleJsInterop.FocusElement", elementRef);
        }
```
Now I can use this function like this `myElementRef.Focus()` in hundreds of places and I have full intellisense and strongly typed arguments and return value. Maybe this example is not perfect because focus() JavaScript function doesn't take any arguments, but I think now it is clear what I mean. I can test my wrapper once and I'm sure that everywhere in my program I call it correctly.

To test something I can use your solution and write in C# code:
```C#
double pi = JavaScriptInterop.Invoke<double>("Math.PI");
```
but I will do it only once. Then I will wrap this in C# function and use:
```C#
double pi = MathPi();
```
It is much shorter and it is impossible to make any mistake.

**Comment by mahdi-ninja** [comment]
@Andrzej-W thanks for the explanation. Obviously, as you said, the code will be much cleaner and more reliable if you wrap the call to `RegisteredFunction.Invoke` (or `RegisteredFunction.Invoke`) in another method to *simulate* strongly typed args and return values.
However, all I'm talking about here is that registering a function (at least in the current way) doesn't change anything in that regard.

**Comment by andymac4182** [comment]
This would be great. Possibly a middle ground would be something similar to Refit https://github.com/reactiveui/refit and the Auto Interface Implementation from Insight.Database https://github.com/jonwagner/Insight.Database/wiki/Auto-Interface-Implementation.

It would give you a strong typed registered function in c# and all for calling any method in the Javascript. It might also help with RegisteredFunction as well.

```csharp
public interface IJavascriptMethods
{
	[Javascript("Js.ExampleJsInterop.FocusElement")]
	public Task Focus(ElementRef elementRef);
}
```

**Comment by Knudel** [comment]
I agree at this point the javascript interop isn't working as it should. 
I believe the solution andymac4182 suggests could be a better one.

**Comment by mahdi-ninja** [comment]
@andymac4182 Good idea. However, I'm not sure if that's possible in the current runtime.
The problem is that `AssemblyBuilder.DefineDynamicAssembly` is not supported in mono.wasm and using it throws `System.PlatformNotSupportedException`.

PS: That's how it's done in [`InterfaceGenerator` in Insight.Database](https://github.com/jonwagner/Insight.Database/blob/master/Insight.Database.Core/CodeGenerator/InterfaceGenerator.cs) too.

**Comment by andymac4182** [comment]
While building the class at runtime isn't possible it might be possible to do at build time. If its part of the framework that would be easier as well I am sure.

**Comment by Terricide** [comment]
Would the retyped project from bridge.net help in creating bindings?

**Comment by mahdi-ninja** [comment]
@andymac4182 I think it will look like a simplified version of #91

**Comment by mahdi-ninja** [comment]
@Terricide take a look at #37

**Comment by chassq** [comment]
To note `var call = RegisteredFunction.Invoke<bool>("IsDeviceLandscape");` for example can return a strongly typed value (in this case a bool). Arguments on the other hand are not strongly typed (i.e. object[] args). I think one step that would be nice to avoid, if possible, is the javascript part of the registration (Blazor.registerFunction).
```
function isDeviceLandscape() {
        return $deviceWin.innerHeight < $deviceWin.innerWidth;
    }
Blazor.registerFunction('IsDeviceLandscape', function () { return isDeviceLandscape(); }); //Remove need for this?
```
So if I am expecting a bool return from the js function I can use `RegisteredFunction.Invoke<bool>("isDeviceLandscape"); //(note the camel case js function call)`  and received an error if not the right return type. Or if I am expecting a dynamic I can use maybe `RegisteredFunction.Invoke<dynamic>("isDeviceLandscape");`. This way maybe one would not need to differentiate between RegisteredFunction.Invoke and something like a Javascript.Invoke?

Like I think what @mahdi-ninja suggested just call the JS directly from the `RegisteredFunction.Invoke<bool>("isDeviceLandscape");` without the need to the Js side of the registration maybe? If the Js function being executed does not exist then an error would occur.

**Comment by SteveSandersonMS** [comment]
In 0.5.0 we have removed the need to pre-register JS functions.
