### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#89]
I've created a project that is outside of the Blazor repo folder, and references Blazor project using relative paths; the project build as I would expect form the commandline; but fails when building using VS2017 15.5.6

```
Error	NU1105	Unable to find project information for '...\Blazor\src\Microsoft.AspNetCore.Blazor.Browser\Microsoft.AspNetCore.Blazor.Browser.csproj'. The project file may be invalid or missing targets required for restore.
Error	NU1105	Unable to find project information for '...\Blazor\src\Microsoft.AspNetCore.Blazor\Microsoft.AspNetCore.Blazor.csproj'. The project file may be invalid or missing targets required for restore.	
Error	NU1105	Unable to find project information for '...\Blazor\src\Microsoft.AspNetCore.Blazor.Server\Microsoft.AspNetCore.Blazor.Server.csproj'. The project file may be invalid or missing targets required for restore.
```

**Comment by SteveSandersonMS** [comment]
Soon we'll ship NuGet packages that make it convenient to consume from outside the Blazor repo.

It sounds like you've found a difference in behaviour between MSBuild command line and VS builds. If you're able to reduce this to a simple repro that doesn't involve Blazor at all, then you could report it to the MSBuild project. Thanks!

**Comment by danpdc** [comment]
Hi all. I am playing around with Blazor and was trying to create a minimal app. Everything works fine on my dev environment, but when I deploy the application to Azure, the application can't be started. I have built Blazor.Server and MonoClient as local NugetPackages. This works again fine in my dev environment, but I get errors when running in Azure AppService.  I get following error: 

ArgumentException: The directory name C:\somepath\Blazor\samples\MonoSanityClient\bin\Release\netcoreapp2.0\dist\ is invalid.
Parameter name: path

It seems that It seems that BlazorConfig.cs in Blazor.Server still relies somehow on some physical paths that won't work when deploying to Azure AppService. 

Do you guys have any hint on how should I proceed to get the app working also in Azure? 

Thanks in advace

**Comment by SteveSandersonMS** [comment]
@danpdc We haven't yet implemented publishing support, which will be needed to collect all the deployable files together in the correct locations for deployment.

**Comment by danpdc** [comment]
@SteveSandersonMS Thank you very much for your notice. I am really excited by the Blazor project and just wanted to play around with it :)
