### ISSUE TITLE
Dynamic routes?

### ISSUE THREAD

**Issue by GoranHalvarsson** [aspnet/Blazor#891]
Hello good people

I have a request it's about routes(page directive). 
The possibility to add routes(@page "xxxx") programmatically. 
Something like this:
@foreach (string item in navigationRepository.GetRelativeUrls())
{
    @page @item
}

Will this be possible?

**Comment by Andrzej-W** [comment]
Your suggestion probably should be added here: #293 
I'm thinking about your suggestion and I have one simple question: why do you need something like this? Do you want to create some kind of generic page component with plenty of @page directives? Maybe route with parameter is enough?
https://blazor.net/docs/components/index.html#route-parameters

**Comment by SteveSandersonMS** [comment]
When we implement catch-all routes (as tracked in #293), it will be possible to handle arbitrary incoming URLs and write your own code to decide what happens.

**Comment by GoranHalvarsson** [comment]
Thanks, great news
