### ISSUE TITLE
What VS version for future Blazor releases?

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/Blazor#892]
Currently I have VS 2017 15.7.2 and 15.7.0 Preview 6. What will be needed for Blazor 0.4.0 and newer? Can I remove Preview 6 and work in 15.7.2 (now and **in the future**) or I should update 15.7.0 Preview to 15.8.0 Preview?

**Comment by rynowak** [comment]
The current plan is to use 15.7.2 (stable channel) for 0.4.

We try to use the stable channel when possible, but will require preview when there's something new in VS that we need. There are no guarantees in life 😆

**Comment by Andrzej-W** [comment]
Thank you for immediate answer Ryan.
