### ISSUE TITLE
Missing type checking on component parameters

### ISSUE THREAD

**Issue by masonwheeler** [aspnet/Blazor#896]
When you put a `[Parameter]` on a component, and then invoke it with `<MyComponent param=@someValue>`, it doesn't do static type checking at compile-time to make sure that value will actually work.  All of the necessary information to do so is present, but no type-checking is done until runtime, when it attempts to set the parameter value through Reflection, making it possible for this to blow up with an `InvalidCastException`.

This should not be the case.

**Comment by Andrzej-W** [comment]
This should be added to #1

**Comment by SteveSandersonMS** [comment]
Good suggestion.

@rynowak The implementation that occurs to me would be changing the `AddAttribute` codegen to insert a cast to whatever the target parameter type is. I know that means an extra runtime cast, at least for non-sealed parameter types. Maybe the compiler is smart enough to no-op the cast if the parameter type is sealed (which would be true for a large proportion of cases where people are passing `int`, `string`, etc.).

Alternatively we could create an `AddAttribute<T>` that requires you to pass a `T`, but that might make our current overload selection mechanism quite difficult to reason about.

What do you think?

**Comment by rynowak** [comment]
This seems pretty straightforward. We'll want to try both and choose based on which provides the better error message.

**Comment by rynowak** [comment]
Adding a thunk that the generated code calls through is pretty straightforward, and seems to fix the problem pretty nicely. We don't have super fine-grained control over what the error message looks like, but I think it's actually pretty decent.

![image](https://user-images.githubusercontent.com/1430011/40987492-80336c72-689d-11e8-8a47-9c06d30fd34a.png)

**Comment by SteveSandersonMS** [comment]
Implemented in 4dee648ab8b3f5b350f3587c5748faee372224ac
