### ISSUE TITLE
Pass parameters to dynamically created component

### ISSUE THREAD

**Issue by Diemauerdk** [aspnet/Blazor#898]
Hi,

I am trying to send parameters to a component that is created dynamically using the RenderTreeBuilder and RenderFragment. What i basically does to create the render fragment is this is:

` private RenderFragment GetContent(Type type)
        {
            return builder =>
            {
                builder.OpenComponent(0, type);
                builder.CloseComponent();
            };
        }`

That code is very simple and working fine.

However I want to be able to send various parameters to the dynamically created comonents. A start could just be an id of type string.

Anyone know if or how this is supported by the framework?

Thanks :)

**Comment by SteveSandersonMS** [comment]
Yes, see the code that gets generated when you construct a child component using Razor syntax. It uses `builder.AddAttribute` calls to pass the parameters. It's quite similar to the code you already have posted above.

**Comment by GoranHalvarsson** [comment]
Why not send a model instead :-)
It works great. Something like this:
Create your model in the shared libray:
 public class MyViewModel
    {
        public string HeaderText { get; set; }

        public string BodyText { get; set; }
    }

Your  component:
<h1>@Model.HeaderText</h1>
<div>
  @Model.BodyText
</div>
@functions{
    [Parameter]
    SitecoreBlazorHosted.Shared.Models.MyViewModel Model { get; set; }
}

And then load/render your component on a page:
public class MyRenderService
        {
            public RenderFragment RenderComponent<T>(string headerText, string bodyText) where T : Microsoft.AspNetCore.Blazor.Components.BlazorComponent
            {

                MyViewModel model = new MyViewModel()
                {
                    HeaderText = headerText,
                    BodyText = bodyText
                };

                return BuildRenderTree =>
                {
                    BuildRenderTree.OpenComponent<T>(0);
                    BuildRenderTree.AddAttribute(1, "Model", model);
                    BuildRenderTree.CloseComponent();
                };


            }
        }

**Comment by Diemauerdk** [comment]
Hi,

Thanks for the answers - I can continue from here with that information. :)

Have a nice day.

**Comment by Diemauerdk** [comment]
Hi @GoranHalvarsson,

I have tried out the solution you suggested which works - but when I create more than one component I start getting this knockout js error: "You cannot apply bindings multiple times to the same element".

> WASM: Microsoft.AspNetCore.Blazor.Browser.Interop.JavaScriptException: You cannot apply bindings multiple times to the same element.

Do you know if the "Model" Parameter has to be unique for each dynamically created component?

Thanks,
Jeppe

**Comment by GoranHalvarsson** [comment]
Hello

Im glad it worked, hmm. I have only tested it on existing components. 
Do you have some code I can look at :-) 
You can mail it to me: goranhalvarsson@gmail.com

**Comment by Diemauerdk** [comment]
Hi,

We have a rather large application using devexpress components so it's quite difficult - though I appreciate your aid :)

I have gotten a bit closer though - it is something happening with devexpress - I'll figure it out - it was just if you have had the same error ;)

Have a nice day.

**Comment by julienGrd** [comment]
Hello ! I'm face on the same problem ! (I'm on blazor 0.8) And i don't know how to resolve it.

I want "Inject" a component in a specific emplacement of my Html, 

To resume, a component c1 which inject a component c2 in a component c3

so I make a communication between c1 and c3, c3 wait for a renderFragment and c1 send them.
My problem is on instanciation of c2. Indeed, I need c1 be notified by event or other things happened to c2. So I can't do that (in c1) because i have no instance to suscribe

`this.myFragment= builder =>
                    {
                        builder.OpenComponent<c2_component>(0);
                        builder.CloseComponent();
                    };`

I can also give raw html, in this case I can give parameters and suscribe to event.
Bu in my case, It wiil be a mess, in this example its simple but I can't keep this solution, it's definitively not maintenable.
`this.myFragment= builder =>
                    {
                        var seq = 0;
                        builder.OpenElement(seq++, "div");
                        builder.AddAttribute(seq++, "class", "btn-group-vertical");

                        builder.OpenElement(seq++, "a");
                        builder.AddAttribute(seq++, "class", "btn btn-outline-primary");
                        builder.AddAttribute(seq++, "onclick", OnOpenChildren);
                        builder.OpenElement(seq++, "i");
                        builder.AddAttribute(seq++, "class", "fas fa-folder fa-fw");
                        builder.CloseElement();
                        builder.AddContent(seq++, " Opening file");
                        builder.CloseElement();

                        builder.CloseElement();
                    };
                }`

I think there is everything in the framework to do this kind of things, but now I don't know how to do it.

Maybe it's not the good way to achieve this ? if you have others solutions I take it :-).

Thanks !

Julien

**Comment by julienGrd** [comment]
Ok sometimes hust speak about a problem solve the problem
after thinking about the first comment of GoranHalvarsson this is my solution (thanks to you !)
in c1
`
 private RenderFragment _actionPage;
        public override RenderFragment ActionPage
        {
            get
            {
                if(this._actionPage == null)
                {
                    this._actionPage = builder =>
                    {
                        builder.OpenComponent<SearchChildren_Action>(0);
                        builder.AddAttribute(1, "Model", this);
                        builder.CloseComponent();
                    };
                }
                return _actionPage;
            }
        }

        public void OnOpenChildren(UIMouseEventArgs e)
        {
            Console.WriteLine("open Child");

        }
        public void OnCreateNewChild(UIMouseEventArgs e)
        {
            Console.WriteLine("Create new Child");

        }
        public void OnCreateWithCarteVitale(UIMouseEventArgs e)
        {
            Console.WriteLine("Create with carte vitale");
        }
`

and the implementation of c2
`<div class="btn-group-vertical">
    <button onclick="@this.Model.OnOpenChildren" class="btn btn-outline-primary"><i class="fas fa-folder fa-fw"></i>&nbsp;Ouvrir le dossier</button>
    <button onclick="@this.Model.OnCreateNewChild" class="btn btn-outline-primary"><i class="fas fa-file fa-fw"></i>&nbsp;Nouvelle Fiche</button>
    <button onclick="@this.Model.OnCreateWithCarteVitale" class="btn btn-outline-primary"><i class="fas fa-file fa-fw"></i>&nbsp;Nouvelle depuis la carte vitale</button>
</div>

@functions{

    [Parameter]
    c1 Model { get; set; }
}`

If it can help someone.

again, if there is better to do, don't hesitate !
