### ISSUE TITLE
[question] Implementing guards for Routes

### ISSUE THREAD

**Issue by dlr1** [aspnet/Blazor#899]
I was able to declare all the routes in one place and change a few lines of code in how the  RouteTable is created and let blazor do all the other things from there and this seem to work (I had to duplicate bunch of classes as they are all internal). now If I want to implement guards on routes,  I was thinking if a page implements interface, I would like to call that method to see if I can route to that or leave that page, what would be a good place for doing that.

**Comment by SteveSandersonMS** [comment]
If you have your own custom router, I'd expect you could add logic to wherever it selects a handler.

If you're aiming to do this with the stock router, then either:

 * Add logic to your `@page` components to check for access during `Init` or `OnParametersSet`
 * Or if you want it on the stock `<Router>` itself, add a request to issue #293 for a suitable virtual method you could override (or a similar extensibility point)

**Comment by GoranHalvarsson** [comment]
Hello dir1

Could you please share what you did regarding declaring routers on one place. Please email it to my address: goranhalvarsson@gmail.com

I would be so grateful 😄
Br
Göran Halvarsson
