### ISSUE TITLE
No Content appears

### ISSUE THREAD

**Issue by HansUrschel** [aspnet/Blazor#900]
I hope someone can help me. I install .Net Core 2.1 Preview ( dotnet --version shows 2.1.300-preview1-008174 ). I works with VS2017 Community Edition Version 15.7.2 and Windows 10. ASP.NET and webdevelopment is installed. Now I downloaded and install the ASP.NET Core Blazor Language Services extension. I start my VS, select File -> New Project -> Web -> ASP.NET Core Web Application. .Net Core and ASP.NET Core 2.0 is active. I select "Blazor" and named my project BlazorTest. All seems ok. I start my project with Ctrl-F5. The Command-Window appears and tell me the program is launching at port 59790. A browser-window (Firefox ) appears. The message "Loading" appears. The message disappears and that all. Nothig else appears. I see a blank page. I tried it with Chrome and IE but it shows the same behavior
Its source code is
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">
    <title>BlazorTest2</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
</head>
<body>
    <app>Loading...</app>

    <script src="_framework/blazor.js" main="BlazorTest2.dll" entrypoint="BlazorTest2.Program::Main" references="Microsoft.AspNetCore.Blazor.Browser.dll,Microsoft.AspNetCore.Blazor.dll,Microsoft.Extensions.DependencyInjection.Abstractions.dll,Microsoft.Extensions.DependencyInjection.dll,mscorlib.dll,netstandard.dll,System.Core.dll,System.dll,System.Net.Http.dll" linker-enabled="true"></script>
</body>
</html>
What is my fault? ( sorry about my bad english )

**Comment by HansUrschel** [comment]
I am a little bit confused. I have a version 2.1.4 of the sdk. which is newer 2.1.300 rc1 or 2.1.4?

**Comment by fileman** [comment]
2.1.300 > 2.1.4 … it must be considered as 2.1.004

**Comment by HansUrschel** [comment]
ok, i install now 2.1.300 rc1

**Comment by HansUrschel** [comment]
Thanks so much from germany. It works with RC1. But i had to change the sdk in the file "global.json". There was the old entry with the preview.

**Comment by danroth27** [comment]
@fileman Thanks for answering this one!

**Comment by Stuart88** [comment]
Hi, I'm getting the same problem.

I have no idea what "update to Rc1 of sdk" means... sorry! What am I supposed to do?

**Comment by danroth27** [comment]
@Stuart88 All you need to do is go to https://dot.net and install the latest .NET Core SDK.

**Comment by Andrzej-W** [comment]
@Stuart88 this thread is a little bit old.
If you want to work with current Blazor version (0.4.0 at the time of writing) you should install current tools:
* Visual Studio 2017 version 15.7.5 (Blazor is currently not compatible with 15.8.x preview)
* .NET Core SDK from here https://www.microsoft.com/net/download/windows (current version is 2.1.302)
* ASP.NET Core Blazor Language Services from here https://marketplace.visualstudio.com/items?itemName=aspnet.blazor (you can simply search for Blazor in Extensions and Updates in VS)

That is enough if you want to create a new project. If you have an old project the best way for you is to create a new project in VS and then compare all *.csproj files and global.json file. Based on these new files you can make adjustments in your old files.

**Comment by HansUrschel** [comment]
don't use the rc1. there is a new release of the sdk. you must use this and all works. excuse my bad english.Am 17.07.2018 6:35 nachm. schrieb Stuart Aitken <notifications@github.com>:Hi, I'm getting the same problem.
I have no idea what "update to Rc1 of sdk" means... sorry! What am I supposed to do?
