### ISSUE TITLE
Where can I get Steve's Samples from NDC Minnesota 2018?

### ISSUE THREAD

**Issue by BenHayat** [aspnet/Blazor#906]
Hello Team;

Where can I find Steve's samples he did for NDC Minnesota 2018?

Thanks!

**Comment by SIkebe** [comment]
Did you check above FlightFinder link? :smiley:

**Comment by BenHayat** [comment]
I checked the link but I didn't have my glasses on and read it as "FlashFinder" so I dismissed it. :-)
Now I will...
But in that video, he also showed some new ones too. Hope he will upload all of them.
But thank you for the link. 
Note to myself: Glasses, don't leave home with out it... :-)

**Comment by SIkebe** [comment]
>But in that video, he also showed some new ones too. Hope he will upload all of them.

Hmm, I missed something...I need glasses, too :stuck_out_tongue_winking_eye:

**Comment by SteveSandersonMS** [comment]
Can you specify which exact content you’re looking for?

**Comment by BenHayat** [comment]
Hi Steve;
Firstly I really enjoyed your NDC video. Reminded me of the old days when you used to work on Silverlight. I'd like to change my initial question after a member pointed me to a link for FlightFinder.
My question, is the older project (a month ago) the same as the one you showed in NDC? If not could you please update the gitup version?

I also want to thank you for being part of the Blazor team.

**Comment by lohithgn** [comment]
@BenHayat there are other sample being built by community .. you can check for community samples here - https://blazor.net/community

**Comment by BenHayat** [comment]
Thanks Lohithgn;

**Comment by SteveSandersonMS** [comment]
> My question, is the older project (a month ago) the same as the one you showed in NDC? If not could you please update the gitup version?

Yes, it's basically the same. There might be some trivial differences but the one on GitHub should be considered more authoritative.
