### ISSUE TITLE
Declarative notation for interop call from CSharp to JavaScript

### ISSUE THREAD

**Issue by ebekker** [aspnet/Blazor#91]
I'm proposing establishing a declarative notation to allow interop calls from CSharp to raw JavaScript in the same spirit as P/Invoke calls from managed code to native libraries.  Something along the lines of:

```csharp
namespace Some.Namespace1
{
    public class Class1
    {
        [JsEmit]
        public static extern int RunSomeJavaScript(int i1, string s1, bool b1)/*-{
            window.alert(s1);
            if (b1)
                return i1;
            else
                return i1 * 2;
        }-*/;
    }
}
```

*(This embedded JS notation is borrowed from the GWT JSNI feature, and serves a similar purpose, although in a very different context.)*

This would emit and register a function, something of the form:
```javascript
_extern_Some_Namespace1_Class1_RunSomeJavaScript(i1, s1, b1) {
            window.alert(s1);
            if (b1)
                return i1;
            else
                return i1 * 2;
}
```

It would be possible to use Roslyn to identify all candidate `extern` methods and extract out all the embedded JS fragment code, and then write it out to generated JS at build time, and then register the function for interop, and map the extern method calls.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. We did originally start with something like that. The reason we're now preferring the "registered function" approach is that it works better with JS bundlers which don't make your libraries available in global scope by default (e.g., Webpack). The approach you've described above is good if you only need to call JS code that's reachable from global scope, but doesn't help in other cases.

This is of course totally open to change as we see usage patterns develop, so perhaps more than one interop mechanism will be available.

I'll close for now but like with everything, we'll review as time goes by. Hope that's OK!

**Comment by ebekker** [comment]
I completely agree about avoiding global scope.  Just spit-balling here, but perhaps something like

**`Class1.cs`:**
```csharp
namespace Some.Namespace1
{
    public partial class Class1
    {
        [WebEmit]
        public static extern int RunSomeJavaScript(int i1, string s1, bool b1)/*-{
            window.alert(s1);
            if (b1)
                return i1;
            else
                return i1 * 2;
        }-*/;
    }
}
```
would actually generate the equivalent to...

**`Class1.gen.cs`:**
```csharp
namespace Some.Namespace1
{
    public partial class Class1
    {
        public static extern int RunSomeJavaScript(int i1, string s1, bool b1)
        {
            return RegisteredFunction.Invoke<int>("RunSomeJavaScript", i1, w1, b1);
        }
    }
}
```
**`Class1.gen.js`:**
```javascript
// somewhere in code...
Blazor.registerFunction('RunSomeJavaScript', (i1, s1, b1) => {
            window.alert(s1);
            if (b1)
                return i1;
            else
                return i1 * 2;
});
```

**Comment by ebekker** [comment]
With this approach, you could use the `WebEmit` attribute to control generated code, such as
* qualifying the target language, `[WebEmit(language=WebEmit.TypeScript)]`
* declare import statements to be generated in the target language: `[WebEmit(imports={ 'angular', 'angular-core', 'preact' })]`

**Comment by grahamehorner** [comment]
I’m thinking don’t decorate C# code that but decorate the code that Blazor would be calling and specify a preprocessing and that script/interface; the decoration could be a simple comment which also helps in documentation of the script code

**Comment by ebekker** [comment]
Are you saying decorate the JavaScript or TypeScript?

**Comment by grahamehorner** [comment]
either, type inference of the script would generate intellisence and the bridging code between the script and the C# would a nice reference re: static typing and dynamic would be https://medium.com/javascript-scene/you-might-not-need-typescript-or-static-types-aa7cb670a77b

**Comment by grahamehorner** [comment]
@ebekker see https://github.com/aspnet/Blazor/issues/37

**Comment by ebekker** [comment]
#37 is about auto-generating C# interfaces to existing libraries that have TS typedefs -- I'm all for that, that would open up access to so much good client-side stuff automagically.  It would be just like what [Retyped](https://retyped.com/) has done for [Bridge.NET](https://bridge.net/).

My intention here is essentially to provide an "escape hatch" for those situations where you need to drop down into the raw JS for a little bit of direct access, such as accessing code or libraries that don't have TS typedefs yet.  It's exactly the same thing as the RegisteredFunctions mechanism that's already there as Steve referenced above, but I'm just proposing a more natural and compact syntax -- at least that's how it feels to me.

This would be *in addition to* RegisteredFunctions, not instead of -- as it would build on top of that under the hood.
