### ISSUE TITLE
Default project throws "CS0234 - The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore'"

### ISSUE THREAD

**Issue by alexanderjwoods** [aspnet/Blazor#915]
Apologize if this is the wrong spot, but when created a blank Blazer app using VS 15.7.3 I get 110 errors of CS0234.  I can't find any references to MVC, and have not made any code changes, but the error appears to be on any function call, i.e., onclick=@ToggleNavMenu.

**Comment by TheRubble** [comment]
See https://github.com/aspnet/Blazor/issues/916

To work around this issue I've been restoring the packages from the cmd line after placing a global.json file in the project:
```
{
  "sdk": {
    "version": "2.1.300"
  }
}
```

Next restart visual studio, seems to address it. On the odd occasion I've also deleted the bin folder.

**Comment by alexanderjwoods** [comment]
That worked for me :)  Thanks!
