### ISSUE TITLE
Blazor on Electron

### ISSUE THREAD

**Issue by PaulOst** [aspnet/Blazor#917]
Are there any thoughts or interest in having the ability to write **Electron** framework apps using Blazor?

**Comment by MilanKovacic** [comment]
Discussed previously in #74

**Comment by SteveSandersonMS** [comment]
Yes, it is something we are interested in. We don't have any confirmed plan about it yet, but it's part of the overall set of questions we're considering while Blazor is in this experimental phase. Thanks for letting us know you're interested in that.

**Comment by PaulOst** [comment]
Thanks, @SteveSandersonMS! We are happy to realize that Microsoft's acquisition of GitHub also puts them in control of Electron.

**Comment by Andy-London** [comment]
This is very useful in our case. We can easily convert our WPF+Winforms thick client to Blazor + Electron. Are there any plans to make it one of Blazor hosting modes?
