### ISSUE TITLE
Fetch request hangs

### ISSUE THREAD

**Issue by abhishekgoenka** [aspnet/Blazor#924]
Interestingly, fetch request hangs. This happens during HttpClient.GetAsync(...). After debugging, I found that call reaches successfully till HTTP.ts but it hangs in sendAsync method. _See below screenshot_ 

![image](https://user-images.githubusercontent.com/14522198/40922902-10e552e8-6831-11e8-850e-42d47ba82737.png)

**Comment by SteveSandersonMS** [comment]
Can you provide minimal repro steps?

HTTP requests do work normally, as demonstrated in the "fetch data" page in the default project template. If you can let us know what specifically triggers the different behaviour you're seeing, we can comment about whether it's an issue or not.

**Comment by Suchiman** [comment]
Are you using `await` or `.Result`? the `.Result` will block the JS / UI Thread.

**Comment by abhishekgoenka** [comment]
@Suchiman You were correct. I was using .Result. This was blocking my UI. The issue is resolved after moving to Task. Thank you very much.
