### ISSUE TITLE
Is it currently possible to use Rx.NET in Blazor?

### ISSUE THREAD

**Issue by enetstudio** [aspnet/Blazor#925]
I'm trying to implement the Angular tutorial Tour of Heroes (HTTP) section in our dear Blazor. Here is the Angular sample: https://stackblitz.com/angular/xkyalvboyrj

As you can see, there is an input textbox to enter a search term. The search is performed whenever the user changes the content of the text box. To make the search efficient, rxjs is used. Now I want to emulate this functionality in Blazor, and I wondered if this can be done employing Rx.NET...

God Blazor you!

**Comment by SteveSandersonMS** [comment]
Long term this should definitely work.

As for whether it works effortlessly or involves some friction with Blazor 0.3.0, I don't know because I haven't personally tested it. If you encounter issues and can describe them with repro steps, please let us know!

**Comment by danroth27** [comment]
@enetstudio I believe @lohithgn also did a Tour of Heroes port: https://github.com/lohithgn/blazor-tour-of-heroes. Take a look and see if it helps.

**Comment by enetstudio** [comment]
@danroth27  thanks... I've seen this project. Problem is that the search feature is completely different from that of the Angular sample, where observable features are used to enable active and efficient search while the user types the search term in a text box...

God Blazor you!

**Comment by MovGP0** [comment]
I agree that one-way-binding to `IObservable<T>` and two-way-binding to `ISubject<T>` should work.

**Comment by weitzhandler** [comment]
Seems like the real issue in making this work, is that mono-wasm has no TFM.
https://github.com/NuGet/Home/issues/8186. Can we come up with a solution to that, even something temporary so we can start working with the Rx in wasm or extending it without having to fork it?
