### ISSUE TITLE
Lazy assembly download

### ISSUE THREAD

**Issue by abhishekgoenka** [aspnet/Blazor#939]
**Current behavior** - All the .NET assemblies are downloaded asynchronously during the first page load
**New feature requirement** - It would be nice if only required assemblies get downloaded during the first-page load. Remaining assemblies should get download as a user navigates to other pages.

**Comment by msdickinson** [comment]
I think there may be a mix up on that. It seems to me he means, If Page a.html needs system.x.dll he it will download and use it, If it also needs system.yy it will download and use it. When you hit page b.html it wont need to download system.yy as its in your cache. 

Excluding some websites most websites just get what they need page to page and reuse what they already have. Pretty sure this would be automatic so the programer wouldnt even have to worry the chain of dependents, as it sounds like that may be your concern here.

There may be value in some use cases, downloading everything up front but in general i dont think there is.

**Comment by SteveSandersonMS** [comment]
We're tracking lazy loading as #25, so will close this as a duplicate
