### ISSUE TITLE
Can initialize the program after a certain JS initialization is completed?

### ISSUE THREAD

**Issue by xxyuze** [aspnet/Blazor#940]
Can  initialize the program after a certain JS initialization is completed?

**Comment by SteveSandersonMS** [comment]
Currently there's no simple API for that. You'd need to edit your compiled `index.html` file to defer the insertion of the `blazor.js` script tag until your JS work is done.

As part of #108, we have a plan to implement a different startup API whereby you'd explicitly call some JS function when you wanted to start up the .NET runtime, so hopefully that would cover your requirements when it's implemented.
