### ISSUE TITLE
Full-Page reloads from 0.4.0-preview1-10314

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/Blazor#947]
When using 0.4.0-preview1-10314 (10313 works fine), I get strange full page reloads (the APP starts-up completely) on unclear circumstances.
After clicking a button, ShouldRender is the last thing I see in the console-output.
It's hard to track down without debugger, so maybe the changes from 10313 to 10314 give a hint what's wrong. Does any commit vs. build-nr - log exist?

**Comment by SteveSandersonMS** [comment]
Can you give repro steps?

I’ll look into which commits were included, but repro steps would be the main thing.

**Comment by DNF-SaS** [comment]
The button which was clicked was (accidentally) wrapped in a <form>-Element.
After removing this, it works in 10314 like before.
Like you already guessed, the preventDefault probably stopped the browser from reloading the page after submission of the form.

So it's no bug, just a new behavior of blazor. :-)

**Comment by SteveSandersonMS** [comment]
Thanks for explaining. Good to know!

**Comment by DNF-SaS** [comment]
@SteveSandersonMS Is it possible to skip preventDefault for routes which Blazor's Router cannot handle?
