### ISSUE TITLE
Browser soft refresh?

### ISSUE THREAD

**Issue by DaveKP** [aspnet/Blazor#956]
Just curious if there is currently/is going to be a way for Blazor to hijack F5 to only refresh the current app page?

Browser back/forward work as I'd expect, but F5 seems to relaunch the whole application? Is it possible to restrict the full application reload to Ctrl+F5?

**Comment by SteveSandersonMS** [comment]
Sorry, client-side applications can't change what the browser does when the user presses refresh. This is a deliberate limitation of browser APIs that applies to all client-side app frameworks.

**Comment by DaveKP** [comment]
Makes sense, cheers. Guess it's server-side rendering I'm looking forward to then :)
