### ISSUE TITLE
Handle FileResult from controller service

### ISSUE THREAD

**Issue by Paradoxon101** [aspnet/Blazor#962]
Currently there is no way to evaluate a FileResult in the browser or to save it via a download dialog.

**Comment by SteveSandersonMS** [comment]
I'm not certain what you're looking for.

If you're trying to trigger a file download with a "Save As" dialog, that's normally handled by server-side code. Specifically, if the server returns the `Content-Disposition` header, this makes the browser show a "Save As" dialog. Also you need to make the browser perform a normal navigation to the URL that returns this content, rather than by using `HttpClient`.

**Comment by Paradoxon101** [comment]
That's exactly what I wanted to do.

Server:
        [HttpGet]
        [Route("download/{downloadId}")]
        public FileResult Download(int downloadId)
        {
            return this.File(bytes, "application/zip", fileName);
        }
		
Client:
@functions {
    void Download()
    {
        UriHelper.NavigateTo("/download/1");
    }
}

Could the bug be in the UriHelper?

**Comment by chucker** [comment]
What exactly is the bug? Does the browser navigate, but then not ask the user to download? Is `Content-Disposition` being set in the response?

**Comment by Paradoxon101** [comment]
I used this on server:
System.Net.Mime.ContentDisposition cd = new System.Net.Mime.ContentDisposition
            {
                FileName = fileName,
                Inline = false  // false = prompt the user for downloading;  true = browser to try to show the file inline
            };

The browser displays the new url in the address bar, but nothing happens. If I now put the focus in the address line and press Enter, the download starts.

**Comment by SteveSandersonMS** [comment]
`UriHelper.NavigateTo` performs internal navigation if you point it to a URL that could be handled by client-side routing. It doesn't know that you wanted the browser to actually do a server-side navigation in this specific case.

To cover this use case, I've filed #979.

In the meantime, as a workaround you could use JS interop to trigger a full-page load to the target URL. The JavaScript code would be something like `location.href = 'download/123';`.

**Comment by vertonghenb** [comment]
@SteveSandersonMS True, but what if the Route `download/123` is protected by the `[Authorize]` attribute and needs a `HTTP Header` like `Authorization Bearer YOUR_TOKEN`

**Comment by dan-drews** [comment]
@vertonghenb Were you able to solve this problem? I am running into the same issue. Entirely API driven application that generates a PDF. I am using a bearer token for this.

**Comment by smartprogrammer93** [comment]
I think what you guys @dan-drews @vertonghenb  need to do is to make the api create a special key that can be passed through the url as a parameter. And if the correct key is requested you download that file the same way AWS does. 
Ref : https://stackoverflow.com/a/35445501

**Comment by SpeedyNZ** [comment]
I'm struggling with a similar issue, I have an API that returns the file to a service on my server side blazor app and wanting to have the option to click a but which will then call the service which returns that byte[] and produces a downloadable file. So the chain would be click button on server side blazor page, function calls a class inside blazor ss app which reaches out to API and returns a byte[] to the page. Now I need to convert that to a downloadable file.

**Comment by IvanJosipovic** [comment]
See if this helps,
https://github.com/IvanJosipovic/BlazorFileSaver

________________________________

**Comment by SpeedyNZ** [comment]
> I'm struggling with a similar issue, I have an API that returns the file to a service on my server side blazor app and wanting to have the option to click a button on the page which will then call the service which returns that byte[] and produces a downloadable file.
> 
> So the chain would be click button (onclick) on server side blazor page which calls a function inside blazor ss app which reaches out to API and returns a byte[] to the page. Now I need to convert that to a downloadable file in my @code{} section on page. I had this working with client side blazor using Steve S excel download example.

Actually, all I had to do was implement the same code and all worked as per the Blazor Client Side solution. My bad.... Thanks Steve for the good work.

**Comment by SpeedyNZ** [comment]
> See if this helps, https://github.com/IvanJosipovic/BlazorFileSaver

I had a few issues with this implementation so went back to Steve's solution which worked. Thanks for the reply and happy to provide additional info on your package.
