### ISSUE TITLE
typing chinese in a textbox will lead to the app break out

### ISSUE THREAD

**Issue by doubletong** [aspnet/Blazor#963]
I created a Blazor app in **chrome**  but when I am typing chinese in an input ,the app will be force to quit

**Comment by SIkebe** [comment]
Small repro project?

**Comment by SteveSandersonMS** [comment]
@doubletong, thanks for reporting this!

Can you give us repro steps? What code is necessary to trigger this fault, and what should one type to make it crash?

It will be difficult for us to take action on this report without more info. Hope that's OK.

**Comment by SIkebe** [comment]
@doubletong I'm Japanese and use Chinese characters, too. I have no problem using them with Blazor input. Are you still having above issue?

**Comment by SteveSandersonMS** [comment]
OK, I'll close this due to lack of repro information. Since @SIkebe says it's working it seems likely not to be a framework bug. But if anyone has a known repro please let us know.

**Comment by doubletong** [comment]
I took a demo video [http://heiniaozhi.cn/ScreenCapture_18-06-16_09.30.04.mp4](demo video)
