### ISSUE TITLE
What about media playing?

### ISSUE THREAD

**Issue by fanoI** [aspnet/Blazor#964]
Silverlight was used a lot to do rich Media Player experiences in particular when there was the need of DRM. I imagine that if Blazor will support this it will have yet more success, doing this things with HTLM5+JS is really complex and indeed a lot of sites continue to use Flash for these type of things.

So what do you think?

**Comment by AWulkan** [comment]
I think that's way outside the scope of a SPA framework. It's a very niche things that the vast majority of users will never need.

You should be able to handle those things with third party tools, or native HTML+JS. Maybe this is what you're looking for? https://developer.mozilla.org/en-US/docs/Web/API/Encrypted_Media_Extensions_API

**Comment by peter0302** [comment]
The whole point of WebAssembly and HTML5 before it - I thought - is to reduce or eliminate the need for plugins. The HTML5 media player is quite sophisticated and I'm sure a C# wrapper class in the Blazor framework is possible and probably easy once the JS interop is nailed down.

**Comment by SteveSandersonMS** [comment]
Indeed, it's certainly possible to interact with the built-in HTML/JS media players from Blazor code. In general Blazor attempts to mesh neatly with existing standards rather than trying to replace them.
