### ISSUE TITLE
Built-in Json isn't compatible with the default serialization in ASP.NET

### ISSUE THREAD

**Issue by ericwj** [aspnet/Blazor#966]
I found that JSON coming from an API controller that uses Entity Framework Core cannot handle the default serialization done by ASP.NET in a few cases.

* `sbyte`, `ushort`, `uint` and `ulong` do not deserialize (ArgumentException)
* `byte[]` content for e.g. `[Timestamp]` properties which are serialized as base64 do not deserialize
* `decimals` outside the range of `double` cq `long` do not deserialize

The first needs a single line changed, the second needs 2 added lines, the third needs two if else statements added.

Would you like me to submit a pull request to fix this?

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know @ericwj!

Longer term our intention is not to have the built-in JSON utilities, but rather to make use of an external package to handle JSON (de)serialization. We only have the built-in JSON utility as a short-term workaround for the lack of an ideal external package, but as soon as one becomes available we'll switch to it.

So if you're interested and you can keep the PR simple and minimal enough, yes please, we'd be happy to include these enhancements. Just bear in mind that it won't be in here forever as we'll be removing all the JSON code as soon as we can. Hope that's OK!

**Comment by ericwj** [comment]
Yes I found Json.NET doesn't work at all. So I ripped your copy of SimpleJson and put it in my project. Then made the changes I needed. This is just to contribute them back.
