### ISSUE TITLE
Howto Embedded resources?

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/Blazor#975]
I have two .resx-Files (Translations.resx and Translations.de.resx) in my project; both with Build Action "Embedded resource" and Custom Tool "ResxFileGenerator".
Namespace is "Testproject".
After compiling, only a resource named "Testproject.Translations.resources" containing the default content is present in the assembly.
Doesn't blazor support .resx-Generation?

**Comment by SteveSandersonMS** [comment]
For embedded resources in general, there's nothing different for a Blazor app build than for any other .NET Core project. The `<EmbeddedResource>` item group will behave as normal.

For resx files, are you trying to generate satellite assemblies? If so, that's not something we've specifically worked in yet. Localisation is being tracked as #60.

**Comment by DNF-SaS** [comment]
My problem was CustomTool == ResxFileGenerator (wrong) - correct is "ResXFile**Code**Generator".
