### ISSUE TITLE
Target Netstandard2.0 in Microsoft.AspNetCore.Blazor.Server package

### ISSUE THREAD

**Issue by zefubachs** [aspnet/Blazor#986]
Currently the [Microsoft.AspNetCore.Blazor.Server](https://dotnet.myget.org/feed/blazor-dev/package/nuget/Microsoft.AspNetCore.Blazor.Server) package targets `netcoreapp2.0`.
This prevents aspnetcore webapps targeting the full framework from using it to server blazor client apps.

Is there a specific reason behind this decision?

A proposed change would be to change the targetframework to `netstandard2.0`.

**Comment by SteveSandersonMS** [comment]
There isn't a specific reason as I recall; it's just not a focus at the moment. If you find that simply changing the TFM in the sources is enough to make it work, we'd be happy to take a PR for that. Thanks!
