### ISSUE TITLE
Form with @onsubmit sends POST to server

### ISSUE THREAD

**Issue by RemiBou** [aspnet/Blazor#988]
This started with Blazor 0.4.

On my form I have a "@onsubmit" handler. When I click on the button with type="submit" the event is not raised but a classic POST is sent to the server.

[My File](https://github.com/RemiBou/Toss.Blazor/blob/master/Toss/Toss.Client/Shared/LoginClassic.cshtml)

And then i get an error "The SPA default page middleware could not return the default page ..." it might be connected to issue #951 or #803

**Comment by chucker** [comment]
Yes, I think you're observing #951. I ended up moving the `button` outside the `form`, which I'm guessing isn't an option for you. Consider andoband's suggestion instead:

>Note that adding `type="button"` to your button markup should stop the browser from trying to submit the form in the first place.

**Comment by RemiBou** [comment]
yes but if I hit "enter" while on the form it's getting submited

**Comment by SteveSandersonMS** [comment]
Fixed by #1171
