### ISSUE TITLE
Demo ==> freeze and error in console after second call

### ISSUE THREAD

**Issue by TheCamel** [aspnet/Blazor#989]
Hello,
from the demo app, i customize the fetchdata page to call and display my data from my api. It woks once. I click on counter, then fetch....this is freezing with errors

my test code

User auth = new User() { Culture = "FR-fr", Login = "USER", Password = "USER", IdProfil="244" };
        auth = await Http.PostJsonAsync<User>(
            "http://localhost/Web.Api/User/Login", auth);
        forecasts = await Http.GetJsonAsync<List<DisplayAlarmBase>>(
            string.Format("http://localhost/Web.Api/Event/GetAlarms?since={0}&token={1}",
            DateTime.Now.AddDays(-200), auth.Token)
         );
        await Http.PostJsonAsync(
            string.Format("http://localhost/Web.Api/User/Logout?token={0}", auth.Token), null );

![blazor1](https://user-images.githubusercontent.com/7381872/41352185-fc1166f6-6f18-11e8-958a-2b7071a31800.png)

**Comment by TheCamel** [comment]
to complete, it work better in chrome...no freeze, no error - it is even quicker = 67.0.3396.87 (Build officiel) (64 bits)

**Comment by danroth27** [comment]
Would it be possible for you to share with us a simple project that reproduces the issue?

**Comment by TheCamel** [comment]
Yes, i have prepared a folder with all you need. Should post it here or send by mail ??? or ?

**Comment by SteveSandersonMS** [comment]
@TheCamel I'm afraid I've not been able to reproduce this issue. If you're able to reduce this to a smaller set of changes (e.g., a series of instructions about how to edit the default project template without bringing in external assemblies) that recreates this error please let us know.

Also from a screenshot in your other issue (#993), it appears that your Edge browser somehow doesn't have WebAssembly enabled. This would explain it being much slower. If there's something unusual about your Edge browser (maybe it's very out of date, or configured in a nonstandard way) this might also explain the crash you're seeing. I'd recommend you make sure your OS/browser is up-to-date and check it with WebAssembly enabled, which it should be by default.

**Comment by SteveSandersonMS** [comment]
I'll close this as it appears to be something nonstandard about your browser, but if you have any info on how it can be reproduced on a typical machine (e.g., what config changes produce this effect, if indeed it's possible to produce it deliberately through config), please let us know. Of course if others report something similar we'll try to investigate. Hope that's OK!

**Comment by SteveSandersonMS** [comment]
Update: I think you're using a very old version of Edge that [disables WebAssembly when the debug console is open](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5201302/).
