### ISSUE TITLE
Quotation marks in bind, onclick, etc. - bug or feature?

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/Blazor#997]
In `cshtml` file we can write something like this:
```html
<input bind="@MyProperty" />
<button onclick="@MyClickHandler">Click Me</button>
```
or exactly the same, but without quotation marks
```html
<input bind=@MyProperty />
<button onclick=@MyClickHandler>Click Me</button>
```
Is it bug or undocumented feature? It confuses some people - read comments in #127
I have browsed documentation and there is only one place in "Introduction" where Razor expression is used without quotation marks:
```html
<button onclick=@OnOK>OK</button>
```
In all other places quotation marks are used.

**Comment by SteveSandersonMS** [comment]
It's neither a bug nor an undocumented feature :)

It's how Razor has always been flexible about syntax on tag helpers. HTML itself is flexible in pretty much the exact same way.
