### ISSUE TITLE
Really slow performance (list of 1000 items)

### ISSUE THREAD

**Issue by sylvainonweb** [aspnet/Blazor#998]
It takes more than 10 seconds to show a list of 1000 items (compared to Angular or React which takes less than 2 seconds).

To reproduce it, use the Visual Studio Blazor template and change the SampleDataController like this :

```
 [HttpGet("[action]")]
        public IEnumerable<WeatherForecast> WeatherForecasts()
        {
            var rng = new Random();
            return Enumerable.Range(1, 1000).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = $"Summary {index}"
            });
        }
```

**Comment by SteveSandersonMS** [comment]
For me, it takes about 2 seconds in Firefox, about 4 in Edge, and yes about 10 in Chrome.

We've known for a while that Chrome's WebAssembly performance lags a long way behind the other browsers. It gets reported often. We spoke with some of the team leads from V8 (the underlying JS/WASM engine for Chrome) and they told us that they have some major work in progress that they expect will make Chrome at least as fast, or faster, than Firefox for WebAssembly. So this difference should go away long before Blazor is ready. I think their ETA was something like "a few months" but can't be more precise about that; you'd have to ask them.

More generally we are working with the Mono team, who supply the underlying .NET-on-WebAssembly runtime to hopefully get some major speedups across all browsers. The Mono folks have told us that their interpreted runtime hasn't yet had any optimisation work done on it, and when they do they expect some very major gains.

**Comment by sylvainonweb** [comment]
I understand.

For information, for me, it would be more : 
* Firefox (last version 47.0.2) : 31 seconds
* Google Chrome (last version 67.0.3396.87) : 21 seconds
* Edge : 4 seconds
=> As you see, Firefox is slower on my computer than Chrome, strange !!!

Hope for you than efforts will be done quickly on performance side else it could discourage people to invest time on your project which seems to be a really great way to see future of web.

Best regards,

**Comment by Suchiman** [comment]
@sylvainonweb the latest version of firefox is 60.0.2, i'm not sure v47 even supports webassembly

**Comment by sylvainonweb** [comment]
Probably not :) which explains the poor performance.
Now that I downloaded the "real" latest version (47.0.2 should probably be the latest x86 version), it takes 2 seconds as you.
Thanks.

**Comment by peter0302** [comment]
Is the issue on the rendering side? And if so wouldn't virtualization of the visual tree be the answer the same way it is in Wpf / Uwp? I'd never put a thousand rendered items in a list box at the same time on any platform

**Comment by sylvainonweb** [comment]
Yes, I think it's on the rendering side. Yes, you're probably right that virtualization could be the answer but I'm a newbie in web and don't know a solution to virtualize data of a <li></li>.
Paging could also be another answer but compared to angular or react Template projets, there is a huge difference (before Steve told me that my version of browser wasn't compatible with webassembly).
Now, for me, there isn't anymore matter. performance are really acceptable.
Note : In WPF, it doesn't take 20s to fill a grid that isn't virtualize (5s OK but not 20s).

**Comment by legistek** [comment]
Virtualization ain't as hard as it seems. I'm sure if TPTB don't build it into Blazor a clever component designer will give us a solution.

PS - It depends on the complexity, but 1000 items in a WPF Listbox could easily take in the double-digit seconds to render the visual tree without virtualization. Also, Angular craps out at around 100-200 items without virtualization with anything complex, I've found. So I don't think this is anything new.

**Comment by sylvainonweb** [comment]
1) Cool
2) In WPF, never see this. it takes time but not 10s.
3) When I do the same test with the Angular Template, it takes 2s so...

**Comment by legistek** [comment]
Again depends on the complexity... But I'm sure you're right that Blazor is slower overall.

**Comment by sylvainonweb** [comment]
But soon, it will be a matter anymore :)
